### PR TITLE
[ARO] `az aro create`: v2022-04-01 API Feature Support

### PR DESCRIPTION
**Pull request by SudoBrendan**
**Related command**

az aro

**Description**

- bump API version from 2020-04-30 -> 2022-04-01, and add supported features:
    - FIPS cryptography modules
    - disk encryption
    - host encryption
- validation format string updates
- correct code owners of ARO

**Testing Guide**

**History Notes**

{ARO} `az aro`: bump API version from 2020-04-30 to 2022-04-01
[ARO] `az aro create`: Add support for FIPS modules, host encryption, and disk encryption for master and worker nodes

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
ARO

**Comment by zhoxing-ms** [comment]
@SudoBrendan Same CI issue as https://github.com/Azure/azure-cli/pull/22100#issuecomment-1121899727, Please wait for PR #22347 to solve this problem

**Comment by SudoBrendan** [comment]
I've converted this back to a Draft after realizing more about how the test setup works - I should have updated tests in the next few days.

**Review by jiasli — APPROVED** [review]
Approve for core.

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
