### PR TITLE
[ARO] Add cluster credential rotation 

### PR DESCRIPTION
**Pull request by mjudeikis**
**Description**

Enables ARO clusters to perform cluster application credential rotation via CLI.

**Testing Guide**

* Create an ARO cluster
* Run `az aro update --refresh-credentials` to trigger automated credential rotation
* Else `az aro update --client-id <byo_client_id> --client-secret <client_secret>` to trigger credential rotation with BYO credentials. 

**History Notes**
[ARO] Add cluster credential rotation 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by mjudeikis** [comment]
ping @qwordy @haroldrandom @MyronFanQiu @fengzhou-msft would appreciate the review! Thanks :)

**Comment by yonzhan** [comment]
ARO

**Comment by mjudeikis** [comment]
@yonzhan I think bot is broken. No labels, assignee?

**Comment by mjudeikis** [comment]
@fengzhou-msft @jiasli @jsntcy gentle reminder

**Comment by weinong** [comment]
@fengzhou-msft, PTAL

**Review by jewzaam — APPROVED** [review]

**Comment by weinong** [comment]
@jsntcy can you please take a look?

**Review by jsntcy — APPROVED** [review]

**Pull request merged**
