### PR TITLE
[DevTestLabs] Adding more commands for environment in lab

### PR DESCRIPTION
**Pull request by vishrutshah**
This is part of feature https://github.com/Azure/azure-cli/issues/2860

- [x] Create environment in the lab from the attached repository
- [x] Update `az lab vm list` command to filter on `environment`
- [x] Update `json.load` load to `get_json_object`

NOTE: You do not need to review the commit d2781b3 which contains updated DTL SDK

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [x] Each command and parameter has a meaningful description.
- [x] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by vishrutshah** [comment]
```
(env) vishrut@mac azure-cli (dtl-create-env) $ az lab environment create -h

Command
    az lab environment create: Create an environment.

Arguments
    --arm-template-id   [Required]: Fully qualified Azure Resource Manager template's identifier in
                                    the lab.
    --lab-name          [Required]: Name of the Lab.
    --name -n           [Required]: Name of the environment.
    --parameters        [Required]: JSON encoded list of parameters. Use @{file} to load from a
                                    file.
    --resource-group -g [Required]: Name of lab's resource group.
    --tags                        : The tags of the resource.

Global Arguments
    --debug                       : Increase logging verbosity to show all debug logs.
    --help -h                     : Show this help message and exit.
    --output -o                   : Output format.  Allowed values: json, jsonc, table, tsv.
                                    Default: json.
    --query                       : JMESPath query string. See http://jmespath.org/ for more
                                    information and examples.
    --verbose                     : Increase logging verbosity. Use --debug for full debug logs.
```

**Comment by tjprescott** [comment]
What is the arm-template-id for??

**Comment by vishrutshah** [comment]
@tjprescott `arm-template-id` represents the ID of the template that has been configured in the lab's associated repository. 

Example: `/subscriptions/88271ab0-9af4-442c-abb0-901d9fa06ca8/resourceGroups/lab/providers/Microsoft.DevTestLab/labs/labname/artifactSources/privaterepo54/armTemplates/documentdb-webapp`

Based on my discussion with @ericame & @ryanvog, we are not intentionally asking for Name/IDs because `Name` would not be unique in one lab because one lab can have multiple repos and they can potentially have same name inside their metadata file in template :)

**Comment by vishrutshah** [comment]
@tjprescott Yup it's not there. Let me export pre-configured ARM template from lab and then build test for it.

**Comment by vishrutshah** [comment]
@tjprescott after entire day of fighting with service, finally, I managed to record it :muscle:

**Comment by vishrutshah** [comment]
Thanks for the review!!

**Pull request merged**
