### PR TITLE
[APIM]Remove unnecessary parameters in order not to confuse customer

### PR DESCRIPTION
**Pull request by RupengLiu**
**Description**  

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ~] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [~ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
APIM

**Comment by MyronFanQiu** [comment]
@RupengLiu What's the meaning of `unused`?

**Comment by RupengLiu** [comment]
@MyronFanQiu Basically remove these parameters in order not to confuse customers, as required by my PM~

**Comment by RupengLiu** [comment]
> Will this breaking change effect user? Usually, we deprecate those at first, and after 6 months we remove them finally.

Hi, this is not breaking changes, since the parameters I am removing is not released yet, also previously these parameter is not working as expected, so i don't believe there are any customers using this.

**Comment by MyronFanQiu** [comment]
> > Will this breaking change effect user? Usually, we deprecate those at first, and after 6 months we remove them finally.
> 
> Hi, this is not breaking changes, since the parameters I am removing is not released yet, also previously these parameter is not working as expected, so i don't believe there are any customers using this.

It should be released. A new Azure CLI package has been released. Deprecating it first and then removing it is our guideline.

**Pull request closed without merging**
