### PR TITLE
{App Service} Allow Azure Functions Create to accept Python 3.10 parameters

### PR DESCRIPTION
**Pull request by YunchuWang**
**Related command**

**Description**

Azure Functions team is going to support Python 3.10 in November, we need to allow customers to create Python 3.10 function app in azure-cli before the Python 3.10 announcement.

This is NOT an official Azure Functions Python 3.10  release.
**Testing Guide**

Customer should be able to create Python 3.10

On Linux Consumption with az functionapp create -g <resource_group> -n <app_name> -c <consumption_plan_location> -s <storage_account> --os-type linux --runtime python --runtime-version 3.10 --functions-version 3
On Linux Dedicated/Premium with az functionapp create -g <resource_group> -n <app_name> -p <dedicated_plan_name> -s <storage_account> --os-type linux --runtime python --runtime-version 3.10 --functions-version 3

**History Notes**

{App Service} Take '--runtime-version 3.10' as Azure Functions v4 az functionapp create parameter

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AppService

**Comment by YunchuWang** [comment]
@yonzhan Hi Yon, can you help trigger the pipelines again? i fixed the pr format issue but dont have permission to rerun

**Review by zhoxing-ms — APPROVED** [review]

**Comment by YunchuWang** [comment]
@zhoxing-ms Hi ZhoXing, can you advise when will next az cli release happen with this change in?

**Comment by yonzhan** [comment]
https://github.com/Azure/azure-cli/milestones

**Comment by YunchuWang** [comment]
> https://github.com/Azure/azure-cli/milestones

Hi @yonzhan , thanks for sharing this! so next release will happen around end of november?

**Comment by YunchuWang** [comment]
Hi @yonzhan, sorry just to check one more thing, next azure-cli release is confirmed on 12/06/22?

**Comment by yonzhan** [comment]
Official Release: 12/06/2022

**Pull request merged**
