### PR TITLE
resource: support generic resource create

### LINKED ISSUE #2606: resource: support generic resource create

### PR DESCRIPTION
**Pull request by yugangw-msft**
Fix #2606 
1. Support inidividual args like rg, name
2. Support full resource id
3. Support full resource object, or just properties for request payload
4. Checkout the test for usages

//cc: @davidebbo 
 
### General Guidelines

- [x] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [x] Each command and parameter has a meaningful description.
- [x] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by tjprescott** [comment]
Can we get the help output for this?  Would you basically be using just the "resource" portion of the arm template to supply to properties?

**Comment by yugangw-msft** [comment]
> Would you basically be using just the "resource" portion of the arm template to supply to properties?

Close, but not exactly as the command uses resource create API not arm template

help output:
```bash
Command
    az resource create: Create a resource.

Arguments
    --properties -p [Required]: A JSON-formatted string containing resource properties.
    --api-version             : The api version of the resource (omit for latest).
    --id                      : Resource ID.
    --is-full-object          : Indicates that the properties object includes other options such as
                                location, tags, sku, and/or plan.
    --location -l             : Location. You can configure the default location using 'az configure
                                --defaults location=<location>'.
    --name -n                 : The resource name. (Ex: myC).
    --namespace               : Provider namespace (Ex: 'Microsoft.Provider').
    --parent                  : The parent path (Ex: 'resA/myA/resB/myB').
    --resource-group -g       : Name of resource group. You can configure the default group using
                                'az configure --defaults group=<name>'.
    --resource-type           : The resource type (Ex: 'resC'). Can also accept namespace/type
                                format (Ex: 'Microsoft.Provider/resC').
```

**Comment by tjprescott** [comment]
We should call out using the @syntax for the properties as that's how most people would (hopefully) use it.  Also, I'm a little confused by `--is-full-object`... how can you have partial objects?

**Comment by yugangw-msft** [comment]
> Also, I'm a little confused by --is-full-object... how can you have partial objects

I ported it from xplat. The partial objects means you only provide the `properties` collection. Some RP will happily accept it. You can check out the test I wrote to create a webapp.
This reminders me that I should add a few samples for this command.

**Comment by tjprescott** [comment]
This `--is-full-object` flag just seems super wonky to me. There's only small set of parameters that can exist outside of the properties (location, tags... ?) could we not simply sniff this condition and act accordingly?  Otherwise it seems like the plan would be:
`az resource create -p @myprops.json`
and if that fails, with no real reason:
`az resource create -p @myprops.json --is-full-object`
And see if that works.

**Comment by yugangw-msft** [comment]
It is `generic resource command`, and by itself it is a wonky command :). I would clarify a bit that the change is already sniffing the location from RG if it is not a full object and construct the resource body accordingly.
I don't like to retry as we have no idea of what failures really mean. It is different with strong typed command that each failure situation of the API is clearly documented 
The full object arg is being used for both powershell and xplat. I like to see more data proving the idea 
 is bad before we like to drop it :): otherwise it hurts the migration.

**Pull request merged**
