### PR TITLE
[App Service] On webapp up set httpsonly true

### LINKED ISSUE #11287: webapp up: By default make the app created using up 'should be 'SSL enabled'
Set httpsonly to true when an app is created using az webapp up

### PR DESCRIPTION
**Pull request by ammanifold**
Fixes #11287 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by ammanifold** [comment]
Fixes #11287

**Comment by ammanifold** [comment]
Only set https true for webapp up
(will be false for webapp create)

**Comment by ammanifold** [comment]
@panchagnula FYI :)

**Comment by ammanifold** [comment]
@qwordy can you please help me understand why Cred scan is failing?

**Comment by panchagnula** [comment]
@ammanifold  the changes look good to me - i will approve once the BUILD passes.

**Comment by qwordy** [comment]
src\azure-cli\azure\cli\command_modules\appservice\tests\latest\recordings\test_webapp_hybridconnectionE2E.yaml(1169,)
src\azure-cli\azure\cli\command_modules\appservice\tests\latest\recordings\test_webapp_hybridconnectionE2E.yaml(1205,)
These two lines have credentials according to the scan results.

**Comment by panchagnula** [comment]
@ammanifold  please go ahead & suppress this file "test_webapp_hybridconnectionE2E.yaml" here

https://github.com/Azure/azure-cli/blob/dev/CredScanSuppressions.json

**Comment by ammanifold** [comment]
@qwordy can you please take another look? Thanks!

**Comment by panchagnula** [comment]
@ammanifold looks the history file changes need to be resolved.

**Comment by ammanifold** [comment]
Resolved :)

**Comment by qwordy** [comment]
please fix test failure. Some errors are "no matching request". I guess you need to add --live to run the test.

**Comment by ammanifold** [comment]
Thanks @qwordy, all checks have passed

**Comment by panchagnula** [comment]
@qwordy can we get this merged please some home i don't have permissions anymore to merge this anymore. Thanks!

**Comment by yonzhan** [comment]
@qwordy please help with the PR.

**Pull request merged**
