### PR TITLE
{Release} Update Version of azure-mgmt-core to 1.2.0

### PR DESCRIPTION
**Pull request by LianwMS**
**Description**  

Update the azure-mgmt-core version as az codegen has rely on the new version
**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by Juliehzl** [comment]
please also change in requirements_xxx.txt

**Comment by yungezz** [comment]
hi @LianwMS just curious what new in core-mgmt 1.2.0? is it necessary to regress extensions since there're extensions on track2?

**Comment by LianwMS** [comment]
> please also change in requirements_xxx.txt

updated~

**Comment by LianwMS** [comment]
> hi @LianwMS just curious what new in core-mgmt 1.2.0? is it necessary to regress extensions since there're extensions on track2?

As codegen need new version of modelerfour which using new autorest.python version, which rely on azure.mgmt.core 1.2.0

**Comment by yonzhan** [comment]
Good to know.

**Comment by yungezz** [comment]
> > hi @LianwMS just curious what new in core-mgmt 1.2.0? is it necessary to regress extensions since there're extensions on track2?
> 
> As codegen need new version of modelerfour which using new autorest.python version, which rely on azure.mgmt.core 1.2.0

thanks @LianwMS . Do you think it's necessary to run one extension test for this change to validate it?

**Pull request merged**
