### PR TITLE
[AppService] Fix bug in create_app_service_plan when use webapp up

### LINKED ISSUE #11100: BUG: az webapp up - AttributeError: 'NoneType' object has no attribute 'upper'
**Describe the bug**

I am trying to run the following tutorial:
https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-html

**To Reproduce**

Follow the steps in the tutorial, there is an error in:
az webapp up --location westeurope --name helloworld12345

Detailed error follows:

webapp helloworld12345 doesn't exist
Creating Resource group 'mcampos_rg_Windows_westeurope' ...
Resource group creation complete
Creating AppServicePlan 'mcampos_asp_Windows_westeurope_0' ...
The command failed with an unexpected error. Here is the traceback:

'NoneType' object has no attribute 'upper'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 603, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 661, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 652, in _run_job
    cmd_copy.exception_handler(ex)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/commands.py", line 55, in _polish_bad_errors
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 631, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 306, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 485, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 2993, in webapp_up
    create_app_service_plan(cmd, rg_name, plan, _is_linux, False, sku, 1 if _is_linux else None, location)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/custom.py", line 1390, in create_app_service_plan
    sku = _normalize_sku(sku)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/appservice/utils.py", line 20, in _normalize_sku
    sku = sku.upper()
AttributeError: 'NoneType' object has no attribute 'upper'

Please note that az webapp up creates some of the resources and then crashes, so the Azure subscription is left in an inconsistent state.

**Expected behavior**
Work as before. 

**Environment summary**
Using Azure Shell - azure-cli 2.0.76

**Additional context**
**IMPORTANT:** I expect to present this in a customer event on Wednesday 6, this funcionality is part of the existing demo script. I not fixed, I will not be able to show this.

### PR DESCRIPTION
**Pull request by Juliehzl**
Fix #11100 
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by panchagnula** [comment]
Thanks for doing this fix. we are missing history.rst changes

**Comment by Juliehzl** [comment]
> Thanks for doing this fix. we are missing history.rst changes

Because I don't add any change for command or parameter, I think it is fine without updating history.rst.

**Comment by Juliehzl** [comment]
> Need history.rst changes otherwise LGTM

Done

**Comment by jboeshart** [comment]
This isn't isolated to Microsoft Learn sandbox, it's any usage in the cloud shell. Any ETA on getting this merged and released?

**Comment by Juliehzl** [comment]
> This isn't isolated to Microsoft Learn sandbox, it's any usage in the cloud shell. Any ETA on getting this merged and released?

I will make it merged ASAP and it will be official released on Nov 26th.

**Comment by jboeshart** [comment]
@Juliehzl why the delay to get this released? `az webapp up` is entirely non-functional. Can we get this out sooner?

**Pull request merged**
