### PR TITLE
Fix some grammar issues

### PR DESCRIPTION
**Pull request by mboersma**
Replaces "till" with "until" and inserts the required hyphen into the phrase "long-running."

### CODE REVIEW

**Comment by sptramer** [comment]
Docs 👍 LGTM

**Comment by mboersma** [comment]
Some linting error seems to have crept into the KnackConversion branch, so I fixed it in 6c0c0ce.

**Comment by derekbekoe** [comment]
@mboersma yes pylint released an update that added some new rules today... Glad it was easy to fix.

**Comment by derekbekoe** [comment]
Running CI again to verify no bad git merge.
The pylint fix you made was already merged in by another PR.
Once CI is green, I'll merge.

**Pull request merged**
