### PR TITLE
Fix #2293: Run code coverage during tests

### LINKED ISSUE #2293: Measure test code coverage in CI.

### PR DESCRIPTION
**Pull request by troydai**

### CODE REVIEW

**Comment by tjprescott** [comment]
What flavor of coverage is run?

**Comment by tjprescott** [comment]
I guess @codecov-io answered my question!  😆 Why is branches 0?  Do we need to configure that?

**Comment by troydai** [comment]
This is a basic line by line code coverage (vs command or parameter coverage). And I didn't turn on branch coverage so the data is missing there. Sure, we can turn it on later. I'm not sure about the performance implication though.

**Comment by troydai** [comment]
@tjprescott agree. Let me track it.

**Comment by troydai** [comment]
Follow up: https://github.com/Azure/azure-cli/issues/2297

**Comment by troydai** [comment]
@derekbekoe is `master` branch open for merge now?

**Comment by derekbekoe** [comment]
@troydai yes! good to go 🛫

**Pull request merged**
