### PR TITLE
Add a spinner, and use it for indeterminate progress notifications.

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes https://github.com/Azure/azure-cli/issues/2619

### CODE REVIEW

**Comment by troydai** [comment]
We're looking at add an API in `azure-cli-core` offers progress indicating functionality. We'd like to have the API meet requirements from various command modules. The spinner could be one of the options. How about we hold on this PR for a while and take a look if the new API we come up can meet your requirement.

**Comment by brendandburns** [comment]
@troydai I'm happy to help implementing the spinner/progress do you need/want help?  Design doc anywhere?

**Comment by troydai** [comment]
@brendandburns, @oakeyc is working on a brief spec and a prototype implementation now. She had looked at your pull request and will make changes similar to the changes you're making here. I'll keep you updated.

**Comment by brendandburns** [comment]
Cool, let me know if I can help...

**Comment by troydai** [comment]
The work has been taken up by https://github.com/Azure/azure-cli/pull/3130. Thanks for opening this pull request.

**Pull request closed without merging**
