### PR TITLE
[Package] Remove azure.storage.blob dependency

### PR DESCRIPTION
**Pull request by Juliehzl**
**Description**  

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by Juliehzl** [comment]
There is one more dependency from azure-batch-cli-extensions, which is not owned in azure-cli-extensions. So it is hard to remove azure.storage.blob package in azure.cli and there are two solutions:
- Add azure namespace support in extension, in this way it can rely on it own setup dependencies not azure cli.
- Change code in azure-batch-cli-extensions source code to utilize azure.multiapi.storage.

**Comment by Juliehzl** [comment]
@fengzhou-msft and @qianwens what do you think about it?

**Comment by yonzhan** [comment]
add to S170

**Comment by haroldrandom** [comment]
It migh effect some extensions loading. There are hiden wrong depedencies on Azure CLI.

**Comment by Juliehzl** [comment]
PR for extension is here https://github.com/Azure/azure-batch-cli-extensions/pull/123

**Comment by yonzhan** [comment]
add to S171

**Comment by yonzhan** [comment]
add to S172

**Pull request closed without merging**
