### PR TITLE
[ACR] Fix #21900: `az acr task identity remove`: Fix incorrect operation_group setting

### LINKED ISSUE #21900: Attribute TaskUpdateParameters does not exist in az acr task identity remove
## Describe the bug

**Command Name**
`az acr task identity remove`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
Attribute TaskUpdateParameters does not exist.
Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\cli\core\profiles\_shared.py", line 428, in __getattr__
    return self._operations_groups_value[item]
KeyError: 'TaskUpdateParameters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\knack\cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\cli\core\commands\__init__.py", line 658, in execute
    raise ex
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\cli\core\commands\__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\cli\core\commands\__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\cli\core\commands\__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\cli\core\commands\command_operation.py", line 121, in handler
    return op(**command_args)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\cli\command_modules\acr\task.py", line 563, in acr_task_identity_remove
    TaskUpdateParameters = cmd.get_models('TaskUpdateParameters', operation_group='TaskUpdateParameters')
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\cli\core\commands\__init__.py", line 351, in get_models
    return self.loader.get_sdk(*attr_args, resource_type=resource_type, mod='models',
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\cli\core\__init__.py", line 756, in get_sdk
    return get_sdk(self.cli_ctx, kwargs.pop('resource_type', self._get_resource_type()),
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\cli\core\profiles\__init__.py", line 91, in get_sdk
    return _sdk_get_versioned_sdk(cli_ctx.cloud.profile, resource_type, *attr_args, **kwargs)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\cli\core\profiles\_shared.py", line 640, in get_versioned_sdk
    sdk_path = get_versioned_sdk_path(api_profile, resource_type, operation_group)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\cli\core\profiles\_shared.py", line 632, in get_versioned_sdk_path
    api_version = getattr(api_version, operation_group)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python310\lib\site-packages\azure\cli\core\profiles\_shared.py", line 430, in __getattr__
    raise AttributeError('Attribute {} does not exist.'.format(item))
AttributeError: Attribute TaskUpdateParameters does not exist.

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr task identity remove -n {} -r {}`

## Expected Behavior

An identity is removed.

## Environment Summary
```
Windows-10-10.0.19044-SP0, 
Python 3.10.4
Installer: PIP

azure-cli 2.34.1

Extensions:
acrtransfer 1.1.0
application-insights 0.1.15
azure-devops 0.25.0
blueprint 0.3.1
interactive 0.4.5

Dependencies:
msal 1.17.0
azure-mgmt-resource 20.0.0
```

### PR DESCRIPTION
**Pull request by juliusl**
**Related command**

`az acr task identity remove`

**Description**

Value for operation group was incorrect. Addresses #29325 #21900

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by northtyphoon — APPROVED** [review]
LGTM

**Comment by yonzhan** [comment]
Please fix CI issues

**Comment by juliusl** [comment]
@yonzhan hey there, what else is missing? I fixed the title already but I'm not sure how to kick off the CI again

**Comment by zhoxing-ms** [comment]
@juliusl Please add some test cases for this change

**Comment by juliusl** [comment]
@zhoxing-ms I cannot get `azdev test` to work at all on my machine, can you please generate a new recording for me.

**Review by rosanch — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
> I cannot get azdev test to work at all on my machine, can you please generate a new recording for me.

May I ask why `azdev test` can't work on your machine?

**Comment by juliusl** [comment]
@zhoxing-ms whenever I try to run it I get,

```py
ERROR: usage: __main__.py [options] [file_or_dir] [file_or_dir] [...]
__main__.py: error: unrecognized arguments: -n auto
  inifile: None
  rootdir: d:\py\azure-cli\src\azure-cli
```

This is after uninstalling/reinstalling python and re-creating my venv several times, initially I was getting:

```py
C:\Python310\python.exe: No module named pytest
```

But then I figured that issue out, and now I just get the former message.

```

**Comment by zhoxing-ms** [comment]
@juliusl Please refer to this doc [doc link](https://github.com/Azure/azure-cli/blob/dev/doc/authoring_tests.md#recording-tests-for-the-first-time) to learn how to use the `azdev test` to record the recording files

**Comment by juliusl** [comment]
@zhoxing-ms I tried following that documentation before I asked for assistance, and also searched for similar issues.

**Comment by juliusl** [comment]
@zhoxing-ms ok looks like tests are passing now, I got someone to help me create a new recording

**Comment by northtyphoon** [comment]
@yanzhudd it looks the new CLI-Style check started to fail in the last run. The PR doesn't change CLI command.

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
