### PR TITLE
Change blob_source to http_url

### PR DESCRIPTION
**Pull request by bgklein**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
@Juliehzl  please help with this PR.

**Comment by bgklein** [comment]
@MyronFanQiu no this is a fix to a broken feature

**Comment by yonzhan** [comment]
@Juliehzl  please help with this PR.

**Comment by Juliehzl** [comment]
@bgklein User have to provide url with SAS token or a public access url, right?

**Comment by bgklein** [comment]
@Juliehzl yes, the user needs to make sure that whatever URL is either publicly accessible or contains a SAS which grants read access.

**Comment by bgklein** [comment]
@Juliehzl  please merge

**Comment by Juliehzl** [comment]
> @Juliehzl yes, the user needs to make sure that whatever URL is either publicly accessible or contains a SAS which grants read access.

Can you specify the requirement for url in help message, which will give user better experience?

**Comment by bgklein** [comment]
Could someone please merge this now?

**Comment by MyronFanQiu** [comment]
@Juliehzl Hi. Is it ok to merge this PR?

**Pull request merged**
