### PR TITLE
fix the wrong help

### PR DESCRIPTION
**Pull request by TsuyoshiUshio**
According to the other help, it might be right.

This pull request is the fix of this issue. 

https://github.com/Azure/azure-cli/issues/6674

This pull request is only for help text.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by tjprescott** [comment]
Closes #6674

**Comment by TsuyoshiUshio** [comment]
Hi @tjprescott 

I have two questions. 

1. error on the CI

On the CI, it compared two sources. How can I fix it ?  I can't find the place to fix.

```
--- a/src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/_help.py
+++ b/src/command_modules/azure-cli-eventhubs/azure/cli/command_modules/eventhubs/_help.py
@@ -74,7 +74,7 @@ helps['eventhubs namespace create'] = """
     examples:
         - name: Creates a new namespace.
           text: az eventhubs namespace create --resource-group myresourcegroup --name mynamespace --location westus
-           --tags tag1=value1 tag2=value2 --sku-name Standard --sku-tier Standard --is-auto-inflate-enabled False --maximum-throughput-units 30
+           --tags tag1=value1 tag2=value2 --sku Standard --is-auto-inflate-enabled False --maximum-throughput-units 30
 """
 
 helps['eventhubs namespace update'] = """
Error(s) on azure-cli-eventhubs
```

2. Close #6674 

You mention that Close #6674, Do you mean I need to close #6674 ?
If so, I'll do it.

**Comment by tjprescott** [comment]
No, when this PR is merged, it will automatically close the referenced issue.

In regards to the error, the problem is listed here:
```
The following modules have invalid versions:
azure-cli-eventhubs
```

All you need to do is _rebase_ your PR on the latest in dev. **DO NOT merge because this won't fix the problem.**

**Comment by TsuyoshiUshio** [comment]
HI @tjprescott  I rebase this branch.

**Comment by tjprescott** [comment]
Thanks @TsuyoshiUshio!

**Pull request merged**
