### PR TITLE
[ACR] BREAKING CHANGE: Update manifest list-referrers to comply with RC1 ORAS spec

### PR DESCRIPTION
**Pull request by mabenedi**
**Related command**
az acr manifest list-referrers

**Description**
Changed command implementation to comply with the new ORAS spec. Behavior to user is unchanged. 

**History Notes**

{acr} CHANGE: `az acr manifest list-referrers`: Update manifest list-referrers to comply with RC1 ORAS spec

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
acr

**Review by northtyphoon — APPROVED** [review]
LGTM

**Comment by zhoxing-ms** [comment]
Is the change introduced by this PR perceived by users? 
If not, we don't need to write the PR title into the history notes, so please change the prefix of the PR title from `[]` to `{}`

**Comment by mabenedi** [comment]
> @mabenedi Is the change introduced by this PR perceived by users?
If not, we don't need to write the PR title into the history notes, so please change the prefix of the PR title from [] to {}

There is one small change perceived by users. The JSON object now nested inside a 'referrers' key. Previously, this key was 'references'

image

**Comment by zhoxing-ms** [comment]
> There is one small change perceived by users. The JSON object now nested inside a 'referrers' key. Previously, this key was 'references'

@mabenedi Please note that modifying the output property name will cause breaking change to users. Is it necessary to modify this name?

**Comment by mabenedi** [comment]
> > There is one small change perceived by users. The JSON object now nested inside a 'referrers' key. Previously, this key was 'references'
> 
> @mabenedi Please note that modifying the output property name will cause breaking change to users. Is it necessary to modify this name?

It is unfortunately necessary in order to comply with the spec. The change is actually happening on the backend. To be honest, it might be considered a bug that it ever said 'references' at all. 

If it makes you feel better our telemetry shows very low usage on this API as this is still a very early preview feature (and much of that usage comes from the OSS ORAS client itself, not Az CLI).

**Review by zhoxing-ms — APPROVED** [review]
Since the breaking change has been appeared on the server side and the current usage of this command is very low, so CLI side can be modified directly. 
I modified the PR title to indicate that this change is a breaking change

**Pull request merged**
