### PR TITLE
{Cosmos DB} Update python SDK

### PR DESCRIPTION
**Pull request by soeom**
**Description**  

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by soeom** [comment]
Re-opening PR as python SDK is ready. Please include this PR to S169. New SDK version adds PrivateEndpointConnection property to DatabaseAccountGetResult. This is needs to be included for build for PrivateEndpoint feature.

**Comment by yonzhan** [comment]
add to S169

**Comment by soeom** [comment]
@Juliehzl  Please review the PR.

**Pull request merged**
