### PR TITLE
[AppService] functionapp: Added support for custom handlers. Deprecated Powershell 6.2.

### PR DESCRIPTION
**Pull request by gzuber**
**Description**  

Added support for custom handlers. Users can now create functions with custom handlers by using a command similar to --
```
az functionapp create -s storage_account -g resource_group -c location -n function_name --runtime custom
```

As part of the support for custom handlers, the stacks api was updated. That brought along with it the powershell 6.2 deprecation. I also added code that handles a runtime being deprecated.

**Testing Guide**  

I added two tests that tests custom handlers on windows and linux

**History Notes**  

[AppService] az functionapp create: Added support for custom handlers. Deprecated Powershell 6.2.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by gzuber** [comment]
@Francisco-Gamino for powershell deprecation and deprecation warning
@pragnagopa for custom handler support

**Comment by Francisco-Gamino** [comment]
Thanks @gzuber for sending this out! 

I'd like to clarify that we are deprecating `PowerShell 6.2` and not `PowerShell 7.0`. 

In the Az.Funcition cmdlets, when a user creates a `PowerShell 6.2` function app, this is the warning that we display:

`
WARNING: PowerShell '6.2' has been deprecated. Please update your PowerShell runtime version to 7.0 by providing '-RuntimeVersion 7.0' when creating PowerShell function apps. For more information, please see 'https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-7#powershell-releases-end-of-life'.
`

cc: @stefanushinardi for FYI

**Review by qwordy — APPROVED** [review]

**Comment by qwordy** [comment]
Wait for Pragna to review

**Comment by gzuber** [comment]
> Thanks @gzuber for sending this out!
> 
> I'd like to clarify that we are deprecating `PowerShell 6.2` and not `PowerShell 7.0`.
> 
> In the Az.Funcition cmdlets, when a user creates a `PowerShell 6.2` function app, this is the warning that we display:
> 
> `WARNING: PowerShell '6.2' has been deprecated. Please update your PowerShell runtime version to 7.0 by providing '-RuntimeVersion 7.0' when creating PowerShell function apps. For more information, please see 'https://docs.microsoft.com/en-us/powershell/scripting/powershell-support-lifecycle?view=powershell-7#powershell-releases-end-of-life'.`
> 
> cc: @stefanushinardi for FYI

Whoops! The code is all correct for deprecating 6.2, but I had just been working on an incident involving Powershell 7 before I wrote out this PR so I mixed must have mixed them up haha. PR text should be fixed now.

As for the warning, I basically took the text you're referencing from the email and made it generic for all runtimes ([see changes here](https://github.com/Azure/azure-cli/pull/15170/files#diff-75a1767a60b87df72982d626136921dbR2798-R2803)). My thought process is that because we're dealing with so many languages and versions that could be deprecated, a general solution would be best. I worry about requiring a code change for every deprecation because that seems against the goals of the stacks API. But let me know if you have concerns we can figure something out

**Review by pragnagopa — APPROVED** [review]
👍

**Pull request merged**
