### PR TITLE
{Packaging} Remove Windows binary from source repository

### PR DESCRIPTION
**Pull request by bluca**
Binaries should not be checked in source trees. All
kind of alarms are set off when packaging a new source and
it includes a pre-built binary.

### CODE REVIEW

**Comment by yonzhan** [comment]
packaging

**Comment by jiasli** [comment]
The exe calles [`SendMessageTimeoutW`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendmessagetimeoutw) with [`WM_SETTINGCHANGE`](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-settingchange):

https://github.com/Azure/azure-cli/blob/df3943f539d29596abd03dd00b28e06b4eace0e5/build_scripts/windows/propagate_env_change/main.cpp#L4-L11

There is some dependency on this exe and it is not compiled in the CI:

https://github.com/Azure/azure-cli/blob/844005a08d19ab7a5544aa9147869e101426ea67/build_scripts/windows/Product.wxs#L42-L53

Removing it causes the CI to report [an error](https://dev.azure.com/azure-sdk/public/_build/results?buildId=266131&view=logs&j=78898306-33c5-5664-2f1b-a3010f777c49&t=69f9f981-48c0-5646-dd49-dca4323702d8&l=3526). (Though I have no idea why CI still shows green.)

```
"D:\a\1\s\build_scripts\windows\azure-cli.wixproj" (rebuild target) (1) ->
(Link target) -> 
  D:\a\1\s\build_scripts\windows\Product.wxs(43): error LGHT0103: The system cannot find the file '.\propagate_env_change\propagate_env_change.exe'. [D:\a\1\s\build_scripts\windows\azure-cli.wixproj]
```

I am not sure of the usage of this file. May be we can contact the author for more details? @fengzhou-msft

**Comment by bluca** [comment]
If the CI needs it, then shouldn't it build it?

**Comment by jiasli** [comment]
The msi installer of Azure CLI adds the path of `az.bat` to the `PATH` environment variable:

https://github.com/Azure/azure-cli/blob/844005a08d19ab7a5544aa9147869e101426ea67/build_scripts/windows/Product.wxs#L95-L101

According to [Environment Variables](https://docs.microsoft.com/en-us/windows/win32/procthread/environment-variables) doc:

> To programmatically add or modify system environment variables, add them to the **HKEY\_LOCAL\_MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\Environment** registry key, then broadcast a [**WM\_SETTINGCHANGE**](https://docs.microsoft.com/windows/desktop/winmsg/wm-settingchange) message with *lParam* set to the string "Environment". This allows applications, such as the shell, to pick up your updates.

So the installer needs to broadcast the environment variable change using `WM_SETTINGCHANGE` to shell (explorer.exe). Otherwise the user needs to logout and login for the change to take effect. 

To verify that, you may change registry key **HKEY_CURRENT_USER\Environment** or **HKEY\_LOCAL\_MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\Environment** to add an environment variable `MYENV=somevalue`, then open cmd.exe to run `echo %MYENV%`.

This will not return `somevalue` because explorer.exe isn't aware of this change. You may end explorer.exe in **Task Manager** and reboot it then open cmd.exe, now `echo %MYENV%` shows `somevalue`. Or you may run propagate_env_change.exe and only reboot cmd.exe, it will also show `somevalue`. Note that `WM_SETTINGCHANGE` doesn't affect cmd.exe directly. (Also see https://github.com/chocolatey/choco/issues/1589)

propagate_env_change.exe calls [`SendMessageTimeoutW`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendmessagetimeoutw) with [`WM_SETTINGCHANGE`](https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-settingchange):

https://github.com/Azure/azure-cli/blob/df3943f539d29596abd03dd00b28e06b4eace0e5/build_scripts/windows/propagate_env_change/main.cpp#L5-L11

It is included in the msi installer:

https://github.com/Azure/azure-cli/blob/844005a08d19ab7a5544aa9147869e101426ea67/build_scripts/windows/Product.wxs#L42-L53

Removing it causes the CI to report [an error](https://dev.azure.com/azure-sdk/public/_build/results?buildId=266131&view=logs&j=78898306-33c5-5664-2f1b-a3010f777c49&t=69f9f981-48c0-5646-dd49-dca4323702d8&l=3526). (Though I have no idea why CI still shows green.)

```
"D:\a\1\s\build_scripts\windows\azure-cli.wixproj" (rebuild target) (1) ->
(Link target) -> 
  D:\a\1\s\build_scripts\windows\Product.wxs(43): error LGHT0103: The system cannot find the file '.\propagate_env_change\propagate_env_change.exe'. [D:\a\1\s\build_scripts\windows\azure-cli.wixproj]
```

The source code is checked into the repository, but we need a signed binary and it was not worthwhile to do auto code sign just for this little one. 

Thanks for understanding.

**Comment by bluca** [comment]
> The source code is checked into the repository, but we need a signed binary and it was not worthwhile to do auto code sign just for this little one.

Please reconsider. I'll have to repack the source downstream to mangle it and remove the offending binary otherwise, and I don't really want to have to do that.
Why does it have to be stored in the git repository? Why can't it be an asset downloaded on demand when needed?

**Comment by jiasli** [comment]
Ok I got your point. @fengzhou-msft can we move it to `https://azurecliprod.blob.core.windows.net/util/` just like the built-in python?

https://github.com/Azure/azure-cli/blob/62307e97c96ba739568e96d7815ec51d35ae6fef/build_scripts/windows/scripts/build.cmd#L15

**Comment by bluca** [comment]
Thank you!

**Comment by fengzhou-msft** [comment]
> Ok I got your point. @fengzhou-msft can we move it to `https://azurecliprod.blob.core.windows.net/util/` just like the built-in python?
> 
> https://github.com/Azure/azure-cli/blob/62307e97c96ba739568e96d7815ec51d35ae6fef/build_scripts/windows/scripts/build.cmd#L15

I will work on it. Can you open an issue to track it?

**Pull request closed without merging**
