### PR TITLE
[RDBMS] Update PostgreSQL flexible server to use the new API version 2023-03-01-preview

### PR DESCRIPTION
**Pull request by ambrahma**
**Related command**
- Create flexible server with data encryption enabled for geo-backup Enabled server
`az postgres flexible-server create -g testGroup -n testServer --location testLocation --geo-redundant-backup Enabled --key $keyIdentifier --identity testIdentity --backup-key $geoKeyIdentifier --backup-identity geoIdentity`
- Show connection strings for cmd and programming languages with PgBouncer enabled.
`az postgres flexible-server show-connection-string -s testserver -u username -p password -d databasename --pg-bouncer`
- Update a flexible server to update private DNS zone for a VNET enabled server, using private DNS zone in the different resource group and subscription. Private DNS zone will be linked to the VNET if not already linked.
`az postgres flexible-server update --resource-group testGroup --name testserver --private-dns-zone /subscriptions/{SubId2}/resourceGroups/{testGroup2}/providers/Microsoft.Network/privateDnsZones/testDNS.postgres.database.azure.com`
- Create a flexible server by reviving a dropped server
`az postgres flexible-server revive-dropped -l testLocation -g testGroup --source-server /subscriptions/{SubId}/resourceGroups/{testGroup}/providers/Microsoft.DBforPostgreSQL/flexibleServers/{sourceServer} --name testServerName`

**Description**
Updated to use new API version for PostgreSQL flexible server features below:
1. Geo backup and Geo-restore with Data encryption.
2. Connection string updated for an incident
3. Allow update of private DNS zone via CLI which was not missing in CLI

**Testing Guide**
Tested manually

**History Notes**

[RDBMS] `az postgres flexible-server create`: Add support to create PostgreSQL flexible server with data encryption enabled for geo-backup enabled server by pasing parameters `--geo-redundant-backup`, `--backup-key` and `--backup-identity`
[RDBMS] `az postgres flexible-server show-connection-string`: Add support to pass `--pg-bouncer` in connection strings for cmd and programming languages with PgBouncer enabled for PostgreSQL flexible server. This will allow users to see correct port for PgBouncer enabled servers. Updated connection strings to show port as well as database
[RDBMS] `az postgres flexible-server update`: Add support for paramater `--private-dns-zone` during update operation, to update private DNS zone for a VNET enabled PostgreSQL flexible server, using private DNS zone in the different resource group and subscription. Private DNS zone will be linked to the VNET if not already linked
[RDBMS] `az postgres flexible-server migration create`: Add support for tags and location using `--tags` and `--location`
[RDBMS] BREAKING CHANGE: `az postgres flexible-server migration update`: Remove unsupported update parameters `--db-names` and `--overwrite-dbs`
[RDBMS] `az postgres flexible-server revive-dropped`: Add support to create PostgreSQL flexible server by reviving a dropped flexible server by pasing parameters `--source-server`, `--location` and `--resource-group`

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
RDBMS

**Comment by evelyn-ys** [comment]
Please make sure all CI checks can pass.

BTW, the code complete date for July 4th release is 6/28, which is tomorrow. If this PR can't be merged by tomorrow, I will change the milestone to next sprint

**Comment by ambrahma** [comment]
> Please make sure all CI checks can pass.
> 
> BTW, the code complete date for July 4th release is 6/28, which is tomorrow. If this PR can't be merged by tomorrow, I will change the milestone to next sprint

Hi @evelyn-ys , this PR is ready to be merged. Can you please help merge this one and include it for current milestone release?

**Review by pradeepkintali — APPROVED** [review]

**Comment by evelyn-ys** [comment]
Please confirm if the breaking changes detected are necessary. We only allow breaking change twice a year and July 4th release is not breaking change window

**Comment by ambrahma** [comment]
> [RDBMS] BREAKING CHANGE: `az postgres flexible-server migration update`: Remove unsupported update parameters `--db-names` and `--overwrite-dbs`

Made only one breaking change as those unsupported operations would never work for the end user and had also added comment for the same in History notes: [RDBMS] BREAKING CHANGE: az postgres flexible-server migration update: Remove unsupported update parameters --db-names and --overwrite-dbs

Other breaking changes like change of default values, I am not sure about those as I havent changed anything there.

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
