### PR TITLE
Dependency azure-cli 0.33 => 0.34

### PR DESCRIPTION
**Pull request by troydai**

### CODE REVIEW

**Comment by derekbekoe** [comment]
What changes were in this update? Will it impact the VM module also/

**Comment by troydai** [comment]
Change log: https://github.com/Azure/azure-storage-python/blob/0c736d4ad26000519e1addafd7f8794e3945a084/ChangeLog.md#version-0340

Needed for May 10th build features.

**Comment by troydai** [comment]
And here's the breaking changes: https://github.com/Azure/azure-storage-python/blob/0c736d4ad26000519e1addafd7f8794e3945a084/BreakingChanges.md#version-0340

**Comment by troydai** [comment]
Close this PR for now. I will rerecord all the tests.

**Pull request closed without merging**
