### PR TITLE
[Profile] `az login`: Use device code flow in GitHub Codespaces

### PR DESCRIPTION
**Pull request by jiasli**
**Related command**
`az login`

**Description**
A temporary solution for https://github.com/Azure/azure-cli/issues/20315

Rework on @sinedied's original PR https://github.com/Azure/azure-cli/pull/27443

In [GitHub Codespaces](https://github.com/features/codespaces), `webbrowser.open()` can open a new tab in the current browser, this makes Azure CLI think a browser is available.

```py
$ python3
>>> webbrowser.get()
<webbrowser.GenericBrowser object at 0x770dbab24e30>
>>> webbrowser.get().name
'/vscode/bin/linux-x64/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/bin/helpers/browser.sh'
>>> webbrowser.open('https://www.microsoft.com/')
True
```

However, after a successful login, the auth code is sent to the redirect URL `http://localhost:xxxxx/` on the local machine, not the Codespace. 

Before we figure out a complete and secure solution with Entra team, we fall back to device code flow in GitHub Codespaces.

**Testing Guide**
In [GitHub Codespaces](https://github.com/features/codespaces), run

```
az login
```

### CODE REVIEW

**Comment by yonzhan** [comment]
Profile

**Comment by jiasli** [comment]
Do this in #27443.

**Comment by jiasli** [comment]
I have verified the PR works as expected in GitHub Codespaces:

image

**Pull request closed without merging**
