### PR TITLE
Added information for empty parameter when using Azure CLI in PowerShell

### PR DESCRIPTION
**Pull request by The-First-Tiger**
Added information to use '""' or --% operator in PowerShell for parameters:
--public-ip-address
--nsg

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by haroldrandom** [comment]
@qwordy Please help here

**Comment by yonzhan** [comment]
@qwordy please help with the PR.

**Comment by qwordy** [comment]
Thanks a lot for your contribution. You are right. I am thinking about how we can use a systematic way to let users know it easily. There are many parameters that can be "".

**Comment by The-First-Tiger** [comment]
Maybe a global section like "global parameters"?

**Comment by MyronFanQiu** [comment]
I met this issue recently. For generic_update_command, we can also use `--remove paramName`. A systematic way may be to add support in azure-cli-core so that we can have something like `enable_detach=true` in `c.argument`.

**Pull request merged**
