### PR TITLE
[containerapp] `az containerapp env workload-profile`: Fix issue when deleting wp with custom domain

### PR DESCRIPTION
**Pull request by Juliehzl**
**Related command**

**Description**

**Testing Guide**

**History Notes**

[containerapp] BREAKING CHANGE: `az containerapp env workload-profile update`: Remove `--workload-profile-type` as it does not work in server side
[containerapp] `az containerapp env workload-profile delete`: Fix issue when deleting wp for env with custom domain

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
containerapp

**Review by Greedygre — APPROVED** [review]

**Comment by yonzhan** [comment]
Please fix CI issues.

**Comment by Greedygre** [comment]
> Please fix CI issues.
@yonzhan 
The CI issue not relat to out service, could you help to handle or ask the relate team to fix? It blocks the PR merge.
```


ERROR: cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
ERROR: az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
ERROR: cli.azure.cli.core.azclierror: The operation 'azext_aosm.custom#generate_definition_config' is invalid.
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
    handler = import_module(mod_to_import)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/az/azcliextensions/aosm/azext_aosm/custom.py", line 23, in <module>
    from azext_aosm._configuration import (
  File "/opt/az/azcliextensions/aosm/azext_aosm/_configuration.py", line 267, in <module>
    @dataclass
     ^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'azext_aosm._configuration.ArtifactConfig'> for field arm_template is not allowed: use default_factory

During handling of the above exception, another exception occurred:



```

**Comment by yanzhudd** [comment]
> > Please fix CI issues.
> > @yonzhan
> > The CI issue not relate to our service, could you help to handle or ask the relate team to fix it? It blocks the PR merge.
> 
> ```
> 
> 
> ERROR: cli.azure.cli.core.azclierror: The command failed with an unexpected error. Here is the traceback:
> ERROR: az_command_data_logger: The command failed with an unexpected error. Here is the traceback:
> ERROR: cli.azure.cli.core.azclierror: The operation 'azext_aosm.custom#generate_definition_config' is invalid.
> Traceback (most recent call last):
>   File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 59, in get_op_handler
>     handler = import_module(mod_to_import)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/opt/az/azcliextensions/aosm/azext_aosm/custom.py", line 23, in <module>
>     from azext_aosm._configuration import (
>   File "/opt/az/azcliextensions/aosm/azext_aosm/_configuration.py", line 267, in <module>
>     @dataclass
>      ^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/dataclasses.py", line 1230, in dataclass
>     return wrap(cls)
>            ^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/dataclasses.py", line 1220, in wrap
>     return _process_class(cls, init, repr, eq, order, unsafe_hash,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/dataclasses.py", line 958, in _process_class
>     cls_fields.append(_get_field(cls, name, type, kw_only))
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/dataclasses.py", line 815, in _get_field
>     raise ValueError(f'mutable default {type(f.default)} for field '
> ValueError: mutable default <class 'azext_aosm._configuration.ArtifactConfig'> for field arm_template is not allowed: use default_factory
> 
> During handling of the above exception, another exception occurred:
> ```

Sorry the CI is failed because of a previous PR. And now the fix PR has been merged. Let's rerun the CI

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
