### PR TITLE
remove python 3.4 support

### LINKED ISSUE #11391: Remove support for Python 3.4
Python 3.4 has been removed from [azure-sdk-for-python](https://github.com/Azure/azure-sdk-for-python#azure-sdk-for-python) and is not supported for some features. Azure CLI should also remove it.

### PR DESCRIPTION
**Pull request by fengzhou-msft**
Fix #11391

### CODE REVIEW

**Comment by yungezz** [comment]
what's the whole plan of remove python 3.4 support, such as plan for users using 3.4 today

**Comment by fengzhou-msft** [comment]
> what's the whole plan of remove python 3.4 support, such as plan for users using 3.4 today

Current azure-cli code already breaks with python 3.4, this is to remove python 3.4 from language support list.

**Comment by haroldrandom** [comment]
@fengzhou-msft Could you reference some issues or problems?

Offering a case, but not related to OpenSSL.
I test to install azure-cli in Ubuntu 18.04 under Python 3.4. Breaks by requests~2.22 not supported.

image

**Comment by fengzhou-msft** [comment]
> @fengzhou-msft Share we add Python 3.8 support in all setup.py recently?

We have done that for the main packages in last sprint. I added it in the remaining setup.py files in this PR.

**Pull request merged**
