### PR TITLE
{Auto Complete} Fix default completer

### LINKED ISSUE #3807: According to telemetry, we have a problem with tab completion
**Message:** <lambda>() got an unexpected keyword argument _prefix_
**Stack**: [_ File _usrlocallibpython3.5site-packagesazureclimain.py_, line 36, in main\n cmd_result = APPLICATION.execute(args)\n_, _ File _usrlocallibpython3.5site-packagesazureclicoreapplication.py_, line 179, in execute\n enable_autocomplete(self.parser)\n_, _ File _usrlocallibpython3.5site-packagesazureclicoreparser.py_, line 41, in enable_autocomplete\n default_completer=lambda _: ())\n_, _ File _usrlocallibpython3.5site-packagesargcomplete__init__.py_, line 214, in __call__\n completions = self._get_completions(comp_words, cword_prefix, cword_prequote, last_wordbreak_pos)\n_, _ File _usrlocallibpython3.5site-packagesargcomplete__init__.py_, line 244, in _get_completions\n completions = self.collect_completions(active_parsers, parsed_args, cword_prefix, debug)\n_, _ File _usrlocallibpython3.5site-packagesargcomplete__init__.py_, line 453, in collect_completions\n completions)\n_, _ File _usrlocallibpython3.5site-packagesargcomplete__init__.py_, line 407, in _complete_active_option\n prefix=cword_prefix, action=active_action, parser=parser, parsed_args=parsed_args)\n_]

I can provide additional callstacks if needed in order to investigate...

### PR DESCRIPTION
**Pull request by fengzhou-msft**
**Description**  

Fix #3807

The current default completer only takes one positional argument and will throw an error when invoked in `argcomplete` with keyword argument:
https://github.com/kislyuk/argcomplete/blob/a93a4f4dc785373f320d168d2d5a1a11bdc50315/argcomplete/__init__.py#L452-L454
`completer(prefix=cword_prefix, action=active_action, parser=parser, parsed_args=parsed_args)`

This PR makes the default completer take any number of positional or keyword arguments.

**Testing Guide**  

On Ubuntu, turn on argcomplete debug with:
`export _ARC_DEBUG=1`

Type the following command and press tab key.
`az vm show --ids /sub`

You can see the error: `TypeError: <lambda>() got an unexpected keyword argument 'prefix'`

Apply the change in this PR to argcomplete by running:
`eval "$(register-python-argcomplete az)"`

Repeat the step for tab completion and the error is gone.

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Which platform does it support?

**Review by houk-ms — APPROVED** [review]
great findings! It would help reduce A LOT of the client side TypeErrors!

**Comment by fengzhou-msft** [comment]
> Which platform does it support?

Linux and macOS.

**Review by arrownj — APPROVED** [review]
💯

**Review by jiasli — APPROVED** [review]

**Comment by houk-ms** [comment]
#15314

**Pull request merged**
