### PR TITLE
[RDBMS] Change MySQL MemoryOptimized tier name to BusinessCritical

### PR DESCRIPTION
**Pull request by DaeunYim**
**Description**

1. Changing customer facing naming of 'MemoryOptimized' tier to 'BusinessCritical' tier. 
No change in RP and only CLI changes in list-skus, create, update commands
2. Location capabilities API table transformer bug fix

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
RDBMS

**Comment by DaeunYim** [comment]
@evelyn-ys Could you run azp-run for this PR please?

**Review by evelyn-ys — APPROVED** [review]
LGTM but I'm curious why not make this change in server side.

**Pull request merged**
