### PR TITLE
[CosmosDB] Allow sever version to be updated.

### PR DESCRIPTION
**Pull request by craigtmc-msft**
**Description**
Allow server version to be updated in CosmosDB accounts.  This allows mongo accounts to update the mongo api version from the CLI.

**Testing Guide**
az cosmosdb update --name <account_name>--resource-group <resource_group> --server-version 4.0

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
CosmosDB

**Comment by evelyn-ys** [comment]
Hi @craigtmc-msft, it seems some recording tests failed after version upgraded, could you take a look?

**Comment by evelyn-ys** [comment]
Hi @craigtmc-msft, Is this PR for Ignite? Pls keep in mind that our release for ignite($183) is going to close by tomorrow.

**Comment by craigtmc-msft** [comment]
This can be discarded.  Changes were included with https://github.com/Azure/azure-cli/pull/17021

**Pull request closed without merging**
