### PR TITLE
[AKS] fix the aks browse in cloud shell.

### PR DESCRIPTION
**Pull request by andyliuliming**
**History Notes:**  
(Fill in the following template if multiple notes are needed, otherwise PR title will be used for history note.)

[Component Name 1] (BREAKING CHANGE:) (az command:) make some customer-facing change.  
[Component Name 2] (BREAKING CHANGE:) (az command:) make some customer-facing change.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yungezz** [comment]
hi @qwordy  @fengzhou-msft  could you pls help to look at this PR? thanks.

**Comment by kennethgp** [comment]
It seems this is broken again, the Cloud Shell CLI 2.1.0 without aks-preview extension shows the JSON API, with the extension it now shows an URL in this form, which opens a blank page:   https://gateway18.eastus.console.azure.com/n/cc-373a90e2/cc-373a90e2/proxy/8001/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy

**Comment by andyliuliming** [comment]
@kennethgp will be fixed by this PR:
https://github.com/Azure/azure-cli/pull/12411

**Comment by JuneZhao** [comment]
@kennethgp @andyliuliming  Thank for your efforts, how long can we have this in azure cli cause both me and my customer tested this function it is still not working as expected,
image

image

**Comment by andyliuliming** [comment]
@JuneZhao  this is released in 2.2.0 . please help double check

**Pull request merged**
