### PR TITLE
[AKS] update max standard load balancer timeout to 100 minutes

### PR DESCRIPTION
**Pull request by gtracer**
**Description**  

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by yungezz** [comment]
hi @arrownj could you pls help to review?

**Comment by gtracer** [comment]
@arrownj please let me know if there is any feedback or if we are ready to merge

**Review by arrownj — APPROVED** [review]
LGTM

**Pull request merged**
