### PR TITLE
[EventHub] : Fix for issue #12406 Argument --capture-interval does not update the "intervalInSeconds"

### PR DESCRIPTION
**Pull request by v-Ajnava**
**Description**  

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S168

**Comment by v-Ajnava** [comment]
fix for issue : https://github.com/Azure/azure-cli/issues/12406

**Comment by yonzhan** [comment]
add to S170

**Comment by v-Ajnava** [comment]
Hi @Juliehzl, @qianwens  and @zhoxing-ms , 

Can you please review the PR

**Pull request merged**
