### PR TITLE
{Containerapp} Fix documentation links for job yaml

### PR DESCRIPTION
**Pull request by lihaMSFT**
**Related command**
`az containerapp job create`
`az containerapp job update`

**Description**
This command changes the referenced documentation link.

**Testing Guide**

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by yonzhan** [comment]
Please fix CI issues

**Comment by lihaMSFT** [comment]
@yonzhan fixed. can you help rerun?

**Review by vinisoto — APPROVED** [review]

**Review by anandanthony — APPROVED** [review]

**Comment by Greedygre** [comment]
The title should be:
[Container app] `az containerapp job create/update`: Fix documentation links for job yaml

**Review by Greedygre — APPROVED** [review]

**Pull request merged**
