### PR TITLE
[AKS] `az aks create`: Remove unsupported scenario command in help message

### PR DESCRIPTION
**Pull request by schaffererin**

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by schaffererin** [comment]
Hi @zhagao-ms, @jsntcy, @yanzhudd, @yonzhan - I'm not sure why certain checks are failing. Could you please help out here? I just want to remove a single command, as it's an unsupported AKS scenario.

**Comment by schaffererin** [comment]
Hi @zhoxing-ms - any update here?

**Comment by yonzhan** [comment]
Please fix CI issues

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
