### PR TITLE
{KeyVault} Modify random vault name prefix

### PR DESCRIPTION
**Pull request by bim-msft**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by bim-msft** [comment]
@jiasli Reduced the name prefix to meet the rule and reran all tests according to your advice, please review it again.

**Comment by jiasli** [comment]
After live run `KeyVaultCertificateDefaultPolicyScenarioTest`, the recording yaml is removed. CI reports [failure](https://dev.azure.com/azure-sdk/public/_build/results?buildId=253736&view=logs&j=201a69fb-575c-5f90-d252-d1ed1e360cc3&t=fb98e434-311f-5204-eaf4-065ec0de8a99&l=7353):

```
  File "/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/azure/cli
    /command_modules/resource/custom.py", line 736, in create_resource_group
  ...
knack.util.CLIError: Please run 'az login' to setup account.
```

By looking into `ResourceGroupPreparer` then `live_only_execute`, see this line returns `True`:

https://github.com/Azure/azure-cli/blob/12f874628f31f6953da1ba1593d815e2c4b9d77f/src/azure-cli-testsdk/azure/cli/testsdk/preparers.py#L34

Then find usage of `in_recording` reviews [this line](https://github.com/Azure/azure-python-devtools/blob/a9cca7d22989d8a3e6f559e617e704f68c61ba06/src/azure_devtools/scenario_tests/base.py#L123) in azure_devtools. 

```py
self.in_recording = self.is_live or not os.path.exists(self.recording_file)
```

Since resource creation and deletion commands are not recorded and there is no network traffic in the test body, after live run the yaml is not created. Later when running with vcr, `ReplayableTest` still thinks this is a live test and tries to create the resource group. This doesn't cause problem locally because `az` has been logged in, but in CI it has not. 

To solve it, we can simply remove: 

```py
@ResourceGroupPreparer(name_prefix='cli_test_kv_cert_default_policy')
```

**Comment by jiasli** [comment]
After live run `KeyVaultCertificateDefaultPolicyScenarioTest`, the recording yaml is removed. CI reports [failure](https://dev.azure.com/azure-sdk/public/_build/results?buildId=253736&view=logs&j=201a69fb-575c-5f90-d252-d1ed1e360cc3&t=fb98e434-311f-5204-eaf4-065ec0de8a99&l=7353):

```
  File "/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/site-packages/azure/cli
    /command_modules/resource/custom.py", line 736, in create_resource_group
  ...
knack.util.CLIError: Please run 'az login' to setup account.
```

By looking into `ResourceGroupPreparer` then `live_only_execute`, see this line returns `True`:

https://github.com/Azure/azure-cli/blob/12f874628f31f6953da1ba1593d815e2c4b9d77f/src/azure-cli-testsdk/azure/cli/testsdk/preparers.py#L34

Then find usage of `in_recording` reveals [this line](https://github.com/Azure/azure-python-devtools/blob/a9cca7d22989d8a3e6f559e617e704f68c61ba06/src/azure_devtools/scenario_tests/base.py#L123) in azure_devtools. 

```py
self.in_recording = self.is_live or not os.path.exists(self.recording_file)
```

How it fails:
1. Because `group create/delete` commands are not recorded and there is no network traffic in the test body, after live run the yaml is not created
2. When running as recording, `ReplayableTest` gets `is_live == False`, but still thinks this is a live test because the yaml doesn't exists. In other words, the current design requires `ResourceGroupPreparer` to be paired with a recording yaml for the test to be treated as **recording**. Even if no `--live` or `AZURE_TEST_RUN_LIVE` is specified, lacking of yaml will still turn this test into a live test
3. The test is ran as live. This doesn't cause problem locally because `az` has been logged in, but in CI it has not. 

To solve it, simply remove: 

```py
@ResourceGroupPreparer(name_prefix='cli_test_kv_cert_default_policy')
```

**Pull request merged**
