### PR TITLE
[Search] Introduce async options for service and shared-private-link-resource commands

### PR DESCRIPTION
**Pull request by huangbolun**
**Description**
Introduce async (--no-wait) options for `search service` and `search shared-private-link-resource` commands;

**Testing Guide**
N/A

**History Notes**
[Search] az search service create: Add async (--no-wait) options.
[Search] az search service update: Add async (--no-wait) options.
[Search] az search shared-private-link-resource create: Add async (--no-wait) options.
[Search] az search shared-private-link-resource update: Add async (--no-wait) options.
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Search

**Comment by huangbolun** [comment]
@kairu-ms, any idea why the Azure.azure-cli check is always waiting for status to be reported? Is there an pipeline outage?

**Comment by kairu-ms** [comment]
> @kairu-ms, any idea why the Azure.azure-cli check is always waiting for status to be reported? Is there an pipeline outage?

Our pipeline needs manual trigger now, because it was attacked several weeks ago.

**Review by kairu-ms — CHANGES_REQUESTED** [review]
You should add `no_wait` parameter in custom function signature and use `sdk_no_wait` to call LongRuningOperation. You can follow this example:

https://github.com/Azure/azure-cli/blob/ee405d307ca84d6013c53c5248e67903b61331f0/src/azure-cli/azure/cli/command_modules/monitor/operations/log_analytics_workspace_linked_service.py#L9-L17

**Comment by huangbolun** [comment]
> You should add `no_wait` parameter in custom function signature and use `sdk_no_wait` to call LongRuningOperation. You can follow this example:
> 
> https://github.com/Azure/azure-cli/blob/ee405d307ca84d6013c53c5248e67903b61331f0/src/azure-cli/azure/cli/command_modules/monitor/operations/log_analytics_workspace_linked_service.py#L9-L17

This is done.

**Comment by huangbolun** [comment]
@kairu-ms, why is it failed when the LINT is [PASSED]: https://dev.azure.com/azure-sdk/public/_build/results?buildId=813902&view=logs&j=168ccbe3-da49-5c0b-6478-08f7016e4bf5&t=10a595be-4223-5cc7-9a73-012871b6eaee

**Comment by kairu-ms** [comment]
You miss help for some commands. Please see [logs](https://dev.azure.com/azure-sdk/public/_build/results?buildId=813902&view=logs&j=bb340607-7cd4-5efc-b5d6-65a14d5a2343&t=eaf6a1a1-b668-52da-325f-6773cd56fb22&l=103) for details.

**Review by kairu-ms — APPROVED** [review]

**Comment by huangbolun** [comment]
@kairu-ms, all checks are passed and the change is ready to merge.

**Pull request merged**
