### PR TITLE
[ACR] az acr connected-registry create: Removing ancestors active validation.

### PR DESCRIPTION
**Pull request by rosanch**
**Description**
The PR #17566 was merged before all comments were resolved. I need to remove a validation check from the command before release. 

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by rosanch** [comment]
@fengzhou-msft  can you review, please? There was pr merged before I could apply the changes

**Review by northtyphoon — APPROVED** [review]
LGTM

**Comment by rosanch** [comment]
@fengzhou-msft is there any chance we can get this in the release?

**Comment by fengzhou-msft** [comment]
@rosanch please change the target branch to be `release` branch. We will have a hotfix release next Monday.

**Review by fengzhou-msft — APPROVED** [review]

**Comment by fengzhou-msft** [comment]
Code merged in Hotfix PR #17749 and will be merged back into dev branch after hotfix release.

**Pull request closed without merging**
