### PR TITLE
added record processor for slashes

### PR DESCRIPTION
**Pull request by williexu**
---
Connected to https://github.com/Azure/azure-python-devtools/pull/31
Merge after^
Added processor on cli side

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [na ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [na ] Each command and parameter has a meaningful description.
- [na ] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by troydai** [comment]
This PR doesn't age well. The processor's name just changed. It also requires the azure.cli.testsdk package to have it's dependency on azure.devtools upgrade to 0.5.1 first. It depends on 0.4.3. (this PR is doing just that: https://github.com/Azure/azure-cli/pull/4396)

**Comment by lmazuel** [comment]
Once #4396 is merged, @williexu please rebase your branch to get 0.5.1 by default

**Comment by williexu** [comment]
Will do

**Comment by troydai** [comment]
This PR includes the changes on #4396, I will close another PR.

**Pull request merged**
