### PR TITLE
[ARO] az aro delete: Add RBAC validation on cluster deletion

### PR DESCRIPTION
**Pull request by ehashman**
**Description**

Upstreams https://github.com/Azure/ARO-RP/pull/1126 which adds RBAC validation on ARO cluster deletion, unblocking deletions when customers remove SPN permissions.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by ehashman** [comment]
cc @jim-minter @mjudeikis

**Comment by yonzhan** [comment]
ARO

**Review by jim-minter — APPROVED** [review]
LGTM, please merge.

**Comment by ehashman** [comment]
@haroldrandom @fengzhou-msft could you PTAL? :)

**Review by haroldrandom — APPROVED** [review]

**Comment by jiasli** [comment]
This PR's is not compatible with #16131 because #16131 bumped `ResourceType.MGMT_NETWORK` to `2020-07-01`, causing `test_aro_delete` to fail: 

https://dev.azure.com/azure-sdk/public/_build/results?buildId=648860&view=logs&j=771f6cdf-8d98-5d9b-2fb9-d3a6e9554788&t=0a182f1d-9946-580d-467e-4d4ebd6af32d&l=2628

```
2020-12-10T07:06:38.2367045Z AssertionError: Can't overwrite existing cassette ('/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/azure/cli/command_modules/aro/tests/latest/recordings/test_aro_delete.yaml') in your current record mode ('once').
2020-12-10T07:06:38.2369298Z No match for the request (<Request (GET) https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_aro_delete000001/providers/Microsoft.Network/virtualNetworks/dev-vnet/subnets/dev_master000002?api-version=2020-07-01>) was found.
```

**Pull request merged**
