### PR TITLE
[Container] `az container exec`: Fix and improve terminal experience

### PR DESCRIPTION
**Pull request by novinc**
**Description**
There were a few issues with the container exec experience:
1. terminal characters where not being handled correctly. I have added enabling virtual terminal mode to fix this.
2. on windows handling of bytes type messages ran into exceptions. use the stdout.buffer to be able to write bytes directly instead of decoding to str.
3. the logic between linux and windows was too different. Converge on a similar model for both linux and windows.
4. arrow keys and ctrl+c did not work on windows. This is fixed now

**Testing Guide**
az container exec -n {cgname} -g {rgname} --exec-command {/bin/bash or /bin/sh or cmd or pwsh}
Run exec sessions with different images (both linux and windows) and see if the terminal window behaves ok
Arrow keys and ctrl+c should also work in both linux and windows

I don't own a Mac device so wasn't able to validate the changes there

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Azure Container Instances

**Comment by zhoxing-ms** [comment]
@novinc Could you please fix the CI issue and change `Fix and improve terminal experience` in the PR title to be more specific?

**Comment by novinc** [comment]
> @novinc Could you please fix the CI issue and change `Fix and improve terminal experience` in the PR title to be more specific?

Sure I'll take a look at the CI issues.
As far as the title do you have any suggestions? There are a couple of changes so I'm not sure if I should have everything in there

**Comment by zhoxing-ms** [comment]
@novinc How about changing it to
> [Container] `az container exec`: Fix terminal character handling issue and support arrow keys and Ctrl+C on Windows

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
