### PR TITLE
{packaging} Update knack to 0.8.3

### PR DESCRIPTION
**Pull request by major**
**Description**
The latest version of knack is 0.8.3 and it was just released.

**Testing Guide**
Existing tests should be used.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by jiasli** [comment]
Thanks @major. The latest knack introduced breaking change about colorama (https://github.com/microsoft/knack/pull/249).

The corresponding Azure CLI adaptation will be covered by https://github.com/Azure/azure-cli/pull/20195.

**Comment by jiasli** [comment]
By the way, just out of curiosity, how did you notice there is a new knack release? 😆

**Comment by major** [comment]
@jiasli Oh, I have knack packaged in Fedora. When a new release appears on GitHub, [Anitya](https://release-monitoring.org/project/87148/) opens a [bugzilla ticket](https://bugzilla.redhat.com/show_bug.cgi?id=2020145) for me to package the update. It's usually pretty fast at finding new releases.

**Comment by major** [comment]
I guess I'll close this ticket since the work is happening in #20195

**Comment by jiasli** [comment]
Interesting. Just a kind reminder that Knack is not stable yet since the major version is still `0`, we don't guarantee its backward compatibility (just like the colorama dependency change (https://github.com/microsoft/knack/pull/249) -  libraries depending on knack shouldn't assume colorama will always be installed).

**Pull request closed without merging**
