### PR TITLE
[Azure Monitor] Adding Azure monitor commands for management and data plane

### PR DESCRIPTION
**Pull request by vishrutshah**
This command module exposes following commands. This module takes dependency on [azure-mgmt-monitor](https://pypi.python.org/pypi/azure-mgmt-monitor) version `0.1.0` and [azure-monitor](https://pypi.python.org/pypi/azure-monitor) version `0.2.0`. 

```
(env) vishrut@mac azure-cli (monitor) $ az monitor -h

Group
    az monitor: Commands to manage Azure Monitor service.

Subgroups:
    activity-log              : Commands to manage activity log.
    alert-rule-incidents       : Commands to manage alert rule incidents.
    alert-rules                : Commands to manage alerts assigned to Azure resources.
    autoscale-settings         : Commands to manage autoscale settings.
    log-profiles               : Commands to manage the log profiles assigned to Azure subscription.
    metric-definitions         : Commands to manage metric definitions.
    metrics                    : Commands to manage metrics.
    diagnostic-settings: Commands to manage service diagnostic settings.
```

Following are the areas, we'd like to request the partner teams sign-off for this module to go preview:
- [x] Expected coverage of the commands for the Azure monitor service
- [x] Correctness and accuracy of the help document for each of the commands. Specifically review [help.json](https://github.com/Azure/azure-cli/pull/2534/commits/9f1b1e3f999f1b1df87123a5ba42f83df1cfea45) file. I will remove that file before merging the PR.
- [x] Basic understanding on the implementation on each commands

 @johnkemnetz / @gucalder Please help us review this command module.

### CODE REVIEW

**Comment by vishrutshah** [comment]
I am planning to update this PR with following changes. Let me know if you have any preferences:

- [ ] Rename `autoscale-settings` to `autoscale`
- [ ] Rename `service-diagnostic-settings` to `diagnostic-settings`
- [ ] Being `activity-logs` & `tenant-activity-logs` differs in the REST enpoing, I will expose flag --tenant into `activity-logs` to perform all the respective operations

**Comment by troydai** [comment]
@vishrutshah, please make sure you limit the number of the commits to this pull request. Each commit will trigger a new Travis CI build. We're trying to save the resource here.

**Comment by johnkemnetz** [comment]
Few comments:

- [ ] Can we rename activity-logs to activity-log (singular) -- we describe it as a single log.
- [ ] Not blocking, but we help the user a lot more with creating an alert in PowerShell (https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/insights-powershell-samples#create-alert-rules). In this we simply assume they have the JSON ready to go. Maybe we can ask for those arguments and build the JSON based off of them like we do in PowerShell?
- [ ] event-categories isn't a very helpful command -- it's mainly in our API for the Portal. We might consider removing it.
- [ ] az monitor log-profiles create -- the 'parameters' argument doesn't make sense as required to me. If you've used the storage-account-id and/or service-bus-rule-id, then you have no need for that parameters argument.
- [ ] az monitor metrics list -- the 'metric-names' argument is not listed as required, but it actually is.
- [ ] az monitor service-diagnostic-settings create -- per the above, this should just be 'diagnostic settings'. Also, can we break out the metrics and logs JSON arguments into regular arguments. You only need the log categories and whether metrics should be enabled or not -- timegrain isn't something that is user configurable, it always has to be PT1M. We do this in the PowerShell.
- [ ] tenant-activity-logs -- we should just remove this from the CLI. The issue is that getting permissions to have this API call actually work is a bit tricky, since it's RBAC at the tenant level, so for most people it will return an auth error. It's also not used frequently.

**Comment by vishrutshah** [comment]
Based on the feedback & suggestions from @johnkemnetz, following actions have been completed:

- [x] Rename `activity-logs` to `activity-log`
- [x] Rename `service-diagnostic-settings` to `diagnostic-settings`
- [x] Remove command `tenant-activity-logs`
- [x] Remove command `event-categories`

Some question for @johnkemnetz :

- [ ] Regarding `parameters` being required in `az monitor log-profiles create`, this command has expanded that arguments to convert complex object into primitive parameters. I do not see that we have `parameters` or I am missing something: [Reference](https://github.com/Azure/azure-cli/pull/2534/files#diff-eee331ea0e084a12e7842649e4aac7b4R406) 
- [ ] Regarding taking JSON as inputs, from the python cli design perspective, we'd find it really hard for users to supply "List of complex objects" from cli. In those cases, we'd be inclined towards providing convenience commands but can be done incrementally. What do you think? 
- [ ] Regarding `az monitor service-diagnostic-settings create` command, are you referring to `time_grain` of `metrics` to be defaulted to `PT1M`? If so, I'd request you to please update swagger's [MetricSettings](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-monitor/2015-07-01/swagger/diagnosticsSettings_API.json#L222) to accurately describe the API with correct defaults. Fixing that at the root would help us fix this at SDKs (Python, NodeJS, Ruby, .Net, Go, Java) + CLI + Fluent SDKs (.Net + Java) :)

**Comment by johnkemnetz** [comment]
@vishrutshah : 
- Interesting, here's the screenshot I see when I type that command:
image
- It's fine to incrementally build up from complex objects, I just think that the arguments for 'metrics' and 'logs' today (JSON encoded lists of metric/log settings) aren't very user-friendly:
image
- Understood, I'll ask Guillermo to update that.

**Comment by vishrutshah** [comment]
Open bugs for enhancements/features:

https://github.com/Azure/azure-cli/issues/2582
https://github.com/Azure/azure-cli/issues/2583

**Comment by vishrutshah** [comment]
Thanks for the review!!

**Pull request merged**
