### PR TITLE
[AKS] Add "az aks update --uptime-sla"

### PR DESCRIPTION
**Pull request by zqingqing1**
**Description**  

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by zqingqing1** [comment]
I tried to run the test without my change, but failed with following error.  I feel the test is not stable, and my change shouldn't have any issue so reluctant to write test for it.
```
AZURE_CLI_TEST_MODULES=acs azdev test test_aks_create_default_service --discover --live

=============
| Run Tests |
=============

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/qizhe/azure-cli/azure-cli/src/azure-cli/azure/cli/__main__.py", line 33, in <module>
    az_cli = get_default_cli()
  File "/Users/qizhe/azure-cli/azure-cli/src/azure-cli-core/azure/cli/core/__init__.py", line 599, in get_default_cli
    from azure.cli.core.azlogging import AzCliLogging
  File "/Users/qizhe/azure-cli/azure-cli/src/azure-cli-core/azure/cli/core/azlogging.py", line 30, in <module>
    from azure.cli.core.commands.events import EVENT_INVOKER_PRE_CMD_TBL_TRUNCATE
  File "/Users/qizhe/azure-cli/azure-cli/src/azure-cli-core/azure/cli/core/commands/__init__.py", line 28, in <module>
    from azure.cli.core.extension import get_extension
  File "/Users/qizhe/azure-cli/azure-cli/src/azure-cli-core/azure/cli/core/extension/__init__.py", line 11, in <module>
    import pkginfo
ModuleNotFoundError: No module named 'pkginfo'
can only concatenate str (not "bytes") to str
Traceback (most recent call last):
  File "/Users/qizhe/azure-cli/azure-cli/env/lib/python3.7/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/Users/qizhe/azure-cli/azure-cli/env/lib/python3.7/site-packages/knack/invocation.py", line 225, in execute
    cmd_result = parsed_args.func(params)
  File "/Users/qizhe/azure-cli/azure-cli/env/lib/python3.7/site-packages/knack/commands.py", line 147, in __call__
    return self.handler(*args, **kwargs)
  File "/Users/qizhe/azure-cli/azure-cli/env/lib/python3.7/site-packages/knack/commands.py", line 254, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/Users/qizhe/azure-cli/azure-cli/env/lib/python3.7/site-packages/azdev/operations/tests/__init__.py", line 44, in run_tests
    original_profile = _get_profile(profile)
  File "/Users/qizhe/azure-cli/azure-cli/env/lib/python3.7/site-packages/azdev/operations/tests/__init__.py", line 158, in _get_profile
    .format(fore_red + original_profile + fore_reset))
TypeError: can only concatenate str (not "bytes") to str
```

**Comment by qwordy** [comment]
You may need to create a new virtual environment and install azdev.

**Comment by zqingqing1** [comment]
Not only this problem, but met others: how to fix it? 
```
ZURE_CLI_TEST_MODULES=acs azdev test test_aks_create_default_service --discover --live
az: 'cloud' is not in the 'az' command group. See 'az --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
Failed to retrieve current az profile
```

**Pull request merged**
