### PR TITLE
{Compute} Update _help.py - add link to article for finding an image URN

### PR DESCRIPTION
**Pull request by cynthn**
Adding a link to an article that walks folks through how to get the URN for an image.

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
vm

**Review by qwordy — APPROVED** [review]
Thanks!

**Review by yungezz — APPROVED** [review]

**Comment by yungezz** [comment]
hi @qwordy could you pls help on CI failure and push for merge? thanks

**Comment by qwordy** [comment]
@cynthn Can you have a look at the following error?
ERROR: /home/vsts/work/1/s/src/azure-cli/azure/cli/command_modules/vm/_help.py:993:117: W291 trailing whitespace

**Pull request merged**
