### PR TITLE
[CDN] Add multi-origin preview and BYOC autorotation.

### PR DESCRIPTION
**Pull request by lsmith130**
**Description**  
Add CDN multi-origin preview feature.

**Testing Guide**  

Create an origin group on a CDN endpoint:
```
az cdn origin-group create -g group --profile-name profile --endpoint-name endpoint -n origin-group-name --origins origin-
```
Set the origin group as default: 
```
az cdn endpoint update --default-origin-group origin-group-name
```
Create multiple origins for a single CDN endpoint:
```
az cdn origin create -g group --host-name example.contoso.com --profile-name profile --endpoint-name endpoint -n origin --host-name example.contoso.com
```
Update new weight and priority fields of an origin
```
az cdn origin update -g group --profile-name profile --endpoint-name endpoint -n origin --priority 3 --weight 500
```
**History Notes**  

[CDN] Add preview multi-origin support.
[CDN] Add BYOC auto-rotation.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
CDN

**Comment by lsmith130** [comment]
@kairu-ms, could you take a look at this PR when you get the chance? Thanks in advance.

**Comment by yonzhan** [comment]
@kairu-ms @haroldrandom please help with PR review.

**Review by kairu-ms — APPROVED** [review]

**Review by haroldrandom — CHANGES_REQUESTED** [review]
Could you solve the conflict first?

**Comment by lsmith130** [comment]
@haroldrandom, Just solved the conflict plus fixed a small bug and a few unrelated tests that were failing in some situations. Please take another look when you get the chance.

**Review by haroldrandom — APPROVED** [review]

**Pull request merged**
