### PR TITLE
{Misc} Remove '?view=' syntax in links where not necessary

### PR DESCRIPTION
**Pull request by jdmartinez36**
**Description**
Only changes are to remove the "?view=azure-cli-latest" and "&preserve-view=true" syntax from Azure CLI-related links. I also removed instances 'en-US' from links per current validation guidelines. These guidelines apply to most, but not all content. I can revert if these links are supposed to go specifically to en-US versions. Please see the user story for more details.

User story [1797650](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1797650)

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by jdmartinez36** [comment]
@dbradish-microsoft 

Hi Delora. Here's the first PR for 1797650 (link edits). Please take a look and verify that this is what you're looking for on this project.

**Comment by dbradish-microsoft** [comment]
@fengzhou-msft , @jiasli, do you want to fix these yourself with your own PR, naming convention and sign off, or are you okay with this PR as-is?  I respect that you have a fixed process in this repo.

**Review by qwordy — APPROVED** [review]

**Comment by qwordy** [comment]
Thanks @jdmartinez36

**Review by jiasli — APPROVED** [review]

**Comment by jiasli** [comment]
@dbradish-microsoft, I am okay with this PR as-is. It looks like the doc page is not appending `?view=azure-cli-latest` anymore. Nice work!

**Comment by jiasli** [comment]
I have removed more `?view=azure-cli-latest`, but there seems to be too many `/en-us`. Should we remove them all?

**Comment by dbradish-microsoft** [comment]
@jiasli , no fully qualified URL should have **/en-us/** in it as it makes the URL country-specific....at least that is the Microsoft Docs rule.

**Review by dbradish-microsoft — APPROVED** [review]

**Comment by jiasli** [comment]
> @jiasli , no fully qualified URL should have **/en-us/** in it as it makes the URL country-specific....at least that is the Microsoft Docs rule. Can we ignore the unsuccessful checks, and can I sign off with the # sign?

@dbradish-microsoft, I tested and it seems we can remove `/en-us` safely and all URLs are working as expected by automatically inserting `/en-us`. Let's do this in another PR to remove all `/en-us`.

I am re-running the CI to pass those tests and will merge it later.

**Review by Juliehzl — APPROVED** [review]

**Comment by dbradish-microsoft** [comment]
Thank you, @Jiasli and @juliehzl

**Comment by MightyPen** [comment]
Thanks for these fixes.

**Pull request merged**
