### PR TITLE
Add orchestrator DockerCE for acs module

### PR DESCRIPTION
**Pull request by rjtsdl**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [x] Each command and parameter has a meaningful description.
- [x] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by rjtsdl** [comment]
@brendandburns @derekbekoe

**Comment by rjtsdl** [comment]
@derekbekoe , please help merge if you approve. Thx

**Comment by rjtsdl** [comment]
@derekbekoe @brendandburns , genteelly ping :)

**Comment by brendandburns** [comment]
Merged.

**Comment by lostintangent** [comment]
@rjtsdl Nice! By `DockerCE`, is this Swarm Mode, using Docker Community Edition?

**Pull request merged**
