### PR TITLE
{RDBMS} `az postgres flexible-server update`: Fix bug not able to enable password authentication during update

### PR DESCRIPTION
**Pull request by nasc17**
**Related command**
`az postgres flexible-server update`

**Description**
If you create a server with password authentication disabled and AAD enabled:
_az postgres flexible-server create --resource-group rg-test --name testpostgresqlserver --password-auth Disabled --active-directory-auth Enabled --location eastus --version 16 --high-availability Disabled --tier GeneralPurpose --public-access Enabled_

And then try to enable it using the update command:
_az postgres flexible-server update --resource-group rg-test --name testpostgresqlserver --password-auth Enabled

It fails with this error:
_(EngineCredentialsNotProvided) The admin credentials are required for creating admin role while enabling Password Authentication and must be provided.
Code: EngineCredentialsNotProvided
Message: The admin credentials are required for creating admin role while enabling Password Authentication and must be provided._

Fix:
Allow "--password-auth Enabled" to work during update. Generate password for user if "--admin-login-password" parameter was not passed in. Also generate username.

**Testing Guide**
az postgres flexible-server update --resource-group rg --name test-1027-721 --password-auth Enabled
**Make a note of password "LSssssssssssssssseeee". You can reset your password with "az postgres flexible-server update -n test-1027-721 -g rg -p <new-password>".**
{
  **"administratorLogin": "gleefuloil1",**
  "administratorLoginPassword": null,
  "authConfig": {
    "activeDirectoryAuth": "Enabled",
    "passwordAuth": "Enabled",
    "tenantId": "xxxxxxxxxxxxxxxxxxxxxxxx"
  }

**History Notes**
{RDBMS} `az postgres flexible-server update`: Fix bug not able to enable password authentication during update

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by mattboentoro — APPROVED** [review]

**Review by evelyn-ys — APPROVED** [review]

**Comment by evelyn-ys** [comment]
Pls fix these style issues:
```
src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py:274:0: R0912: Too many branches (21/20) (too-many-branches)

/mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py:401:21: E128 continuation line under-indented for visual indent
/mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/rdbms/flexible_server_custom_postgres.py:402:21: E128 continuation line under-indented for visual indent

```

**Review by evelyn-ys — APPROVED** [review]

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
