### PR TITLE
Switch Centos 7 build of azure-cli to use Python 3

### PR DESCRIPTION
**Pull request by rodrigc**
Fixes https://github.com/Azure/azure-cli/issues/11234 https://github.com/Azure/azure-cli/issues/11206

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by fengzhou-msft** [comment]
Hi @rodrigc, thanks for submitting this PR. Since our el7 rpm package is also targeting RHEL 7, will the package built with Python 3 work on RHEL 7 as well? As far as I know, RHEL 7 does not support Python 3 officially.

**Comment by rodrigc** [comment]
@fengzhou-msft from my branch with this PR, I was able to successfully build following these instructions:

https://github.com/Azure/azure-cli/blob/dev/scripts/release/rpm/README.md

```
docker build --target build-env -f ./scripts/release/rpm/Dockerfile.centos -t mcr.microsoft.com/azure-cli:centos7-builder .
```

I was then also able to successfully `yum install` this package in a Centos 7 environment
and run it.

**Comment by rodrigc** [comment]
If you want to double check, you can follow the instructions at to create a clean centos/7 environment: https://app.vagrantup.com/centos/boxes/7

1.  Create a directory:

```
mkdir centos-7-clean
cd centos-7-clean
```

2.  In this directory:

Create a file:

```
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
end
```

3.  In the same directory, create the VM:

```
vagrant up
```

4.  When VM is created, log into it:

```
vagrant ssh
```

Then in that clean Centos7 environment, you can build the Centos7 azure-cli rpm package and run it.


I am running the Centos7 package built from my branch in a Centos7 environment used in my automation testing.

**Comment by rodrigc** [comment]
@fengzhou-msft for RHEL 7, RedHat has this document: https://developers.redhat.com/blog/2018/08/13/install-python3-rhel/

**Comment by fengzhou-msft** [comment]
@rodrigc Your changes work perfectly with Cento 7. I will try to install Python 3 on RHEL 7 according to your link and see how the package works on RHEL 7.

**Comment by fengzhou-msft** [comment]
Looks like RHEL 7.7 has support for Python 3 now : https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.7_release_notes/new_features#enhancement_compiler-and-tools

**Comment by rodrigc** [comment]
@fengzhou-msft  thanks for accepting my patch.

One question, will Azure-cli drop support for Python 2.7?  Maybe that can be done in 2020

**Comment by fengzhou-msft** [comment]
We've planned that in [S163](https://github.com/Azure/azure-cli/milestone/80), first release in 2020.

**Pull request merged**
