### PR TITLE
Delete empty file (accidentally committed?)

### PR DESCRIPTION
**Pull request by derekbekoe**

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/5558
This is an **experimental preview** for @microsoft users.

**Comment by tjprescott** [comment]
Running `azdev test` or `run_tests` automatically creates the file. We could add it to gitignore.

**Comment by derekbekoe** [comment]
Okay will add to .gitignore

**Comment by derekbekoe** [comment]
Added to .gitignore

**Pull request merged**
