### PR TITLE
[Role] Fix #15278: az role assignment list/delete: Forbid empty string arguments

### LINKED ISSUE #15278: azure role assignment delete will delete all assignments when --assignee is empty string
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Fork the issue from #13577, to track specific issue from customer when --assignee is empty string, az role assignment delete will delete all assignments. After fix, az will throw error when --assignee is empty string

```copy from original issue
I accidentally did this:

az role assignment create --assignee "$SOME_VAR" --role "Owner"

SOME_VAR was accidentally set to empty string. I did not get any prompt and EVERY OWNER WAS DELETED.I lost access to my subscription. Cannot even file a support ticket cause I lost permissions.
Is there a way to fix this?
```
**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

### PR DESCRIPTION
**Pull request by jiasli**
**Description**  

Fix #15278: `az role assignment delete` will delete all assignments when `--assignee` is empty string

In `az role assignment list/delete`, when `--assignee`, `--scope`, `--role`, `--resource-group` are accidentally provided as an empty string `""` (especially when in a script), they won't take effect when filtering the role assignments, causing all matched role assignments to be listed/deleted. For example,

```
az role assignment delete --assignee ""
```

removes all role assignments under the subscription.

This PR checks whether these arguments are empty strings and throws `CLIError` accordingly.

**Testing Guide**  
```
az role assignment list --assignee ""
az role assignment list --scope ""
az role assignment list --role ""
az role assignment list --resource-group ""

az role assignment delete --assignee ""
az role assignment delete --scope ""
az role assignment delete --role ""
az role assignment delete --resource-group ""
```

(Use `'""'` for empty string in PowerShell.)

### CODE REVIEW

**Review by arrownj — APPROVED** [review]
It seems that you forgot to push the test recording file.

**Comment by yungezz** [comment]
I though the issue is assigned to @arrownj right :)

**Comment by jiasli** [comment]
> I though the issue is assigned to @arrownj right :)

Oh. Sorry. I didn't check issue before submitting the PR...

**Comment by jiasli** [comment]
> It seems that you forgot to push the test recording file.

The command fails immediately without triggering any network requests.

**Comment by yungezz** [comment]
> > I though the issue is assigned to @arrownj right :)
> 
> Oh. Sorry. I didn't check issue before submitting the PR...

I think we agreed on this during offline sync. Immediate hotfix tracked by #15278, @arrownj will take care of it. long term tracked in #13577 , reassigned to @jiasli . Right? It doesn't matter one PR who fixing it.

**Pull request merged**
