### PR TITLE
{IoT} Update to eTag / if-match header format

### PR DESCRIPTION
**Pull request by c-ryan-k**
**Related command**

`az iot hub update`
`az iot hub identity [assign | remove]`
`az iot hub policy [create  | delete | renew-key]`
`az iot hub routing-endpoint [create | delete]`
`az iot hub route [create | delete | update]`
`az iot hub message-enrichment [create | update | delete]`

**Description**

This changes our previous eTag / if-match header format from an object of `{'IF-MATCH': 'eTag'}` to simply the string `eTag`.
This change does not affect user parameters, but technically affects all `if-match` headers sent to ARM in any IoT Hub control-plane update request.

**Testing Guide**

This change affects no parameters, but any command that updates the IoT Hub control-plane resource can be used to test that it is working successfully:
- `az iot hub update`
- `az iot hub routing-endpoint create`
- `az iot hub identity assign`
- `az iot hub policy create`
- `az iot hub message-enrichment create`

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
IoT

**Review by digimaun — APPROVED** [review]

**Comment by yanzhudd** [comment]
> Related command
> 
> az iot hub update

Since there are several places being changed in this PR, may I ask if this change only applies to `az iot hub update` command?

**Comment by c-ryan-k** [comment]
> > Related command
> > az iot hub update
> 
> Since there are several places being changed in this PR, may I ask if this change only applies to `az iot hub update` command?

Good point, technically it is only our `iot_hub_resource.begin_create_or_update` operation (which is used for all IoT Hub control-plane updates) but I can list the user-facing commands that are technically updated in the PR comment.

**Comment by yanzhudd** [comment]
please resolve code conflicts

**Comment by zhoxing-ms** [comment]
Please note that we are launching the release for this sprint this week. Please resolve all comments and conflicts by Tomorrow, otherwise the release of this PR will have to be postponed to the next sprint **(on 12-05)**

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
