### PR TITLE
[Storage] Fix #16519: azcopy is given more powerful SAS than needed (has write, only needs read)

### LINKED ISSUE #16519: azcopy is given more powerful SAS than needed (has write, only needs read)
**Is your feature request related to a problem? Please describe.**
Using `azure-cli` ` 2.17.1`, when copying a blob from a blob storage account to a local file using `azcopy` (via `az storage copy`), even though I am logged in, a SAS is generated. The SAS is displayed as a part of the console output with no censoring whatsoever (which makes it more likely to accidentally leak) and it includes more permissions than needed. I think read permission for the blob service would suffice, but apparently all of them are granted (`sp=rwdlacup`). The generated command line is:

```
'C:\\Users\\<usr>\\.azcopy\\azcopy.exe', 'copy', 'https://<account>.blob.core.windows.net/<blobpath>?se=2021-01-14T13%3A53%3A27Z&sp=rwdlacup&sv=2018-03-28&ss=b&srt=sco&sig=redacted', 'D:\\<destinationpath>'
```

**Describe the solution you'd like**
The SAS would ideally not be generated, the `az login` credentials would ideally be used for `azcopy` too.
Alternatively, if the SAS is used, it should not be displayed uncensored. Also, it should only include the minimum permissions necessary to do the job.

**Describe alternatives you've considered**
I've considered using `az storage blob copy` but in some scenarios it's much, much slower than `az storage copy`, in some cases more than 10x slower.

### PR DESCRIPTION
**Pull request by Juliehzl**
**Description**

Fix #16519 
image

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Storage

**Comment by Juliehzl** [comment]
Hi @zezha-msft , if possible, please help check the permissions assigned for azcopy operations:
`sync`: srt=co sp=rwdlac
`copy`: source: srt=sco sp=rl destination srt=co sp=wac
`remove`: src=co sp=rdl

**Comment by evelyn-ys** [comment]
This PR guarantees the right permission for each operation but will still output the SAS token, right? Can we hide it from console output?

**Comment by Juliehzl** [comment]
> This PR guarantees the right permission for each operation but will still output the SAS token, right? Can we hide it from console output?

Yes

**Comment by zezha-msft** [comment]
@Juliehzl looks good to me.

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
