### PR TITLE
[ACR] Add tty check before prompting for user input

### PR DESCRIPTION
**Pull request by djyou**

### CODE REVIEW

**Comment by djyou** [comment]
@ahmetalpbalkan @SajayAntony

**Comment by djyou** [comment]
To address this issue https://github.com/Azure/azure-cli/issues/1349

**Comment by ahmetalpbalkan** [comment]
@djyou I think this should be fixed in a higher layer. Is it too much to go through `raw_input()` and `getpass()` usages and create a wrapper function for those that checks `.istty()`?

**Comment by djyou** [comment]
@ahmetalpbalkan I wasn't sure how much we want to go towards that direction since clearly this is a common issue to azure-cli. For example, you would have the same issue for `az login -u myUsername` command. I would wait to see what the CLI folks would comment.

**Comment by troydai** [comment]
@johanste this is on our radar? I seems to be something worth to consider to be done in our infrastructure.

**Comment by johanste** [comment]
Having a core prompting function that does the tty check seems like a very reasonable suggestion!

**Comment by djyou** [comment]
Can we have this PR merged and track this issue here https://github.com/Azure/azure-cli/issues/1349?

**Pull request merged**
