### PR TITLE
Add EVENT_INVOKER_PRE_TRUNCATE_CMD_TBL event to core.

### PR DESCRIPTION
**Pull request by chewong**
Currently, azure-cli only supports command-based extensions. `ArgumentExtensionsLoader` will support non-command-based extensions that modify input arguments in the CLI. The format of the extension is as follow:

```python
class ExampleArgumentExtension:

    def __init__(self, **kwargs):
        pass

    def transform(self, args):
        # Process input argument here
        return processed_args

ARG_EXT_CLS = ExampleArgumentExtension
```
Each argument extension has an export class `ARG_EXT_CLS` and its constructor accepts `**kwargs`. Within the class, it has a function `transform` that accepts the CLI input arguments `args` and output the processed arguments.

@troydai and @derekbekoe, could you please review? Thanks!

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [ ] (N/A) Each command and parameter has a meaningful description.
- [ ] (N/A) Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/5438
This is an **experimental preview** for @microsoft users.

**Comment by derekbekoe** [comment]
Can we discuss what the goal of this change is on Wednesday?
Would really want to avoid multiple types of extensions.

**Comment by troydai** [comment]
@derekbekoe great suggestion. Let's go over this tomorrow.

**Comment by troydai** [comment]
I share the same concern with @derekbekoe. The essence of this change is to allow extension to alter the arguments before it go through the command parse. It enhances the capability of extension. However, it will introduce confusions if a new type of extension is introduced. Nor it should limit one extension's capacity to one category.

**Comment by tjprescott** [comment]
Agree with Derek. This should all be possible using essentially a no-op extension that adds hooks into the Knack framework.

**Comment by tjprescott** [comment]
Isn't this already in from a previous PR?

**Comment by chewong** [comment]
Merged @ #5460

**Pull request closed without merging**
