### PR TITLE
{Core} Expose public interface for `SecretStore`

### PR DESCRIPTION
**Pull request by jiasli**
**Description**

Expose public interface for using encrypted `SecretStore` so that command modules or extensions (such as https://github.com/calvinsID/azure-cli-extensions/pull/97) can leverage `msal-extensions` to save custom data such as tokens.

**Testing Guide**

On Windows:

```
> az demo secret-store save "name=Johann Sebastian Bach" job=musician
Data written to C:\Users\username\.azure\secret_store_demo.bin: {'name': 'Johann Sebastian Bach', 'job': 'musician'}

> az demo secret-store load
{
  "job": "musician",
  "name": "Johann Sebastian Bach"
}
```

Turn off token encryption:

```
> az config set core.encrypt_token_cache=False

> az demo secret-store save "name=Johann Sebastian Bach" job=musician
Data written to C:\Users\username\.azure\secret_store_demo.json: {'name': 'Johann Sebastian Bach', 'job': 'musician'}

> az demo secret-store load
{
  "job": "musician",
  "name": "Johann Sebastian Bach"
}
```

### CODE REVIEW

**Comment by yonzhan** [comment]
Core

**Review by StrawnSC — APPROVED** [review]
This works as expected when I try with our setup [here](https://github.com/calvinsID/azure-cli-extensions/pull/104) (caching GitHub credentials for the `containerapp` extension). Thanks!

**Review by evelyn-ys — APPROVED** [review]

**Review by calvinhzy — APPROVED** [review]

**Comment by jiasli** [comment]
@rayluo, CLI is helping `msal-extensions` have more users! 🤣

**Review by rayluo — APPROVED** [review]

**Pull request merged**
