### PR TITLE
support generate sdk auth info

### PR DESCRIPTION
**Pull request by yugangw-msft**
//cc: @mayurid @jianghaolu @selvasingh
Per our discussion and following mail exchange
```bash
(env) D:\sdk\azure-cli>az ad sp create-for-rbac -n yugangwdelete --sdk-auth
{
  "clientId": "56dc7894-2cb8-40d8-9a29-fdc8b6c66xxx",
  "clientSecret": "2457b4e1-1e42-4cd8-98f2-3e510a502xxx",
  "subscriptionId": "0b1f6471-1bf0-4dda-aec3-cb9272f09xxx",
  "tenantId": "54826b22-38d6-4fb2-bad9-b7b93a3e9xxx",
  "resourceManagerEndpointUrl": "https://management.azure.com/",
  "activeDirectoryEndpointUrl": "https://login.microsoftonline.com"
}
```
### General Guidelines

- [x] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [x] Each command and parameter has a meaningful description.
- [x] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by jianghaolu** [comment]
Please add more endpoints: https://github.com/Azure/azure-sdk-for-java/blob/master/AUTH.md according to the names here: https://github.com/Azure/azure-sdk-for-ruby/blob/master/management/azure_mgmt_devtestlabs/lib/generated/azure_mgmt_devtestlabs/environments.rb.

**Comment by yugangw-msft** [comment]
@jianghaolu, I added more. The list can grow at any time we like, even including suffix.
```bash
{
  "clientId": "0271f80e-4289-4b0d-b6cb-483d2605b14f",
  "clientSecret": "19428891-707b-420d-94cd-111157b58469",
  "subscriptionId": "0b1f6471-1bf0-4dda-aec3-cb9272f09590",
  "tenantId": "54826b22-38d6-4fb2-bad9-b7b93a3e9c5a",
  "activeDirectoryEndpointUrl": "https://login.microsoftonline.com",
  "resourceManagerEndpointUrl": "https://management.azure.com/",
  "activeDirectoryGraphResourceId": "https://graph.windows.net/",
  "sqlManagementEndpointUrl": "https://management.core.windows.net:8443/",
  "galleryEndpointUrl": "https://gallery.azure.com/",
  "managementEndpointUrl": "https://management.core.windows.net/"
}
```

**Comment by lmazuel** [comment]
@yugangw-msft @jianghaolu can we agree on an environment variable for this file? Similar to the `AZURE_AUTH_LOCATION` used currently in C# and Java?

What about `AZURE_SDK_AUTH_LOCATION`?

**Comment by jianghaolu** [comment]
@lmazuel In Java SDK an environment variable isn't required for using the SDK. Only the automated tests use `AZURE_AUTH_LOCATION` to find where the auth file is.

**Comment by yugangw-msft** [comment]
Accepting a common environment variable pointing to the auth file will make it pretty convenient to make all sdk just works in a same box. Of course all SDK still need to support to accept a file path argument. Again, it is just for convenience.

**Comment by jianghaolu** [comment]
Sounds good. Would like to have this option set to off by default though.

**Comment by jianghaolu** [comment]
If it's set to on by default, it must check if `AZURE_AUTH_LOCATION` exists already.

**Comment by yugangw-msft** [comment]
Note, this is not for `azure-cli` which doesn't handle the file operation. The env variable is used between SDKS, which we can consider to having all SDKs opt in

**Comment by jianghaolu** [comment]
I see. Thanks for clarifying.

**Comment by lmazuel** [comment]
@jianghaolu `AZURE_AUTH_LOCATION` is not just for testing, it's documented for customers:
https://docs.microsoft.com/java/azure/java-sdk-azure-authenticate#file-based-authentication-preview

It's why I suggested another name, to avoid conflict (it's documented as a properties file).

**Comment by lmazuel** [comment]
So, are telling to customers "this was a preview, now it's JSON and a new format"? Or a new variable? I'm fine either, I didn't release anything for Python anyway :)

**Comment by jianghaolu** [comment]
@lmazuel To me it seems just a way of reading a file - nothing else.  We will continue to support the java properties format too.

**Comment by lmazuel** [comment]
So your `authenticate` method will accept both a properties and a JSON file as input? I'm just trying to understand the customer experience.

**Comment by jianghaolu** [comment]
Yes to keep backward compatibility.

**Comment by lmazuel** [comment]
Thanks @jianghaolu !

**Pull request merged**
