### PR TITLE
[Backup] Trigger AFS container/item discovery only when needed

### PR DESCRIPTION
**Pull request by hiaga**
**Description**  

 Improving AFS container/item discovery experience
       * Now Discover protection containers only when it's not already registered/discovered.
       * Trigger item inquiry only if it is not already discovered.

**Testing Guide**  

az backup protection enable-for-azurefileshare --azure-file-share fileShareName -p policyName --storage-account stAccName -g resourceGroupName -v vaultName

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [Yes] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [Yes] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
backup

**Comment by hiaga** [comment]
Can someone from CLI team review this PR? @fengzhou-msft

**Comment by yonzhan** [comment]
@fengzhou-msft  could you help with this PR?

**Comment by hiaga** [comment]
@fengzhou-msft :  refreshed to latest commit as we discussed. Please proceed to merge.

**Comment by hiaga** [comment]
@fengzhou-msft: error reported at  https://dev.azure.com/azure-sdk/public/_build/results?buildId=474648&view=logs&j=cedb4d72-63c2-581b-2274-24a4ef43c946&t=1b7b5e8c-f0d3-504e-ebf4-a86923fb02b9 looks like some CLI infra issue. Please check

**Pull request merged**
