### PR TITLE
[App Service] `az webapp config connection-string set`: Allow users to use json file to set the connection string

### PR DESCRIPTION
**Pull request by shnjefff**
**Related command**

az webapp config connection-string set --name myappname --resource-group myrgname --settings "@test.json"
az webapp config connection-string set --name myappname --resource-group myrgname --slot-settings "@test.json" -s myslotname

**Description**

User want to do bulk update to different type of connection string using json file. This PR enabled this features.
Now, user can update connection string in two ways.

1. If user does not use json to update, connection_string_type is required.
for prod slot: 
az webapp config connection-string set --name myappname --resource-group myrgname --settings name-1=conn_str-1 -connection-string-type MySql
az webapp config connection-string set --name myappname --resource-group myrgname --settings name-1=conn_str-1 name-2=conn_str-2 --connection-string-type MySql
for staging slot:
az webapp config connection-string set --name myappname --resource-group myrgname --slot-settings name-1=conn_str-1 -connection-string-type MySql -s myslotname
az webapp config connection-string set --name myappname --resource-group myrgname --slot-settings name-1=conn_str-1 name-2=conn_str-2 --connection-string-type MySql -s myslotname

2. If user use json to update, json file need to follow the following format
[
  {
    "name": "name-1",
    "value": "conn-string-1",
    "type": "SQLServer",
    "slotSetting": false
  },
  {
    "name": "name-2",
    "value": "conn-string-2",
    "type": "PostgreSQL"
  }
]
for prod slot: 
az webapp config connection-string set --name myappname --resource-group myrgname --settings "@test.json"
for staging slot:
az webapp config connection-string set --name myappname --resource-group myrgname --slot-settings "@test.json" -s myslotname

**Testing Guide**

Error messages test
if the json is incorrect format or connection-string-type is not provided when not using json, user will receive the following error
_'either --connection-string-type is required if not using json, or bad json file'_

if the json does not contain required keys, users will receive the following error
_'In json settings, 'value', 'name' and 'type' is required; 'slotSetting' is optional'_

if nether settings nor slot-settings is provided, users will receive the following error
_'Usage Error: --settings |--slot-settings'_

Function test
for prod slot: 
az webapp config connection-string set --name myappname --resource-group myrgname --settings name-1=conn_str-1 -connection-string-type MySql
az webapp config connection-string set --name myappname --resource-group myrgname --settings name-1=conn_str-1 name-2=conn_str-2 --connection-string-type MySql
for staging slot:
az webapp config connection-string set --name myappname --resource-group myrgname --slot-settings name-1=conn_str-1 -connection-string-type MySql -s myslotname
az webapp config connection-string set --name myappname --resource-group myrgname --slot-settings name-1=conn_str-1 name-2=conn_str-2 --connection-string-type MySql -s myslotname
for prod slot: 
az webapp config connection-string set --name myappname --resource-group myrgname --settings "@test.json"
for staging slot:
az webapp config connection-string set --name myappname --resource-group myrgname --slot-settings "@test.json" -s myslotname

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AppService

**Review by haroonf — DISMISSED** [review]

**Comment by zhoxing-ms** [comment]
@shnjefff Could you please resolve these CI issues?

**Comment by zhoxing-ms** [comment]
Could you add some test cases for this PR change?

**Comment by shnjefff** [comment]
> Could you add some test cases for this PR change?

Just added some test cases! Let me know what do you think

**Comment by shnjefff** [comment]
> @shnjefff Could you please resolve these CI issues?

resolved

**Review by haroonf — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Comment by seligj95** [comment]
resolves: https://github.com/Azure/azure-cli/issues/15395

**Pull request merged**
