### PR TITLE
[SQL] BREAKING CHANGE: `az sql mi link`: Rename parameters for `az sql mi link create`, add `az sql mi link failover`

### PR DESCRIPTION
**Pull request by jovancevic123**
**Related command**

- az sql mi link show
- az sql mi link create
- az sql mi link list
- az sql mi link update
- az sql mi link failover - new cmdlet

**Description**

This PR introduces update of sql mi link cmdlets to use new version of API (2023-08-01). Because of this new failover cmdlet is introduced. Other commands are changed in a way that the output type is different.  `az sql mi link create` cmdlet is now using new input parameters, some of them are just renamed and some of them changed type.

New properties in output: databases, partnerAvailabilityGroupName, instanceAvailabilityGroupName, partnerEndpoint, distributedAvailabilityGroupName, instanceLinkRole, partnerLinkRole, failoverMode, seedingMode.

Removed properties in output: targetDatabase, primaryAvailabilityGroupName, secondaryAvailabilityGroupNamesourceEndpoint, sourceReplicaId, targetReplicaId, linkState, lastHardenedLsn.

And input breaking changes for:

az sql mi link create
target-database ---> databases
source-endpoint ---> partner-endpoint
primary-availability-group-name ---> partner-availability-group-name
secondary-availability-group-name ---> instance-availability-group-name

**Testing Guide**

Multiple tests are written to test the new change. Tests require live setup, which can't be automated and therefore they are tagged with @record_only, to avoid playing them in live mode by pipeline.

**History Notes**

[SQL] BREAKING CHANGE: `az sql mi link create`: Rename input from `--source-endpoint` to `--partner-endpoint`, `--primary-availability-group-name` to `--partner-availability-group-name`, `--secondary-availability-group-name` to `--instance-availability-group-name`, `--target-database` to `--databases`
[SQL] BREAKING CHANGE: `az sql mi link create/show/list/update`: Rename output from `targetDatabase`, `primaryAvailabilityGroupName`, `secondaryAvailabilityGroupNamesourceEndpoint`, `sourceReplicaId`, `targetReplicaId`, `linkState`, `lastHardenedLsn` to `databases`, `partnerAvailabilityGroupName`, `instanceAvailabilityGroupName`, `partnerEndpoint`, `distributedAvailabilityGroupName`, `instanceLinkRole`, `partnerLinkRole`, `failoverMode`, `seedingMode`
[SQL] `az sql mi link failover`: Support performing requested failover type in this Managed Instance link

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by jovancevic123** [comment]
image

**Comment by jovancevic123** [comment]
I need to add one more iteration where I will change the version of SDK for SQL. Currently I am waiting for the SDK to be publicly released.

**Comment by jovancevic123** [comment]
DON'T merge until I change the version of SDK.

**Comment by jovancevic123** [comment]
> DON'T merge until I change the version of SDK.

I have bumped SQL version.

**Comment by jovancevic123** [comment]
SQL tests run in playback mode:

image

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
