### PR TITLE
[Synapse]BREAKING CHANGE: az synapse : add and change some cmdlets

### PR DESCRIPTION
**Pull request by kevinzz6**
**Description**

Add cmdlets:
- az synapse integration-runtime start
- az synapse integration-runtime stop
- az synapse trigger wait
- az synapse trigger-run cancel

Change cmdlets:
- Replace the existing command "az synapse integration-runtime create" and add two new "az synapse integration-runtime managed create","az synapse integration-runtime self-hosted create"
- Rename "az synapse dataset set" to "az synapse dataset update"
- Rename "az synapse pipeline set" to "az synapse pipeline update"
- Rename "az synapse linked-service set" to "az synapse linked-service update"
- Rename "az synapse trigger set" to "az synapse trigger update"

**Testing Guide**

**History Notes**

-  [Synapse] `az synapse integration-runtime`: Support start/stop integration-runtime
-  [Synapse] `az synapse trigger`: Add az synapse trigger wait
-  [Synapse] `az synapse trigger-run`: Add az synapse trigger-run cancel
-  [Synapse] `az synapse integration-runtime`: Deprecate `create` command and will redirect to `managed create` or `self-hosted create` command
-  [Synapse] `az synapse dataset/pipeline/linked-service/trigger`: Deprecate `set` command and will redirect to `update` command

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Synapse

**Comment by kevinzz6** [comment]
@jsntcy Could you take a time to look at this PR? Thanks!

**Comment by jsntcy** [comment]
@kevinzz6, usually we use [deprecation mechanism](https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#deprecating-commands-and-arguments) for renaming a command to give users some buffer time to update their script accordingly instead of breaking users' scripts suddenly.

**Comment by evelyn-ys** [comment]
For complicated PR, please update **History Notes** part in PR description since PR title can't handle all for release notes. See [Format PR Description](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#format-pr-description)

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
