### PR TITLE
[ARM] `az provider register`: Make parameter `--accept-term` become not required

### PR DESCRIPTION
**Pull request by 00Kai0**
**Description**

az provider register: make parameter --accept-term become not required

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Deprecation

**Review by jsntcy — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@00Kai0 At present, this parameter has not been completely removed, but it is no longer required, so it will not cause breaking change to users, right?

**Comment by zhoxing-ms** [comment]
I'm not sure it would be more appropriate to change this PR title to 
> [ARM] `az provider register`: make parameter `--accept-term` become not required

@00Kai0  What do you think of it?

**Comment by 00Kai0** [comment]
> @00Kai0 At present, this parameter has not been completely removed, but it is no longer required, so it will not cause breaking change to users, right?

Yes, will not.

**Comment by 00Kai0** [comment]
> I'm not sure it would be more appropriate to change this PR title to
> 
> > [ARM] `az provider register`: make parameter `--accept-term` become not required
> 
> @00Kai0 What do you think of it?

I think you are right, I have updated this title

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
