### PR TITLE
Fix #2176: fixes for SDK changes for AppService.

### LINKED ISSUE #2176: AppService failures from missing SDK components.
## Description

It looks like there are AppService failures with the latest bits due to SDK issues (?).  Some operations work; others fail with a `WebAppsOperations` failure.

_This does **not** repro with the latest released bits: I am running into it on latest bits on my dev box only._

## Actual Behavior

```bash
$ az appservice web deployment slot swap \
    -g my_rg \
    -n myunqiueapp \
    --slot staging \
    --target-slot production
```

results in 

```bash
'WebAppsOperations' object has no attribute 'swap_slots_slot'
Traceback (most recent call last):
  File "c:\users\twitc\onedrive\projects\azure-cli\src\azure-cli\azure\cli\main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "c:\users\twitc\onedrive\projects\azure-cli\src\azure-cli-core\azure\cli\core\application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "c:\users\twitc\onedrive\projects\azure-cli\src\azure-cli-core\azure\cli\core\commands\__init__.py", line 343, in _execute_command
    raise ex
AttributeError: 'WebAppsOperations' object has no attribute 'swap_slots_slot'
```

## Expected Behavior

The operation should work as it does with the latest released bits.

### PR DESCRIPTION
**Pull request by twitchax**
Fix #2176.

### CODE REVIEW

**Comment by yugangw-msft** [comment]
@twitchax , could you add a test step at [here](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/tests/test_webapp_commands.py#L343) . By default, to swap with 'prod', `--target-slot` is not required, so we do not need to rush here; but nonetheless, it is a bug we need to fix. Thanks for the effort!

**Comment by twitchax** [comment]
Will do: pending.

**Comment by twitchax** [comment]
@yugangw-msft, what is this cassette error?

**Comment by yugangw-msft** [comment]
@twitchax , you will need to re-record the test. Please delete related .yaml file under "tests/recordings" and rerun the test. Also I suggest do not change that existing step which test the right way to swap with the prod slot, rather add a new step to swap with any other slow

**Comment by twitchax** [comment]
@yugangw-msft, can you sign off: we can add test later.

**Comment by twitchax** [comment]
@derekbekoe, can we pull this in before the build?

**Pull request merged**
