### PR TITLE
{AKS} Upgrade api-version to 2022-04-01 for ACS module

### PR DESCRIPTION
**Pull request by moreOver0**
**Related command**

Upgrade api-version to 2022-04-01 for ACS module.

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by moreOver0** [comment]
@zhoxing-ms It's my first time to contribute to azure-cli. What does this check mean?
image
What action I need to take?

**Comment by zhoxing-ms** [comment]
@moreOver0 This is caused by the modification of CI task. I triggered the CI pipeline again for you

**Review by zhoxing-ms — APPROVED** [review]

**Comment by moreOver0** [comment]
@zhoxing-ms  Thanks!

**Pull request merged**
