### PR TITLE
Remove 'starting' message for long running operations

### LINKED ISSUE #764: az vm extension delete: does not print completion
```
$ az vm extension delete -g ahmet-test --vm-name myvm -n CustomScript
Starting vm extension delete
$
```

### PR DESCRIPTION
**Pull request by derekbekoe**
Fixes #764

### CODE REVIEW

**Comment by tjprescott** [comment]
>     def __init__(self, start_msg='', finish_msg='', poll_interval_ms=1000.0):

Is there any reason to keep these around?

---
Refers to: src/azure/cli/commands/__init__.py:87 in 49bf67f. [](commit_id = 49bf67f66262f9d8461440ee2ee02f523b331264, deletion_comment = True)

**Comment by tjprescott** [comment]
>     def __init__(self, start_msg='', finish_msg='', poll_interval_ms=1000.0):

Johan talked about changing this name, because it doesn't do what it sounds like it does.

---
Refers to: src/azure/cli/commands/__init__.py:87 in 49bf67f. [](commit_id = 49bf67f66262f9d8461440ee2ee02f523b331264, deletion_comment = True)

**Comment by derekbekoe** [comment]
start_msg is used for the log messages.

**Comment by derekbekoe** [comment]
@tjprescott Isn't it the interval for checking when the poller is done?
Or is the confusion that it could be interpreted as the interval that the poller itself makes requests.

**Comment by johanste** [comment]
The latter. Yes. It would very likely be interpreted as how often the client/CLI pings the service.

**Comment by derekbekoe** [comment]
@tjprescott, @johanste Comment addressed - https://github.com/Azure/azure-cli/pull/767/files#diff-761a6c6d363f8ca8f0db3c27ef256af6R86.

**Comment by tjprescott** [comment]
:shipit:

**Pull request merged**
