### PR TITLE
Add remote build support for Azure Functions

### PR DESCRIPTION
**Pull request by Hazhzeng**
### Add remote build support
Add remote build support in `az functionapp deployment source config-zip`. The user can now upload their source code zip package and deploy it with server side build process.

e.g. `az functionapp deployment source config-zip -g hazeng-rg -n hazeng-fa-euap-python --src .\PythonOryxBuild.zip --build remote`

User can trace their build result in scm/api/deployments endpoint.

### Attempt to implement test scenarios, but they fails due to testsdk failure
Related issue is here https://github.com/Azure/azure-cli/issues/10705
The issue affects the e2e test scenario which using StorageAccountPreparer and containing file upload request.

My colleague also ran into this issue, https://github.com/Azure/azure-cli/pull/9784#issuecomment-505541134

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by Hazhzeng** [comment]
@qwordy CI failure due to version conflict in dependencies. https://travis-ci.org/Azure/azure-cli/jobs/591760525. I haven't changed requirements.txt in this PR, please check.

**Comment by yugangw-msft** [comment]
@Hazhzeng, please rebase with the latest dev which should have the version conflict error go away,

**Comment by Hazhzeng** [comment]
@yugangw-msft .Please add this PR into **Sprint 75**, thanks.

**Comment by yonzhan** [comment]
@qwordy  we can plan it after holiday.

**Comment by qwordy** [comment]
I think maybe you should add a test case to test the new feature.

**Comment by yonzhan** [comment]
@Hazhzeng, as Feiyue mentioned, please add a test case to test the new feature.

**Comment by Hazhzeng** [comment]
Hey @qwordy and @yonzhan,
Thanks for reminding, due to the issue https://github.com/Azure/azure-cli/issues/10705, when writing e2e test cases, the test-sdk fails due to POST request content serialization.

I've added some mock test cases for my new feature, please check again.

**Comment by qwordy** [comment]
> 
> 
> Hey @qwordy and @yonzhan,
> Thanks for reminding, due to the issue #10705, when writing e2e test cases, the test-sdk fails due to POST request content serialization.
> 
> I've added some mock test cases for my new feature, please check again.

Hi @Hazhzeng , Thank you so much for adding test cases.

**Pull request merged**
