### PR TITLE
{AKS} Revert `az aks create`: Add edge zone support

### PR DESCRIPTION
**Pull request by andyliuliming**
Reverts Azure/azure-cli#18852

### CODE REVIEW

**Comment by andyliuliming** [comment]
@rheaparekh I'm trying to revert one of your PR.
I've heard from @FumingZhang  that this feature is not working now.
so I think that PR should not be merged.

and for the feature which is not GA.
the best place is to put it into the extensions:
https://github.com/Azure/azure-cli-extensions/tree/main/src/aks-preview

**Review by zhoxing-ms — APPROVED** [review]

**Comment by yonzhan** [comment]
AKS

**Comment by zhoxing-ms** [comment]
@andyliuliming If you don't want to add this PR title into release note,  this PR Title needs to start with `{}` instead of `[]`

**Comment by zhoxing-ms** [comment]
@andyliuliming Could you please resolve the conflict and CI issue?

**Comment by zhoxing-ms** [comment]
@andyliuliming Hi, please solve these CI issues and conflicts in time today, otherwise this PR will miss the release of this sprint and can only be released in the next sprint (09-07)

**Pull request closed without merging**
