### PR TITLE
{Servicebus} Add Breaking change message for `az servicebus georecovery-alias fail-over` cmdlets

### PR DESCRIPTION
**Pull request by schaudhari6254888**
**Related command**

**Description**
`parameters` argument will be removed from `az servicebus georecovery-alias fail-over` cmdlets in future release.

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Servicebus

**Comment by schaudhari6254888** [comment]
Hey @evelyn-ys , the `fail-over` cmdlets is not present in param.py file.
I want to deprecate the parameters argument from `az servicebus georecovery-alias fail-over` cmdlets.
Where do i write the `deprecate_info` here. So instead of this I have added warning & description.

**Review by evelyn-ys — DISMISSED** [review]

**Comment by evelyn-ys** [comment]
@schaudhari6254888  If there's no existing argument definition, you can add by yourself

**Comment by schaudhari6254888** [comment]
> @schaudhari6254888 If there's no existing argument definition, you can add by yourself

Hey @evelyn-ys, I have tried like this
    **with self.argument_context('eventhubs georecovery-alias fail-over') as c:
        c.extra('parameters', deprecate_info=c.deprecate(expiration='2.50.0'))**
        
       But CI's were failing saying that missing help for parameters in fail-over command

**Comment by evelyn-ys** [comment]
1. Add `help=...` for the argument
2. You shouldn't use `c.extra` but `c.argument`

Please learn how to authoring CLI first https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#customize-arguments

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
