### PR TITLE
[ServiceConnector] `az webapp/spring-cloud connection`: Add command `create redis/redis-enterprise` to support more target resources

### PR DESCRIPTION
**Pull request by houk-ms**
**Description**

This PR

1. Adds supports for more target resources: `redis` and `redis-enterprise`.
2. Adds support for AKS as source resource. It is hidden from customers in this PR, and will be shown to users after service connector's new api version is ready.
3. Provide `--deployment` the default value `default` for `az spring-cloud connection`.
4. Fix some known issues in arguement and command help message.

**Testing Guide**

**History Notes**

[ServiceConnector] `az webapp/spring-cloud connection`: Add command `create redis/redis-enterprise` to support more target resources

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
ServiceConnector

**Review by wangzelin007 — APPROVED** [review]

**Comment by kairu-ms** [comment]
@houk-ms, Could you fill [History Notes] of your PR?

**Review by kairu-ms — APPROVED** [review]

**Comment by houk-ms** [comment]
@kairu-ms added.

**Review by xfz11 — APPROVED** [review]

**Comment by houk-ms** [comment]
@kairu-ms Can you help merge the pr when you think it's ready?

**Pull request merged**
