### PR TITLE
sql server & sql mi: use rg location

### LINKED ISSUE #6204: SQL: use default location from resource group
SQL commands should use new `get_default_location_from_resource_group` validator to create servers in the default location for the resource group.

### PR DESCRIPTION
**Pull request by jaredmoo**
Fixes #6204

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by jaredmoo** [comment]
Needs test coverage

**Comment by jaredmoo** [comment]
Test recording blocked by #9591

**Comment by adewaleo** [comment]
@jaredmoo  Please update dev and rebase this branch onto dev to get the test preparer fixes.
I apologize for any inconvenience

**Comment by jaredmoo** [comment]
Error not caused by this pr
> Install src/command_modules/azure-cli-appservice
ERROR: paramiko 2.5.0 has requirement cryptography>=2.5, but you'll have cryptography 2.4.2 which is incompatible.

**Comment by tjprescott** [comment]
@jaredmoo this has also been fixed in https://github.com/Azure/azure-cli/pull/9612. If you pull the latest you should be good to go.

**Pull request merged**
