### PR TITLE
[App Service] Fix #20901: `az functionapp update`: Update `--slot` logic to work correctly

### LINKED ISSUE #20901: azure functionapp update does not properly handle the --slot setting
**Describe the bug**
When the trying to update properties for a Azure Function Slot (specifically the loadBalancing property) using Azure CLI, the change is applied to the production slot rather than the slot specified

**To Reproduce**
ex: `az functionapp update -g $resourceGroup -n $name -s $slotName --set siteConfig.loadBalancing=PerSiteRoundRobin`

**Expected behavior**
The expectation is that properties for the `$slotName` slot is updated.

**Environment summary**
run in Powershell Core 7.1.3, Azure CLI 2.31.0

**Additional context**
The biggest reason this is a big problem is that we change all our configuration in our staging slot and then swap into the main slot, which ensures no down time during deployments.

### PR DESCRIPTION
**Pull request by haroonf**
**Related command**
`az functionapp update`

**Description**
Fixes #20901

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Review by panchagnula — APPROVED** [review]
Just one comment on re-recording tests for functionapp slot

**Comment by haroonf** [comment]
> Please check the tests & re-record as needed.

Test using `functionapp update` run with --live and all passed.

**Comment by yonzhan** [comment]
App Service

**Review by wangzelin007 — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@haroonf Could you add test case for this change?

**Comment by zhoxing-ms** [comment]
By the way, please note that if you do not resolve those comments before Thursday, this PR will not be able to catch up with the release of this sprint, we can only postpone it to the next sprint **(08-02)**

**Comment by haroonf** [comment]
> 

Added test

**Comment by haroonf** [comment]
> @haroonf Could you add test case for this change?

Added test

**Comment by haroonf** [comment]
> By the way, could you please resolve these comments in time? Please note that if you do not resolve those comments before Thursday, this PR will not be able to catch up with the release of this sprint, we can only postpone it to the next sprint **(08-02)**

All comments have been addressed.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
