### PR TITLE
[ACR] Better support of top/orderby in show-tags/manifests commands (#294)

### PR DESCRIPTION
**Pull request by djyou**
Fixes https://github.com/Azure/acr/issues/146

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by SteveLasker** [comment]
What does the end result look like?

**Comment by djyou** [comment]
The results are the same as what they are today, but `--orderby` and `--top` can be used without `--detail`.

```
>az acr repository show-tags -n registry --repository repo --top 10 --orderby time_desc -o table
Result
--------
44
43
42
41
40
39
38
37
36
35
```

```
>az acr repository show-manifests -n registry --repository repo --top 10 --orderby time_desc -o table
Digest                                                                   Timestamp
-----------------------------------------------------------------------  ----------------------------
sha256:1a6fd470b9ce10849be79e99529a88371dff60c60aab424c077007f6979b4812  2018-10-30T00:51:10.584711Z
sha256:9a473576460dbe2875e2453e062c164e8e143d4f1a6034df6ef3d4bfef8647d0  2018-09-26T00:25:09.0731995Z
sha256:fe15f45ce2323b8aafcbf2f624fda8c50828f9d462f45b5cfc8b72985802ef57  2018-09-26T00:20:04.4117687Z
sha256:3f4ac4b661b8148b1e9e9c4599d0d8a171befffc2c71704f877873765f57b10d  2018-09-26T00:15:08.5194697Z
sha256:70c9fc6dcd1f267e66736ded6ede3e02eea4675f75f93f2b8c428b7d20725ade  2018-09-26T00:09:41.418886Z
sha256:feedfe953beb766a33d71045a8a2a84ffc516061c62b58c3aba557940e68b37f  2018-09-26T00:05:07.6533834Z
sha256:340c287d579746a990ef0d4a7949d3d3f6dbd664f46533aad5e27d65199ac572  2018-09-26T00:00:38.6599204Z
sha256:9ae917c1249b7e94989ffeb2f83e1d7b4950e0d641adda410ece8b0d0e27e950  2018-09-25T23:56:17.7610829Z
sha256:05f635822318e4b9327ac88843f4d26af32aa5198d10f48f5e4720405e3ad361  2018-09-25T23:47:13.105366Z
sha256:dc101cd899e0d8cfcd56cbd5386386bc0cbc574245daeb11fb37283bbdc55b04  2018-09-25T23:38:20.6350034Z
```

**Comment by SteveLasker** [comment]
LGTM

**Pull request merged**
