### PR TITLE
{ACR} Fix "Message: The subscription '00000000-0000-0000-0000-000000000000' could not be found." test error by waiting for operation

### PR DESCRIPTION
**Pull request by nguyenm2151**
**Related command**
az acr connected-registry delete

**Description**
Fix "Message: The subscription '00000000-0000-0000-0000-000000000000' could not be found." test error by waiting for delete operation to finish. Addressing these two issues https://github.com/Azure/azure-cli/pull/18853#discussion_r1810260089 and https://github.com/Azure/azure-cli/pull/18611#discussion_r1810284183 following this solution https://github.com/Azure/azure-cli/pull/17185. Previous PR https://github.com/Azure/azure-cli/pull/30195

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by yanzhudd** [comment]
please resolve the style check issue: https://dev.azure.com/azclitools/public/_build/results?buildId=203331&view=logs&j=36dd4138-4d53-5e46-00d9-e5cd9744be05&t=1cf3879c-0a42-5ccd-7693-7a4781d739d8&l=94

**Comment by yanzhudd** [comment]
@bebound Could you please help to review this PR as well?

**Comment by bebound** [comment]
> @bebound Could you please help to review this PR as well?

LGTM, need to trigger batch CI as well.

**Comment by nguyenm2151** [comment]
@yanzhudd, I fixed the style issue. Tried to rerun the tests, but its stuck at "Waiting for status to be reported". Also how do I trigger a batch CI, not sure if I have permission to do that

**Comment by bebound** [comment]
I've push this pr to https://github.com/Azure/azure-cli/tree/nguyenma/fixTrack2SDKBug and the batched CI is triggered.

**Review by bebound — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
