### PR TITLE
[Backup] `az backup restore restore-disks`: Add support for enabling Disk access settings for managed VM restores

### PR DESCRIPTION
**Pull request by zubairabid**
**Related command**

`az backup restore restore-disks`

**Description**

Some managed VMs have disks with PE enabled (they have some Disk Access associated). We can now use Enhanced Policy to back them up. During restore, we have the option of allowing public access, specifying a new disk access, or specifying PE with the same disk access. We have added changes that allow for this.

**Testing Guide**

**History Notes**

[Backup] Add support for enabling Disk access settings for managed VM restores

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Backup

**Comment by zubairabid** [comment]
Requesting a review for this release cycle (subject to merge validation).

**Comment by yonzhan** [comment]
Please fix CI issues

**Comment by zhoxing-ms** [comment]
@zubairabid Please add some test cases for these new parameters

**Comment by zhoxing-ms** [comment]
Please note that we are launching the release for this sprint this week. Please resolve all comments by tomorrow, otherwise the release of this PR will have to be postponed to the next sprint **(on 10-08)**

**Comment by zhoxing-ms** [comment]
@zubairabid Any update? Please note that we are launching the release for this sprint this week. Please resolve all comments and CI issues by tomorrow, otherwise the release of this PR will have to be postponed to the next sprint **(on 10-08)**

**Comment by zubairabid** [comment]
> @zubairabid Any update? Please note that we are launching the release for this sprint this week. Please resolve all comments and CI issues by tomorrow, otherwise the release of this PR will have to be postponed to the next sprint **(on 11-05)**

Hi @zhoxing-ms , we're waiting on the service team to confirm when we can go ahead with this release, will fix the issues after that. Might go into the next sprint.

**Comment by zubairabid** [comment]
@zhoxing-ms I've fixed the PR content issue flagged by the pipeline, please rerun the pipeline once. Service team has given their approval, if all else is good then we can merge this into main for next sprint's release.

**Comment by zhoxing-ms** [comment]
Please add some test cases for these changes

**Comment by zubairabid** [comment]
Added a new test, and that + all local tests are working - please rerun the pipeline @zhoxing-ms

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
