### PR TITLE
[AKS] `az aks create`/`az aks nodepool add`: Remove restrictions on optional values for option `--zones`

### PR DESCRIPTION
**Pull request by FumingZhang**
**Related command**

- az aks create
- az aks nodepool add

**Description**

Remove restrictions on candidate values (previously only `"1"`, `"2"`, `"3"` are allowed) of option `--zones` in commands `az aks create` and `az aks nodepool add`.

**Testing Guide**

**History Notes**

[AKS] `az aks create`: Remove restrictions on optional values for option `--zones`
[AKS] `az aks nodepool add`: Remove restrictions on optional values for option `--zones`

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by yanzhudd** [comment]
Please rerun related tests for this change.

**Comment by FumingZhang** [comment]
There are 3 live test cases related to the option, queued [live test pipeline](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=80398296&view=results) to rerun these cases.

- test_aks_availability_zones
- test_aks_availability_zones_msi
- test_aks_enable_utlra_ssd

**Comment by yanzhudd** [comment]
Since the restriction will be removed from the core module in the coming new version of CLI, it is not necessary to make this change in the AKS module.

**Pull request closed without merging**
