### PR TITLE
[AppService]: fix  # 18266 - webapp config appsettings set command causing all values to default to "false" in version 2.24.0

### PR DESCRIPTION
**Pull request by Kotasudhakarreddy**
#18265 , #18266 
**Description**

When executing the webapp config appsettings set command the result Application Settings in the WebApp Configuration value is set to false for each setting defined in the settings array.
**Testing Guide**

JSON Settings Example
[
{
"slotSetting": false,
"name": "ExampleParameter1",
"value": "@Microsoft.KeyVault(SecretUri=https://xxxxx.vault.azure.net/secrets/ExampleParameter1)"
},
{
"slotSetting": false,
"name": " ExampleParameter2",
"value": "@Microsoft.KeyVault(SecretUri=https://xxxxx.vault.azure.net/secrets/ExampleParameter2)"
}
]

Command Example
az webapp config appsettings set --name $WebAppName --resource-group $ResourceGroup --settings @$settings.json

Expected behavior
**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by Juliehzl** [comment]
As it is a bug fix for breaking change, please send PR tp `release` branch. We will do a hotfix next Monday in Shanghai time.

**Comment by Juliehzl** [comment]
please create a new branch target release as your current branch contains too many features in dev, which should not be added to release for hot fix.

**Comment by Kotasudhakarreddy** [comment]
> please create a new branch target release as your current branch contains too many features in dev, which should not be added to release for hot fix.

I am working on it. Will create a new branch and a PR too.

**Comment by Juliehzl** [comment]
> > please create a new branch target release as your current branch contains too many features in dev, which should not be added to release for hot fix.
> 
> I am working on it. Will create a new branch and a PR too.

Then I will close this one

**Pull request closed without merging**
