### PR TITLE
[acr] import --image warn users if target_tag/image is prefixed with '/'

### PR DESCRIPTION
**Pull request by adewaleo**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by adewaleo** [comment]
Simple validation to deal with the user-input issue @SteveLasker found. Does this look good or is this overkill @sajayantony

target tags warning

**Comment by SteveLasker** [comment]
Is this an error or warning? I'm still not convinced we shouldn't just fix this up for the user. 
what happens when I `push demo42.azurecr.io/repo//image:tag` Does the // generate an error, or just get fixed up?

**Comment by adewaleo** [comment]
@SteveLasker 

The warning is coming from the CLI (the yellow), whilst the error is coming from the service. This PR is only for the CLI

I have made a PR to the service's RP to use a shortened link instead of the longer url. The spacing error was actually a field reference not the period between two sentences.

I tried tagging an image locally so I could attempt to push the image to a private ACR instance. I got the following error:

```
> docker tag hello-world tosinreg5.azurecr.io//hello-world:v1
Error parsing reference: "tosinreg5.azurecr.io//hello-world:v1" is not a valid repository/tag: invalid reference format
```

**Comment by adewaleo** [comment]
I will be closing this pr. Seems like we won't be moving ahead with client-side validation this time.

**Pull request closed without merging**
