### PR TITLE
[ARM] `az bicep uninstall`: Add new command to uninstall bicep

### PR DESCRIPTION
**Pull request by shenglol**
**Description**

Closes https://github.com/Azure/bicep/issues/2551.
Closes https://github.com/Azure/azure-cli/issues/18437.

**Testing Guide**

**History Notes**

[ARM] az bicep uninstall: Add new command to uninstall bicep
[ARM] az bicep build: Fix an issue where running with --stdout doesn't print any output

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by shenglol** [comment]
@zhoxing-ms Could you please take a look at this when you get a chance?

**Comment by yonzhan** [comment]
ARM

**Comment by zhoxing-ms** [comment]
@Shenglol Could you add help for `bicep uninstall` to fix the CI issue. And please check whether the PR title I modified is suitable.

**Comment by shenglol** [comment]
> @shenglol Could you add help for `bicep uninstall` to fix the CI issue. And please check whether the PR title I modified is suitable.

@zhoxing-ms Whoops I forgot to add help...just pushed a commit to fix it. The PR title looks good!

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
