### PR TITLE
[APIM] `apim create/update`: Add new parameters `--public-network-access` and `--disable-gateway`

### PR DESCRIPTION
**Pull request by yingru97**
**Related command**

**Description**

Add parameters to allow users to to set "disable_gateway" and "public_network_access" properties of apim service

**Testing Guide**

**History Notes**

[APIM] `apim create/update`: Add `--public-network-access` to support specifying whether or not public endpoint access is allowed for this API management service
[APIM] `apim create/update`: Add `--disable-gateway` to support disabling gateway in the master region

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
APIM

**Comment by zhoxing-ms** [comment]
@yingru97 Could you please resolve those conflicts?

**Comment by zhoxing-ms** [comment]
@yingru97 Please refer to this [guideline](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests) to add the specific description of those new parameters in the PR description

**Comment by zhoxing-ms** [comment]
Could you add some test cases for the new parameter `--disable-gateway`?

**Comment by zhoxing-ms** [comment]
@yingru97 I updated the PR title and PR description for you, please see if they meet your expectations

**Comment by zhoxing-ms** [comment]
@yingru97 Since we will launch the release of this sprint tomorrow, please address all the comments before tomorrow, otherwise this PR will not be able to catch up with the release of this sprint, and it can only be postponed to the next sprint **(12-06)**

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
