### PR TITLE
[APIM] Onboard to private endpoint for API Management

### PR DESCRIPTION
**Pull request by yingru97**
**Description**

This PR added support for managing private endpoint in API Management and added test for validation
**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
APIM

**Review by wangzelin007 — APPROVED** [review]

**Review by jsntcy — APPROVED** [review]

**Comment by yingru97** [comment]
Updated the PR to resolve merge conflicts. Please merge it. Thanks! @wangzelin007 @jsntcy

**Comment by zhoxing-ms** [comment]
@yingru97 Could you please address those CI test issues?

**Comment by yingru97** [comment]
@zhoxing-ms  All CI test issues are resolved now. Forgot to run test again after resolving merge conflicts before.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
