### PR TITLE
[AKS] az aks create: add enable-encryption-at-host parameter

### PR DESCRIPTION
**Pull request by andyzhangx**
**Description**

az aks create: add enable-encryption-at-host parameter

**Testing Guide**

```console
docker run -v ${HOME}:/root -it andyzhangx/azure-cli:2.22.1
az aks create -g $RESOURCE_GROUP_NAME -n $CLUSTER_NAME --node-count 1 --node-vm-size Standard_DS2_v2 --generate-ssh-keys --kubernetes-version 1.20.2 --enable-encryption-at-host
az aks nodepool add --name nodepool2 --cluster-name $CLUSTER_NAME --resource-group $RESOURCE_GROUP_NAME --enable-encryption-at-host
```

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by andyzhangx** [comment]
```
2021-04-22T03:48:24.7236220Z -  FAIL - HIGH severity: option_length_too_long
2021-04-22T03:48:24.7237497Z     Parameter: aks create, `enable_encryption_at_host` - The lengths of all options ['--enable-encryption-at-host'] are longer than threshold 22. Argument enable_encryption_at_host must have a short abbreviation.
2021-04-22T03:48:24.7238773Z     Parameter: aks nodepool add, `enable_encryption_at_host` - The lengths of all options ['--enable-encryption-at-host'] are longer than threshold 22. Argument enable_encryption_at_host must have a short abbreviation.
```

**Comment by andyzhangx** [comment]
I already added exception rules in `linter_exclusions.yml`, not sure why it still failed:

```
2021-04-22T03:48:24.7236220Z -  FAIL - HIGH severity: option_length_too_long
2021-04-22T03:48:24.7237497Z     Parameter: aks create, `enable_encryption_at_host` - The lengths of all options ['--enable-encryption-at-host'] are longer than threshold 22. Argument enable_encryption_at_host must have a short abbreviation.
2021-04-22T03:48:24.7238773Z     Parameter: aks nodepool add, `enable_encryption_at_host` - The lengths of all options ['--enable-encryption-at-host'] are longer than threshold 22. Argument enable_encryption_at_host must have a short abbreviation.
```

**Comment by andyzhangx** [comment]
@fengzhou-msft would you help review? thanks.

**Comment by andyzhangx** [comment]
@qwordy could you help review? thanks.

**Review by qwordy — APPROVED** [review]

**Comment by andyzhangx** [comment]
@qwordy can you merge this PR? thanks.

**Review by fengzhou-msft — APPROVED** [review]

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
