### PR TITLE
[ARM] `az deployment`: Fix the error message of ARM deployment to the correct JSON format

### PR DESCRIPTION
**Pull request by zhoxing-ms**
**Related command**

`az deployment sub/mg/tenant/group create`

**Description**

Issue: #22835 
Related PR: #20238
Fix the error message of ARM deployment to the correct JSON format

Before
Screenshot 2022-06-13 120803

After
Screenshot 2022-06-13 115802

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
ARM

**Review by wangzelin007 — APPROVED** [review]

**Review by wbreza — APPROVED** [review]
LGTM, validated MSI package locally.

**Comment by jsntcy** [comment]
Do other commands need this behavior?   @zhoxing-ms

**Comment by zhoxing-ms** [comment]
> Do other commands need this behavior?

Not at the moment. It is only used to deal with the problem of nested error messages for ARM deployment error

**Review by jsntcy — APPROVED** [review]

**Pull request merged**
