### PR TITLE
[sql] `az sql midb update`: Add update command

### PR DESCRIPTION
**Pull request by MilanBrkicFON**
**Related command**

az sql midb

**Description**

This PR adds update command for managed database and added tags parameter to create managed database command.

**Testing Guide**

Manually tested only

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
sql

**Comment by MilanBrkicFON** [comment]
@yonzhan can someone review this PR? Thanks

**Comment by evelyn-ys** [comment]
Can you add test for this new command?

**Comment by MilanBrkicFON** [comment]
@evelyn-ys test are added

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
