### PR TITLE
[Consumption] Fix #20995 #23825: Update `az consumption` API version

### LINKED ISSUE #20995: az consumption budget show returns error
## Describe the bug

When running `az consumption budget show`, I get the following error: 

`(400) You are using old version :2018-01-31 with new filter interface - change the version to 2019-04-01-preview (Request ID: 95daf08c-61fc-496f-85a6-aa81ac5b2889)`

Any idea on how to fix this? 

**Command Name**
`az consumption budget show`

**Errors:**
```
(400) You are using old version :2018-01-31 with new filter interface - change the version to 2019-04-01-preview (Request ID: 95daf08c-61fc-496f-85a6-aa81ac5b2889)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az consumption budget show --budget-name {}`

## Expected Behavior
The commando returns a budget and its information. 

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.32.0

Extensions:
account 0.2.1
application-insights 0.1.14
authV2 0.1.1
azure-devops 0.20.0
log-analytics-solution 0.1.1
portal 0.1.2
scheduled-query 0.4.0

Dependencies:
msal 1.16.0
azure-mgmt-resource 20.0.0
```

### PR DESCRIPTION
**Pull request by matsest**
**Related command**

`az consumption`

**Description**

Updates the API version due to errors listed in https://github.com/Azure/azure-cli/issues/20995 and https://github.com/Azure/azure-cli/issues/23825

**Testing Guide**

```
az consumption budget list
```

**History Notes**

[Consumption] Fix #20995 #23825: Update `az consumption` API version

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by aglazer7** [comment]
Hi guys,
I really need this to be merged as soon as possible.
Is there something I can do to help?
It looks weird that some tests failed as the only change is in few string values.
@jsntcy , @kairu-ms ? Can you please review and give some feedback?
I will really appreciate that. Thanks!

**Comment by jsntcy** [comment]
@matsest, please fix CI error first.

@necusjz, @kairu-ms, please help review.

**Comment by matsest** [comment]
Thanks for reviewing this @jsntcy - I don't have access to see the build outputs from CI pipelines here. Not sure if it due to the builds expired or if it's not visible in ADO for me publicly. Could one of you help either retrigger or provide information about the build errors?

**Comment by matsest** [comment]
Added a commit with updating the API versions in the tests as well.

**Comment by matsest** [comment]
The remaining pipeline executions seems to time out. I've updated the formatting of the PR title and content accordingly, but other CI tests seem to pass @jsntcy

**Comment by aglazer7** [comment]
Hi @matsest ,
Thanks for help. You can check pipelines here: https://dev.azure.com/azclitools/public/_build?definitionId=32&_a=summary
Looks like it still has some issues with PR guidelines.
It's probably just a typo. In pipeline logs you will find:

[Consumption] Fix #20995 #23825: Update az consumption API versions: missing ` around az consumption API versions

**Comment by matsest** [comment]
> Hi @matsest , Thanks for help. You can check pipelines here: [dev.azure.com/azclitools/public/_build?definitionId=32&_a=summary](https://dev.azure.com/azclitools/public/_build?definitionId=32&_a=summary) Looks like it still has some issues with PR guidelines. It's probably just a typo. In pipeline logs you will find:
> 
> [Consumption] Fix #20995 #23825: Update az consumption API versions: missing ` around az consumption API versions

Thanks, I updated the title and content of the PR to add those ` - but it doesn't retrigger the pipeline. Don't know if it is possible from your side to retrigger only that step, or if it would need to do a full build/test for that?

**Comment by aglazer7** [comment]
Not possible from my side either.
@jsntcy, @kairu-ms, @necusjz  Could you please trigger the pipeline manually? The issue with PR title has been fixed, but this not auto triggers the pipeline. Pipeline should now run without errors. Thanks.

**Comment by matsest** [comment]
@jsntcy @kairu-ms @necusjz The CI is now running successfully :) Thanks for the helpful comments.

**Comment by aglazer7** [comment]
Thank you for your effort @matsest. Really appreciate that!

**Review by kairu-ms — APPROVED** [review]

**Comment by necusjz** [comment]
@matsest @aglazer7 As it leveraged codegen tool, could you please upload the model in https://github.com/Azure/aaz as well? Otherwise, there will be potential risks...

**Comment by matsest** [comment]
@necusjz Thanks - I'm not familiar with the codegen mechanism aaz and aaz-dev-tools from before - I spent some time reading and trying to set it up locally to update the model last week but was not able to get it to run successfully. If a maintainer could help with that part I would greatly appreciate it. A pointer to a step in the doc to update the model or a similar PR with an API update would probably help as well.

**Comment by Hymian7** [comment]
This change most probably broke the `az consumption usage list` command as described in #28323. Still looking into this but I think this is because the new API version does not provide the usageStart and usageEnd attributes.

**Pull request merged**
