### PR TITLE
[App Service] Fix #12289: `az functionapp deployment source config-zip`: Allow build on zip deploy for windows function apps 

### LINKED ISSUE #12289: functionapp: az cli disables build on deploy for windows function apps
**Describe the bug**
https://github.com/Azure/azure-cli/pull/10706 effective disables remote builds for windows consumption plan function apps. 

Changelog does not mention that new flag is for linux function apps only:
> Added --build-remote flag for az functionapp deployment source config-zip to support remote build action during function app deployment.

Also no deprecation warning for have been given for windows consumption plan with SCM_DO_BUILD_DURING_DEPLOYMENT=true

Documentation[1] does not specify any ways to trigger `npm install`.

**To Reproduce**
Running `az functionapp deployment source config-zip --build-remote ...` fails with `Remote build is only available on Linux function apps`

Alternative running `az functionapp deployment source config-zip` without --build-remote flag **changes function app settings** and does **not trigger `npm install`**:

```
Setting ENABLE_ORYX_BUILD to false
Setting SCM_DO_BUILD_DURING_DEPLOYMENT to false
```

**Expected behavior**
After zip deployment function host should trigger `npm install`(or other installation method) like az cli did before the pull request.

Alternative fix: another way to trigger `npm install` after deployment with az cli should be documented.

**Environment summary**
```
azure-cli                          2.1.0

command-modules-nspkg              2.0.3
core                               2.1.0
nspkg                              3.0.4
telemetry                          1.0.4
```

**Additional context**

[1] https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies#remote-build

**Workrounds**

- Trigger npm install manually in kudu console
- fetch publishing profile with az cli and trigger npm install through kudu REST API

### PR DESCRIPTION
**Pull request by StrawnSC**
**Description**

Fixes #12289 by removing the check that was preventing building on zip deploy for windows functionapps. Also prevents updating the `ENABLE_ORYX_BUILD` and `SCM_DO_BUILD_DURING_DEPLOYMENT` app settings for windows function apps to comply with the [docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies#remote-build). 

**Testing Guide**

`azdev test test_functionapp_windows_zip_deploy --live`

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
App Service

**Review by wangzelin007 — APPROVED** [review]
LGTM

**Review by panchagnula — CHANGES_REQUESTED** [review]
The changes look good however there are a bunch of tests in FunctionApps, that should be re-recorded/tested as well since we update the function app deployment code. Thanks!

**Review by panchagnula — APPROVED** [review]
LGTM

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
