### PR TITLE
Specify output for interactive mode on windows

### LINKED ISSUE #3929: az interactive doesn't work on Windows Server 2016 Datacenter
### Description
az interactive brings up the interactive session but none of the cmds work

---
```
az interactive
 
az>> cloud list
'NoneType' object has no attribute 'write'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35\lib\site-packages\azclishell\app.py", line 662, in cli_execute
    OutputProducer(formatter=formatter, file=self.output).out(result)
  File "C:\Program Files (x86)\Python35\lib\site-packages\azure\cli\core\_output.py", line 116, in out
    print(output, file=self.file, end='')
  File "C:\Program Files (x86)\Python35\lib\site-packages\colorama\ansitowin32.py", line 40, in write
    self.__convertor.write(text)
  File "C:\Program Files (x86)\Python35\lib\site-packages\colorama\ansitowin32.py", line 141, in write
    self.write_and_convert(text)
  File "C:\Program Files (x86)\Python35\lib\site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Program Files (x86)\Python35\lib\site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
    self.wrapped.write(text[start:end])
AttributeError: 'NoneType' object has no attribute 'write'
az>>
 

```
### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Answer here:
pip install

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
Answer here:
azure-cli (2.0.9+1.dev20170627)

acr (2.0.7+1.dev20170627)
acs (2.0.9+1.dev20170627)
appservice (0.1.9+1.dev20170627)
batch (3.0.2+1.dev20170627)
billing (0.1.2+1.dev20170627)
cdn (0.0.5+1.dev20170627)
cloud (2.0.5+1.dev20170627)
cognitiveservices (0.1.5+1.dev20170627)
command-modules-nspkg (2.0.0+1.dev20170627)
component (2.0.6+1.dev20170627)
configure (2.0.9+1.dev20170627)
consumption (0.1.2+1.dev20170627)
core (2.0.10+1.dev20170627)
cosmosdb (0.1.9+1.dev20170627)
dla (0.0.9+1.dev20170627)
dls (0.0.9+1.dev20170627)
feedback (2.0.5+1.dev20170627)
find (0.2.5+1.dev20170627)
interactive (0.3.5+1.dev20170627)
iot (0.1.8+1.dev20170627)
keyvault (2.0.7+1.dev20170627)
lab (0.0.7+1.dev20170627)
monitor (0.0.7+1.dev20170627)
network (2.0.9+1.dev20170627)
nspkg (3.0.0+1.dev20170627)
profile (2.0.7+1.dev20170627)
rdbms (0.0.4+1.dev20170627)
redis (0.2.6+1.dev20170627)
resource (2.0.9+1.dev20170627)
role (2.0.7+1.dev20170627)
sf (1.0.4+1.dev20170627)
sql (2.0.6+1.dev20170627)
storage (2.0.9+1.dev20170627)
vm (2.0.9+1.dev20170627)
Python (Windows) 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)]

Python location 'C:\Program Files (x86)\Python35\python.exe'

**OS Version:** What OS and version are you using?  
Answer here:
Windows Server 2016 Datacenter

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
cmd.exe

### PR DESCRIPTION
**Pull request by oakeyc**
fixes #3929
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by derekbekoe** [comment]
@oakeyc What was the cause of the issue? How does this fix it? Were you able to repro it and the Windows server VM?

**Comment by oakeyc** [comment]
It was a problem on windows because the file output wasn't specified causing the 
```bash
AttributeError: 'NoneType' object has no attribute 'write'
```

**Comment by derekbekoe** [comment]
@oakeyc What's the difference between `self.output` and `sys.stdout` and how is this change specific to the issue on Windows?

**Comment by oakeyc** [comment]
@derekbekoe, before when `self.output` was None I would use the OutputProducer. But I would specify `file=self.output,' and on line 111 in _output.py
``` bash
    def out(self, obj):
        if platform.system() == 'Windows':
            self.file = colorama.AnsiToWin32(self.file).stream
        output = self.formatter(obj)
```
will now throw an error because self.file is None.

**Comment by derekbekoe** [comment]
@oakeyc There are different changes now?
Can you run on a Windows Server 2016 Datacenter VM to verify the change?

**Comment by oakeyc** [comment]
@derekbekoe can verify the changes work as expected.

**Pull request merged**
