### PR TITLE
{Role} Fixed typo in example of az ad user get-member-groups

### PR DESCRIPTION
**Pull request by bablulawrence**
**Description**  
Changed "myuser@consoso.com" in example provided for command `az ad user get-member-groups` to "myuser@contoso.com".

**Testing Guide**  

**History Notes**  

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Role

**Review by MyronFanQiu — APPROVED** [review]

**Review by jiasli — APPROVED** [review]

**Comment by jiasli** [comment]
Nice catch. Thank you for the contribution. 😊

**Comment by jiasli** [comment]
@haroldrandom, this example is auto-generated. How do we report to Aladdin team about erroneous examples?

**Comment by jiasli** [comment]
@mirdaki, this example is auto-generated. Is it possible to fix erroneous examples?

**Comment by mirdaki** [comment]
@jiasli sure, I'll let the relevant team members know about this!

**Comment by mirdaki** [comment]
Found the original source of the example and have a PR to fix it https://github.com/MicrosoftDocs/azure-docs/pull/62482. Once that change goes in, our system should pull it in and use the right spelling.

**Pull request merged**
