### PR TITLE
{App Service}:Updating azure-mgmt-web to latest verion

### PR DESCRIPTION
**Pull request by panchagnula**
**Description**  

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yungezz** [comment]
hi @panchagnula the change itself looks good,  it will need live tests regression full webapp related commands, and maybe some other services who depends on azure-mgmt-web. Just to double confirm live test is executed and no regression.

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls review this PR? thanks

**Comment by jongio** [comment]
@panchagnula - Can we work on getting this merged this week so we can continue the CLI updates?  Thanks, Jon

**Comment by panchagnula** [comment]
> @panchagnula - Can we work on getting this merged this week so we can continue the CLI updates? Thanks, Jon

Yep working on it.

**Comment by panchagnula** [comment]
> How did you update the version? It seems that there is no corresponding code.

Sorry - I re-added the missing setup.py files with the recordings now.

**Comment by qwordy** [comment]
@panchagnula  ready to merge?

**Comment by panchagnula** [comment]
> @panchagnula ready to merge?

Yes please :)

**Pull request merged**
