### PR TITLE
ams command-module: Bug fix in parser logics for --play-ready-template option input.

### PR DESCRIPTION
**Pull request by shigeyf**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by tjprescott** [comment]
This fails a test on Python 2.7.
test_content_key_policy_create_with_playready_success

**Comment by shigeyf** [comment]
@tjprescott 
Travis CI testing is against not only to 'ams' module.
The error seems to be about 'vmss' and others.
This fix does not seem to be harmful. Please check doubly on your side.

**Comment by tjprescott** [comment]
The test that is failing is test_content_key_policy_create_with_playready_success which is a test for the AMS module. You will need to fix that. I have re-started the performance test.

**Comment by shigeyf** [comment]
Oops! Sorry, I missed the error line in such a long log! Let me check how I can fix the error.

**Comment by shigeyf** [comment]
I have fixed the test error: test_content_key_policy_create_with_playready_success
Appreciate your review!

**Pull request merged**
