### PR TITLE
convert long 'or not' chains to use any()

### PR DESCRIPTION
**Pull request by Brodan**
There were a few spots throughout the codebase I noticed a list of multiple `or not` clauses. To shorten these conditionals and clean up a few lines, I've converted to these clauses to use the `any()` built-in.
---

### CODE REVIEW

**Comment by yugangw-msft** [comment]
I will resolve the version bump for this PR

**Comment by adewaleo** [comment]
@yugangw-msft I have a local copy of these changes. Should i create a new PR?

**Comment by yugangw-msft** [comment]
I will handle it later

**Comment by tjprescott** [comment]
Closing due to inactivity.

**Pull request closed without merging**
