### PR TITLE
Sprint 67 - BotService: remove v3 bot creation support

### PR DESCRIPTION
**Pull request by stevengum**
- Remove v3 bot creation support
   - v3 Web App and Function App Bots can no longer be created
   - Left `--version` flag for future-proofing
- Rerecord tests

@adewaleo FYI

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by stevengum** [comment]
@adewaleo, @tjprescott the tests that failed were tests for commands that don't perform any network calls for their success. I added the `ResourceGroupPreparer` to avoid the `"Please run 'az login' to setup account."` when I first added the tests which worked until now.

Now that the .yaml files were removed (example test: `test_botservice_prepare_deploy_csharp`) the error message is reappearing, but locally the test runs successfully in live and "recorded" mode. Do either of you have any workarounds for avoiding this error message?

**Comment by stevengum** [comment]
I added back the recordings that were deleted when I re-recorded the tests, and that caused the build to pass.

**Comment by stevengum** [comment]
@yugang-msft could I get a review please? 😄

**Comment by yugangw-msft** [comment]
Can you please rebase for me to merge?

**Comment by stevengum** [comment]
@yugangw-msft, done! Pending CI

**Pull request merged**
