### PR TITLE
{Keyvault} Vendor `azure-keyvault` track1 SDK to make customization for supporting Python 3.11

### PR DESCRIPTION
**Pull request by evelyn-ys**
**Description**

Keyvault module now depends on
- public **track1** sdk `azure-keyvault` (api version `2016-10-01` and `7.0`)
- **vendored track1** sdk for `az keyvault security-domain` command group (api version `7.2`)
- public **track2** sdk `azure-keyvault-keys`/`azure-keyvault-secrets`/`azure-keyvault-certificates`/`azure-keyvault-administration`

But track1 sdk can't work with Python 3.11 because sdk uses `inspect.getargspec` which has been dropped in Python 3.11.

This PR removes public track1 sdk dependency and migrate all related commands to use vendored track1 sdk so that we can customize sdk code to unblock Python 3.11 support as a tmp workaround. Considering track1 sdk is not maintained and won't release new version anymore, our goal is to fully migrate all track1 sdk dependency to track2 which needs to be planned ASAP.

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Keyvault

**Review by bebound — APPROVED** [review]

**Review by kairu-ms — COMMENTED** [review]
Did you test how many extensions will be affected?

**Review by jiasli — APPROVED** [review]

**Comment by jiasli** [comment]
Should we use a separate PR to fix the usage of `inspect.getargspec`?

https://github.com/Azure/azure-cli/blob/df516d7935e38843e0e33c5d22417ae41a1e260f/src/azure-cli/azure/cli/command_modules/keyvault/vendored_sdks/azure_keyvault_t1/key_vault_authentication.py#L62

**Comment by jiasli** [comment]
> Did you test how many extensions will be affected?

This is a good point and reminds me that once we start bundling Python 3.11, extensions that don't support Python 3.11 will be broken.

**Comment by evelyn-ys** [comment]
> Did you test how many extensions will be affected?

Yes I have triggered [extension regression pipeline](https://dev.azure.com/azclitools/internal/_build/results?buildId=82344&view=results) and manually check the failure extension tests. The failures are not caused by keyvault

**Comment by evelyn-ys** [comment]
> Should we use a separate PR to fix the usage of `inspect.getargspec`?
> 
> https://github.com/Azure/azure-cli/blob/df516d7935e38843e0e33c5d22417ae41a1e260f/src/azure-cli/azure/cli/command_modules/keyvault/vendored_sdks/azure_keyvault_t1/key_vault_authentication.py#L62

Yes I would prefer to let @bebound to modify this in https://github.com/Azure/azure-cli/pull/26923

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
