### PR TITLE
[WebPubSub] Initial PR for Azure WebPubSub Service

### PR DESCRIPTION
**Pull request by zackliu**
**Description**

Initial PR for onboard azcli for Azure WebPubSub Service

**Testing Guide**

General commands:
Create: `az webpubsub create`
Update: `az webpubsub update`
Show: `az webpubsub show`
List: `az webpubsub list`
Restart: `az webpubsub restart`
Delete : `az webpubsub delete`

Key management:
List keys: `az webpubsub key list`
Regenerate keys: `az webpubsub key regenerate`

Event handler management:
Clear all event handler: `az webpubsub event-handler clear`
General update event handler: `az webpubsub event-handler update`
List event handler: `az webpubsub event-handler list`
Update with subgroup command: `az webpubsub event-handler hub update` `az webpubsub event-handler hub remove`

Network rules management:
List rules: `az webpubsub network-rule list`
Update rules: `az webpubsub network-rule update`
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
WebPubSub

**Review by kairu-ms — APPROVED** [review]
LGTM

**Comment by yonzhan** [comment]
WebPubSub

**Comment by yungezz** [comment]
hi @azckliu, for new RP onboarding to CLI, the recommend way is extension https://github.com/Azure/azure-cli-extensions. Pls move this to extension repo. Could you share more about the context of putting this in core module?

**Comment by zackliu** [comment]
@yungezz This service shares similar commands and RP with SignalR, so I think it's mature to put in core module. And we will have extension part for data plane commands which are more experimental and still in progress.

**Comment by yungezz** [comment]
> @yungezz This service shares similar commands and RP with SignalR, so I think it's mature to put in core module. And we will have extension part for data plane commands which are more experimental and still in progress. But, I can move to Extension.

thanks @azckliu for context. Difference between core and extension is not about command preview or GA. It's more about how CLI package. Azure CLI has extension dynamic install feature. When user run a command in extension, the extension willl be automatically installed, user no need to remember extension name. With this feature, user experience for modules in Core and extension is quite same. Meanwhile, there're more benefit to use extension:
- Fast iteration. extension could release it on demand, no need to wait for 3 weeks release cadence of cli core.
- based on vendor SDK, remove dependency to released Python SDK.
- More autonomy on extension

**Comment by zackliu** [comment]
Moved to extensions https://github.com/Azure/azure-cli-extensions/pull/3297
And private endpoint part will be in core module. I will create another PR for it.

**Pull request closed without merging**
