### PR TITLE
[RDBMS] `az postgres flexible-server backup create/delete`: New commands to support creating and deleting backups on PostgreSql Flex Server

### PR DESCRIPTION
**Pull request by nasc17**
**Related command**
`az postgres flexible-server backup`

**Description**
Adding ability to create and delete backups.

**Testing Guide**
Manually

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by nasc17** [comment]
@evelyn-ys please review

**Comment by evelyn-ys** [comment]
Pls fix this
```
-  FAIL - HIGH severity: missing_parameter_help
    Parameter: postgres flexible-server backup delete, `yes` - Missing help
```

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
