### PR TITLE
{RDBMS} Add support for left-shift clusters in new regions

### PR DESCRIPTION
**Pull request by nasc17**
Related command
Add support for Left Shift clusters in regions westus2 and eastus2. Needed for capacity.

Description
Add support for Left Shift clusters in regions westus2 and eastus2. Needed for capacity.

Testing Guide
Verified manually

### CODE REVIEW

**Comment by yonzhan** [comment]
RDBMS

**Comment by nasc17** [comment]
@evelyn-ys can we please get this reviewed. Needed for running test in current release

**Review by evelyn-ys — APPROVED** [review]

**Comment by evelyn-ys** [comment]
Can you add the related command info following https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#format-pr-title

**Comment by nasc17** [comment]
> Can you add the related command info following https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#format-pr-title

Non-customer facing change, updated title. Update does not change command, just allows for proper mapping of dns naming conventions in testing regions

**Pull request merged**
