### PR TITLE
Fix kubectl version, always use latest stable.

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes https://github.com/Azure/azure-cli/issues/2506

### CODE REVIEW

**Comment by troydai** [comment]
@brendandburns can you take a look the build break on 3.6?

**Comment by troydai** [comment]
Ping @brendandburns

**Comment by johanste** [comment]
Ping @brendandburns

**Comment by brendandburns** [comment]
Sorry will look @ this today.

**Comment by brendandburns** [comment]
The travis results appear to be borked... I can't see the issue. I'll push a revised commit to try to trigger a rebuild.

**Comment by johanste** [comment]
@troydai, it looks like the storage account create failed on Python 3.5...

======================================================================
FAIL: test_create_account_sas (tests.test_storage_account_scenarios.StorageAccountTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Azure/azure-cli/src/azure-cli-testsdk/azure/cli/testsdk/preparers.py", line 55, in _preparer_wrapper
    fn(test_class_instance, **kwargs)
  File "/home/travis/build/Azure/azure-cli/src/azure-cli-testsdk/azure/cli/testsdk/preparers.py", line 55, in _preparer_wrapper
    fn(test_class_instance, **kwargs)
  File "/home/travis/build/Azure/azure-cli/src/command_modules/azure-cli-storage/tests/test_storage_account_scenarios.py", line 136, in test_create_account_sas
    assert u'sig' in sas_keys
AssertionError:

**Comment by brendandburns** [comment]
@troydai that seems very unlikely to be related to my change. Flakey test?

**Comment by troydai** [comment]
This is a known flakey test. It will pass once rerun.

**Comment by troydai** [comment]
Test rerun and pass. The flakey test is known and unrelated. The changes look good. I'll merge this PR shortly.

**Pull request merged**
