### PR TITLE
[Network] `az network private-endpoint-connection`: Add provider `Microsoft.DBforMySQL/flexibleServers`

### PR DESCRIPTION
**Pull request by Ruiion**
**Related command**

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Networks

**Comment by Ruiion** [comment]
@necusjz I tried to build the local cli use this command: azdev setup --cli ./azure-cli --repo ./azure-cli-extensions. However, the cli I've built cannot get error messages when running this command. Do you know if something wrong in my environment?

command:
az network private-endpoint create 

exception:
Error loading command module 'network': expected str, bytes or os.PathLike object, not NoneType
'private-endpoint' is misspelled or not recognized by the system.
Did you mean 'private-dns' ?

**Comment by necusjz** [comment]
@Ruiion IMO, there could be 2 possible reasons:
1. Have you pull the latest of azure-cli dev branch?
2. If Yes, if there any **empty folders** under `xx/network/aaz/latest/network`?

**Comment by Ruiion** [comment]
@necusjz 
1. I've pull the latest azure-cli branch.
2. There is no empty folders under xx/network/aaz/latest/network. The private_endpoint folder is there but I get error when using az network private-endpoint create Eg:
image

**Comment by necusjz** [comment]
@Ruiion Maybe it's caused by other folders, e.g. `cross-lb`, could you please double check it?

**Comment by Ruiion** [comment]
@necusjz This folder do look wired. cross_region_lb

image

**Comment by necusjz** [comment]
> @necusjz This folder do look wired. cross_region_lb
> 
> image

Ya, just remove it and it can be back to normal.

**Comment by hzhang87** [comment]
Can you please try add tests?

**Comment by Ruiion** [comment]
> Can you please try add tests?

Yes, will do

**Comment by necusjz** [comment]
correct the title for you :)

**Comment by Ruiion** [comment]
Thank you so much. 

> correct the title for you :)

Thank you. I still have some test to finish. Do you think that I can still catch up with CC?

**Comment by necusjz** [comment]
> Thank you. I still have some test to finish. Do you think that I can still catch up with CC?

Our next build is Match 3rd, everything before that is allowed.

**Comment by Ruiion** [comment]
image
@necusjz Do you have some insight for why pipeline test fail? I successfully run it in my local

**Comment by necusjz** [comment]
> image
> 
> @necusjz Do you have some insight for why pipeline test fail? I successfully run it in my local

Sorry, I have no idea about that, just provide a similar PR https://github.com/Azure/azure-cli/pull/25489. Maybe you can pull the latest codes and run `azdev setup` again, then re-recording.

**Comment by Ruiion** [comment]
Thanks for your great help. Request for your review. Thanks. @necusjz

**Review by necusjz — APPROVED** [review]

**Pull request merged**
