### PR TITLE
[IoT] Update iothub mgmt sdk

### PR DESCRIPTION
**Pull request by xscript**
Official Azure MGMT SDK for IoTHub is released recently. So remove the generated client library and use the official SDK.

### CODE REVIEW

**Comment by tjprescott** [comment]
> from azure.cli.command_modules.iot.sas_token_auth import SasTokenAuthentication

My only question is whether this should be pulled out of the CLI and hosted elsewhere so that other Python implementations can use it. Does IoT have a data-plane SDK that this would be part of?

---
Refers to: src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/custom.py:20 in 23d4a66. [](commit_id = 23d4a661c3b13937cc6170c0ee3225e314765833, deletion_comment = True)

**Comment by xscript** [comment]
@tjprescott  Agree with you. This class should be part of [IoT SDK for Python](https://github.com/Azure/azure-iot-sdks/tree/master/python). Unfortunately, the Python SDK there is a wrapper of C implementation, which makes it not convenient enough for cross-platform support. That's why I implement my version in the first place. 
This class is essentially a custom authentication for [msrest package](https://pypi.python.org/pypi/msrest/0.4.3). However it is not public in GitHub yet. I can create a issue to request them to add this authentication.
But before the request is accepted and released, I think we don't have many options but leaving it as now.

**Comment by tjprescott** [comment]
@xscript I do understand that. So if you have a developer writing a cross-platform IoT application in Python, are you going to direct them to get the SAS source from the CLI repo? Long term, do you see your Python-only implementation replacing the C-wrapper implementation currently in the SDK? This isn't something I would hold up this PR for, but I think in the medium to long term we need to look at moving this out of the CLI repo and either hosting in its own repo or getting it promoted into the SDK and deprecating the C-wrapper implementation.

---
In reply to: [245911732](https://github.com/Azure/azure-cli/pull/840#issuecomment-245911732) [](ancestors = 245911732)

**Comment by xscript** [comment]
@tjprescott  Good question. I wouldn't direct Python IoT application developers to reference the CLI repo. For now, they **SHOULD** use the official Python wrapper for IoT SDK. Since the Python wrapper doesn't have cross platform support in place, application developers have to deal with it.
We have synced with IoT SDK team before. They will improve the Python wrapper implementation and make it more cross-platform friendly. And then, we will use the official IoT Python SDK (wrapper of the C implementation) to replace what we have now in CLI repo, just as now I am using official Azure IoTHub MGMT SDK to replace previous implementation. This is the long term plan AFAIK.

**Comment by tjprescott** [comment]
@xscript sounds good to me. It looks like there are conflicts that need to be resolved before the PR can be merged, likely the result of merging #828 yesterday. Once it's updated I'm happy to merge it.

**Comment by xscript** [comment]
@tjprescott I've resolved the conflict. Please help merge this PR. 
Thanks! :smiley:

**Comment by tjprescott** [comment]
:shipit:

**Pull request merged**
