### PR TITLE
{Maps} update terms text for create account

### PR DESCRIPTION
**Pull request by SudhindraKovalam**
**History Notes:**  
{Maps} az maps account create: updated terms text displayed during account creation process per CELA guidance.  

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S167

**Comment by jiasli** [comment]
Please fix the indentation. Alternatively, you may use  triple quotes `"""` to make the paragraph more readable. 

Also, please make sure to check **Allow edits from maintainers** when submitting PR to accelerate the reviewing process.

**Comment by SudhindraKovalam** [comment]
I had changed the PR title accidently.. But realized that it was non conformant to standards and changed back... but it still says the PR title check has failed. How can I fix this ?

**Pull request merged**
