### PR TITLE
{AKS} `az aks create`: Correct use of "comma-separated" in help

### PR DESCRIPTION
**Pull request by mboersma**
**Related command**

`az aks create --help`

**Description**

This fixes some typos and missing hyphens in the phrase "comma-separated".

**Testing Guide**

**History Notes**

[AKS] `az aks create`: Correct use of "comma-separated" in help

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Review by FumingZhang — COMMENTED** [review]
LGTM

Please fix failed CI check

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
