### PR TITLE
[AKS] Hotfix: `az aks create`: Fix issue that `--attach-acr` option can't work

### PR DESCRIPTION
**Pull request by FumingZhang**
**Description**

Fix the issue that `--attach-acr` option would raise an error "No service principal provided to create the acrpull role assignment for acr." in `az aks create` when using managed identity or user assigned identity.

The code bug was introduced in [PR #19429](https://github.com/Azure/azure-cli/pull/19429) and [PR #19509](https://github.com/Azure/azure-cli/pull/19509). In the process of refactoring the implementation of `aks create`, we added an additional check when processing the option `--attach-acr` to verify whether service principal exists when managed identity is not enabled. However, when managed identity is enabled, we still check for the existence of service principal by mistake, which resulted in this error.

May refer the dev branch [PR #20406](https://github.com/Azure/azure-cli/pull/20406).

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Review by andyliuliming — APPROVED** [review]

**Comment by yonzhan** [comment]
AKS

**Review by wangzelin007 — APPROVED** [review]

**Review by wangzelin007 — CHANGES_REQUESTED** [review]
Please pull the latest code from remote dev branch.

**Comment by FumingZhang** [comment]
> Please pull the latest code from remote dev branch.

Ok, now code base is on dev branch. But in this way, we are shipping all the changes since last release, is this expected?

**Review by calvinhzy — APPROVED** [review]

**Comment by FumingZhang** [comment]
Will follow official release, may refer the dev branch PR #20406.

**Pull request closed without merging**
