### PR TITLE
[App Config] `az appconfig`: GA features - soft-delete, feature-filter, strict-import and, disable-local-auth

### PR DESCRIPTION
**Pull request by pratiksanglikar**
**Related command**
- `az appconfig list-deleted`
- `az appconfig show-deleted`
- `az appconfig purge`
- `az appconfig recover`
- `az appconfig kv import`

**Description**
This PR makes the commands listed above generally available with the release of new stable API version 2022-05-01.

**Testing Guide**
No functional changes in this PR, passing unit tests are good indicator of everything working as expected.

**History Notes**
- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by pratiksanglikar** [comment]
@avanigupta @shenmuxiaosen please take a look.

**Comment by yonzhan** [comment]
App Config

**Review by avanigupta — APPROVED** [review]
Looks good! Two test recording files got deleted. Can you check if those need to be added back?

**Comment by pratiksanglikar** [comment]
@avanigupta I have observed the same issue in the past, new test runs don't create the recording files for some of the tests. I will check what's happening!

**Comment by pratiksanglikar** [comment]
@avanigupta, out of the two files, one is a stray file that we never cleared up and I was able to generate the another one.
- `test_azconfig_disable_local_auth.yaml` this file hasn't been updated since Azure CLI version `2.23.x` and `azure-mgmt-appconfig` package version `0.1.0`. We probably removed the test case long back, but never cleared the recording file and have been carrying it up since then. I have removed it now.
- `test_azconfig_aad_auth.yaml` is the one which I was able to generate again by cleaning the local files and running the tests again.

We should be good to go!

**Review by wangzelin007 — APPROVED** [review]

**Comment by pratiksanglikar** [comment]
@zhoxing-ms this PR is ready to merge!

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
