### PR TITLE
Fix examples and documentation to correctly escape or quote shell cha…

### PR DESCRIPTION
**Pull request by sptramer**
…racters where required. [#4876]

Simplify user-supplied values by marking them as ${...} variables.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [ ] Each command and parameter has a meaningful description.
- [ ] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by sptramer** [comment]
@tjprescott This is probably a `sed` issue on my part. I am intending this to be bash-style variable notation to both make it clear that these are user-provided values and to allow for easier cut-and-paste from examples.

**Comment by tjprescott** [comment]
@sptramer thanks. Before we had discussed avoiding shell-specific nomenclature or at the very least calling it out. This would make many examples that would work in bash or CMD now bash-specific. I'm not necessarily against that--I just want that to be a deliberate decision. I agree with the CAP_SNAKE vs. CamelCase.

**Comment by sptramer** [comment]
@tjprescott I believe that we have standardized on the idea that examples and inline code presented in documentation is meant to be `bash`-style only since we have multiple examples which do not work on all platforms. Double-check with @JasonRShaver on that. If we'd like to keep things platform-agnostic I can reformat `${USER_VALUE}` into something user-supplied but not system-specific by removing the leading `$`.

**Comment by tjprescott** [comment]
I'm okay with the bash specific if Jason is.  But I would like use to resolve the ${foo} or {$foo} references in the PR :)

**Comment by sptramer** [comment]
@tjprescott On it and it should be fixed by EOB today.

**Comment by sptramer** [comment]
@tjprescott - Went ahead and fixed things. Right now I'm leaving off the `$` identifiers because I want to make sure that this is a good docs strategy, _and_ there isn't time to fix everything (even piece by piece.) This should be good for now.

**Comment by sptramer** [comment]
@tjprescott CI is failing due to not having version-bumped the command modules, but in the past we have agreed that `_help.py` changes alone should not require a version bump. Merging is blocked however, due to the versioning issue. What's the recommendation?

**Comment by tjprescott** [comment]
Due to recent changes to the CLI core, you will need to rebase your changes against the latest in the dev branch.

**Comment by sptramer** [comment]
@tjprescott Rebased and updated.

**Comment by tjprescott** [comment]
@derekbekoe can the version check script be updated to ignore modules whose only changes are to `_help.py`?

**Comment by tjprescott** [comment]
Can you rebase the latest dev changes?  Should fix the issue with role version.

**Pull request merged**
