### PR TITLE
websites: Updating to use the latest python SDK version

### PR DESCRIPTION
**Pull request by panchagnula**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by panchagnula** [comment]
still waiting for the latest SDK drop to be published - CI/CD will pass once this is published.

**Comment by lmazuel** [comment]
@panchagnula released as https://pypi.org/project/azure-mgmt-web/0.40.0/

**Comment by panchagnula** [comment]
@tjprescott i am seeing CI build errors stating T**he following modules have invalid versions:
azure-cli-core
azure-cli**

Do i need to update the setup.py version for these projects as well?

**Comment by troydai** [comment]
Please rebase on latest `dev`, the CI issue will be resolved.

**Comment by troydai** [comment]
We need this PR to fix `dev` branch as the `azure-mgmt-web` release just broke the CI.

**Comment by panchagnula** [comment]
Fixing the failing tests

**Comment by troydai** [comment]
Thank you @panchagnula . Because I pin the botservice dependency of azure-mgmt-web to 0.40.0, in addition to the changes in the appservice module, please also:
1) Update the botservice dependency of azure-mgmt-web to 0.40.0 and use `==` operator to pin version.
2) Fix build break in botservice.

**Comment by panchagnula** [comment]
@troydai, i cannot run the bot-service CLI tests using Visual Studio, i added the Folder to the existing project & noticed that i still don't find the tests - i usually use this method to debug & fix tests easily. I tried running via env command line as follows
` env\Scripts\run_tests.exe --src-file G:\CLI\azure-cli\src\command_modules\azure-cli-botservice\azure\cli\command_modules\botservice\tests\latest\test_bot_commands.py`
& i get the message - No tests set to run. Can i get some help with this so that i can fix the bot app tests as well?

**Comment by troydai** [comment]
@swagatmishra2007 can you help?

**Comment by panchagnula** [comment]
@troydai , @tjprescott - the CI is failing on the cli-extension commands, haven't updated these as yet, how do i fix these CLI errors? Should i start a new PR for CLI-extensions?

**Comment by troydai** [comment]
@williexu for the extension question. The tests are in place to prevent from changes in the CLI breaking extension. In your case I guess the extension is sharing the same `azure-mgmt-web` with the Core, am I right?

**Comment by williexu** [comment]
@panchagnula it seems like the webapp extension does not support the newer version of `azure-mgmt-web`. This will mean that the webapp extension will be broken if a user tries to use it once this PR is released with the CLI.

You have two options, both of which require a extension PR:
-Make a PR specifying a max CLI version for the webapp extension.
-Fix the webapp extension to allow for the newer sdk version.

**Comment by panchagnula** [comment]
@williexu i was planning to start a new PR for extensions once this got merged to dev, especially to work with the new SDK. I understand that the next CLI release is September so i was planning to get extension release around the same time. One question is how do i find the current CLI version, so that i can set the value here https://github.com/Azure/azure-cli-extensions/blob/master/src/webapp/azext_webapp/azext_metadata.json, so that i can unblock this PR. Thank you.

**Comment by williexu** [comment]
@panchagnula the most recently released CLI version is v2.0.45: https://pypi.org/project/azure-cli/
With the extension change, keep in mind you will have publish the extension and update the index.json.

**Comment by panchagnula** [comment]
Updated extensions with the max corecli version https://github.com/Azure/azure-cli-extensions/pull/275

**Pull request merged**
