### PR TITLE
[AKS] `az aks create/update`: Update region map for default region creation with new Azure Monitor Workspace regions

### PR DESCRIPTION
**Pull request by bragi92**
**Related command**

```az aks create -n kaveeshcli22 -g kaveeshcli --location westeurope --enable-azure-monitor-metrics --grafana-resource-id "{full_id}"```

```az aks update -n kaveeshcli22 -g kaveeshcli --enable-azure-monitor-metrics --enable-windows-recording-rules```

**Description**

Azure Monitor Workspace now supports new regions so I am updating the default mapping for Azure Monitor Workspace to support these new regions in case the customer does not provide one while onboarding to the Managed Prometheus addon.

**Testing Guide**

**Scenario (region map update)**:
- Set context to AzureCloud `az cloud set --name AzureCloud` 
- Create a new cluster without specifying an Azure Monitor Workspace -> `az aks create -n kaveeshcli -g kaveeshcli --location canadaeast--enable-azure-monitor-metrics`
- Use a cluster in a new region that is being updated in this PR like -> italynorth, israelcentral or germanywestcentral. Make sure that the onboarding succeeds and the output contains a line similar to the following -> Using Azure Monitor Workspace (stores prometheus metrics) : DefaultAzureMonitorWorkspace-canadaeast

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by bragi92** [comment]
@zhoxing-ms , @FumingZhang please have a look at this PR whenever you have a chance.

**Review by FumingZhang — COMMENTED** [review]
lgtm

btw, do you have a chance to fix the issue related to a CRI before? I think the following line should be deleted.
https://github.com/Azure/azure-cli/blob/248054ec7c0a045ff597231cd86f3b605cc79231/src/azure-cli/azure/cli/command_modules/acs/managed_cluster_decorator.py#L7424

**Comment by bragi92** [comment]
@FumingZhang  I created another PR to fix the CRI issue here : https://github.com/Azure/azure-cli/pull/28414/files

**Review by zhoxing-ms — APPROVED** [review]

**Review by FumingZhang — APPROVED** [review]

**Comment by bragi92** [comment]
@FumingZhang or @zhoxing-ms can you help me with merging this PR in? I do not have write permissions to the repo.

**Pull request merged**
