### PR TITLE
Enable HTTP logger after msrest change

### PR DESCRIPTION
**Pull request by derekbekoe**
This PR is in response to https://github.com/Azure/msrest-for-python/pull/86

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/5596
This is an **experimental preview** for @microsoft users.

**Comment by derekbekoe** [comment]
@lmazuel What's the best way to verify this change?

**Comment by lmazuel** [comment]
If you mean CLI unittests, I don't think you can :/. If really you want to do it, I would use a `assertLog` tests, something like this:
https://github.com/Azure/msrest-for-python/blob/b79de4259d99eb46878ae17255bb3667df08bdd9/tests/test_serialization.py#L1986-L2006

If you mean manually test it on your local machine, install msrest from the branch of the PR and `--debug` should show HTTP logs exactly like now.

**Comment by derekbekoe** [comment]
I wanted to verify manually and just have 👍

**Comment by lmazuel** [comment]
Do you have an estimated release date for this CLI core? This way I merge the msrest one after new cli-core is out, and no disruption for users.

**Comment by derekbekoe** [comment]
We'll publish on 2/27

**Comment by derekbekoe** [comment]
@lmazuel Can you 'approve' this if it looks good then I can merge.

**Pull request merged**
