### PR TITLE
[Synapse] `az link-connection`: Add cmdlets to support synapse link connections

### PR DESCRIPTION
**Pull request by kevinzz6**
**Related command**

**Description**

Add some cmdlets to spport synapse link connections 

**Testing Guide**

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Synapse

**Comment by jsntcy** [comment]
@kevinzz6, please fix the CI first.

**Comment by kevinzz6** [comment]
@jsntcy  Hi, I updated most test yaml files then test passed. Unfortunately 3 tests still failed with strange error message. They are not related to this new adding feature cmdlets and they were good before. Could we make these 3 test skipped temporarily so that can deploy link connection on May release? I will fix them later.

**Comment by jsntcy** [comment]
NO, it means your new api version breaks the previous functionalities, you need figure out why it failed.

**Comment by jsntcy** [comment]
As this PR increase the version for azure-core, it may break other functionalities in Azure CLI since azure-core has some breaking changes in new version. We plan to increase the version for azure-core in next sprint as we only have one day left for release, and it's a big risk to increase the version for azure-core now. So this PR will probably postpone to next sprint.

**Pull request closed without merging**
