### PR TITLE
[Backup] increasing VM protection limit from 100 to 1000

### PR DESCRIPTION
**Pull request by hiaga**
**Description**  

Relaxed the client side limit for AzureIaasVM protection from 100 to 1000
 
**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [Yes ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [Yes ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Backup

**Comment by yungezz** [comment]
cc @houk-ms for error message

**Comment by hiaga** [comment]
@fengzhou-msft   please trigger a rerun for the azure pipeline build checks

**Review by fengzhou-msft — APPROVED** [review]

**Pull request merged**
