### PR TITLE
{Packaging} Adapt entry script to Mariner

### PR DESCRIPTION
**Pull request by jiasli**
## Description

See code comments.

## References

- https://github.com/Azure/azure-cli/pull/17491
- https://github.com/Azure/azure-cli/pull/20061

### CODE REVIEW

**Comment by jiasli** [comment]
A very valuable post: https://stackoverflow.com/questions/3113472/how-to-make-an-rpm-spec-that-installs-libraries-to-usr-lib-xor-usr-lib64-based

Thanks @chalamalasetty

**Comment by yonzhan** [comment]
Packaging

**Comment by mfrw** [comment]
> A very valuable post: https://stackoverflow.com/questions/3113472/how-to-make-an-rpm-spec-that-installs-libraries-to-usr-lib-xor-usr-lib64-based. Thanks @chalamalasetty.
> 
> According to this, if we download a package from https://packages.microsoft.com/yumrepos/azure-cli/ and unzip it, we can see `lib64` is already hardcoded when packaging:
> 
> image
> 
> image

This looks like a `win-win` :)

**Review by wangzelin007 — APPROVED** [review]

**Review by mfrw — APPROVED** [review]
LGTM.
Thank you @jiasli

**Pull request merged**
