### PR TITLE
{Core} Add synapse endpoint and suffix.

### PR DESCRIPTION
**Pull request by sunsw1994**
**Description**  
This PR adds the synapse endpoint suffix for AzureCloud and AzureChinaCloud. Prepare for adding cli synapse module.

**Testing Guide**  

`az cloud show -n AzureCloud`
`az cloud show -n AzureChinaCloud`

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Core

**Comment by sunsw1994** [comment]
hi @fengzhou-msft， ping for reviewing this PR. Thanks.

**Comment by fengzhou-msft** [comment]
@sunsw1994 have you submitted a PR to modify the [ARM metadata](https://management.azure.com/metadata/endpoints?api-version=2019-05-01) as well? You need to update `Microsoft.WindowsAzure.ResourceStack.Frontdoor.CloudEndpoints_2019_05_01` in [`ServiceConfiguration.cscfg`](https://msazure.visualstudio.com/One/_git/AzureUX-ARM?path=%2Fsrc%2Ffrontdoor%2FDeployment%2FCloud%2FPackage%2FServiceConfiguration.cscfg) for public clouds.

Otherwise, using the ARM metadata URL in Azure CLI will break synapse:
https://github.com/Azure/azure-cli/blob/bea3ae6fb3202ff050453f66b73d03d99ea0bc10/src/azure-cli-core/azure/cli/core/cloud.py#L218

**Comment by idear1203** [comment]
> @sunsw1994 have you submitted a PR to modify the [ARM metadata](https://management.azure.com/metadata/endpoints?api-version=2019-05-01) as well? You need to update `Microsoft.WindowsAzure.ResourceStack.Frontdoor.CloudEndpoints_2019_05_01` in [`ServiceConfiguration.cscfg`](https://msazure.visualstudio.com/One/_git/AzureUX-ARM?path=%2Fsrc%2Ffrontdoor%2FDeployment%2FCloud%2FPackage%2FServiceConfiguration.cscfg) for public clouds.
> 
> Otherwise, using the ARM metadata URL in Azure CLI will break synapse:
> https://github.com/Azure/azure-cli/blob/bea3ae6fb3202ff050453f66b73d03d99ea0bc10/src/azure-cli-core/azure/cli/core/cloud.py#L218

Hi @fengzhou-msft , thank you for the guide! We didn't have experience in updating the ARM metadata before. Could you please provide some information/documentation about ARM metadata? For example, how is the ARM metadata used in Azure CLI? Besides, I would like to know who usually maintain update the [`ServiceConfiguration.cscfg`](https://msazure.visualstudio.com/One/_git/AzureUX-ARM?path=%2Fsrc%2Ffrontdoor%2FDeployment%2FCloud%2FPackage%2FServiceConfiguration.cscfg)? Is our backend devs or CLI team a better choice for this task?

**Comment by fengzhou-msft** [comment]
@idear1203 Azure CLI supports importing cloudendpoints from a metadata url using env var: `ARM_CLOUD_METADATA_URL` to prepare for cloud parity and JEDI requirements. In the future, the hard-coded endpoints will only be used as a fallback when the url is not available.
https://github.com/Azure/azure-cli/blob/bea3ae6fb3202ff050453f66b73d03d99ea0bc10/src/azure-cli-core/azure/cli/core/cloud.py#L362-L371

RP Team is responsible for adding endpoints in ARM metadata first, then they can be used in client tools such as Azure CLI and Azure Powershell.

This is a new process, I will let you know once I have the contact person from ARM team.

**Comment by sunsw1994** [comment]
> @idear1203 Azure CLI supports importing cloud endpoints from a metadata url using env var: `ARM_CLOUD_METADATA_URL` to prepare for cloud parity and JEDI requirements. In the future, the hard-coded endpoints will only be used as a fallback when the url is not available.
> https://github.com/Azure/azure-cli/blob/bea3ae6fb3202ff050453f66b73d03d99ea0bc10/src/azure-cli-core/azure/cli/core/cloud.py#L362-L371
> 
> RP Team is responsible for adding endpoints in ARM metadata first, then they can be used in client tools such as Azure CLI and Azure Powershell.
> 
> This is a new process, I will let you know once I have the contact person from ARM team.

Hi @fengzhou-msft thanks for your guide and important information.  We plan to add Synapse CLI Module recently, a controllable schedule is important for us.  So our team have some concern want to confirm with you: 

1. Is ` Microsoft.WindowsAzure.ResourceStack.Frontdoor.CloudEndpoints_2019_05_01`  in ServiceConfiguration.cscfg just for CLI or Powershell to get endpoint? We want to confirm our change will not have other effect.

2. Whether we have authentication to open a PR to modify [ServiceConfiguration.cscfg](https://msazure.visualstudio.com/One/_git/AzureUX-ARM?path=%2Fsrc%2Ffrontdoor%2FDeployment%2FCloud%2FPackage%2FServiceConfiguration.cscfg)? `Who` will review that and `how long` it will take?

3. If we just remove related code and only use hardcode endpoint in cloud.py, can this PR be trusted valid and merged? Or add endpoint to metadata url is a required operation now?  
https://github.com/Azure/azure-cli/blob/bea3ae6fb3202ff050453f66b73d03d99ea0bc10/src/azure-cli-core/azure/cli/core/cloud.py#L218

**Comment by fengzhou-msft** [comment]
@sunsw1994 If you need to release recently, you could add a patch for your endpoints first. I have refactored the code to make it easier to do, like:
https://github.com/Azure/azure-cli/blob/5de3cef4c79d307e8aa55229584e7a294e3e64fb/src/azure-cli-core/azure/cli/core/cloud.py#L259
and suffix
https://github.com/Azure/azure-cli/blob/5de3cef4c79d307e8aa55229584e7a294e3e64fb/src/azure-cli-core/azure/cli/core/cloud.py#L266

Arm endpoint suffix value removes the beginning dot, so you'll use `add_dot=True` as well.

Meanwhile, please continue the process to add it in ARM metadata. To answer your question:
1. `CloudEndpoints_2019_05_01` is used by both Azure CLI and Powershell. Other client tools may already use it as well.
2. You can contact Manik Sikka on how to submit the PR.
3. It is required to at least patch the metadata URL as it will become the default source of endpoints soon.

**Comment by yungezz** [comment]
hi @sunsw1994 is this endpoint and suffix added to ARM metadata also? https://management.azure.com/metadata/endpoints?api-version=2019-05-01. We can sync with you offline on this.

**Comment by sunsw1994** [comment]
> hi @sunsw1994 is this endpoint and suffix added to ARM metadata also? https://management.azure.com/metadata/endpoints?api-version=2019-05-01. We can sync with you offline on this. @fengzhou-msft already give very clear instruction and information. pls ignore the message :)

Hi @yungezz , endpoint and suffix have not been added to ARM metadata. I try to contract with Manik Sikka to add it last Friday, but no reply from him now. I can add you in that thread, thanks for your help. 

And I have committed a patch to fit with new code structure, could you or @fengzhou-msft please review that.

**Pull request merged**
