### PR TITLE
[Botservice - Do Not Merge] Add --signing-secret to Slack Channel Creation

### PR DESCRIPTION
**Pull request by mdrichardson**
Partially Fixes: https://github.com/microsoft/botframework-sdk/issues/5647

This takes care of the AZ CLI portion of the linked issue, above. Basically it allows the `az bot slack create` command to auto-register the Slack Channel, so long as the user provides their `--signing-secret` (which can be found in Slack).

This needs additional updates to other Azure tooling (swagger and ARM, I believe) before merging.

## Discussion

Should this be a required parameter? In my own testing, there isn't a link or anything that pops up in Azure Portal to go through the OAuth flow and the Slack channel is sort of...frozen. I think we should either:

1. Make it a required parameter, or
2. When not included, open a link for the user to start the OAuth flow (it's returned in the HTTP request when successful) -- or at least make the link **very** apparent

## Review Requests

I don't believe I have the permissions to add them myself so,

@stevengum 
@swagatmishra2007 

Please review.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
@jiasli please help with this PR.

**Comment by jiasli** [comment]
@stevengum, could you please help review this PR?

**Comment by jiasli** [comment]
Temporarily close as service is not ready yet.

**Pull request closed without merging**
