### PR TITLE
Computefleet CLI for 2024-11-01

### PR DESCRIPTION
**Pull request by rahuls-microsoft**
**Related command**

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by rahuls-microsoft** [comment]
The tests need to be bound with the helpers and set the correct fleet parameter.
The recordings should be updated accordingly.
This code is generated by Github Copilot by looking at the CLI modules and .Net SDK tests. Some final changes will be needed.
Please assist, as I am not familiar with Python and this code structure.

**Comment by rahuls-microsoft** [comment]
The tests need to be bound with the helpers and set the correct fleet parameter.
The recordings should be updated accordingly.
This code is generated by Github Copilot by looking at the CLI modules and .Net SDK tests. Some finishing touches will be needed.
Please assist, as I am not familiar with Python and this code structure.

**Comment by kairu-ms** [comment]
Hi @rahuls-microsoft any reason to onboarding as azure-cli module? We recommend you onboard it as the extension in azure-cli-extensions repo.

**Pull request closed without merging**
