### PR TITLE
{AppConfig} Migrating AppConfig to use official data plane SDK

### PR DESCRIPTION
**Pull request by avanigupta**
**Description**  

This PR will adopt the [official python SDK for App Configuration](https://pypi.org/project/azure-appconfiguration/) for all data plane operations. 

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by avanigupta** [comment]
Hi @recao, could you please help in reviewing this PR?

**Comment by yonzhan** [comment]
AppConfig

**Review by recao — APPROVED** [review]
:shipit:

**Comment by avanigupta** [comment]
Hi @bim-msft, this PR is ready for your review.

**Review by bim-msft — APPROVED** [review]
Changes look good to me!

**Pull request merged**
