### PR TITLE
{AppConfig} Update azure-mgmt-appconfiguration version to 0.5.0

### PR DESCRIPTION
**Pull request by avanigupta**
**Description**  

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by avanigupta** [comment]
@shenmuxiaosen can you please help review this PR?

**Comment by yungezz** [comment]
hi @bim-msft could you pls review this PR?

**Comment by shenmuxiaosen** [comment]
Please hold this pr as we have some issue with central India RP API version.

**Comment by avanigupta** [comment]
Hi @bim-msft , this PR can be merged now. We can include these changes in the next CLI release.

**Comment by bim-msft** [comment]
Hi @haroldrandom @fengzhou-msft please take your time to review this PR, thanks.

**Comment by bim-msft** [comment]
@avanigupta Hi, could you please run live tests again? Because there are conflicts with dev branch.

**Pull request merged**
