### PR TITLE
[Packaging] Add Ubuntu 21.10 Impish Indri support and drop Ubuntu 21.04 Hirsute Hippo support

### PR DESCRIPTION
**Pull request by jiasli**
**Description**

- Close https://github.com/Azure/azure-cli/issues/20058

Per https://wiki.ubuntu.com/Releases:

- Ubuntu 21.04 Hirsute Hippo has reached End of Life. We should drop it.
- Ubuntu 21.10 Impish Indri is the latest release. We should support it. Customers running Impish can't install Azure CLI (https://github.com/MicrosoftDocs/azure-docs-cli/issues/2256).

**History Notes**

[Packaging] Add Ubuntu 21.10 Impish Indri support
[Packaging] Drop Ubuntu 21.04 Hirsute Hippo support

### CODE REVIEW

**Comment by yonzhan** [comment]
Packaging

**Comment by jiasli** [comment]
Building Python 3.6 on Impish fails

https://dev.azure.com/azure-sdk/public/_build/results?buildId=1334752&view=logs&j=3785ca6e-0e58-5722-c7f7-f718f26c5084&t=c716ad81-3cd2-56a0-7de7-4ff271e84af1

```
Segmentation fault (core dumped)
make: *** [Makefile:1102: install] Error 139
```

I think we need to bump the embedded Python to 3.8 first (https://github.com/Azure/azure-cli/pull/20869).

**Review by calvinhzy — APPROVED** [review]

**Review by wangzelin007 — APPROVED** [review]

**Comment by jiasli** [comment]
Release CI has been updated accordingly: https://dev.azure.com/azure-sdk/internal/_releaseDefinition?definitionId=79&_a=definition-tasks&environmentId=153

**Comment by jiasli** [comment]
Unexpectedly, https://packages.microsoft.com/ doesn't support zstd-compressed deb packages generated by Ubuntu 21.10 Impish:

```
$ ar t azure-cli_2.33.1-1~impish_all.deb
debian-binary
control.tar.zst
data.tar.zst
```

Before Ubuntu 21.04, packages are zx-compressed.

```
$ ar t azure-cli_2.33.1-1~focal_all.deb
debian-binary
control.tar.xz
data.tar.xz
```

We will work with Microsoft Linux Repo team to make sure zstd compression is supported as soon as possible, before the release of the next LTS version of Ubuntu - 22.04 Jammy Jellyfish.

**Pull request merged**
