### PR TITLE
Add iotcentral commands

### PR DESCRIPTION
**Pull request by emgarten**
Command line support for create/list/update/delete of IoT Central applications on http://aka.ms/iotcentral

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

//cc @zzcodework @amrenbin

### CODE REVIEW

**Comment by troydai** [comment]
Hi @emgarten did you manage to talk to any of CIL team members? For new command modules, we need to do a command review first. Additionally, can these commands be folded under `iot` command module?

**Comment by zzcodework** [comment]
Hi @troydai, iotcentral is a new product with different resource types, so we decided to use a separate folder instead of under existing iot module. @emgarten is currently on vacation, I think he's already talked to some folks in their team, but we'll double check after he's back.

**Comment by zzcodework** [comment]
Add @r-delgadillo

**Comment by emgarten** [comment]
✅  Everything looks good on the CI now, this is ready for review.

**Pull request merged**
