### PR TITLE
[SQL] `az sql midb restore`: Add support for cross-subscription restore

### PR DESCRIPTION
**Pull request by milanbrkic-ms**
**Related command**

**Description**

Adding support for cross-subscription restore for managed database. One additional parameter - `--s` has been added in order to distinguish restore in same subscription with cross-subscription restore. 

**Testing Guide**

Automation couldn't be established as we need instance in both subscription, but only one of our subscriptions has pre-set infra for fast MI creation. Everything was manually tested and verified in Kusto and backend that correct params were passed.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by milanbrkic-ms** [comment]
Pending on sdk release - https://github.com/Azure/sdk-release-request/issues/3678

**Comment by yonzhan** [comment]
SQL

**Comment by milanbrkic-ms** [comment]
@yonzhan SDK is released, and CLI is now targeting new package. Could you please merge this PR if everything looks okay to you?

**Comment by milanbrkic-ms** [comment]
cc: @evelyn-ys

**Comment by evelyn-ys** [comment]
LGTM but not sure if you need to re-record new tests after #25225 gets merged

**Comment by milanbrkic-ms** [comment]
let's wait for new build results when you merge both and I will re-record if needed. But I doubt as it is not same resource type

**Comment by evelyn-ys** [comment]
There's conflicts after I merge both

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
