### PR TITLE
[App Service] `az webapp config set`: Add MinTlsCipherSuite support

### PR DESCRIPTION
**Pull request by crosenblatt**
**Related command**

**Description**

This PR simply adds support for MinTlsCipherSuite to the az cli for updating the webapp config.

**Testing Guide**

`azdev test test_webapp_config` - This test has been updated to test the code added in this PR.

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by yonzhan** [comment]
Please fix CI issues

**Comment by crosenblatt** [comment]
@yonzhan I fixed the CI issues. Thanks.

**Comment by crosenblatt** [comment]
@yonzhan , Are there any further issues with this PR?

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
