### PR TITLE
[AppService] `az appservice list-locations`: Add `--hyperv-workers-enabled` parameter to get regions which support hosting web apps on windows container workers

### PR DESCRIPTION
**Pull request by mstxsun**
Add hyperv-workers-enabled parameter to get regions which support hosting web apps on windows container workers

**Related command**

az appservice list-locations
**Description**

Add hyperv-workers-enabled parameter to get regions which support hosting web apps on windows container workers
**Testing Guide**

Tested getting regions support hosting web apps on windows container worker by running az appservice list-locations --hyperv-workers-enabled
**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AppService

**Comment by mstxsun** [comment]
> Please add some test cases for this new parameter

Test case for this new parameter is added

**Comment by yonzhan** [comment]
Please fix CI issues.

**Comment by mstxsun** [comment]
> Please fix CI issue

A new fix is merged in dev to fix test_read_images_from_alias_doc test, all CI checks passed after merging with latest dev.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
