### PR TITLE
Update some docs for Virtual Kubelet and AKS

### LINKED ISSUE #9480: Az aks install-connector documentation should be updated
The snippet for `install-connector` still refers to ACI Connector instead of Virtual Kublet.  Should be updated from
```
--connector-name aci-connector
```
to
```
--connector-name virtual-kubelet
```
(see https://docs.microsoft.com/en-us/azure/aks/virtual-kubelet#installation)

There should also be a note stating that the recommended method for acheiving virtual-kubelet functionality in most cases is now [*virtual nodes*](https://docs.microsoft.com/en-us/azure/aks/virtual-nodes-cli#before-you-begin) and can be activated with [`enable-addons`](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-enable-addons)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-install-connector)
* Content Source: [src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes #9480

cc @rbitia

### CODE REVIEW

**Comment by qwordy** [comment]
Looks good to me. But some checks were not successful. It's strange.

**Comment by yonzhan** [comment]
@qwordy  I found CI was not success. I just restarted and please merge it when CI is green.

**Comment by qwordy** [comment]
> 
> 
> @qwordy I found CI was not success. I just restarted and please merge it when CI is green.

OK

**Comment by qwordy** [comment]
Azure.azure-cli (Check Module Load Performance) failed. Rerun, failed again. Can't see detailed error information.

**Pull request merged**
