### PR TITLE
[AppService]: fix #17053- `az webapp show` returning null values for SiteConfig properties

### LINKED ISSUE #17053: WebApp: `az webapp show` returning null values for SiteConfig properties
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

WebApp: `az webapp show` returning null values for SiteConfig properties

**To Reproduce**

`az webapp show --name <name> --resource-group <RGName>`

**Expected behavior**

It should have a site config properties

**Environment summary**

**Additional context**

### PR DESCRIPTION
**Pull request by Kotasudhakarreddy**
…operties

**Description**

#17053 
WebApp: az webapp show returning null values for SiteConfig properties
**Testing Guide**

az webapp show --name <name> --resource-group <RGName>
**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AppService

**Review by yungezz — APPROVED** [review]

**Comment by qwordy** [comment]
@Kotasudhakarreddy Is SiteConfig in service response? Is it extra information you want to display to users?

**Review by qwordy — APPROVED** [review]

**Comment by panchagnula** [comment]
Nice 👍 Will review mostly tomorrow :) PST time. Thanks @Kotasudhakarreddy  for prioritizing this fix. @calvinsID  can you review please?

**Comment by Kotasudhakarreddy** [comment]
> @Kotasudhakarreddy Is SiteConfig in service response? Is it extra information you want to display to users?
> Some checks were not successful

@qwordy - it is a fix to the null response we receive currently.

**Comment by Kotasudhakarreddy** [comment]
@qwordy - it is failing with `ValueError: API version 2021-01-01 does not have operation group 'storage_accounts'` error for below tests. None of them are related to the current PR changes.
1.test_linux_webapp_ssh
2.test_functionapp_consumption_e2e
3.test_functionapp_consumption_ragrs_storage_e2e
4.test_functionapp_local_context

please suggest

**Review by calvinsID — APPROVED** [review]
looks good!

**Comment by calvinsID** [comment]
@Kotasudhakarreddy can you also try re-running the `az functionapp show` tests with `--live`, since it uses the same function as `az webapp show`

**Comment by qwordy** [comment]
> 
> 
> @qwordy - it is failing with `ValueError: API version 2021-01-01 does not have operation group 'storage_accounts'` error for below tests. None of them are related to the current PR changes.
> 1.test_linux_webapp_ssh
> 2.test_functionapp_consumption_e2e
> 3.test_functionapp_consumption_ragrs_storage_e2e
> 4.test_functionapp_local_context
> 
> please suggest

@Kotasudhakarreddy Storage API version was upgraded recently. Please pull latest code from `dev` branch. Install python package dependencies. Rerun failed test cases with `--live`.

**Comment by Kotasudhakarreddy** [comment]
> > @qwordy - it is failing with `ValueError: API version 2021-01-01 does not have operation group 'storage_accounts'` error for below tests. None of them are related to the current PR changes.
> > 1.test_linux_webapp_ssh
> > 2.test_functionapp_consumption_e2e
> > 3.test_functionapp_consumption_ragrs_storage_e2e
> > 4.test_functionapp_local_context
> > please suggest
> 
> @Kotasudhakarreddy Storage API version was upgraded recently. Please pull latest code from `dev` branch. Install python package dependencies. Rerun failed test cases with `--live`.

@qwordy I have taken the latest but still the tests are failing.

**Comment by calvinsID** [comment]
Hey @Kotasudhakarreddy, can you try running `azdev setup -c` then re-run the failing tests with `--live`

**Comment by qwordy** [comment]
```
FAILED src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py::LinuxWebappSSHScenarioTest::test_linux_webapp_ssh
FAILED src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py::FunctionAppWithConsumptionPlanE2ETest::test_functionapp_consumption_e2e
FAILED src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py::FunctionAppWithConsumptionPlanE2ETest::test_functionapp_consumption_ragrs_storage_e2e
FAILED src/azure-cli/azure/cli/command_modules/appservice/tests/latest/test_webapp_commands.py::FunctionappLocalContextScenarioTest::test_functionapp_local_context
```

**Pull request merged**
