### PR TITLE
updating BYOS commands to mark them as preview

### PR DESCRIPTION
**Pull request by btardif**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by panchagnula** [comment]
@yonzhan this change is to basically reflect that this command/feature is in Preview. We noticed that adding the _is_preview attribute to the command doesn't update the documentation (help) to reflect the same -> is this something that can be done automatically without needing an update to _help.py?

**Comment by qwordy** [comment]
When you type -h to show help, make sure you can see a notification saying that it's in preview. I think it's enough.

**Comment by btardif** [comment]
@qwordy will the auto-gen doc page also get updated with preview information?

Specifically --> https://docs.microsoft.com/en-us/cli/azure/webapp/config/storage-account?view=azure-cli-latest

I didn't see this happening for other commands marked as preview.

**Comment by qwordy** [comment]
Oh. I understand the problem now.
Doc page won't be updated automatically.
@Juliehzl Do you know how to mark a command as preview in _help.py?

**Comment by btardif** [comment]
ping on this @Juliehzl any guidance on how to decorate docs for preview commands?

**Comment by Juliehzl** [comment]
we don't have the capability to mark preview in official document now. we only can show up preview information in command line interface.

**Comment by btardif** [comment]
@Juliehzl give this is causing customer confusion, can we have a tracking item to address this?

**Comment by btardif** [comment]
@Juliehzl filed #11923 to track and assigned to you. please triage.

**Pull request merged**
