### PR TITLE
Added tests for acr command module

### PR DESCRIPTION
**Pull request by djyou**
To address issue https://github.com/Azure/azure-cli/issues/1201

### CODE REVIEW

**Comment by djyou** [comment]
@tjprescott Can we merge and close this issue https://github.com/Azure/azure-cli/issues/1201?

**Comment by tjprescott** [comment]
@djyou we just merged a major PR. Would you please rebase your PR and after the CI runs I'll gladly merge it. It looks like it should rebase fine.

**Comment by djyou** [comment]
@tjprescott Done, thanks for the heads up.

**Pull request merged**
