### PR TITLE
[AKS] `az aks create`: Fix issue that `--attach-acr` parameter can't work

### PR DESCRIPTION
**Pull request by FumingZhang**
**Description**

Fix the issue that `--attach-acr` option would raise an error "No service principal provided to create the acrpull role assignment for acr." in `az aks create` when using managed identity or user assigned identity.

The code bug was introduced in [PR #19429](https://github.com/Azure/azure-cli/pull/19429) and [PR #19509](https://github.com/Azure/azure-cli/pull/19509). In the process of refactoring the implementation of `aks create`, we added an additional check when processing the option `--attach-acr` to verify whether service principal exists when managed identity is not enabled. However, when managed identity is enabled, we still check for the existence of service principal by mistake, which resulted in this error.

May refer the hotfix [PR #20405](https://github.com/Azure/azure-cli/pull/20405).

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by zhoxing-ms** [comment]
Could you add some tests for this case?

**Comment by FumingZhang** [comment]
> Could you add some tests for this case?

Good point, added a unit test case to cover this in [commit #6167b26](https://github.com/Azure/azure-cli/pull/20406/commits/6167b261edfb3ba5a6b7e18c9c5cabe4eed21014).

**Review by zhoxing-ms — APPROVED** [review]

**Review by wangzelin007 — APPROVED** [review]

**Comment by FumingZhang** [comment]
I suppose the error in CI is not relevant to the changes in this PR.

> 2021-11-18T08:05:14.5984185Z ERROR: cli.azure.cli.command_modules.profile.custom: Error occurred loading commands!
> ......
> 2021-11-18T08:05:14.6100925Z   File "/opt/az/azcliextensions/arcdata/azext_arcdata/sqlmi/custom.py", line 15, in <module>
> 2021-11-18T08:05:14.6101385Z     import azext_arcdata.core.kubernetes as kubernetes_util
> 2021-11-18T08:05:14.6101836Z   File "/opt/az/azcliextensions/arcdata/azext_arcdata/core/kubernetes.py", line 15, in <module>
> 2021-11-18T08:05:14.6102296Z     from kubernetes.client.exceptions import ApiException
> 2021-11-18T08:05:14.6103234Z ModuleNotFoundError: No module named 'kubernetes.client.exceptions'

**Review by andyliuliming — APPROVED** [review]

**Comment by guiliguili** [comment]
Hi,
I am affected by this bug. Do you know when this fix will be available ?

**Comment by FumingZhang** [comment]
> Hi, I am affected by this bug :
> 
> * Do you know when this fix will be available ?
> * Is there a workaround meanwhile ?
> 
> Thanks for you support.

- The [next official release](https://github.com/Azure/azure-cli/milestone/112) would include this fix, it should be delivered at 12/07.
- As for workaround, please consider the following two suggestions
  1. Use an older version of azure-cli (<= 2.29.2).
  1. Attach acr after the cluster has been created with command `aks update`. An example would be `az aks update -g {resource_group_name} -n {cluster_name} --attach-acr {acr_name_or_id}`

**Pull request merged**
