### PR TITLE
[Extension] az extension add: Add --upgrade option to update the extension if already installed

### LINKED ISSUE #13930: Make it easier to add and update extensions
**Is your feature request related to a problem? Please describe.**

Our team has a number of automation scripts, which as part of the bootstrapping install necessary az CLI extensions. Unfortunately, over time extensions go stale and it's problematic to get them add or update, depending on the current state of extension.

Example: I have extension front-door installed and blueprint not installed.

Attempt to add an existing extension: warning is printed, no attempt to update.

```
$ az extension add --name front-door
Extension 'front-door' is already installed.
```

Attempt to update an extension w/o new updates: fails with error (why ?!?!).

```
$ az extension update --name front-door
No updates available for 'front-door'. Use --debug for more information.
```

Attempt to update extension that's not installed locally: fails with error.

```
$ az extension update --name blueprint
The extension blueprint is not installed.
```

**Describe the solution you'd like**

I'd like to be able to add-or-update, or update-or-add, or update-all.

Add-or-update: `az extension add --name front-door --update` - will add, if extension is missing, update to latest version otherwise.

Update-or-add: `az extension update --name front-door --add` - will update, if extension is present, add latest version otherwise.

Update-all: `az extension --update-all` - will update all extensions to their latest versions.

**Alternative**

At least make `az extension update` not fail, if there're no updates: it's hard to tell "update failed because problems" from "update failed because no updates" apart.

### PR DESCRIPTION
**Pull request by fengzhou-msft**
**Description**  

Resolve #13930

This PR makes it possible to use `az extension add --upgrade` to install or update an extension. The behavior of `az extension add`(without `--upgrade`) will not change.

**When the extension is not installed**:(the behavior is the same as not providing `--upgrade` option)
`az extension add --upgrade -n anext` will install the latest version of `anext`.
`az extension add --upgrade -n anext --version aversion` will install the specific version of `anext`.

**If the extension is already installed**:
`az extension add --upgrade -n anext` will try to update the extension to the latest version if available.
`az extension add --upgrade -n anext --version aversion` will override the existing version if the specified version is different from it. Otherwise, it prints a warning message: `Extension 'anext' x.x.x is already installed`.

**Testing Guide**  

**History Notes**  

[Extension] `az extension add`: Add `--upgrade` option to update the extension if already installed

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
@haroldrandom to help review this PR.

**Review by arrownj — COMMENTED** [review]
Why not use `az extension upgrade` ? It confuses me that `add` command has a `upgrade` parameter.

**Review by haroldrandom — APPROVED** [review]
LGTM. Nice done.

**Comment by fengzhou-msft** [comment]
> Why not use `az extension upgrade` ? It confuses me that `add` command has a `upgrade` parameter.

Similar to `pip install --upgrade`, conveying the meaning that this command will add the extension if not installed, if installed then upgrade it while `az extension upgrade` is hard to distinguish with `az extension update`.

**Review by arrownj — APPROVED** [review]

**Pull request merged**
