### PR TITLE
Added sql db op list/cancel

### PR DESCRIPTION
**Pull request by jaredmoo**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [x] Each command and parameter has a meaningful description.
- [x] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

```
(env) C:\git\azure-cli [cancelop ≡]> az sql db op -h

Group
    az sql db op: Manage operations on a database.

Commands:
    cancel: Cancels the asynchronous operation on the database.
    list  : Gets a list of operations performed on the database.

(env) C:\git\azure-cli [cancelop ≡]> az sql db op cancel -h

Command
    az sql db op cancel: Cancels the asynchronous operation on the database.

Arguments
    --database -d       [Required]: Name of the database.
    --name -n           [Required]: The operation id.
    --resource-group -g [Required]: Name of resource group. You can configure the default group
                                    using `az configure --defaults group=<name>`.
    --server -s         [Required]: Name of the Azure SQL server.

Global Arguments
    --debug                       : Increase logging verbosity to show all debug logs.
    --help -h                     : Show this help message and exit.
    --output -o                   : Output format.  Allowed values: json, jsonc, table, tsv.
                                    Default: json.
    --query                       : JMESPath query string. See http://jmespath.org/ for more
                                    information and examples.
    --verbose                     : Increase logging verbosity. Use --debug for full debug logs.
(env) C:\git\azure-cli [cancelop ≡]> az sql db op list -h

Command
    az sql db op list: Gets a list of operations performed on the database.

Arguments
    --database -d       [Required]: Name of the database.
    --resource-group -g [Required]: Name of resource group. You can configure the default group
                                    using `az configure --defaults group=<name>`.
    --server -s         [Required]: Name of the Azure SQL server.

Global Arguments
    --debug                       : Increase logging verbosity to show all debug logs.
    --help -h                     : Show this help message and exit.
    --output -o                   : Output format.  Allowed values: json, jsonc, table, tsv.
                                    Default: json.
    --query                       : JMESPath query string. See http://jmespath.org/ for more
                                    information and examples.
    --verbose                     : Increase logging verbosity. Use --debug for full debug logs.
```

### CODE REVIEW

**Comment by jaredmoo** [comment]
The checkin will fail for the moment because the updated python sdk is not yet published - that will be done in the next day or two. Sending now for initial feedback.

**Comment by jaredmoo** [comment]
Using published SDK, and this is my team's feature so no other SQL signoff required - good to merge from SQL team's point of view.

**Comment by tjprescott** [comment]
Can an operation ID be referenced via an ARM resource ID?  If so it seems that the `cancel` operation should support `--ids`.

**Comment by troydai** [comment]
@jaredmoo can you address @tjprescott 's concern? Other then that the code change looks good.

**Comment by jaredmoo** [comment]
Here's an example operation resource that we can refer to:

```
{
   "properties":{
      "databaseName":"cliautomationdb01",
      "operation":"UpdateLogicalDatabase",
      "operationFriendlyName":"ALTER DATABASE",
      "percentComplete":0,
      "serverName":"clitestserver000002",
      "startTime":"2017-10-03T23:25:09.073Z",
      "state":"InProgress"
   },
   "id":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.Sql/servers/clitestserver000002/databases/cliautomationdb01/operations/d2896db1-2ba8-4c84-bac1-387c430cce40",
   "name":"d2896db1-2ba8-4c84-bac1-387c430cce40",
   "type":"Microsoft.Sql/servers/databases/operations"
}
```

As per standard, the `-n` param is the resource's `name`, which in this case is `d2896db1-2ba8-4c84-bac1-387c430cce40`. For the help text I wrote `operation ID` in order to try to disambiguate between `name`, `operationName`, and `operationFriendlyName` since `name` is the only one of those which is a GUID. It is not the full ARM ID. Do you have any suggestions on how to make this help text clearer?

**Pull request merged**
