### PR TITLE
{Security} `az security automation create/update`: Fix bug when using LogicApp action

### PR DESCRIPTION
**Pull request by surashed**
**Related command**

`az security automation create_or_update`

**Description**

Fixing a bug in `az security automation create_or_update` command, specifically when running it with action of type LogicApp.
The bug prevents the command from completing successfully due to an issue that addressed in this PR

**History Notes**

{Security} `az security automation create_or_update` bug fix when using LogicApp action

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by kairu-ms — APPROVED** [review]

**Comment by kairu-ms** [comment]
The code looks good to me. Please fix the PR header and history notes.

**Comment by jsntcy** [comment]
@surashed, please add more description about why we need this change to help the reviewer understand the context.

**Pull request merged**
