### PR TITLE
Cloud console links are hardened, remove the warning, default to true.

### PR DESCRIPTION
**Pull request by brendandburns**
@mboersma @yugangw-msft

### CODE REVIEW

**Comment by yugangw-msft** [comment]
Please do 2 things for me to get this merged
1. Fix the lint error. Importing `prompt_y_n` is not needed any more, please remove it
2. this flag is no longer under a testing tag, please update [help](https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_help.py#L140)

**Comment by brendandburns** [comment]
Comments addressed, please re-check.

Thanks!

**Comment by yugangw-msft** [comment]
There is a new command linter error you need to fix

**Comment by yugangw-msft** [comment]
@samkreter had this taken care of through his PRs. Closing.

**Pull request closed without merging**
