### PR TITLE
[SQL] az sql db/elastic-pool create/update: Added maint-config-id argument

### PR DESCRIPTION
**Pull request by hotsnr**
**Description**
- Added 'maintenance-configuration' argument for create/update of SQL db/pool resources. Argument can accept ARM resource id as well as short name for public maintenance configurations.

**Testing Guide**
- az sql db create --server testfmw2 --resource-group rokhotrg --name db9cli --service-objective S2 --maint-config-id SQL_EastUS2EUAP_DB_1
- az sql db update --server testfmw2 --resource-group rokhotrg --name db9cli --maint-config-id SQL_EastUS2EUAP_DB_2
- az sql elastic-pool create --server testfmw2 --resource-group rokhotrg --name p8cli --maint-config-id SQL_EastUS2EUAP_DB_1
- az sql elastic-pool update --server testfmw2 --resource-group rokhotrg --name p8cli --maint-config-id SQL_EastUS2EUAP_DB_2

**History Notes**

[SQL] az sql db/elastic-pool create/update: Added maintenance-configuration argument

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
SQL

**Comment by yonzhan** [comment]
@evelyn-ys please help with this PR after holiday.

**Comment by hotsnr** [comment]
@evelyn-ys @yonzhan Lint fails because of unrelated error not yet fixed in master

**Comment by evelyn-ys** [comment]
> @evelyn-ys @yonzhan Lint fails because of unrelated error not yet fixed in master

Can you add `# pylint: disable=no-member` to bypass linter? I know `servicefabric` is not your module but can you do me a favor😀

**Review by evelyn-ys — APPROVED** [review]

**Comment by hotsnr** [comment]
> @evelyn-ys @yonzhan Lint fails because of unrelated error not yet fixed in master

@evelyn-ys Added linter bypass, please restart CI

**Comment by evelyn-ys** [comment]
> @evelyn-ys Added linter bypass, please restart CI

We have fixed this in https://github.com/Azure/azure-cli/pull/16970. Could you merge `dev` branch again? And then I will trigger CI😊

**Pull request merged**
