### PR TITLE
Add support for deleting by ip-address and subnet to support empty name.

### PR DESCRIPTION
**Pull request by madsd**
Fix issue #10965

Add support for deleting by ip-address and subnet to support empty name.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by fengzhou-msft** [comment]
@qwordy please review the changes.

**Comment by madsd** [comment]
@qwordy can you review this, or let me know if I need to do something to push this forward?

**Comment by panchagnula** [comment]
@madsd  now that we have a new version released could you move the history item to the next release. Will make sure to take this with the upcoming release.

**Comment by madsd** [comment]
@panchagnula History entry has been moved to the next version

**Comment by yonzhan** [comment]
@qwordy please help with the PR.

**Pull request merged**
