### PR TITLE
fix: add app insights + log analytics cloud endpoints

### PR DESCRIPTION
**Pull request by alexeldeib**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by haroldrandom** [comment]
Two tiny errors against PEP8 in:
1. src/azure-cli-core/azure/cli/core/cloud.py:87:65: W291 trailing whitespace
2. src/azure-cli-core/azure/cli/core/cloud.py:87:64: C0303: Trailing whitespace (trailing-whitespace)


Please fix that.

**Comment by Juliehzl** [comment]
cc @mdewan do you need to retrieve app insights & log analytics from ARM metadata info [here](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/cloud.py#L159)?

**Comment by MyronFanQiu** [comment]
@mdewan Hello. Could you take a look at this issue?

**Comment by alexeldeib** [comment]
added arm to cli mapper, and that's correct about Black Forest 👍

**Comment by mdewan** [comment]
> added arm to cli mapper, and that's correct about Black Forest 👍

Looks good, pending CI/CD

**Comment by MyronFanQiu** [comment]
@alexeldeib Hello. Could you help fix the style error? The length of one line extend 120. Besides, did you test this command locally for Azure China or any Azure Stack Cloud?

**Comment by MyronFanQiu** [comment]
@alexeldeib Thanks for contributions!

**Pull request merged**
