### PR TITLE
Use 'az monitor autoscale list' instead

### PR DESCRIPTION
**Pull request by DaveVoyles**
```
DaveVoyles@Dave-MacBook-Pro  ~  az monitor autoscale-settings list
This command is deprecating and will be removed in future releases. Use 'az monitor autoscale list' instead.
```

Removed ```settings```

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by troydai** [comment]
@DaveVoyles  we don't see the necessity of this change. There are help docs for the `az monitor autoscale` commands as just above you changes: https://github.com/DaveVoyles/azure-cli/blob/cd90cf33d6cb9f47733aeb5a8b21e6b8572986c2/src/command_modules/azure-cli-monitor/azure/cli/command_modules/monitor/_help.py#L273.

I will close this PR. Please feel free to share your concerns if we missed your point.

**Comment by DaveVoyles** [comment]
I'm confused. Is this command being deprecated or removed?  I changed the command to the one the warning suggested.

**Comment by tjprescott** [comment]
There are two commands in the CLI:
`az monitor autoscale list` - the new version
`az monitor autoscale-settings list` - the deprecated version which will be removed.

There is already help for both of these.  You were changing the `autoscale list` help to use the `autoscale-settings list` help, which is not a change we want to make.  The warning is to tell *you* to use `autoscale list` instead of `autoscale-settings list` because the deprecated command will be removed in the future (the near future in this case).

**Comment by DaveVoyles** [comment]
Ah OK, now I understand. Thank you for clarifying!

**Pull request closed without merging**
