### PR TITLE
[Network] `az network virtual-appliance inbound-security-rule`: Support of GET operation for NVA Inbound Security Rule

### PR DESCRIPTION
**Pull request by ashutmi**
**Related command**

network virtual-appliance inbound-security-rule show

**Description**

Added Support of GET Operation for Network Virtual Appliance Inbound Security Rule

**Testing Case**

GET an existing Inbound Security Rule Command:

`az network virtual-appliance inbound-security-rule show --nva-name "storageTest3" -g "AshuSneaky" --subscription 62364504-2406-418e-971c-05822ff72fad --name "RulePermant"`

Expected Output:
`{
  "etag": "92c48608-9147-4658-a93d-61b9b71fb6ae",
  "id": "/subscriptions/62364504-2406-418e-971c-05822ff72fad/resourceGroups/AshuSneaky/providers/Microsoft.Network/networkVirtualAppliances/storageTest3/inboundSecurityRules/RulePermant",
  "name": "RulePermant",
  "provisioningState": "Failed",
  "resourceGroup": "AshuSneaky",
  "ruleType": "Permanent",
  "rules": [
    {
      "appliesOn": [
        "slbip"
      ],
      "destinationPortRanges": [
        "81-91"
      ],
      "name": "inbound",
      "protocol": "TCP",
      "sourceAddressPrefix": "0.0.0.0/0"
    }
  ],
  "type": "Microsoft.Network/NetworkVirtualAppliances/InboundSecurityRules"
}`

image

Help Command:

`az network virtual-appliance inbound-security-rule show --help`

Output:

image

Associated documentation (AAZ) PR: https://github.com/Azure/aaz/pull/505

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Network

**Review by necusjz — APPROVED** [review]

**Pull request merged**
