### PR TITLE
[Network] Fix #21845: `az network routeserver create` required `--public-ip-address` argument

### LINKED ISSUE #21845: Review required parameters for ARS CLI
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
The CLI documentation for Azure Route Server lists location and public IP as optional, whereas public documentation and the portal UI indicate both are required. We have seen one customer case where this guide was cited as being incorrect. 

**CLI Guide in Question**
https://docs.microsoft.com/en-us/cli/azure/network/routeserver?view=azure-cli-latest#az-network-routeserver-create

**Supporting FAQ**
https://docs.microsoft.com/en-us/azure/route-server/route-server-faq#why-does-azure-route-server-require-a-public-ip-address

*To Reproduce**
Attempt to deploy a new ARS via CLI and leave out Public IP and you will get an error. 

**Additional context**
I would suggest validating the parameters to ensure that all required parameters are listed as such on the CLI deployment guide. For certain, publicIP, but also suggest validating Location.

### PR DESCRIPTION
**Pull request by YuanyuanNi**
Closes: https://github.com/Azure/azure-cli/issues/21845

**Description**

fix public IP address validate issue:
The CLI documentation for Azure Route Server lists location and public IP as optional, whereas public documentation and the portal UI indicate both are required. We have seen one customer case where this guide was cited as being incorrect.

**Testing Guide**

To Reproduce*
Attempt to deploy a new ARS via CLI and leave out Public IP and you will get an error:
az network routeserver create --resource-group xxx --name xxx --hosted-subnet xxxx
**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by YuanyuanNi** [comment]
#21845

**Comment by yonzhan** [comment]
network

**Comment by jiasli** [comment]
Please add detailed PR description about the "issue".

**Comment by necusjz** [comment]
@YuanyuanNi,
https://github.com/Azure/azure-cli/blob/3c6fe4a8ed264aa6ccf8e7b162db3ba6d826b095/src/azure-cli/azure/cli/command_modules/network/custom.py#L7602

Since `--public-ip-address` is mandatory, we don't need such judgement anymore.

**Review by necusjz — APPROVED** [review]

**Pull request merged**
