### PR TITLE
WIP [AKS] az aks create: add enable-encryption-at-host parameter

### PR DESCRIPTION
**Pull request by andyzhangx**
**Description**

This PR:
 - upgrade aks component to api-version 2020-12-01
 - add enable-encryption-at-host in `az aks create` and `az aks nodepool add`

**Testing Guide**

```console
az aks create -g $RESOURCE_GROUP_NAME -n $CLUSTER_NAME --node-count 1 --node-vm-size Standard_DS2_v2 --generate-ssh-keys --kubernetes-version 1.20.2 --enable-encryption-at-host
az aks nodepool add --name nodepool2 --cluster-name $CLUSTER_NAME --resource-group $RESOURCE_GROUP_NAME --enable-encryption-at-host
```

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by andyzhangx** [comment]
@fengzhou-msft @yungezz do you know how to trigger the CI tests? thanks.

**Comment by andyzhangx** [comment]
@kairu-ms could you help run test again? thanks.

**Comment by andyzhangx** [comment]
would you trigger test again? thanks.

**Comment by andyzhangx** [comment]
would you trigger test again? thanks.

**Comment by andyzhangx** [comment]
@kairu-ms

**Comment by yungezz** [comment]
hi @andyzhangx we'll enable permsision to trigger CI pipeline for you soon. Recently Azure CLI got attacked via CI so we temporarily disabled it before solution ready. Pls ping me or @fengzhou-msft for CI need for now. Sorry for inconvinience. :)

**Comment by fengzhou-msft** [comment]
@andyzhangx can you resolve the conflicts and take a look at the CI failures?

**Review by kairu-ms — APPROVED** [review]

**Comment by yungezz** [comment]
hi @andyzhangx could you pls rebase the PR?

**Comment by andyzhangx** [comment]
close this PR since EncryptionAtHost feature GA on AKS is postponed

**Pull request closed without merging**
