### PR TITLE
[Network] `az network nat gateway`: Validate attaching public IPs

### PR DESCRIPTION
**Pull request by necusjz**
Closes https://github.com/Azure/azure-cli/issues/21069

**Description**

Issue:
Customers can create a NAT gateway without adding a public IP address. No error messages are generated when creating a NAT gateway without a public IP address or prefix attached.

Requirements for resolving this issue:
Require that customers must do one of the following when creating a new NAT gateway resource:
Create one new public IP address -or-
Create one new public IP prefix -or-
Attach at least one existing and available public IP address in the network to NAT gateway -or-
Attach at least one existing and available public IP prefix in the virtual network to NAT gateway

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change.
[Component Name 2] `az command b`: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Network

**Review by kairu-ms — APPROVED** [review]

**Comment by aimee-littleton** [comment]
@necusjz, I see that this item has been merged and closed. I just did some testing in cloudshell in order to confirm that you now must associate a public IP address to NAT gateway when NAT gateway is created and I didn't see any kind of error message generated. It looks like I was able to create the NAT gateway without any issue. Can you provide some clarity on what was done here?

**Comment by necusjz** [comment]
@aimee-littleton, it hasn't been released yet. After next coming release (04/06), it will be like:
image

**Comment by aimee-littleton** [comment]
@necusjz , got it. Thank you for letting me know estimated release date, very much appreciated!

**Comment by aimee-littleton** [comment]
@necusjz , will implementation of this validation error prevent customers from deploying a NAT gateway until a public IP is attached?

**Comment by aimee-littleton** [comment]
@necusjz , apologies for having to do this, but can we withdraw this PR? Been having more discussions with my team this week and we are now rethinking on whether or not we should have a validation or warning message.

**Comment by necusjz** [comment]
@aimee-littleton, of course, we can.

**Comment by aimee-littleton** [comment]
thank you, @necusjz !

**Pull request merged**
