### PR TITLE
[RDBMS] Fix #20124: `az mysql/postgres flexible-server db create`: Make resource group and server name required

### LINKED ISSUE #20124: Azure cli sent me here
## Describe the bug

**Command Name**
`az mysql flexible-server db create`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
No value for given attribute
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/rdbms/flexible_server_custom_mysql.py", line 622, in database_create_func
    parameters)
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/rdbms/mysql_flexibleservers/operations/_databases_operations.py", line 154, in begin_create_or_update
    **kwargs
  File "/opt/az/lib/python3.6/site-packages/azure/mgmt/rdbms/mysql_flexibleservers/operations/_databases_operations.py", line 72, in _create_or_update_initial
    'resourceGroupName': self._serialize.url("resource_group_name", resource_group_name, 'str', max_length=90, min_length=1),
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 650, in url
    output = self.serialize_data(data, data_type, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/msrest/serialization.py", line 758, in serialize_data
    raise ValueError("No value for given attribute")
ValueError: No value for given attribute

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az mysql flexible-server db create -d {}`

## Environment Summary
```
Linux-5.4.0-1062-azure-x86_64-with-debian-10.2 (Cloud Shell), Common Base Linux Delridge (quinault)
Python 3.6.10
Installer: DEB

azure-cli 2.29.0 *

Extensions:
ai-examples 0.2.5
ssh 0.1.6

```

### PR DESCRIPTION
**Pull request by DaeunYim**
**Description**

We are not accepting 'db create' command without resource group and server name
 Fix #20124 

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
RDBMS

**Review by calvinhzy — APPROVED** [review]

**Comment by DaeunYim** [comment]
@calvinhzy hello, I closed and re-opened this PR. 
I'm seeing Python39 test and linter failure with this same error
image

Not sure if this pipeline issue or caused by my change.. Could you help looking at it? Thank you!

**Comment by calvinhzy** [comment]
> @calvinhzy hello, I closed and re-opened this PR. I'm seeing Python39 test and linter failure with this same error image
> 
> Not sure if this pipeline issue or caused by my change.. Could you help looking at it? Thank you!

We tried running the CI a few more times and it passed. Since it is not reproducible consistently, we are still tracking down the root cause.

**Comment by DaeunYim** [comment]
> us

Thanks a lot for checking and modifying the title of it. Will try to follow this formatting from next time

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
