### PR TITLE
[Backup] `az backup policy create/set`: Add support for creating/updating IaaSVM MBPD policy

### PR DESCRIPTION
**Pull request by akshayneema**
**Description**
`az backup policy create/set`: Added support for creating/updating IaaSVM MBPD policy

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Backup

**Comment by zhoxing-ms** [comment]
Could you add some tests for the new change?

**Comment by akshayneema** [comment]
> Could you add some tests for the new change?

It is not a new feature. We added it some while back in this PR https://github.com/Azure/azure-cli/pull/21643 with relevant tests. We are just removing a client-side check in this PR. It will now be handled on the service side.

**Comment by zhoxing-ms** [comment]
Yes, I personally think we need to test this new scenario that the server can support `schedule_run_frequency == ScheduleRunType.hourly`

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
