### PR TITLE
[AKS] Remove explicit setting of VMSS in Windows example command since it is now default

### LINKED ISSUE #14283: Please update --vm-set-type VirtualMachineScaleSet to plural form "VirtualMachineScaleSets" in document
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d75c3a8d-1187-bea1-a7d4-7ebba71c1790
* Version Independent ID: 75b0c352-762e-16ae-5cc6-d807ffc1dc3f
* Content: [az aks](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest)
* Content Source: [src/azure-cli/azure/cli/command_modules/acs/_help.py](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acs/_help.py)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

### PR DESCRIPTION
**Pull request by seanmck**
**Description**  
Now that VMSS is the default vm-set-type, we do not need to explicitly set it. Fixes #14283 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by yungezz** [comment]
hi @seanmck this looks like a breaking change: remove an params from command. Did you mention this change  in doc?

**Comment by seanmck** [comment]
@yungezz The parameter is optional because there is a default. When this help text was originally introduced, the default was AvailabilitySets, so we called out that you needed to explicitly set it to VirtualMachineScaleSets, since that is required for Windows clusters. Since then, the default has changed to VMSS, so whether you explicitly specify it or not, you get the same behavior. This simply shortens the command by taking advantage of the new default.

**Comment by seanmck** [comment]
Yes, #10797 which was merged last October.

**Pull request merged**
