### PR TITLE
[NetAppFiles] BREAKING CHANGE: Add commands for new features and updates for netappfiles 2020-06

### PR DESCRIPTION
**Pull request by hildurhodd**
**Description**  

This PR is for new commands for new features in NetAppFiles version 2020-06 along with some updates.
The following was changed or added:
- Added optional boolean parameter named --force-break-replication to 'az netappfiles volume replication suspend' to be able to force break a volume replication.
- Added new command 'az netappfiles volume replication re-initialize' that is used to re initialise a volume replication.
- Added new command 'az netappfiles volume pool-change' with a new parameter named new_pool_resource_id to indicate which pool to change the volume to.
- Added new command group 'az netappfiles snapshot policy' with following commands: 
  - show, list, volumes, delete, update and create.
- Added new command group 'az netappfiles account backup' with following commands:
  - show, list and delete
- Added new command group 'az netappfiles volume backup' with the following commands:
  - show, list, delete, update and create
- Added new command group 'az netappfiles account backup-policy' with following commands:
  - show, list, delete, update and create
- Added new command group 'az netappfiles vault' with command 'list'
- Added optional parameters to 'az netappfiles account ad add'
  - kdc-ip, ad-name, server-root-ca-certificate and backup-operators
- BREAKING CHANGE: Removed service-level parameter from command 'az netappfiles pool update'
- Added optional parameter 'qos-type' to 'az netappfiles pool update' and 'az netappfiles pool create'
- Added optional parameters to 'az netappfiles volume create'
  - snapshot-policy-id, backup-policy-id, backup-enabled, backup-id, policy-enforced, vault-id, kerberos-enabled, throughput-mibps, snapshot-directory-visible, security-style, kerberos5-read-only, kerberos5-read-write, kerberos5i-read-only, kerberos5i-read-write, kerberos5p-read-only, kerberos5p-read-write and has-root-access
- Added optional parameters to 'az netappfiles volume update'
  - vault-id, backup-enabled, backup-policy-id, policy-enforced and throughput-mibps

**Testing Guide**  

**History Notes**  

[NetAppFiles] BREAKING CHANGE: az netappfiles pool update: Removed service-level from parameters.  
[NetAppFiles] az netappfiles pool update: Added optional parameter qos-type.
[NetAppFiles] az netappfiles pool create: Added optional parameter qos-type.
[NetAppFiles] az netappfiles volume replication suspend: Added force-break-replication as optional parameter.
[NetAppFiles] Add az netappfiles volume replication re-initialize: New command added to re-initialise replication.
[NetAppFiles] Add az netappfiles volume pool-change: New command to change the pool of a volume.
[NetAppFiles] Add az netappfiles snapshot policy: New command group with list, delete, update, show, create and volumes commands.
[NetAppFiles] Add az netappfiles account backup: New command group with show, list and delete commands
[NetAppFiles] Add az netappfiles volume backups: New command group with show, list, delete, update and create commands.
[NetAppFiles] Add az netappfiles account backup-policy: New command group with show, list, delete, update and delete commands.
[NetAppFiles] Add az netappfiles vault list: New command added. 
[NetAppFiles] az netappfiles account ad add: Added optional parameters kdc-ip, ad-name, server-root-ca-certificate and backup-operators
[NetAppFiles] az netappfiles volumes create: Added optional parameters snapshot-policy-id, backup-policy-id, backup-enabled, backup-id, policy-enforced, vault-id, kerberos-enabled, throughput-mibps, snapshot-directory-visible, security-style, kerberos5-read-only, kerberos5-read-write, kerberos5i-read-only, kerberos5i-read-write, kerberos5p-read-only, kerberos5p-read-write and has-root-access.
[NetAppFiles] az netappfiles volume update: Added optional parameters vault-id, backup-enabled, backup-policy-id, policy-enforced and throughput-mibps

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
NetAppFiles

**Comment by hildurhodd** [comment]
@jsntcy @kairu-ms Is it possible to get this PR going?

**Comment by audunn** [comment]
@haroldrandom  @jsntcy @kairu-ms Can we please get this reviewed

**Comment by yonzhan** [comment]
@haroldrandom @kairu-ms @jsntcy please help with this PR.

**Review by haroldrandom — CHANGES_REQUESTED** [review]
Could you rebase against the latest dev to bring in the fix https://github.com/Azure/azure-cli/pull/15804 to CI?

**Comment by hildurhodd** [comment]
@haroldrandom rebase complete

**Review by haroldrandom — APPROVED** [review]

**Pull request merged**
