### PR TITLE
[AKS] `az aks create` `az aks nodepool add/update`: Add Trusted Launch options `--enable-vtpm` and `--enable-secure-boot`

### PR DESCRIPTION
**Pull request by lilypan26**
**Related command**

- az aks create
- az aks nodepool add
- az aks nodepool update

**Description**

Add trusted launch options `--enable-vtpm`, `--disable-vtpm`, `--enable-secure-boot`, `--disable-secure-boot` to support enabling disabling vTPM and secure boot on AKS nodepools.

**Testing Guide**

**History Notes**

[AKS] `az aks create`: Add Trusted Launch options `--enable-vtpm` and `--enable-secure-boot`
[AKS] `az aks nodepool add/update`: Add Trusted Launch options `--enable-vtpm` and `--enable-secure-boot`

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Review by FumingZhang — COMMENTED** [review]
lgtm, please fix failed CI checks

Queued [live test](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=97031408&view=results) to validate the change
- test_aks_create_update_secure_boot_flow
- test_aks_create_update_vtpm_flow

**Comment by FumingZhang** [comment]
> lgtm, GA previous change in aks-preview [#7243](https://github.com/Azure/azure-cli-extensions/pull/7243), please fix failed CI checks
> 
> Queued [live test](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=97031408&view=results) to validate the change
> 
> * test_aks_create_update_secure_boot_flow
> * test_aks_create_update_vtpm_flow

Requeued [live test](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=97179745&view=results)

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@lilypan26 @FumingZhang  Could you please resolve these CI issues?

**Comment by FumingZhang** [comment]
feature not ready, expected to be postponed to September

**Comment by zhoxing-ms** [comment]
@lilypan26 Could you resolve these CI issues and conflicts?

**Comment by zhoxing-ms** [comment]
Please note that we are launching the release for this sprint this week. Please resolve all comments by tomorrow, otherwise the release of this PR will have to be postponed to the next sprint **(on 10-08)**

**Comment by FumingZhang** [comment]
[Live test](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=103481867&view=logs&j=b162b355-d59d-5864-ce0f-0a70f12dd28b&t=dc59ccd1-231f-538b-777f-33a592c7ca57) failed with the following error
```
E                   azure.cli.core.azclierror.BadRequestError: (UnmarshalError) Invalid request body. Converting request body to a managed cluster encountered error: json: unknown field "securityProfile" Check that the field is in the right location, is spelled correctly, and is supported in the API version. Visit aka.ms/aks/apiversions for more API version information..
E                   Code: UnmarshalError
E                   Message: Invalid request body. Converting request body to a managed cluster encountered error: json: unknown field "securityProfile" Check that the field is in the right location, is spelled correctly, and is supported in the API version. Visit aka.ms/aks/apiversions for more API version information..
```

**Comment by zhoxing-ms** [comment]
@lilypan26 Could you please address these CI issues and comments? Please note that we are launching the release for this sprint this week. Please resolve all comments and CI issues by tomorrow, otherwise the release of this PR will have to be postponed to the next sprint **(on 11-05)**

**Comment by lilypan26** [comment]
successful live test run: https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=105831660&view=results

**Comment by yonzhan** [comment]
Please fix CI issues

**Review by FumingZhang — APPROVED** [review]
LGTM

[live test](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=105911697&view=results) passed!
- test_aks_create_update_secure_boot_flow
- test_aks_create_update_vtpm_flow

**Comment by yanzhudd** [comment]
since there are multiple commands impacted in this PR, it is better to split the title into small ones and list them in the History Notes session, e.g.,

History Notes

[AKS] `az aks create`: Add Trusted Launch options `--enable-vtpm` and `--enable-secure-boot`
[AKS] `az aks nodepool add/update`: Add Trusted Launch options `--enable-vtpm` and `--enable-secure-boot`

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
