### PR TITLE
{AzureSynapse} fixes Azure/azure-cli#23631

### PR DESCRIPTION
**Pull request by SaurabhSharma-MSFT**
**Related command**
{AzureSynapse} fixes Azure/azure-cli#23631

**Description**

--main-class-name seems a mandatory parameter when submitting the spark job. However, it is mentioned in Optional Parameters

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AzureSynapse

**Comment by wonner** [comment]
--main-class-name is not mandatory parameter for pySpark job

**Comment by SaurabhSharma-MSFT** [comment]
> --main-class-name is not mandatory parameter for pySpark job

I tried creating without using this parameter, but it did not work and asked for entering this parameter to create the job.

**Comment by wonner** [comment]
> > --main-class-name is not mandatory parameter for pySpark job
> > @wonner
> > I tried creating without using this parameter, but it did not work and asked for entering this parameter to create the job.

@SaurabhSharma-MSFT 
When the language is python, I suppose you don't need to provide the main class name. Could you please have a try?

**Comment by jsntcy** [comment]
Close this PR as it has created for more than 3 months. If needed, you can reopen it later.

**Pull request closed without merging**
