### PR TITLE
[Hilo] New module onboard

### PR DESCRIPTION
**Pull request by yuc-Li**
**Related command**

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by kairu-ms** [comment]
Hi @yuc-Li, thanks for your contribution. Recommend to release a cli extension which is more flexible to maintain and release.

**Comment by yuc-Li** [comment]
> Hi @yuc-Li, thanks for your contribution. Recommend releasing it as a cli extension which is more flexible to maintain and release.

Hi @kairu-ms  Thank you for your reminder. I will try to convert this into an extension for releasing.

**Comment by kairu-ms** [comment]
https://github.com/Azure/azure-cli-extensions/pull/6926

**Pull request closed without merging**
