### PR TITLE
[Service Connector] `az functionapp connection`: Add new command group to support service connector for function app

### PR DESCRIPTION
**Pull request by houk-ms**
**Related command**

`az functionapp connection`

**Description**

The PR adds a new command group `az functionapp connection` to support service connector for function app.
The experience (commands with their arguments) will be same with `az webapp connection`

**Testing Guide**

All commands work for `az webapp connection` should work in the same way with `az functionapp connection`
https://learn.microsoft.com/en-us/cli/azure/webapp/connection?view=azure-cli-latest

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Service Connector

**Review by yungezz — COMMENTED** [review]
LGTM

**Comment by houk-ms** [comment]
Hold until @xfz11 makes service connector passwordless extension compatable for the PR/

**Review by kairu-ms — APPROVED** [review]

**Comment by houk-ms** [comment]
Depend on https://github.com/Azure/azure-cli-extensions/pull/6356

**Comment by xfz11** [comment]
Depends on https://github.com/Azure/azure-cli-extensions/pull/6376

**Comment by houk-ms** [comment]
Hide the commands from customers in PR https://github.com/Azure/azure-cli/pull/26681 
until partner team sign off

**Pull request merged**
