### PR TITLE
update _help change the parameter name of blob name

### PR DESCRIPTION
**Pull request by moataseem**
update _help change the parameter name of blob name in cli command from --name to --blob-name

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
@Juliehzl please help with this PR.

**Comment by Juliehzl** [comment]
Hi @moataseem, --name is by design for `az storage blob exists`.  For `az storage blob exists` command, the target of this command is just blob and we think it is better to use --name. Do you have any concern for changing it to `--blob-name`?

**Comment by moataseem** [comment]
Hi @Juliehzl actually I've tried to execute the command and I've got the error: unrecognized arguments: --name 
I was able to execute it successfully through changing the parameter --name to --blob-name .
so it's not about naming. It's more about being able to execute the command to get the result if there is a blob under a specific container

**Comment by Juliehzl** [comment]
> Hi @Juliehzl actually I've tried to execute the command and I've got the error: unrecognized arguments: --name
> I was able to execute it successfully through changing the parameter --name to --blob-name .
> so it's not about naming. It's more about being able to execute the command to get the result if there is a blob under a specific container

Can you verify it again? I tried it locally, but --name works well not --blob-name as follows:
```
C:\Users\zuh>az storage blob exists --name a.txt -c test --account-name zuhstoragetest1
{
  "exists": true
}
```

**Comment by moataseem** [comment]
[image: azureBlob.png]
I have tried it by me you may say how it looks like in the image

**Comment by yonzhan** [comment]
@moataseem have you figured out the problem? Do we still need this PR ?

**Comment by moataseem** [comment]
@yonzhan As I've mentioned before. It worked for by changing the parameter
from --name to --blob-name so you can test against that if it works like
this by you too then we need it

yonzhan <notifications@github.com> schrieb am Sa., 2. Nov. 2019, 09:11:

**Comment by yonzhan** [comment]
@Juliehzl  please help verify.

**Comment by Juliehzl** [comment]
Hi @moataseem , it really strange and I think there should be something wrong. I have tried in az interactive and it shows as follows:
image
Could you please create an issue for your problem and share with me your debug information? One more thing to know is which cli version you are using.

**Pull request closed without merging**
