### PR TITLE
{Compute} Fix test package issue for image build 

### PR DESCRIPTION
**Pull request by zhoxing-ms**
**Description**

At present, three tests operate on the same resource `template01` under the same resource group `img_tmpl_customizers`.

```Python
    @ResourceGroupPreparer(name_prefix='img_tmpl_customizers')
    def test_image_builder_customizers(self, resource_group, resource_group_location):
        ......
        self.kwargs.update({
            'tmpl': 'template01',
```

```Python
    @ResourceGroupPreparer(name_prefix='img_tmpl_customizers', location='westus2')
    def test_image_template_outputs(self, resource_group, resource_group_location):
        ......
        self.kwargs.update({
            'tmpl_01': 'template01',
```

```Python
    @ResourceGroupPreparer(name_prefix='img_tmpl_customizers', location='westus2')
    def test_defer_only_commands(self, resource_group, resource_group_location):
        ......
        self.kwargs.update({
            'tmpl': 'template01',
```

When testing the test package in CI, because the tests are executed in parallel, the properties created by these tests will interfere with each other, and the check results do not meet the expectations, such as [pipeline link](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1323470&view=logs&j=1e6fba43-bdcf-51f0-a062-3712c33fbb51&t=a1e787eb-ec67-5c3d-79ec-0c68f4f59d65&s=96ac2280-8cb4-5df5-99de-dd2da759617d)

Therefore, modify the resource groups created by those tests and let them create resources in different resource groups

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Compute

**Comment by PARADISSEEKR** [comment]
There are three `name_prefix='img_tmpl_customizers'` in this file

**Comment by zhoxing-ms** [comment]
> There are three @ResourceGroupPreparer(name_prefix='img_tmpl_customizers') in this file

Yes, we only need to modify two and let all of f them create resources under different resource groups

**Review by PARADISSEEKR — APPROVED** [review]

**Review by wangzelin007 — APPROVED** [review]

**Review by jiasli — APPROVED** [review]

**Pull request merged**
