### PR TITLE
[Docker] alpine container image: Install jp from repos

### PR DESCRIPTION
**Pull request by Finkregh**
jp is available in the normal repositories:

https://pkgs.alpinelinux.org/packages?name=jp&branch=v3.19&repo=&arch=x86_64&maintainer=

**Related command**
When building the alpine container

**Description**
Use distro-provided packages instead of github-releases, should lead to less breakage along the way as they are more likely to work with _that_ distro and _these_ other libraries.

**Testing Guide**
?

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

FIXME please edit this, I'm not sure what to choose for this change.
Perhaps add a link _here_ instead of in the footer to the available components.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Docker

**Comment by Finkregh** [comment]
> ERROR: failed to solve: python:3.11-alpine: failed to resolve source metadata for docker.io/library/python:3.11-alpine: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/library/python/manifests/sha256:4350f4caccd5f014eb107fd0c7348f428d6e9d9fb089797d6264a234592e0981: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

**Comment by yonzhan** [comment]
Please fix CI issues

**Comment by Finkregh** [comment]
> Please fix CI issues

Can you retrigger the CI?

**Comment by Finkregh** [comment]
@bebobenehmen why is that and where can I read more about it?

**Comment by bebound** [comment]
See https://github.com/Azure/azure-cli/pull/29628

**Pull request closed without merging**
