### PR TITLE
Retry webbrowser.open() after a TypeError

### LINKED ISSUE #7033: az login fails with python 3.7
**Describe the bug**
There's a bug in the `webbrowser` module in newer python versions which affects the browser url opening when doing `az login`.

python bug report: https://bugs.python.org/msg322439

**To Reproduce**
```
$ az login
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./virtualenv-az/lib/python3.7/site-packages/azure/cli/core/_profile.py", line 1033, in _get_authorization_code_worker
    succ = open_page_in_browser(url)
  File "./virtualenv-az/lib/python3.7/site-packages/azure/cli/core/util.py", line 266, in open_page_in_browser
    return webbrowser.open(url, new=2) # 2 means: open in a new tab, if possible
  File "/usr/lib64/python3.7/webbrowser.py", line 75, in open
    register_standard_browsers()
  File "/usr/lib64/python3.7/webbrowser.py", line 567, in register_standard_browsers
    cmd = _synthesize(cmdline, -1)
  File "/usr/lib64/python3.7/webbrowser.py", line 116, in _synthesize
    register(browser, None, controller, update_tryorder)
TypeError: register() takes from 2 to 3 positional arguments but 4 were given
```

**Expected behavior**
It should open a browser tab as usual

**Environment summary**
I'm using virtualenv for the install

```
$ python --version
Python 3.7.0
$ az --version
azure-cli (2.0.41)

acr (2.0.28)
acs (2.1.3)
advisor (0.5.1)
ams (0.1.1)
appservice (0.1.36)
backup (1.1.2)
batch (3.2.4)
batchai (0.3.1)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.15)
cognitiveservices (0.1.13)
command-modules-nspkg (2.0.1)
configure (2.0.17)
consumption (0.3.1)
container (0.2.1)
core (2.0.41)
cosmosdb (0.1.21)
dla (0.1.0)
dls (0.0.22)
dms (0.0.1)
eventgrid (0.1.12)
eventhubs (0.1.3)
extension (0.1.0)
feedback (2.1.3)
find (0.2.11)
interactive (0.3.25)
iot (0.1.21)
keyvault (2.0.23)
lab (0.0.22)
monitor (0.1.8)
network (2.1.5)
nspkg (3.0.2)
profile (2.0.27)
rdbms (0.2.5)
redis (0.2.14)
reservations (0.2.1)
resource (2.0.32)
role (2.0.26)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.27)
storage (2.0.35)
vm (2.0.35)

Python location './virtualenv-az/bin/python'
Extensions directory '/home/exfalso/.azure/cliextensions'

Python (Linux) 3.7.0 (default, Jul 15 2018, 10:44:58) 
[GCC 8.1.1 20180531]

Legal docs and information: aka.ms/AzureCliLegal
```

**Additional context**

The bug can be worked around by catching the TypeError and simply retrying (the browsers are initialized at this point), like so:

```python
def open_page_in_browser(url):
    if sys.platform.lower() == 'darwin':
        # handle 2 things:
        # a. On OSX sierra, 'python -m webbrowser -t <url>' emits out "execution error: <url> doesn't
        #    understand the "open location" message"
        # b. Python 2.x can't sniff out the default browser
        import subprocess
        return subprocess.Popen(['open', url])
    import webbrowser
    try:
        return webbrowser.open(url, new=2) # 2 means: open in a new tab, if possible
    except TypeError as err: # See https://bugs.python.org/msg322439. A simple retry works
        return webbrowser.open(url, new=2)
```

### PR DESCRIPTION
**Pull request by JamieMagee**
This is a workaround for [This bug](https://bugs.python.org/msg322439) in Python 3.7

Fixes #7033

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by JamieMagee** [comment]
@yugangw-msft Can I get a review please?

**Comment by yugangw-msft** [comment]
@JamieMagee, sorry for the delay, but I have tried Python 3.7 on osx, but could not reproduce. Can you please share a bit detail of the system configuration? Does the os have to be high sierra? 
I hope I can get a repro so i can co-verify your fix before merge.

**Comment by JamieMagee** [comment]
Sure. I'm running Python 3.7 on Arch Linux. Here's the python specific environment information

```
$ python --version
Python 3.7.0
$ az --version
azure-cli (2.0.44)

acr (2.1.3)
acs (2.3.0)
advisor (0.6.0)
ams (0.2.2)
appservice (0.2.2)
backup (1.2.0)
batch (3.3.2)
batchai (0.4.1)
billing (0.2.0)
cdn (0.1.0)
cloud (2.1.0)
cognitiveservices (0.2.0)
command-modules-nspkg (2.0.2)
configure (2.0.18)
consumption (0.4.0)
container (0.3.3)
core (2.0.44)
cosmosdb (0.2.0)
dla (0.2.1)
dls (0.1.0)
dms (0.1.0)
eventgrid (0.2.0)
eventhubs (0.2.2)
extension (0.2.1)
feedback (2.1.4)
find (0.2.12)
interactive (0.3.28)
iot (0.3.0)
iotcentral (0.1.0)
keyvault (2.2.2)
lab (0.1.0)
maps (0.3.1)
monitor (0.2.2)
network (2.2.3)
nspkg (3.0.3)
policyinsights (0.1.0)
profile (2.1.1)
rdbms (0.3.0)
redis (0.3.0)
relay (0.1.0)
reservations (0.3.1)
resource (2.1.2)
role (2.1.3)
search (0.1.1)
servicebus (0.2.1)
servicefabric (0.1.1)
sql (2.1.2)
storage (2.2.0)
vm (2.2.1)

Python location '/usr/bin/python'
Extensions directory '/home/jamie/.azure/cliextensions'

Python (Linux) 3.7.0 (default, Sep 15 2018, 19:13:07) 
[GCC 8.2.1 20180831]

Legal docs and information: aka.ms/AzureCliLegal
```

My linux environment details are

```
$ uname -a
Linux laptop 4.18.14-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 13 13:42:37 UTC 2018 x86_64 GNU/Linux
```

And the package is installed from the AUR. The install steps are pretty standard (`python setup.py install`), but the full install script can be found [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-azure-cli)

Please let me know if you need more information to help with the repro.

**Comment by yugangw-msft** [comment]
looks sane. I will update the history through #7609

**Pull request merged**
