### PR TITLE
[ACR] 'az acr task update': null pointer exception.

### LINKED ISSUE #12276: Failed to update task with "--commit-trigger-enabled true"
## Describe the bug
Unable to update an existing task to enable commit trigger.

**Command Name**
`az acr task update`

**Errors:**
```
expected string or bytes-like object
Traceback (most recent call last):
Temp\pip-install-0u_uiwkq\knack\knack\cli.py, ln 206, in invoke
azure\cli\core\commands\__init__.py, ln 608, in execute
azure\cli\core\commands\__init__.py, ln 666, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 659, in _run_job
Local\Temp\pip-install-0u_uiwkq\six\six.py, ln 696, in reraise
azure\cli\core\commands\__init__.py, ln 636, in _run_job
azure\cli\core\commands\__init__.py, ln 306, in __call__
azure-cli-core\azure\cli\core\__init__.py, ln 493, in default_command_handler
azure\cli\command_modules\acr\task.py, ln 392, in acr_task_update
azure\cli\command_modules\acr\task.py, ln 997, in _get_branch_name
Microsoft SDKs\Azure\CLI2\lib\re.py, ln 182, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az acr task update -n {} -r {} -f {} --commit-trigger-enabled true`

## Expected Behavior
Update the task

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: cmd.exe

azure-cli 2.0.80 *

Extensions:
azure-devops 0.8.0
dev-spaces 1.0.4
interactive 0.4.3

```

### PR DESCRIPTION
**Pull request by rosanch**
Acr task update null pointer exception
Fixes issue #12276

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S166.

**Comment by northtyphoon** [comment]
>                         repository_url=context_path,

If context_path is null, do you need to update the context_path with the existing context_path in task?

---
Refers to: src/azure-cli/azure/cli/command_modules/acr/task.py:410 in f6abe6b. [](commit_id = f6abe6b2c4bc67b51332f0415003386ea173ad94, deletion_comment = False)

**Comment by northtyphoon** [comment]
>                         repository_url=context_path,

And _get_branch_name can get the value from it as weel?

---
In reply to: [593748093](https://github.com/Azure/azure-cli/pull/12416#issuecomment-593748093) [](ancestors = 593748093)

---
Refers to: src/azure-cli/azure/cli/command_modules/acr/task.py:410 in f6abe6b. [](commit_id = f6abe6b2c4bc67b51332f0415003386ea173ad94, deletion_comment = False)

**Comment by northtyphoon** [comment]
@rosanch will you go with the solution to require the customer to provide context-path and access-token if they attempt to re-enable the commit trigger?

**Comment by northtyphoon** [comment]
@rosanch can you also update the pr title?

https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/README.md#submitting-pull-requests

**Comment by rosanch** [comment]
> @rosanch can you also update the pr title?
> 
> https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/README.md#submitting-pull-requests

**Comment by rosanch** [comment]
> @rosanch will you go with the solution to require the customer to provide context-path and access-token if they attempt to re-enable the commit trigger?

I wanted to merge the bug fix first. I'll provide support for using existing context in a different pr

**Pull request merged**
