### PR TITLE
avail-set: make "--platform-update-domain-count" arg optional

### PR DESCRIPTION
**Pull request by yugangw-msft**
This leverages server defaults 

### General Guidelines

- [x] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [x] Each command and parameter has a meaningful description.
- [x] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by tjprescott** [comment]
Is this a recent service update? I thought we used to have defaults but had to change them because different regions had different numbers of domains?

**Comment by yugangw-msft** [comment]
@tjprescott, yep, that was for the fault domain which we had to adjust. This PR is about update domain which should have been set to None by default from the start

**Comment by tjprescott** [comment]
So fault-domain is required but update-domain has a default?

**Comment by yugangw-msft** [comment]
@tjprescott, yes

**Pull request merged**
