### PR TITLE
appservice: make SKU optional when creating an appservice plan

### PR DESCRIPTION
**Pull request by mayurid**
Closes https://github.com/Azure/azure-cli/issues/1381

### CODE REVIEW

**Comment by derekbekoe** [comment]
I think we should use the reflection we do on the methods for this.
There was a bug there in the method definition.
In the method linked below, we should have `sku='B1'` instead of `sku`.

And then, we can remove `default='B1'` from the params file.

https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-appservice/azure/cli/command_modules/appservice/custom.py#L252

**Comment by yugangw-msft** [comment]
I author'd the defaults in the `_param.py` so all related literals will be in the same file for easier update in future. I am fine to leverage reflections, since if there are mismatch, the test will catch it anyway.

**Comment by mayurid** [comment]
@derekbekoe : Addressed the feedback. @yugangw-msft : Thanks for helping with it

**Comment by derekbekoe** [comment]
@mayurid I added 'Closes #1381' to the PR description so the issue closes when the PR is merged.

link: https://github.com/blog/1506-closing-issues-via-pull-requests

**Pull request merged**
