### PR TITLE
[AKS] az aks get-credentials: Add a check for KUBECONFIG environmental variable

### LINKED ISSUE #18700: AKS Get-credentials does not respect KUBECONFIG env var
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
`az aks get-credentials` runs fine but writes only to `/Users/xs/.kube/config` despite `export KUBECONFIG=$HOME/.config/kube/config`. Yes, the specified KUBECONFIG file does exist and even has 4 contexts in it.

**To Reproduce**
`az aks get-credentials -n <cluster name> -g <resource group>`. I currently have 4 other contexts in my KUBECONFIG.

**Expected behavior**
The new config for the cluster should be added to the existing kubeconfig file.

**Environment summary**
Installed with brew on M1 MacBook. (darwin/arm64, BigSur)
az version:
```json
{
  "azure-cli": "2.25.0",
  "azure-cli-core": "2.25.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```
`kubectl version --client`:
```
Client Version: version.Info{
Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/arm64"
}
```

### PR DESCRIPTION
**Pull request by Volatus**
**Description**
`az aks get-credentials` does not check for the `KUBECONFIG` variable when creating/merging credentials. This PR fixes that and adds a check.

**Testing Guide**
```bash
touch ~/testconfig
export KUBECONFIG=~/testconfig
az aks get-credentials -n <cluster name> -g <resource group>
```

Fixes #18700
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@Volatus Please solve the CI issue in time today, otherwise this PR will miss the release of this sprint and can only be released in the next sprint (about 08-06)

**Comment by Volatus** [comment]
> @Volatus Please solve the CI issue in time today, otherwise this PR will miss the release of this sprint and can only be released in the next sprint (about 08-06)

Thanks for the heads up, how would I check if the `az aks get-credentials` command has the `-f/--file` option passed?

**Comment by zhoxing-ms** [comment]
> Thanks for the heads up, how would I check if the az aks get-credentials command has the -f/--file option passed?

I want to know what this means? Could you please explain it in detail?

**Comment by Volatus** [comment]
> > Thanks for the heads up, how would I check if the az aks get-credentials command has the -f/--file option passed?
> 
> I want to know what this means? Could you please explain it in detail?

Nothing, it's just I didn't want the `-f/--file` option where you specify the KUBECONFIG file to clash with this environmental variable check but I figured out a way to do it simply. Thanks for the help.

**Comment by paddycarey** [comment]
Hi @zhoxing-ms, I've noticed that since this change `get-credentials` is broken if a user's `KUBECONFIG` contains multiple files e.g.

`KUBECONFIG=/home/me/.kube/config:/home/me/.kube/anotherconfig:/home/me/.kube/yetanotherconfig`

Other tooling such as `kubectl` and `kubectx` handle this use case fine, but `az` now doesn't.

Should I file a new issue for this?

**Comment by Volatus** [comment]
@paddycarey Thanks for the information. What's the expected behavior when there are multiple files in the `KUBECONFIG`? Should it write to the first one or?

**Comment by paddycarey** [comment]
> What's the expected behavior when there are multiple files in the `KUBECONFIG`? Should it write to the first one or?

Good question! I'm not sure, I'll check what `kubectx` does here.

> Besides, what's the use case for having multiple files anyway?

In my case I have several tools which manage their own files (think one that manages configs for all dev clusters, one for prod, etc), so it's simpler to have multiple files than it is to have all the tools try to manage the same files.

**Pull request merged**
