### PR TITLE
Add acr to default installation list

### PR DESCRIPTION
**Pull request by djyou**

### CODE REVIEW

**Comment by djyou** [comment]
Sending the PR while waiting for approval from PMs.

@derekbekoe Please ping me if additional changes are needed.

/cc @SajayAntony @SteveLasker @mayurid @twitchax

**Comment by troydai** [comment]
@derekbekoe

**Comment by derekbekoe** [comment]
LGTM but marking as Do Not Merge for now pending approval

**Comment by troydai** [comment]
@derekbekoe who's approval we're waiting for?

**Pull request merged**
