### PR TITLE
Fallback to python3 when running az command

### PR DESCRIPTION
**Pull request by robertfairhead**
Closes https://github.com/Azure/azure-cli/issues/7367
Closes https://github.com/Azure/azure-cli/issues/1043

This removes the bash script wrapper for the `az` command that hardcoded `python` as the python executable, breaking the az cli for python3 users.

In it's place, it uses distutils entry points to have python create its own shim that chooses the correct python executable based on how it was installed, adding python3 support.

The functionality in `azure-cli/azure/cli/__main__.py was refactored into a main function there to allow for the entry point to work.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [N/A] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by derekbekoe** [comment]
@robertfairhead This shim that `entry_points` introduces an import from `pkg_resources` which itself has a large set of other imports. This adds a significant penalty to the start up time for each invocation of `az`.

This was why we didn't use `entry_points` in `setup.py` in the first place.

For example, 3 runs of that import shows the following times on a MacBook Pro with Intel i7 and SSD:
```
$ time python -c 'import pkg_resources'
real	0m0.547s
user	0m0.244s
sys	0m0.175s

$ time python -c 'import pkg_resources'
real	0m0.317s
user	0m0.231s
sys	0m0.081s

$ time python -c 'import pkg_resources'
real	0m0.317s
user	0m0.230s
sys	0m0.083s
```

**Comment by robertfairhead** [comment]
@derekbekoe Fair enough on the start up time. I switched to a test in the bash script that checks if `azure` is available via the `python` binary and if so uses that. If not, it fallback to trying `python3`.

That should present to change to behavior to most users but provide support for those who invoke it as in the issues.

**Comment by troydai** [comment]
Assign this to @williexu

**Comment by troydai** [comment]
This is indeed an idea we should keep exploring. It should have also carefully considered in the broader discussion around what's the long-term plan as we approaching the end of the Python2 lifecycle. Reassign to @williexu as I'm moving out of the project.

**Comment by yugangw-msft** [comment]
//CC @lmazuel

**Comment by akx** [comment]
FWIW, there's https://pypi.org/project/fastentrypoints/ if you want entrypoints-like behavior without the startup time penalty.

**Comment by tjprescott** [comment]
@robertfairhead we are going to investigate some other options but I appreciate you being willing to share what works for you with the project. For now I will close this PR.

**Pull request closed without merging**
