### PR TITLE
[ACR] Improve manifest sha256 example

### PR DESCRIPTION
**Pull request by djyou**
Fixes https://github.com/Azure/azure-cli/issues/5337

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [x] Each command and parameter has a meaningful description.
- [x] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/5391
This is an **experimental preview** for @microsoft users.

**Comment by mmacy** [comment]
@djyou @sajayantony Definitely better! Would it be appropriate/possible to also mention in the help message that they can obtain manifest digests with `az acr repository show-manifests`? Or is mentioning another command in a command's help text non-standard?

**Comment by tjprescott** [comment]
@mmacy there is specific kwarg in the help file to accomplish that.  It is called `populator-commands`.  Here's an example usage:
```
helps['network application-gateway ssl-policy set'] = """
    type: command
    short-summary: Update or clear SSL policy settings.
    parameters:
        - name: --cipher-suites
          populator-commands:
            - az network application-gateway ssl-policy list-options
```

Then the help will say "Values from: <your command here>".

**Comment by djyou** [comment]
@tjprescott @mmacy Updated to the following:
```
    --manifest             : The sha256 based digest of manifest to delete.  Values from: az acr
                             repository show-manifests.
```
```
    Delete a manifest using a sha256 based digest. This also deletes any associated layer data and
    all tags referencing the manifest.
        az acr repository delete -n MyRegistry --repository MyRepository --manifest sha256:abc123
```

**Pull request merged**
