### PR TITLE
[Packaging] Use Python 3.9 in Homebrew formula

### PR DESCRIPTION
**Pull request by jiasli**
**Description**

Finish the work of #18224:

1. Use the latest macOS on ADO
2. Use Python 3.9 to generate the formula

### CODE REVIEW

**Comment by jiasli** [comment]
Currently pending on https://github.com/Homebrew/homebrew-core/pull/78022 to be merged so that we can test with the formula from homebrew master branch:

https://github.com/Azure/azure-cli/blob/d201b4aeb7351d8671825cbf4874301130baa402/scripts/release/homebrew/docker/run.sh#L13-L15

**Comment by carlocab** [comment]
Homebrew/homebrew-core#83088 has been merged.

**Comment by jiasli** [comment]
As expected, [`azure-cli.rb`](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1047173&view=artifacts&pathAsName=false&type=publishedArtifacts) is now generated from https://github.com/Homebrew/homebrew-core/blob/master/Formula/azure-cli.rb with

```rb
  depends_on "python@3.9"
```

The CI shows no problem with Python 3.9.

https://dev.azure.com/azure-sdk/public/_build/results?buildId=1047173&view=logs&j=ebe8970d-a8af-5d7e-4086-8f4ce0be006b&t=3f22f999-770c-5d06-3bb8-1a936f5d8384

```
2021-08-13T15:32:15.5319250Z ==> Summary
2021-08-13T15:32:19.0458940Z 🍺  /usr/local/Cellar/azure-cli/2.27.0: 41,764 files, 689.0MB, built in 17 minutes 5 seconds
2021-08-13T15:32:19.1064300Z Removing: /Users/runner/Library/Caches/Homebrew/azure-cli--azure-mgmt-compute--22.1.0.zip... (4.2MB)
2021-08-13T15:32:19.1498690Z Removing: /Users/runner/Library/Caches/Homebrew/azure-cli--azure-mgmt-containerregistry--8.1.0.zip... (859.4KB)
2021-08-13T15:32:19.2334590Z Removing: /Users/runner/Library/Caches/Homebrew/azure-cli--azure-mgmt-security--1.0.0.zip... (395.6KB)
2021-08-13T15:32:21.0578450Z 
2021-08-13T15:32:21.0585530Z echo == Az Version ==
2021-08-13T15:32:21.0588350Z az --version
2021-08-13T15:32:21.0589490Z == Az Version ==
2021-08-13T15:32:21.8603710Z WARNING: You have 2 updates available. Consider updating your CLI installation with 'az upgrade'
2021-08-13T15:32:21.8605690Z 
2021-08-13T15:32:22.0090200Z Please let us know how we are doing: https://aka.ms/azureclihats
2021-08-13T15:32:22.0152750Z and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
2021-08-13T15:32:22.0534420Z azure-cli                         2.27.0 *
2021-08-13T15:32:22.0546570Z 
2021-08-13T15:32:22.0547800Z core                              2.27.0 *
2021-08-13T15:32:22.0548950Z telemetry                          1.0.6
2021-08-13T15:32:22.0549810Z 
2021-08-13T15:32:22.0552400Z Python location '/usr/local/Cellar/azure-cli/2.27.0/libexec/bin/python'
2021-08-13T15:32:22.0554140Z Extensions directory '/Users/runner/.azure/cliextensions'
2021-08-13T15:32:22.0554660Z 
2021-08-13T15:32:22.0555780Z Python (Darwin) 3.9.6 (default, Jun 29 2021, 06:20:32) 
2021-08-13T15:32:22.0557260Z [Clang 12.0.0 (clang-1200.0.32.29)]
2021-08-13T15:32:22.0558050Z 
2021-08-13T15:32:22.0559440Z Legal docs and information: aka.ms/AzureCliLegal
2021-08-13T15:32:22.0560210Z 
2021-08-13T15:32:22.0560930Z 
2021-08-13T15:32:22.0910560Z 
2021-08-13T15:32:22.0919690Z echo == Run Self-Test ==
2021-08-13T15:32:22.0927350Z az self-test
2021-08-13T15:32:22.0929480Z == Run Self-Test ==
2021-08-13T15:32:23.5114580Z WARNING: This command has been deprecated and will be removed in a future release.
2021-08-13T15:32:47.6423340Z Running CLI self-test.
2021-08-13T15:32:47.6424010Z 
2021-08-13T15:32:47.6424970Z Loading all commands and arguments...
2021-08-13T15:32:47.6425610Z Commands loaded OK.
2021-08-13T15:32:47.6425860Z 
2021-08-13T15:32:47.6426260Z Retrieving all help...
2021-08-13T15:32:47.6426740Z Help loaded OK.
2021-08-13T15:32:47.6427000Z 
2021-08-13T15:32:47.6427990Z CLI self-test completed: OK
2021-08-13T15:32:48.6705420Z ##[section]Finishing: Bash Script
```

**Comment by jiasli** [comment]
Tested with a [release pipeline](https://dev.azure.com/azure-sdk/playground/_releaseProgress?_a=release-environment-logs&releaseId=829&environmentId=900) and [Azure CLI on Homebrew](https://formulae.brew.sh/formula/azure-cli) works as expected.

```
2021-08-14T04:05:40.1361880Z brew uninstall azure-cli

2021-08-14T04:05:59.5570120Z brew update --verbose

2021-08-14T04:06:21.6007540Z brew install azure-cli --verbose

2021-08-14T04:07:09.8734350Z az --version
2021-08-14T04:07:09.8735030Z == Az Version ==
2021-08-14T04:07:12.4127830Z 
2021-08-14T04:07:12.5313940Z Please let us know how we are doing: https://aka.ms/azureclihats
2021-08-14T04:07:12.5316590Z and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
2021-08-14T04:07:12.6062200Z azure-cli                         2.27.1
2021-08-14T04:07:12.6062530Z 
2021-08-14T04:07:12.6063080Z core                              2.27.1
2021-08-14T04:07:12.6063480Z telemetry                          1.0.6
2021-08-14T04:07:12.6063690Z 
2021-08-14T04:07:12.6064440Z Python location '/usr/local/Cellar/azure-cli/2.27.1/libexec/bin/python'
2021-08-14T04:07:12.6065410Z Extensions directory '/Users/runner/.azure/cliextensions'
2021-08-14T04:07:12.6065630Z 
2021-08-14T04:07:12.6065970Z Python (Darwin) 3.9.6 (default, Jun 29 2021, 06:20:32) 
2021-08-14T04:07:12.6066750Z [Clang 12.0.0 (clang-1200.0.32.29)]
2021-08-14T04:07:12.6067450Z 
2021-08-14T04:07:12.6067790Z Legal docs and information: aka.ms/AzureCliLegal
2021-08-14T04:07:12.6067980Z 
2021-08-14T04:07:12.6068080Z 
2021-08-14T04:07:12.6068710Z Your CLI is up-to-date.
2021-08-14T04:07:12.6417430Z 
2021-08-14T04:07:12.6418850Z echo == Run Self-Test ==
2021-08-14T04:07:12.6419670Z az self-test
2021-08-14T04:07:12.6420910Z == Run Self-Test ==
2021-08-14T04:07:15.2633900Z WARNING: This command has been deprecated and will be removed in a future release.
2021-08-14T04:07:47.1789220Z Running CLI self-test.
2021-08-14T04:07:47.1789560Z 
2021-08-14T04:07:47.1789880Z Loading all commands and arguments...
2021-08-14T04:07:47.1790240Z Commands loaded OK.
2021-08-14T04:07:47.1790380Z 
2021-08-14T04:07:47.1790620Z Retrieving all help...
2021-08-14T04:07:47.1790900Z Help loaded OK.
2021-08-14T04:07:47.1791030Z 
2021-08-14T04:07:47.1791660Z CLI self-test completed: OK
```

**Review by yonzhan — APPROVED** [review]

**Pull request merged**
