### PR TITLE
Skip DevTest Lab tests

### PR DESCRIPTION
**Pull request by troydai**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/6153
This is an **experimental preview** for @microsoft users.

**Comment by derekbekoe** [comment]
Please rebase with the latest on dev branch. There was a fix just merged to fix a Travis CI change.

**Comment by troydai** [comment]
@derekbekoe and @tjprescott ?

**Comment by troydai** [comment]
Pending me figuring out the right way to automate this with DevTest lab team.

**Pull request merged**
