### PR TITLE
[ACR] `az acr task credential`: Fix the issue where task credentials were not used

### PR DESCRIPTION
**Pull request by savaradh**
**Description**
Contains fix for regression on acr task credentials command

### CODE REVIEW

**Review by northtyphoon — APPROVED** [review]
LGTM

**Comment by yonzhan** [comment]
ACR

**Review by shahzzzam — APPROVED** [review]
LGTM

**Comment by zhoxing-ms** [comment]
Please specify the affected command in the PR title.
You can refer to the doc [submitting-pull-requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests) to write the PR title

**Comment by zhoxing-ms** [comment]
Could you add some test cases for this change?

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
