### PR TITLE
{ARM} `az stack` Deprecate the `--delete-*` options and redirect to the new `--action-on-unmanage` argument for the `create` and `delete` subcommands.

### PR DESCRIPTION
**Pull request by kalbert312**
**Related command**
`az stack group create`
`az stack group delete`
`az stack sub create`
`az stack sub delete`
`az stack mg create`
`az stack mg delete`

**Description**
This PR deprecates the following command options from the commands listed in `Related commands`:
- `--delete-resources`
- `--delete-resource-groups`
- `--delete-all` (resources + resource groups)

If none of these `delete-*` flags are specified in the command, the default behavior is to detach resources and resource groups.

These deprecated options are replaced by a new optional argument `--action-on-unmanage`/`--aou` that requires a value from this list:
- `detachAll` (resources + resource groups)
- `deleteResources`
- `deleteAll` (resources + resource groups)

A validation check has been added to enforce exclusive use of either the `--action-on-unmanage` argument or the `--delete-*` options approach.

In a future release, the `--delete-*` flags will be removed entirely and the `--action-on-unmanage` argument will become required, requiring the user to explicitly define a behavior. The default "unmanage" behavior is "detachAll" before and after this PR if none of the arguments/options are specified.

Note that it's not possible to represent just `--delete-resource-groups` with the new `--action-on-unmanage` argument. Specifying that flag without `--delete-all` or `--delete-resources` before this PR was also unsupported so this is not a breaking change.

Regarding the tests, I decided to randomly update some test commands to use the new argument to get coverage on both paths. When the deprecated commands are removed, all tests will be updated.

**Testing Guide**
Refer to deployment stacks CLI documentation to get started: https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/deployment-stacks?tabs=azure-cli 
This requires:
- Permission to create deployments in ARM.
- A valid deployment template to use.
- Pre-existing subscription/resource group setup for the deployment to occur in.

The behaviors of "detach" and "delete" are described here https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/deployment-stacks?tabs=azure-cli#control-detachment-and-deletion and carry over to the `--action-on-unmanage` argument.

**History Notes**

[ARM] `az stack group create`: Deprecate the `--delete-resources`, `--delete-resource-groups` and `--delete-all` options and redirect to the new `--action-on-unmanage` argument
[ARM] `az stack group delete`: Deprecate the `--delete-resources`, `--delete-resource-groups` and `--delete-all` options and redirect to the new `--action-on-unmanage` argument
[ARM] `az stack sub create`: Deprecate the `--delete-resources`, `--delete-resource-groups` and `--delete-all` options and redirect to the new `--action-on-unmanage` argument
[ARM] `az stack sub delete`: Deprecate the `--delete-resources`, `--delete-resource-groups` and `--delete-all` options and redirect to the new `--action-on-unmanage` argument
[ARM] `az stack mg create`: Deprecate the `--delete-resources`, `--delete-resource-groups` and `--delete-all` options and redirect to the new `--action-on-unmanage` argument
[ARM] `az stack mg delete`: Deprecate the `--delete-resources`, `--delete-resource-groups` and `--delete-all` options and redirect to the new `--action-on-unmanage` argument

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
ARM

**Comment by snarkywolverine** [comment]
Hi @zhoxing-ms, @yonzhan, and @jsntcy - Can you please review and merge this for the March 26 deadline? This is a small change that is laying groundwork for a breaking change that we will release in May. Thanks!

/ cc @azcloudfarmer

**Comment by yanzhudd** [comment]
Hi @kalbert312 
let me check with you if there is any breaking change to this PR?

**Comment by kalbert312** [comment]
> Hi @kalbert312 let me check with you if there is any breaking change to this PR?

@yanzhudd There are no breaking changes in this PR.

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
