### PR TITLE
Making exec-command required for Container Exec

### PR DESCRIPTION
**Pull request by samkreter**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/5945
This is an **experimental preview** for @microsoft users.

**Comment by derekbekoe** [comment]
Update HISTORY to mention this.
Technically, it's a breaking change.

**Comment by tjprescott** [comment]
@derekbekoe I thought the same, but if it failed at the service side without that parameter then its really is more akin to just adding client-side validation. No script could be broken by the change because it would fail in either case.

**Comment by samkreter** [comment]
Yes this is a fix that should have been in the first PR. The server side is expecting the command. Is this still a change that should update the history? @derekbekoe

**Pull request merged**
