### PR TITLE
{App Service} az appservice ase: Fix issue with resource group in new SDK

### PR DESCRIPTION
**Pull request by madsd**
**Description**
Change resource group to be fetched from the resource id of the ASE. The issue occurs if you call commands without explicitly defining the resource group.

**Testing Guide**
az appservice ase list-addresses -n <ase-name>

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
App Service

**Review by wangzelin007 — APPROVED** [review]

**Comment by panchagnula** [comment]
@madsd like we discussed offline please create a task/issue for ASE to team to update the swagger to include the missing property so that the next SDK drop will have this, instead of CLI/client making the changes to handle this.
This can be a temporary work around for CLI, property missing on SDK/swagger would be a breaking change & if this is not expected, this should be fixed at the source correctly. Thanks!

**Review by zhoxing-ms — APPROVED** [review]

**Review by panchagnula — APPROVED** [review]
LGTM

**Pull request merged**
