### PR TITLE
[iot] Updated device key generation

### PR DESCRIPTION
**Pull request by c-ryan-k**
**Description**
Updated device key generation to use python `secrets.token_bytes`

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
iot

**Comment by c-ryan-k** [comment]
Hey @yonzhan / @zhoxing-ms - looks like there were some CI updates made to the pipeline last night that may have fixed the errors here (I don't think any of the failures were caused by the IoT module), would you mind triggering a new CI run when you can? Thanks!

**Review by zhoxing-ms — APPROVED** [review]

**Review by digimaun — APPROVED** [review]

**Comment by c-ryan-k** [comment]
Well this is embarrassing, looks like I made the mistake of using this branch for two PRs, will resubmit both.

**Pull request closed without merging**
