### PR TITLE
[ACR] Update ACR SDK version

### PR DESCRIPTION
**Pull request by djyou**

### CODE REVIEW

**Comment by tjprescott** [comment]
@djyou please rebase this onto master and the CI should pass.

**Comment by djyou** [comment]
@tjprescott There are still errors which don't seem to be caused by this PR.

**Comment by tjprescott** [comment]
@djyou you are right. Now there seem to be issues with tests no longer being accepted. I'm investigating.

**Comment by tjprescott** [comment]
@djyou an update was released for msrestazure that no longer works with several test recordings. The CI pulls that version and that's why it is failing. I will rerecord the affected tests and let you know when you can rebase your changes.

**Pull request merged**
