### PR TITLE
{Misc} wrap issue templates hint messages.

### PR DESCRIPTION
**Pull request by yungezz**
**History Notes:**  
(Fill in the following template if multiple notes are needed, otherwise PR title will be used for history note.)

[Component Name 1] (BREAKING CHANGE:) (az command:) make some customer-facing change.  
[Component Name 2] (BREAKING CHANGE:) (az command:) make some customer-facing change.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
issue templates

**Comment by qwordy** [comment]
What's purpose of this PR? Why comment these explanations?

**Comment by yungezz** [comment]
> What's purpose of this PR? Why comment these explanations?

today, the hint messages mixed with real issue input from creator. wrap those hint messages up  so that issue creator could still see them when creating issues, why it will not be showed after rendering in broswer.

**Comment by qwordy** [comment]
> 
> 
> > What's purpose of this PR? Why comment these explanations?
> 
> today, the hint messages mixed with real issue input from creator. wrap those hint messages up so that issue creator could still see them when creating issues, why it will not be showed after rendering in broswer.

They all disappear in preview page:
https://github.com/Azure/azure-cli/blob/f39f4bf94078577561cf9c930e6e7d1072438db7/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by yungezz** [comment]
> What's purpose of this PR? Why comment these explanations?
> 
> today, the hint messages mixed with real issue input from creator. wrap those hint messages up so that issue creator could still see them when creating issues, why it will not be showed after rendering in broswer.
> 
> They all disappear in preview page:
> https://github.com/Azure/azure-cli/blob/f39f4bf94078577561cf9c930e6e7d1072438db7/.github/ISSUE_TEMPLATE/Bug_report.md

that's the purpose, so issue reader could  see only real messages about the issue. when creating a new issue, those messages are still there. I can close the PR if people like those hints message in issue :)

**Pull request merged**
