### PR TITLE
{RDBMS} `az postgres flexible-server restore`: Add empty string validation to resource group name

### PR DESCRIPTION
**Pull request by mattboentoro**
**Related command**
az postgres flexible-server restore

**Description**
Add empty string validation to resource group name for PG commands.

**Testing Guide**
Manual testing

**History Notes**

{RDBMS} `az postgres flexible-server restore`: Add empty string validation to resource group name

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
RDBMS

**Comment by mattboentoro** [comment]
@yonzhan @evelyn-ys  I recently joined PostgreSQL team, and this is my first PR on GitHub for RDBMS. I was wondering why I couldn't get to add my team member as a reviewer? Is there any other permission that I need to obtain for me to do that? In my last PR, one of my team member has to do it for me

**Comment by evelyn-ys** [comment]
There's no special policy from our repo's settings. Maybe some restriction from Github

**Review by nasc17 — APPROVED** [review]

**Comment by nasc17** [comment]
@evelyn-ys Please review this PR, looks good

**Comment by evelyn-ys** [comment]
will review after current 10-08 release

**Comment by mattboentoro** [comment]
@yonzhan @evelyn-ys do you mind reviewing and merging this PR?

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
