### PR TITLE
{CI} Update CODEOWNERS(Do not merge)

### PR DESCRIPTION
**Pull request by msyyc**
**Description**

**Testing Guide**

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
CODEOWNERS

**Review by kairu-ms — APPROVED** [review]

**Review by jiasli — COMMENTED** [review]
@ghost is a placeholder for deleted GitHub users. Why is this PR merge? Please kindly add some description.

**Comment by jiasli** [comment]
If @ghost is a placeholder for non-owner files, please refer to the official document. 

YAML files can contain credentials which should be manually reviewed (#16795).

**Pull request merged**
