### PR TITLE
[Network] `az network private-endpoint-connection`: Enable private link support for provider `Microsoft.Dashboard/grafana`

### PR DESCRIPTION
**Pull request by MSGaryWang**
**Related command**

az network

**Description**

This PR added managing private endpoint support for Azure Managed Grafana Service

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Network

**Comment by necusjz** [comment]
@MSGaryWang, please add test cases for the new command, as https://github.com/Azure/azure-cli/blob/dev/doc/private_endpoint_connection_command_guideline.md#command-guideline mentioned.

**Review by necusjz — CHANGES_REQUESTED** [review]
@MSGaryWang, please add test cases for the new command, as https://github.com/Azure/azure-cli/blob/dev/doc/private_endpoint_connection_command_guideline.md#add-test-case-for-your-new-service mentioned.

**Comment by necusjz** [comment]
@MSGaryWang, any updates so far?

**Comment by necusjz** [comment]
> There is an issue with NRP on boarding process so we can't verify E2E case and network team is working on it. Once they fix it and we will be back on this PR again.

**Comment by MSGaryWang** [comment]
@necusjz I had added the test cases

**Review by necusjz — APPROVED** [review]

**Pull request merged**
