### PR TITLE
{Batch} Fix `az batch account create`: AttributeError: 'str' object has no attribute 'tolower'

### LINKED ISSUE #15888: az batch account create fails with 'str' object has no attribute 'tolower'
hit a bug when running az batch account create command saying 'str' object has no attribute 'tolower'

**Command Name**
az batch account create

**Errors:**
```
'str' object has no attribute 'tolower'
Traceback (most recent call last):
Local\Temp\pip-unpacked-wheel-mtleih48\knack\cli.py, ln 215, in invoke
azure\cli\core\commands\__init__.py, ln 654, in execute
azure\cli\core\commands\__init__.py, ln 718, in _run_jobs_serially
azure\cli\core\commands\__init__.py, ln 709, in _run_job
azure\cli\command_modules\batch\_exception_handler.py, ln 30, in batch_exception_handler
AppData\Local\Temp\pip-unpacked-wheel-qqxn1krb\six.py, ln 703, in reraise
azure\cli\core\commands\__init__.py, ln 688, in _run_job
azure\cli\core\commands\__init__.py, ln 325, in __call__
pip-unpacked-wheel-a_t_wugh\azure\cli\core\__init__.py, ln 782, in default_command_handler
azure\cli\command_modules\batch\custom.py, ln 84, in create_account
AttributeError: 'str' object has no attribute 'tolower'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

az batch account create --encryption-key-source Microsoft.KeyVault --resource-group aed-synthetics-rg --keyvault aed-synthetics-keyvault --name aedsyntheticsbatch  --location centralus

## Expected Behavior

should work.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.14.2 *

```

### PR DESCRIPTION
**Pull request by bgklein**
Fixes #15888

### CODE REVIEW

**Comment by yonzhan** [comment]
Batch

**Comment by yungezz** [comment]
hi @qwordy ,could you pls help to review the PR?

**Review by qwordy — APPROVED** [review]

**Comment by qwordy** [comment]
How can we prevent this kind of error? It indicates that this line of code has not been tested neither manually nor automatically.

**Comment by qwordy** [comment]
Azure.azure-cli (Build Homebrew Formula) Failing after 1m — Build Homebrew Formula failed

**Comment by qwordy** [comment]
I clicked the error and saw Build not found.

**Review by zhoxing-ms — APPROVED** [review]

**Review by jiasli — APPROVED** [review]

**Review by Juliehzl — APPROVED** [review]

**Pull request merged**
