### PR TITLE
[ACS] Starting the install-connector deprecation process

### PR DESCRIPTION
**Pull request by jeremyrickard**
We will be replacing the `install-connector` command with a new add-on in AKS. This PR begins the process of deprecating the `install-connector` command. 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ x ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ x ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by troydai** [comment]
Please fix the CI.

**Comment by troydai** [comment]
Please bump the version in the setup.py

**Comment by jeremyrickard** [comment]
Forgot to run linter, fixing that now.

**Comment by troydai** [comment]
I will merge it nevertheless. Most of the CI checks already passed. The style check is low risk and I will take care of it. This is the cut off day of this sprint, so I'd like to speed things up.

**Comment by troydai** [comment]
Thank you @jeremyrickard

**Pull request merged**
