### PR TITLE
[App Config] `az appconfig kv export`: Stop throwing error if no key-values are exported to App Service

### PR DESCRIPTION
**Pull request by avanigupta**
**Description**
Fix https://github.com/Azure/AppConfiguration/issues/596

**Testing Guide**

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by avanigupta** [comment]
cc @shenmuxiaosen @pratiksanglikar

**Comment by pratiksanglikar** [comment]
Can we look at other places while we are at it?
I think we may need to add a check in `__write_kv_and_features_to_config_store` as well.
We currently check for `if not key_values and not features`, but there could be a case where `features` are present but not `key_values` that may land us in trouble.

**Comment by yonzhan** [comment]
App Config

**Comment by avanigupta** [comment]
> Can we look at other places while we are at it? I think we may need to add a check in `__write_kv_and_features_to_config_store` as well. We currently check for `if not key_values and not features`, but there could be a case where `features` are present but not `key_values` that may land us in trouble.

Thanks! Updated the check in all 3 export destinations. We should only check for `if not key_values and not features` because if either one is non-empty, we will definitely write something to the destination. This error occurs when there is nothing to write at all.

**Comment by pratiksanglikar** [comment]
There are two cases - 
1. When `key_values` is a `None` 
2. And, when `key_values` is not a `None` but an empty array.

Let's now consider a scenario where `key_values` is a `None` and `features` has a valid value.
The following statement will throw an error because we are trying to extend `None` - 
```python
    if features:
        key_values.extend(__convert_featureflag_list_to_keyvalue_list(features))   # This will throw an error
```
If it is guaranteed that `key_values` and `features` would never be `None` and would always have an empty array, then
the check `if not key_values and not features` is redundant, but if they can be `None`, then we should check for `if key_values` before we try to extend it.

**Comment by avanigupta** [comment]
The check `if not list` will return true if list is None or if list is empty ([reference](https://docs.python.org/3/library/stdtypes.html#truth-value-testing)).
Since the calling method always initializes `key_values` and `features` as empty lists, they will never be None. So the `extend` call cant throw.

**Review by pratiksanglikar — APPROVED** [review]
Looks good!

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
