### PR TITLE
[AKS] BREAKING CHANGE: `az aks create`: Remove legacy AAD related parameters when creating AKS cluster

### PR DESCRIPTION
**Pull request by bingosummer**
**Related command**

```
az aks create --resource-group={resource_group} --name={name} \
  --aad-server-app-id 00000000-0000-0000-0000-000000000001 \
  --aad-server-app-secret fake-secret \
  --aad-client-app-id 00000000-0000-0000-0000-000000000002
```

**Description**

Legacy AAD feature is deprecated and will be removed. This PR is to remove the related parameters `--aad-client-app-id`, `--aad-server-app-id` and `--aad-server-app-secret` when creating AKS cluster.

**Testing Guide**

**History Notes**

[AKS] BREAKING CHANGE: `--aad-client-app-id`, `--aad-server-app-id` and `--aad-server-app-secret`: Will be removed

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by FumingZhang — APPROVED** [review]
LGTM

**Comment by yonzhan** [comment]
Please fix CI issues

**Comment by bingosummer** [comment]
> Please fix CI issues

Fixed, thanks

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
