### PR TITLE
[Network] BREAKING CHANGE: `az network watcher flow-log`: Add support for `--vnet`, `--subnet`, `--nic` as targetId

### PR DESCRIPTION
**Pull request by srisakthimaheswari**
**Related command**

az network watcher flow-log

**Description**

PR includes changes to add support for --vnet, --subnet and --nic as targetId in addition to --nsg for flow logs.

**Testing Guide**

Command to test the module: azdev test test_nw_flow_log
Includes 6 test cases to test create, delete, show and update commands under az network watcher flow-log.

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Network

**Review by trdey — APPROVED** [review]

**Comment by necusjz** [comment]
@srisakthimaheswari, please fix the linter issues.

**Comment by srisakthimaheswari** [comment]
@necusjz, linter issues fixed

**Review by necusjz — APPROVED** [review]

**Comment by jsntcy** [comment]
See our [breaking change policy](https://eng.ms/docs/cloud-ai-platform/azure/azure-core-compute/control-plane-bburns/azure-cli-tools-azure-cli-powershell-and-terraform/azure-cli-tools/teams_docs/azcli_docs/breaking_changes).

**Pull request merged**
