### PR TITLE
[App Service] `az functionapp create` : Remove preview from PowerShell runtime for linux 

### PR DESCRIPTION
**Pull request by StrawnSC**
**Description**

Fixes https://github.com/Azure/azure-cli/issues/20631

**Testing Guide**

`az functionapp create -h`

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by panchagnula** [comment]
FYI @Francisco-Gamino

**Comment by panchagnula** [comment]
@StrawnSC can you also check if we have any preview text in the help section, we need to update?

**Comment by StrawnSC** [comment]
> @StrawnSC can you also check if we have any preview text in the help section, we need to update?

The runtimes in the `az functionapp create` help text are loaded from the file programmatically (instead of being hardcoded). So this is taken care of: 

Screen Shot 2022-01-07 at 11 48 12 AM

^ Note there's no (preview) next to the PowerShell runtime version in the help text

**Review by panchagnula — APPROVED** [review]
LGTM

**Comment by yonzhan** [comment]
App Service

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
