### PR TITLE
[Compute] sig image-definition create: add --features; New API version of gallery_images 2020-09-30

### PR DESCRIPTION
**Pull request by qwordy**
**Description**  

Resolve https://github.com/Azure/azure-cli/issues/15138
[Compute] sig image-definition create: add --features;

**Testing Guide**  

```
az sig image-definition create -g fy4 --gallery-name gg1 --gallery-image-definition image --os-type linux -p publisher1 -f offer1 -s sku1 --features "IsSecureBootSupported=true IsMeasuredBootSupported=false"
```

**History Notes**  

[Compute] sig image-definition create: add --features
[Compute] New API version of gallery_images 2020-09-30

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Compute

**Comment by yungezz** [comment]
hi @arrownj could you pls review the PR?

**Review by arrownj — APPROVED** [review]
👍

**Review by jiasli — APPROVED** [review]
Core LGTM.

**Pull request merged**
