### PR TITLE
Database is a sub-group instead of command for az sql elastic-pools 

### PR DESCRIPTION
**Pull request by vishrutshah**
Fix for #1777 

```
(env) vishrut@mac azure-cli (fix-elastic-pools-database-help) $ az sql elastic-pools database -h

Group
    az sql elastic-pools database: Command to manage databases activities in database elastic pools.

Commands:
    list         : Returns information about an Azure SQL database inside of an Azure SQL elastic
                   pool.
    show         : Gets information about an Azure SQL database inside of an Azure SQL elastic pool.
    show-activity: Returns information about activity on Azure SQL databases inside of an Azure SQL
                   elastic pool.

(env) vishrut@mac azure-cli (fix-elastic-pools-database-help) $ az sql elastic-pools database show -h

Command
    az sql elastic-pools database show: Gets information about an Azure SQL database inside of an
    Azure SQL elastic pool.

Arguments
    --database-name     [Required]: The name of the Azure SQL database to be retrieved.
    --elastic-pool-name [Required]: The name of the Azure SQL Elastic Pool to be retrieved.
    --resource-group -g [Required]: Name of resource group.
    --server-name       [Required]: The name of the Azure SQL server.

Global Arguments
    --debug                       : Increase logging verbosity to show all debug logs.
    --help -h                     : Show this help message and exit.
    --output -o                   : Output format.  Allowed values: json, jsonc, list, table, tsv.
                                    Default: json.
    --query                       : JMESPath query string. See http://jmespath.org/ for more
                                    information and examples.
    --verbose                     : Increase logging verbosity. Use --debug for full debug logs.
```

@troydai / @derekbekoe / @tjprescott Please have a look when you get a chance. Thanks

### CODE REVIEW

**Comment by vishrutshah** [comment]
@tjprescott Yes that seems better for consistence across commands. Let me know if anyone has any other preference or i can add fix to this PR itself.

**Comment by tjprescott** [comment]
I think it'd be fine to fix here.

**Comment by troydai** [comment]
Agree with @tjprescott regarding the name.

**Comment by vishrutshah** [comment]
```
(env) vishrut@mac azure-cli (fix-elastic-pools-database-help) $ az sql elastic-pools -h

Group
    az sql elastic-pools: Commands to manage database elastic pools.

Subgroups:
    db         : Command to manage databases activities in database elastic pools.
    recommended

Commands:
    create     : Creates a new Azure SQL elastic pool or updates an existing Azure SQL elastic pool.
    delete     : Deletes the Azure SQL elastic pool.
    list       : Returns information about Azure SQL elastic pools.
    show       : Gets information about an Azure SQL elastic pool.
    update     : Update a database elastic pool.

(env) vishrut@mac azure-cli (fix-elastic-pools-database-help) $ az sql elastic-pools db -h

Group
    az sql elastic-pools db: Command to manage databases activities in database elastic pools.

Commands:
    list         : Returns information about an Azure SQL database inside of an Azure SQL elastic
                   pool.
    show         : Gets information about an Azure SQL database inside of an Azure SQL elastic pool.
    show-activity: Returns information about activity on Azure SQL databases inside of an Azure SQL
                   elastic pool.

```

**Pull request merged**
