### PR TITLE
[App Service] `az functionapp deployment github-actions`: Add linux powershell support and fix publish profile bug

### PR DESCRIPTION
**Pull request by haroonf**
**Related command**
az functionapp deployment gihub-actions

**Description**
Minor improvements to the functionapp github-actions command. 

**Testing Guide**
Manual testing since we cannot hardcode github tokens

**History Notes**
[App Service] `az functionapp deployment github-actions`: Add support for linux powershell runtimes
[App Service] `az functionapp deployment github-actions`: Fix issue where publish profile would not be populated before the github action was run

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
App Service

**Comment by zhoxing-ms** [comment]
@haroonf Please do not add a list symbol under the `History Notes`. I have updated it for you

**Comment by zhoxing-ms** [comment]
@haroonf Could you add some tests for those PR change?

**Comment by haroonf** [comment]
> @haroonf Could you add some tests for those PR change?

These changes impact github-actions commands, which we can't write tests for since we require a GitHub Authentication Token.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
