### PR TITLE
[Synapse] Update to AZ Synapse artifact0.6.0 and fix notebook creation failure

### PR DESCRIPTION
**Pull request by zesluo**
**Description**
Update to AZ Synapse artifact0.6.0 and fix notebook creation failure

**Testing Guide**
az synapse notebook create -h

**History Notes**
[Synapse] az synapse notebook create : Create a notebook
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Synapse

**Comment by idear1203** [comment]
@zesluo regarding the test failure, I suspect this is caused by the recent changes of upgrading storage SDK in the entire Azure CLI repo level. If so, you might try sync up with the latest master branch then re-recorded the test case

**Review by Juliehzl — APPROVED** [review]

**Review by idear1203 — APPROVED** [review]

**Pull request merged**
