### PR TITLE
[SQL] Add az sql mi op list, az sql mi op get to display operation steps and operation parameters

### PR DESCRIPTION
**Pull request by toki95**
**Description**  

Add az sql mi op list, az sql mi op get to display operation steps and operation parameters
**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S174

**Comment by Juliehzl** [comment]
Hi @toki95 , could you take a look at failed tests?

**Comment by toki95** [comment]
> Hi @toki95 , could you take a look at failed tests?

These tests don't correlate to my change, I've informed the owning team of these failures.

**Comment by toki95** [comment]
@Juliehzl friendly ping :)

**Comment by MyronFanQiu** [comment]
@toki95 I thought the failed tests are test_sql_managed_db_short_retention, test_sql_managed_deleted_db_restore, test_sql_managed_db_mgmt and test_sql_managed_db_long_term_retention  which are related with SQL.

**Comment by toki95** [comment]
Yes, but not with this change. I have informed the team. We can merge this.

**Comment by toki95** [comment]
@MyronFanQiu ping :)

**Comment by MyronFanQiu** [comment]
@toki95 Hi. Since you change the sdk's verison and the api-version is also changed. You have to re-run the failed tests lively. These four failed tests should be caused your change.

**Comment by toki95** [comment]
@MyronFanQiu tests fixed, please merge.

**Comment by MyronFanQiu** [comment]
Approved. @Juliehzl I'm not code owner. Please help merge this pr.

**Comment by Juliehzl** [comment]
Hi @toki95, it seems you just replace the api version. Could we run all test in live mode for sql service to prevent there is breaking change for sql related command with new sdk version?

**Comment by toki95** [comment]
New PR https://github.com/Azure/azure-cli/pull/14728.
Old closed due to branch issues.

**Pull request closed without merging**
