### PR TITLE
{MYSQL} Fix default value of acclog parameter for mysql felxible server

### PR DESCRIPTION
**Pull request by linyudoa**
**Related command**

**Description**

There are bugs in default value handling for mysql logOnDisk feature, which will make it not take effect as expected

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by evelyn-ys** [comment]
Please format PR title and add PR description following https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests

Do you want to add tests for new changes?

**Comment by honghr** [comment]
> Please format PR title and add PR description following https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests
> 
> Do you want to add tests for new changes?

Hi @evelyn-ys, There is no new changes from this PR. And we just adjust code to fix bug so that we don't need new testcases. @linyudoa will update the title.

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
