### PR TITLE
{Auth} Provide GitHub issue links for DPAPI errors

### PR DESCRIPTION
**Pull request by jiasli**
**Description**

We see users constantly creating duplicated issues of 

- https://github.com/Azure/azure-cli/issues/20278
- https://github.com/Azure/azure-cli/issues/20231
- https://github.com/Azure/azure-cli/issues/21010

But the root cause for these issues remains unknown.

`msal-extensions` has made these errors catch-able in https://github.com/AzureAD/microsoft-authentication-extensions-for-python/pull/108, but since `azure-identity` has pinned dependency `msal-extensions~=0.3.0`, ~~it is not possible for Azure CLI to use the latest `msal-extensions` which contains that improvement (https://github.com/Azure/azure-sdk-for-python/issues/23927).~~ the dependency on `azure-identity` is removed by https://github.com/Azure/azure-cli/pull/22124.

**Testing Guide**

Raise an `OSError` at https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/0.3.1/msal_extensions/windows.py#L99

```py
        err_code = -2146893813
        raise OSError(None, _err_description.get(err_code, ''), None, err_code)
```

This will produce an error message like

```
Decryption failed: [WinError -2146893813] Key not valid for use in specified state.. App developer may consider this guidance: https://github.com/AzureAD/microsoft-authentication-extensions-for-python/wiki/PersistenceDecryptionError
Please report to us via Github: https://github.com/Azure/azure-cli/issues/20231
```

### CODE REVIEW

**Comment by yonzhan** [comment]
Auth

**Comment by jiasli** [comment]
Several small blemishes of `msal-extensions` error messages are refined by https://github.com/AzureAD/microsoft-authentication-extensions-for-python/pull/113.

**Review by evelyn-ys — APPROVED** [review]

**Review by calvinhzy — APPROVED** [review]

**Review by rayluo — APPROVED** [review]

**Pull request merged**
