### PR TITLE
[NetAppFiles] Anf 25576 resource query info

### PR DESCRIPTION
**Pull request by audunn**
**Related command**
az netappfiles

**Description**
Add validation to `az netappfiles volume replication resume` command to add warning on action to re-sync replication volumes that  if destination volume has quota rules they will be overwritten by the source volumes quota rules.

 "If any quota rules exists on destination volume  they will be overwritten with source volume's quota rules."

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
NetAppFiles

**Comment by audunn** [comment]
@kairu-ms are we good to move on with this ?

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
