### PR TITLE
[Monitor] az monitor log-analytics workspace data-export removes --export-all-tables parameter

### LINKED ISSUE #15742: Fix Log Analytics data export CLIs
**Resource Provider**
operationalinsights

**Description of Feature or Work Requested**
Log Analytics data export CLI includes '--all' and '--export-all-tables' which were removed in swaggers.
1. Removed these in CLI.
2. The example in CLI doesn't include Tables as required parameter. Tables should be added to required parameters:
az monitor log-analytics workspace data-export create **--tables** --destination
                                                      --name
                                                      --resource-group
                                                      --workspace-name
                                                      [--all {false, true}]
                                                      [--enable {false, true}]
                                                      [--subscription]

**Minimum API Version Required**
2020-08-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/2020-08-01

**Target Date**
We get support cases for it, please do at the first update iteration you can.

### LINKED ISSUE #15743: CLI requires parameter is showing as optional
**Resource Provider**
operationalinsights

**Description of Feature or Work Requested**
Log Analytics data export CLI includes '--all' and '--export-all-tables' which were removed in swaggers.
1. Removed these in CLI.
2. The example in CLI doesn't include Tables as required parameter. Tables should be added to required parameters:
az monitor log-analytics workspace data-export create **--tables** --destination
                                                      --name
                                                      --resource-group
                                                      --workspace-name
                                                      [--all {false, true}]
                                                      [--enable {false, true}]
                                                      [--subscription]

**Minimum API Version Required**
2020-08-01

**Swagger Link**
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/2020-08-01

**Target Date**
We get support cases for it, please do at the first update iteration you can.

### PR DESCRIPTION
**Pull request by kairu-ms**
Close #15742 
Close #15743 

**Description**

**Testing Guide**

**History Notes**

[Monitor] BREAKING CHANGE: az monitor log-analytics workspace data-export : Remove deprecated  --export-all-tables parameter and require--tables parameter

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Monitor

**Review by savelinomediagroup — CHANGES_REQUESTED** [review]
Hotfix

**Comment by savelinomediagroup** [comment]
HistoryRST.

**Review by savelinomediagroup — CHANGES_REQUESTED** [review]
Releasemergebacktnodev

**Review by msyyc — APPROVED** [review]

**Pull request merged**
