### PR TITLE
{App Service} replacement for a cheaper sku example

### PR DESCRIPTION
**Pull request by jeffwmartinez**
**Description**

Replacing example with a cheaper SKU to avoid customer sticker shock

**Testing Guide**

run the command:
az appservice plan create -g MyResourceGroup -n MyPlan \
--hyper-v --sku P1V3

This will create a new Windows container app service plan in your designated resource group.  You must use a new resource group.

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
appservice

**Review by yungezz — APPROVED** [review]

**Review by qwordy — APPROVED** [review]

**Comment by qwordy** [comment]
Some checks were not successful.

**Comment by yungezz** [comment]
hi @jeffreychenmsft could you pls help to fix CI failure so that we can merge the PR? thanks.

**Comment by qwordy** [comment]
Hi @jeffreychenmsft, could you help fix CI failure so that we can merge the PR? Thanks.

**Comment by panchagnula** [comment]
@calvinsID can you include this help fix in your current PR so we can close this one? Thanks!

**Comment by calvinsID** [comment]
Combined this fix into PR: https://github.com/Azure/azure-cli/pull/16528

**Pull request closed without merging**
