### PR TITLE
[AppService]: fix for #13291- az webapp deployment slot swap should support preserv…

### PR DESCRIPTION
**Pull request by Kotasudhakarreddy**
…eVnet

**Description**
#13291 
When swapping slots in an App Service via az webapp deployment slot swap, you can specify preserve vnet.

**Testing Guide**
az webapp deployment slot swap  -g <rg_name> -n <appsvc_name> --slot staging --target-slot production --preserve-vnet true

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by Kotasudhakarreddy** [comment]
@ThejaChoudary - FYI.

**Review by qwordy — APPROVED** [review]

**Comment by yonzhan** [comment]
AppService

**Review by panchagnula — APPROVED** [review]
LGTM!

**Comment by qwordy** [comment]
There are conflicting files.
```
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_slot_swap.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_slot.yaml
src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_slot_swap.yaml 
```

**Comment by Kotasudhakarreddy** [comment]
> There are conflicting files.
> 
> ```
> src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_functionapp_slot_swap.yaml
> src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_slot.yaml
> src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_webapp_slot_swap.yaml 
> ```

@qwordy - I have resolved the conflicts. But build is failing while loading the extensions. I am not sure on how to resolve it. Could you please help me here.

**Comment by qwordy** [comment]
@Kotasudhakarreddy The connection is not stable. Let's retry.
```
Verifying extension: alertsmanagement
ERROR: Unable to get extension index.
Please ensure you have network connection. Error detail: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Pull request merged**
