### PR TITLE
[Service Connector] `az containerapp connection`: Add new command group to support container app connection

### PR DESCRIPTION
**Pull request by ChenTanyi**
**Related command**

`az containerapp connection`

**Description**

Add service connector for containerapp in command group `az containerapp connection`.

**Testing Guide**

add test: test_containerapp_mysql_e2e, test_containerapp_storageblob_e2e

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Service Connector

**Review by houk-ms — APPROVED** [review]

**Comment by ChenTanyi** [comment]
@kairu-ms please help to review and merge the PR. I've fixed the pipeline but cannot rerun it.

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
