### PR TITLE
webapp: rename component from webapp to appservice

### PR DESCRIPTION
**Pull request by yugangw-msft**

### CODE REVIEW

**Comment by derekbekoe** [comment]
The text in `azure-cli-appservice/README.rst ` should change also as this is what is used for the package descriptions on PyPI.

**Comment by derekbekoe** [comment]
Also, please refer to #1151 and update doc_source_map.json. cc/ @formulahendry

**Comment by yugangw-msft** [comment]
@derekbekoe, I assume we have 2 follow-up items
a. Add this to the default-installed component list
b. Send a notification mail to related folks
Let me know...

**Comment by derekbekoe** [comment]
Yes that's correct.
When we create a release here, https://github.com/Azure/azure-cli/releases, it will also state that it's part of the default install also.

**Pull request merged**
