### PR TITLE
[reservations] Bump reservations sdk version 0.6 -> 0.8

### PR DESCRIPTION
**Pull request by aditink**
**Description**  

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by aditink** [comment]
@fengzhou-msft as you already have context, this is a version bump to unblock purchase for new reserved resource types. Want to request review but do not see it as an option in the UI.

**Comment by yonzhan** [comment]
Bump reservations

**Comment by fengzhou-msft** [comment]
@aditink The test is based on some exsiting resources and not live-test friendly, they should be improved. Do you knw who will pick up this work?

**Comment by aditink** [comment]
I don't; you should probably contact resextteam-dev alias.

**Comment by yungezz** [comment]
hi @aditink are you still on this PR? could you pls update recording test files also?

**Comment by jsntcy** [comment]
This PR was inactive for more than half year, so close it first. If you want it back, please reopen it in the future.

**Pull request closed without merging**
