### PR TITLE
[VM] `vm open-port` fix

### LINKED ISSUE #3322: az vm open-port returns error but executes successfully
### Description
az vm open-port returns an error but executes successfully

Example:
PS C:\Users\larry> az vm open-port -g JUMPBOXRG -n jumpbox --port 80  --priority 500
Operation failed with status: 'Not Found'. Details: 404 Client Error: Not Found for url: https://management.azure.com/subscriptions/5ba80c27-8c76-[***]/providers/Microsoft.Network/locations/eastus/operations/5c5fa1c7-3e4a-4dd3-[***]?api-version=2017-03-01

Error occurs on Windows & Linux
---

### Environment summary

**Install Method:** How did you install the CLI? (e.g. pip, interactive script, apt-get, Docker, MSI, nightly)  
Windows:  pip.  Linux: apt-get

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  
2.0.6

**OS Version:** What OS and version are you using?  
Windows 10, Ubuntu 17.04

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Powershell, Bash

### PR DESCRIPTION
**Pull request by tjprescott**
Closes #3322.

With the change, the `vm open-port` command will no longer attempt to update the NIC or subnet unless a NSG was not already found and had to be created.  Avoids an unnecessary REST call and opportunity for failure. 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [X] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [N/A] Each command and parameter has a meaningful description.
- [N/A] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by tjprescott** [comment]
@yugangw-msft I agree.

**Comment by tjprescott** [comment]
@yugangw-msft I made the change you suggested.

**Comment by alexeyshishkin01** [comment]
may I ask you how to install this fix on my machine?

**Comment by tjprescott** [comment]
It won't be publicly available until the next release (end of May) but you can explore a nightly build install or dev setup.

https://github.com/Azure/azure-cli#developer-installation-see-below

**Comment by alexeyshishkin01** [comment]
ok, I'll try to install the fix before release
btw may I ask you about the difference of azure-cli version if I use two commands to check it:

root@ALEXEY-HP:/mnt/d# az --version | grep azure-cli
azure-cli (2.0.6)

root@ALEXEY-HP:/mnt/d# apt list --installed | grep azure-cli
azure-cli/wheezy,now 0.2.9-1 all [installed]

**Comment by tjprescott** [comment]
@derekbekoe would be best able to answer that, but in general, `azure-cli (2.0.6)` is the version of the `azure-cli` PIP package, and the `0.2.9-1` is the "package version" of the bundled apt-get package.

**Comment by derekbekoe** [comment]
Adding to what @tjprescott said.
The CLI is built of multiple parts so `az --version` shows the versions for each of these parts.
For the `apt-get` package, all the parts are packaged together into one artifact which has version `0.2.9`.

**Pull request merged**
