### PR TITLE
[ACR] `az acr task logs`: Fix the AttributeError when querying the task logs

### LINKED ISSUE #19332: az acr task logs failed since 2.26.0
It is a regression issue from 2.26.0. 

repro step:
az acr task logs --registry $registryname

Expected:  Got the log of the latest run

Actual: Got the following error 
Could not find the latest created run. 

With -debug, we can see the error
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/acr/task.py", line 994, in acr_task_logs
    run_id = paged_runs.get(0)[0].run_id
AttributeError: 'ItemPaged' object has no attribute 'get'

### PR DESCRIPTION
**Pull request by rosanch**
Fixes #19332 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by zhoxing-ms** [comment]
Please refer to this doc [format-pr-title](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#format-pr-title) to modify your PR title

**Comment by zhoxing-ms** [comment]
Could you add some related tests?

**Comment by rosanch** [comment]
@zhoxing-ms is there a way I can make the pr run the tests again?

**Comment by zhoxing-ms** [comment]
@huanwu I have rerun the CI for you. Could you add some tests for this case?

**Review by huanwu — APPROVED** [review]

**Comment by rosanch** [comment]
@zhoxing-ms I have an item. I'm working on expanding our test coverage across all our commands. I'll submit them all in another PR. Can we merge this for now, please?

**Review by northtyphoon — APPROVED** [review]
LGTM

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
