### PR TITLE
{Network} Close bastion session from cli

### PR DESCRIPTION
**Pull request by AndrewRobie**
**Description**
Clean up the Bastion session established from the az cli after disconnecting.

**Testing Guide**
Azure SSH
1. Connect to an existing VM via `az network bastion ssh`
2. Verify session in the Azure portal
3. Exit the session from the command line by typing `exit` and pressing enter
4. Verify session is no longer present in Azure portal

Azure tunnel + SSH exit
1. Establish a tunnel to an existing VM via `az network bastion tunnel`
2. SSH into the VM (e.g., via putty)
3. Verify session in the Azure portal
4. Exit from the SSH session
5. Verify session is no longer present in Azure portal

Azure tunnel + SSH close tunnel
1. Establish a tunnel to an existing VM via `az network bastion tunnel`
2. SSH into the VM (e.g., via putty)
3. Verify session in the Azure portal
4. Close the tunnel as specified with "Ctrl + C"
5. Verify session is no longer present in Azure portal 

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by AndrewRobie** [comment]
@jsntcy @kairu-ms @wangzelin007 I'm not entirely sure why the docker build is failing. Based on the logs, it seems like a dependency conflict, but nothing in my changes should've caused that.

**Comment by yonzhan** [comment]
We will take a look after public holiday (1.31-2.6).

**Review by kairu-ms — APPROVED** [review]

**Comment by wangzelin007** [comment]
@AndrewRobie,
May I ask whether this pr is customer-facing?

**Review by wangzelin007 — APPROVED** [review]

**Pull request merged**
