### PR TITLE
{CI} Fix Codegen Coverage

### PR DESCRIPTION
**Pull request by wangzelin007**
**Related command**

Due to the inconsistent versions of jinja2 required by aosm and alias, and the random order of extension installations, installing a lower version of jinja2 can result in the following error:

```
  File "/mnt/vss/_work/1/s/env/lib/python3.11/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/mnt/vss/_work/1/s/env/lib/python3.11/site-packages/markupsafe/__init__.py)
```
Therefore, i want to enforce the use of a higher version of jinja2 for codegen coverage.
image

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by bebound** [comment]
Looks good as a workaround.

This task has bad design. It should not install **all extensions** in the same env and expects every extension works fine. We'll likely encounter another dependency conflict in the future.

**Review by bebound — APPROVED** [review]

**Review by AllyW — APPROVED** [review]

**Comment by wangzelin007** [comment]
> Looks good as a workaround.
> 
> This task has bad design. It should not install **all extensions** in the same env and expects every extension works fine. We'll likely encounter another dependency conflict in the future.

We need to install all extensions to calculate code generation coverage.
If the problem occurs again, consider not installing the extension that uses the lower version of the dependency.

**Comment by AllyW** [comment]
> > Looks good as a workaround.
> > This task has bad design. It should not install **all extensions** in the same env and expects every extension works fine. We'll likely encounter another dependency conflict in the future.
> 
> We need to install all extensions to calculate code generation coverage. If the problem occurs again, consider not installing the extension that uses the lower version of the dependency.

I feel the reliable way is to install, calculate and then uninstall each extension modules one by one and finally sum up the whole result from extension modules.

**Pull request merged**
