### PR TITLE
[Service Connector] `az spring connection`: Add deprecated message for `--deployment` breaking change

### PR DESCRIPTION
**Pull request by ChenTanyi**
**Related command**

`az spring connection`

**Description**

As https://github.com/Azure/azure-cli/issues/27371 said, we would delete the default value of --deployment. Therefore, we would like to add a deprecated message as warning for customer before the breaking change.
It displays as 
image

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Service Connector

**Comment by houk-ms** [comment]
Hi @kairu-ms, can you please help rerun the CI pipeline?

**Review by houk-ms — APPROVED** [review]

**Comment by ChenTanyi** [comment]
Hi @kairu-ms, it seems the pipeline is always canceled after 47mins. Is there anything wrong with the pipeline? Should we expect to rerun it until success?

**Review by kairu-ms — APPROVED** [review]

**Comment by kairu-ms** [comment]
> Hi @kairu-ms, it seems the pipeline is always canceled after 47mins. Is there anything wrong with the pipeline? Should we expect to rerun it until success?

You can simply rerun the failed task.

**Comment by kairu-ms** [comment]
@wangzelin007, could you help to check the ARM build task? It constantly failed

**Comment by ChenTanyi** [comment]
> > Hi @kairu-ms, it seems the pipeline is always canceled after 47mins. Is there anything wrong with the pipeline? Should we expect to rerun it until success?
> 
> You can simply rerun the failed task.

@kairu-ms can you help to rerun this failed task? as you can see above, I don't have the permission to rerun the pipeline

**Comment by wangzelin007** [comment]
> > > Hi @kairu-ms, it seems the pipeline is always canceled after 47mins. Is there anything wrong with the pipeline? Should we expect to rerun it until success?
> > 
> > 
> > You can simply rerun the failed task.
> 
> @kairu-ms can you help to rerun this failed task? as you can see above, I don't have the permission to rerun the pipeline. I think the problem of this task is that there are limited ARM64 agent, so most of the task can't find a agent to run with.

Reruning, we have enough machines, but the arm64 agent pool of 1es has this problem intermittently. 
Even though we submitted sev2 icm, this problem was never fundamentally solved. 😔

**Pull request merged**
