### PR TITLE
Fix bytes returned from hex fingerprint -o tsv

### PR DESCRIPTION
**Pull request by devigned**
The hex fingerprint of a Key Vault certificate returns as bytes in py3. This corrects that and returns a str as the method says it should.

```bash
$ az keyvault certificate show --vault-name testvaultdj -n testcert --query "x509ThumbprintHex" -o tsv
b'73863FFDAD3BA0E7C08BAEFBAD09F661298341C6'
```

After the fix
```bash
$ az keyvault certificate show --vault-name testvaultdj -n testcert --query "x509ThumbprintHex" -o tsv
73863FFDAD3BA0E7C08BAEFBAD09F661298341C6
```

### CODE REVIEW

**Comment by devigned** [comment]
damn... @troydai. I knew you were going to say that. I'll add a test.

**Comment by troydai** [comment]
I'm too predictable.

**Comment by derekbekoe** [comment]
Looks good but does it work with Python 2 and 3?
```
$ python
Python 2.7.10 (default, Feb  6 2017, 23:53:20) 
>>> bytes
<type 'str'>
>>> 
```

```
$ python3
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
>>> bytes
<class 'bytes'>
>>> 
```

**Comment by devigned** [comment]
@derekbekoe should be good. I'll prove with a test.
```
$ az keyvault certificate show --vault-name level1zb4tc -n sp-cert-level1 --query "x509ThumbprintHex" -o tsv
3EF38981A3EAE51D34E06C93D6D074216DD75323
(env27)
```

**Pull request merged**
