### PR TITLE
{IOT} Docs clarification for the IOT HUB endpoint create

### PR DESCRIPTION
**Pull request by navba-MSFT**
The examples description is confusing. So it needs to be clarified.

  - name: Add a new endpoint "S1" of type AzureStorageContainer to "MyIotHub" IoT Hub within the endpoint resource group "MyEndpointResourceGroup".
    text: |
        az iot hub routing-endpoint create --resource-group MyResourceGroup --hub-name MyIotHub \\
        --endpoint-name S1 --endpoint-type azurestoragecontainer --endpoint-resource-group RGS1 \\
        --endpoint-subscription-id {SubscriptionId} --connection-string {ConnectionString} \\
        --container-name {ContainerName} --batch-frequency 100 --chunk-size 100 \\
        --ff {iothub}-{partition}-{YYYY}-{MM}-{DD}-{HH}-{mm}

Docs link: https://learn.microsoft.com/en-us/cli/azure/iot/hub/routing-endpoint?view=azure-cli-latest#az-iot-hub-routing-endpoint-create

fixes Azure/azure-cli#26841

**Related command**

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by digimaun** [comment]
Just FYI, the `az iot hub routing-endpoint` command group is deprecated. The user should be pointed to the `az iot hub message-endpoint` and `az iot hub message-route` command groups in the [`azure-iot` extension](https://learn.microsoft.com/en-us/cli/azure/iot/hub/message-endpoint?view=azure-cli-latest).

Here is an MS learning doc link https://learn.microsoft.com/en-us/azure/iot-hub/how-to-routing-azure-cli?tabs=azurestorage

CC: @vilit1

**Review by zhoxing-ms — APPROVED** [review]

**Comment by navba-MSFT** [comment]
> Just FYI, the `az iot hub routing-endpoint` command group is deprecated. The user should be pointed to the `az iot hub message-endpoint` and `az iot hub message-route` command groups in the [`azure-iot` extension](https://learn.microsoft.com/en-us/cli/azure/iot/hub/message-endpoint?view=azure-cli-latest).
> 
> Here is an MS learning doc link https://learn.microsoft.com/en-us/azure/iot-hub/how-to-routing-azure-cli?tabs=azurestorage
> 
> CC: @vilit1

@digimaun Thanks for reviewing this. Your suggestions have been shared with the customer to use  `az iot hub message-endpoint` and `az iot hub message-route` command groups. 

This PR was to enhance the docs description for `az iot hub routing-endpoint`, Could you please review and let us know if that is good ? so that this PR can be merged.

**Comment by vilit1** [comment]
> This PR was to enhance the docs description for `az iot hub routing-endpoint`, Could you please review and let us know if that is good ? so that this PR can be merged.

I work on the same team as Paymaun and the changes look good to me. The pr can be merged.

**Review by digimaun — APPROVED** [review]

**Pull request merged**
