### PR TITLE
{Relay} Fix typos in azure relay

### PR DESCRIPTION
**Pull request by scottsauber**
**Description**
Fix typos

**Testing Guide**
N/A

**History Notes**
N/A

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Relay

**Comment by jsntcy** [comment]
@scottsauber, you cannot create PR to `master` branch directly, your PR should target to `dev` branch as we use it as our daily development branch.

**Review by jiasli — APPROVED** [review]

**Pull request merged**
