### PR TITLE
[Misc] homebrew: Generate shell completions for bash, fish, and zsh

### PR DESCRIPTION
**Pull request by maxbrunet**
**Related command**

Misc

**Description**

This switches to generate the completion with `register-python-argcomplete` directly, similarly to other Python tools like pipx in Homebrew.

The `az.completion.sh` script is not the actual completion, but runs `eval`: https://github.com/Azure/azure-cli/blob/3194af8f245f6d7e30ad70813c58eef779142482/src/azure-cli/az.completion.sh#L11

This also adds completion support for zsh and fish.

Initially raised at Homebrew/homebrew-core#192912, but it was pointed out that the source of truth is here.

**Testing Guide**

Follow https://github.com/Homebrew/homebrew-core/blob/9ce8743dc3ea3a130f80dc2c120e896c7eaf47a0/CONTRIBUTING.md#to-contribute-a-fix-to-the-foo-formula

**History Notes**

[Misc] homebrew: Generate shell completions for bash, fish, and zsh

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by bebound** [comment]
`formula_template.txt` is no used anymore.
Please update the formula in the Homebrew repo; our pipeline will then pick up and modify the new formula.

**Comment by p-linnane** [comment]
Hello @bebound 👋. I'm a maintainer for Homebrew. I'm seeking some clarity on your comment. Are you going to be using a method like `brew bump` or something to send us PR's? No longer using `formula_template.txt` is great and allows us to make modifications downstream without disrupting your CI. It would also make it much easier for us to maintain. Let me know your thoughts. Thanks!

**Comment by bebound** [comment]
Hi @p-linnane, formula generation logic is here: https://github.com/Azure/azure-cli/blob/c2f8ede19ae79486aba131f7fe87a3ec061c24b4/scripts/release/homebrew/docker/formula_generate.py#L120
It downloads the upstream formula, replaces the resource section, and makes some additional modifications.


@maxbrunet Your PR also bump Python to 3.12, which may break the `az extension` commands. See https://github.com/Azure/azure-cli/pull/29922

**Pull request closed without merging**
