### PR TITLE
[ACR] Add yml as a reserved task file type

### PR DESCRIPTION
**Pull request by ehotinger**
Add yml as a reserved task file type, which is often used on Windows.

/cc @djyou @northtyphoon @ankurkhemani 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by ehotinger** [comment]
@troydai @tjprescott could we merge this today if possible, it was left out as a part of https://github.com/Azure/azure-cli/pull/7255 for Ignite.

**Comment by troydai** [comment]
The cut off date was yesterday.

**Comment by ehotinger** [comment]
Oh ok, np then. NBD.

**Comment by troydai** [comment]
The `dev` branch is open for the next release. I will merge this PR shortly.

**Pull request merged**
