### PR TITLE
Turn off CI Code Coverage

### LINKED ISSUE #3895: [Test] CI Output cluttered with Coverage information
Recently I have noticed that when a CI build fails, the output is filled with pages and pages of code coverage statistics.  These are not in any way helpful as they are never the cause of the build failure. This was not the behavior until recently so we should revert whatever change introduced this along with #3878.

### PR DESCRIPTION
**Pull request by tjprescott**
Close #3895.

### CODE REVIEW

**Comment by derekbekoe** [comment]
😄 that branch name... 😆

**Comment by troydai** [comment]
I have a fix to suppress the output of code coverage report. This is entirely turned off the code coverage, which we should not do.

**Comment by tjprescott** [comment]
@troydai I agree. Wanted to see if this was a quick fix.  Looking forward to your PR.

**Comment by troydai** [comment]
Preview (it will look like this):
screen shot 2017-07-05 at 10 37 51 am

**Comment by tjprescott** [comment]
Looks good to me... though it's funny that it's uploading to S3 instead of Azure. :laugh:

**Pull request closed without merging**
