### PR TITLE
[Compute] `az vmss create`: Change `--orchestration-mode` to support only `uniform` for old profile

### PR DESCRIPTION
**Pull request by Jing-song**
**Related command**

`az vmss create`

**Description**

`flexible` is not supported for all versions before `2020-12-01`, so change these versions to only support `uniform`
close https://github.com/Azure/azure-cli/issues/27806

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Compute

**Comment by zhoxing-ms** [comment]
@yanzhudd Could you please help review this PR?

**Comment by yanzhudd** [comment]
Let me confirm with you if there is any `checks` in tests to check the actual value sent to service side (actual output value)?

**Comment by Jing-song** [comment]
> Let me confirm with you if there is any `checks` in tests to check the actual value sent to service side (actual output value)?

In older versions it showed up in the response, but since it's not in the SDK we can't see it in the output.

**Review by yanzhudd — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
