### PR TITLE
[App Service] BREAKING CHANGE: Remove python|3.6, php|7.3, ruby|2.5 runtimes; Add python|3.9, php|8.0, ruby|2.7 runtimes

### PR DESCRIPTION
**Pull request by StrawnSC**
**Description**

Removes support for the `python|3.6` (linux and windows) and `php|7.3` (windows) runtimes and adds support for the `python|3.9` runtime (linux). This affects the web apps that can be created with `az webapp up` and `az webapp create` as well as the output of the `az webapp list-runtimes` command. 

**Testing Guide**

`azdev test --live test_webapp_up_commands`
`azdev test test_webapp_commands`

**History Notes**

[App Service]  BREAKING CHANGE: az webapp up: Remove support for the python|3.6 (linux and windows), ruby|2.5 (linux), and php|7.3 (windows) runtimes. Add support for the python|3.9 runtime (linux), php|8.0 (linux), and ruby|2.7 (linux)

[App Service]  BREAKING CHANGE: az webapp create: Remove support for the python|3.6 (linux and windows), ruby|2.5 (linux), and php|7.3 (windows) runtimes. Add support for the python|3.9 runtime (linux), php|8.0 (linux), and ruby|2.7 (linux)

[App Service] BREAKING CHANGE: az functionapp create: Remove python 3.6 support 

[App Service] az webapp list-runtimes: Remove support for the python|3.6 (linux and windows), ruby|2.5 (linux), and php|7.3 (windows) runtimes. Add support for the python|3.9 runtime (linux), php|8.0 (linux), and ruby|2.7 (linux)

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by panchagnula** [comment]
@StrawnSC is this change for webapps only or do we need to do the same for function apps as well?

**Comment by panchagnula** [comment]
Also, yaml files for up tests need not be checked in - just delete these files since these tests run live only.

**Comment by StrawnSC** [comment]
> @StrawnSC is this change for webapps only or do we need to do the same for function apps as well?

I'm not sure -- I'll look into that

**Comment by StrawnSC** [comment]
converting to a draft while I figure out function apps and make sure we aren't missing any other web apps stack changes

**Comment by yonzhan** [comment]
App Service

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
