### PR TITLE
check doc generation for all the profiles.

### PR DESCRIPTION
**Pull request by daxianji007**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by troydai** [comment]
@williexu

**Comment by troydai** [comment]
CI failed.

**Comment by williexu** [comment]
@daxianji007 can you address the CI failure?

**Comment by troydai** [comment]
Where are we now?

**Comment by troydai** [comment]
I'm closing this PR for lack of activity.

**Pull request closed without merging**
