### PR TITLE
[webapp] add local context scope for `az connect`

### PR DESCRIPTION
**Pull request by qianwens**
**Description**  

Add webapp local context scope for `az connect` 

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
webapp

**Comment by qwordy** [comment]
Could you share some context?

**Review by qwordy — CHANGES_REQUESTED** [review]
Add a description

**Comment by qianwens** [comment]
This is a draft PR which won't be merged.

**Comment by qianwens** [comment]
> Add a description

done

**Comment by qwordy** [comment]
Why remove cupertino and add connect? You want to rename cupertino to connect? What is connect? 
```
az cupertino -h
az: 'cupertino' is not in the 'az' command group. See 'az --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
az connect -h
az: 'connect' is not in the 'az' command group. See 'az --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview
```

**Review by qwordy — APPROVED** [review]

**Comment by arrownj** [comment]
Close this PR as it is only for testing purpose.

**Pull request closed without merging**
