### PR TITLE
[Network] `az network private-endpoint-connection`: Add Provider Microsoft.Monitor/Accounts

### PR DESCRIPTION
**Pull request by GokulPrasad-Work**
**Related command**
az network vnet create

**Description**
Added support to manage Private Endpoint of Microsoft.Monitor accounts with Azure CLI.

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Network

**Review by necusjz — APPROVED** [review]

**Comment by GokulPrasad-Work** [comment]
Hello, How do we track the release for this change?

**Comment by yonzhan** [comment]
https://github.com/Azure/azure-cli/milestone/127

**Comment by GokulPrasad-Work** [comment]
Thanks. Is there a way for us to take the intermediate version and install it in the local machine to run the new commands added?

**Comment by necusjz** [comment]
> Thanks. Is there a way for us to take the intermediate version and install it in the local machine to run the new commands added?

You can leverage https://github.com/Azure/azure-cli/blob/dev/doc/try_new_features_before_release.md in the current PR.

**Pull request merged**
