### PR TITLE
[EventHubs]Add cmdlets for schema registry

### PR DESCRIPTION
**Pull request by damodaravadhani**
**Description**
Add cmdlets to support schema registry for eventhubs.

**Testing Guide**
az eventhubs namespace schema-registry create -g {resourcegroup} --namespace-name {namespacename} --name s2 --schema-compatibility Forward --schema-type Avro 

**History Notes**

[EventHubs] `az eventhubs namespace schema-registry`: Add cmdlets for schema registry

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
EventHubs

**Comment by damodaravadhani** [comment]
Hello @evelyn-ys , could you please help figure out why the automation test pipelines are failing, it is pointing to a test in IOT Hub that is not out service. Thanks.

**Comment by evelyn-ys** [comment]
As you have bumped the API version for eventhubs, then all module tests containing eventhubs commands should be re-recorded. IOT is just one of such tests.

**Comment by damodaravadhani** [comment]
@evelyn-ys , these pipelines were passing until the last commit. I pushed in a small change, and for some reason it shows the tests in hybrid that I have already pushed recordings for as failed. And it points to a few tests in latest that do not use eventhubs at all. Could you please help me figure out what's wrong.

**Comment by damodaravadhani** [comment]
image
It points to test in back up that doesn't use eventhubs, could you please help me find why is this the case ?

**Comment by evelyn-ys** [comment]
@zhoxing-ms Can you help take a look at `iot` and `backup` failures?

**Comment by zhoxing-ms** [comment]
> self = <azure.cli.testsdk.base.ExecutionResult object at 0x7f597e0c99e8>
cli_ctx = <azure.cli.core.mock.DummyCli object at 0x7f597f63fef0>
command = 'storage account show-connection-string -n clitest000003 -g clitest.rg000001'
expect_failure = False
......
except CannotOverwriteExistingCassetteException as ex:
>           raise AssertionError(ex)
E           AssertionError: Can't overwrite existing cassette ('/home/vsts/work/1/s/src/azure-cli/azure/cli/command_modules/backup/tests/latest/recordings/test_afs_backup_policy.yaml') in your current record mode ('once').
E           No match for the request (<Request (GET) [https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.Storage/storageAccounts/clitest000003?api-version=2021-09-01>](https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.Storage/storageAccounts/clitest000003?api-version=2021-09-01%3E)) was found.
E           Found 47 similar requests with 2 different matcher(s) :




The failure of these CI may be caused by the change of command `storage account show-connection-string`

For Iot related tests, this command is called by `_get_azurestorage_connectionstring()` method
For Backup related tests, this command is called by `@FileSharePreparer()`

@evelyn-ys I guess this problem was introduced by PR #22280, could you help check it?

**Comment by damodaravadhani** [comment]
@evelyn-ys , can we have a review on this and merge this if there are no concerns further ? Thanks.

**Review by evelyn-ys — APPROVED** [review]

**Review by necusjz — APPROVED** [review]

**Review by kairu-ms — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
