### PR TITLE
[AKS] `az aks create/update`: Add support for KEDA workload auto-scaler

### PR DESCRIPTION
**Pull request by FumingZhang**
**Related command**

**Description**

[AKS] `az aks create/update`: Add support for KEDA workload auto-scaler

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by FumingZhang** [comment]
Live test [failed](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=66500712&view=logs&j=b162b355-d59d-5864-ce0f-0a70f12dd28b&t=dc59ccd1-231f-538b-777f-33a592c7ca57&l=664) due to some error on rp side.

**Comment by yonzhan** [comment]
AKS

**Review by v-shenoy — APPROVED** [review]
Looks good. We also need to add some test yamls, right?

**Comment by zhoxing-ms** [comment]
@v-shenoy In fact, it is not necessary to add yaml files for the `@live_only` tests.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
