### PR TITLE
[Draft]Azurestack aks

### PR DESCRIPTION
**Pull request by hhz1992**
**Description**  

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Azurestack aks

**Comment by yungezz** [comment]
hi @hhz1992 what's latest status of this PR? Is this ready to review? thanks.

**Comment by arrownj** [comment]
Hi @hhz1992 , please ping us to merge when this PR is ready. Thanks

**Comment by arrownj** [comment]
Hi @hhz1992 , we will close this PR first as there is no update and feedback for a long time. You can reopen it or submit a new one if you actually need to change. Thanks

**Pull request closed without merging**
