### PR TITLE
[BatchAI] BatchAI module Knack conversion

### PR DESCRIPTION
**Pull request by tjprescott**
Implements #4925. Tests to be re-enabled in future PR.

### CODE REVIEW

**Comment by AlexanderYukhanov** [comment]
The changes look fine to me. Is it already runnable, can I test it?

**Comment by derekbekoe** [comment]
@AlexanderYukhanov You should be able to visit https://prompt.ws/r/Azure/azure-cli/5120 to try it out! It takes a few mins to load your instance.

**Comment by derekbekoe** [comment]
```
$ az batchai cluster create -h

Command
    az batchai cluster create: Create a cluster.

Arguments
    --name -n        [Required]: Name of the cluster.
    --resource-group [Required]
```

RG has no description.

**Comment by AlexanderYukhanov** [comment]
the help string for resource-group is missing from every command

**Comment by AlexanderYukhanov** [comment]
and '-g' now doesn't work

**Comment by tjprescott** [comment]
Thanks @AlexanderYukhanov, I fixed the issue with resource group.

**Pull request merged**
