### PR TITLE
[HDInsight] - Change OMS group name and Refine auto completers

### PR DESCRIPTION
**Pull request by idear1203**
- Change command group name from omsto monitor
  - Change all instances of "Operations Management Suite (OMS)" in descriptions to "Azure Monitor logs integration”
  - Autocomplete workspace id and key (remove workspace key parameter)

- ESP parameters updates
  -	cluster-admin-account completer
  -	cluster-users-group-dns completer
  -	cluster-users-group-dns parameter is required when --esp presentes

- Some other changes:
  -	Make the "--http-password -p" a required parameter
  -	Add time out for all existing argument auto-completers.
  -	Add time out for transforming recourse name to resource id.
  -	Allow auto-completers to select resources from any resource group. It can be a different resource group that '-g' specifies.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by marstr** [comment]
Howdy @idear1203, I've gone ahead and merged your changes with the most recent version of dev to fix some conflicts for you. Other than having your local repository need a pull there should be no further action needed by you.

**Comment by idear1203** [comment]
@marstr Thank you!!

**Comment by idear1203** [comment]
@tjprescott please don't merge the PR. We will do a update on `History.rst`

**Comment by tjprescott** [comment]
@idear1203 please let us know when you are happy with your history entry and would like this merged.

**Comment by idear1203** [comment]
Hi @tjprescott, we have updated the history. Please help merge the PR. Thank you!

**Pull request merged**
