### PR TITLE
{CI} Add CI trigger pipeline yaml for docs reference

### PR DESCRIPTION
**Pull request by xmdanni**
**Related command**

No, just added a pipeline yaml for docs team.

**Description**

Add a CI trigger pipeline yaml for docs reference, to replace existing webhook, and make dev branch preview page build become automated.

**Testing Guide**

**History Notes**

No.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by jsntcy** [comment]
@wangzelin007, @allyw, please help review if there is any side effect, especially security concern for this change.

**Comment by wangzelin007** [comment]
> Just made a minor update, ready for review now, thanks!

Hi @xmdanni 
Can you provide the link of Content CI/ReferenceAutomation？

**Review by wangzelin007 — DISMISSED** [review]

**Review by wangzelin007 — APPROVED** [review]

**Pull request merged**
