### PR TITLE
[ARM] `az bicep install`: Add a new parameter `--target-platform/-t` to specify the running platform of Bicep CLI

### PR DESCRIPTION
**Pull request by shenglol**
**Description**
Our Bicep CLI runtime detection logic does work for some Linux users. For example, installing bicep on a ubuntu machine that contains`/lib/ld-musl-x86_64.so.1` will download the musl Linux version of Bicep CLI. The PR addresses the issue by adding a new parameter `--target-platfrom/-t` to allow users to specify the target running platform of Bicep CLI(fixes https://github.com/Azure/bicep/issues/5040).

The PR also fixes output coloring when bicep produces both warnings and errors (fixes https://github.com/Azure/bicep/issues/4556).

**Testing Guide**
```
az bicep install -t linux-x64
```
```
az bicep upgrade -t linux-musl-x64
```

**History Notes**

[ARM] `az bicep install`: Add a new parameter `--target-platform/-t` to specify the running platform of Bicep CLI
[ARM] `az bicep upgrade`: Add a new parameter `--target-platform/-t` to specify the running platform of Bicep CLI

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
ARM

**Comment by zhoxing-ms** [comment]
Could you add some tests for this change?

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
