### PR TITLE
[ACR] Updates for 2017-03-01 api-version

### PR DESCRIPTION
**Pull request by djyou**
1. New ApiVersion 2017-03-01.
2. Support two passwords for admin login credentials.
3. Renew credential now requires an argument to specify which password to regenerate.
4. Add SKU as a required property when creating registries.
5. General improvement.

Fixes https://github.com/Azure/azure-cli/issues/1889

### CODE REVIEW

**Comment by djyou** [comment]
@tjprescott Regarding https://github.com/Azure/azure-cli/issues/1889

What is the recommended way to default location now? For example, if I set the default location by `az configure --defaults location=westus` but my resource group is in `eastus`, where should the resource be created when I didn't provide a location in `az acr create` command?

Another question regarding default `deployment_name`. Considering each resource group allows a maximum of 800 deployments, wouldn't `generate_deployment_name` [here](https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/azure/cli/core/commands/validators.py#L38) be a concern when a large number of resources are deployed/created?

**Comment by tjprescott** [comment]
@djyou 

1) If you configured a default resource group, it will use that (correct me if I'm wrong @yugangw-msft). If you didn't configure a default, then  it is up to the logic of your command to decide. There's a stock validator in `azure.cli.core.commands .validators` called `get_location_from_resource_group` which will do just that. That is the most common thing to do.

2) We've not run into any instances of people hitting their quotas on deployments. Is there a particular place where you envision potentially exceeding the quota?

**Comment by djyou** [comment]
Thanks. `appservice plan create` defaults to the resource group's location when a location is not provided, even if I also set a default location that is different from the resource group's location. I have made the similar change to fix https://github.com/Azure/azure-cli/issues/1889.

Even our own CI exceeds the limit.  Our CLI implementation uses resource provider's name plus a small number as index to avoid deployment conflict but a deployment can also be overridden when it is completed. If we were using unique names the workaround was to clear deployments in a resource group, or use a different resource group, etc.

**Comment by SajayAntony** [comment]
:shipit:

**Pull request merged**
