### PR TITLE
[IoTCentral] az iot central app: Remove preview warning since it is already GA

### PR DESCRIPTION
**Pull request by poanchen**
**Description**  
We moved from az iotcentral to az iot central and forgot to remove the preview tag for the az cli command for IoTCentral. Removing the preview tag so that user will not see the warning stated that it is preview although we already GAed.

**Testing Guide**  

**History Notes**  

[IoTCentral] CLI: Removing preview warning since it is already GAed

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
IoTCentral

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@poanchen Please refer to the guidance to modify the PR title, guidance link: [link](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests)

> [Recommendation] Use the right verb with present-tense in base form and capitalized first letter to describe what is done

**Comment by poanchen** [comment]
R we good? Or I still need to change my PR title?

**Comment by zhoxing-ms** [comment]
> R we good? Or I still need to change my PR title?

No, I will help you modify your PR title to pass the CI check of PR title

**Review by digimaun — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
Find the reason why the PR title check failed: there is an extra space at the beginning in this PR title

**Pull request merged**
