### PR TITLE
{Search} Upgrade to use the latest (8.0.0) azure-mgmt-search python sdk

### PR DESCRIPTION
**Pull request by huangbolun**
**Description**
- Upgrade 'az search' to use the latest search-mgmt python sdk, introducing:
   - CRUD of public IP rules to the search service;
   - CRUD of private endpoint access to the search service;
   - CRUD of private link resources in the search service;
   - Configure MSI in the search service;

- Unittest/Integration Tests for the above commands & operations;
- Add Microsoft.Search/searchServices to the 'az network private-link-resource list' command;

**Testing Guide**
https://github.com/Azure/azure-cli/blob/dev/doc/authoring_tests.md#authoring-tests

**History Notes**
- [Search] `az search create`: Create search service with IP rules, public endpoint access and/or msi.
- [Search] `az search update`: Update search service with IP rules, public endpoint access and/or msi.
- [Search] `az search private-endpoint-connection`: Manage private endpoint connection to a search service.
- [Search] `az search shared-private-link-resource`: Manage shared private link resources in a search service.
- [Search] `az search private-link-resource`: List available private link resources in a search service.
- [Search] `az network private-link-resource list`: Add Microsoft.Search/searchServices to the supported provider list.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Search

**Comment by huangbolun** [comment]
@kairu-ms, how do I onboard module upgrade onto the Azure CLI release notes: https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md? We would like to advertise this az search upgrade to end customers.

**Comment by kairu-ms** [comment]
> @kairu-ms Kai Ru FTE, how do I onboard module upgrade onto the Azure CLI release notes: https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md? We would like to advertise this az search upgrade to end customers.

The "History Notes" of your PR description will be added into release notes.

**Review by kairu-ms — CHANGES_REQUESTED** [review]

**Comment by huangbolun** [comment]
> > @kairu-ms Kai Ru FTE, how do I onboard module upgrade onto the Azure CLI release notes: https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md? We would like to advertise this az search upgrade to end customers.
> 
> The "History Notes" of your PR description will be added into release notes.

@kairu-ms, could you review my **History Notes** section and see if it looks good?

**Comment by kairu-ms** [comment]
> > > @kairu-ms Kai Ru FTE, how do I onboard module upgrade onto the Azure CLI release notes: https://github.com/MicrosoftDocs/azure-docs-cli/blob/master/docs-ref-conceptual/release-notes-azure-cli.md? We would like to advertise this az search upgrade to end customers.
> > 
> > 
> > The "History Notes" of your PR description will be added into release notes.
> 
> @kairu-ms, could you review my **History Notes** section and see if it looks good?

I've updated the History Notes.

**Review by kairu-ms — APPROVED** [review]

**Review by arv100kri — APPROVED** [review]

**Comment by huangbolun** [comment]
@kairu-ms, my teammates have reviewed and approved. Could you merge the PR? Thanks.

**Comment by huangbolun** [comment]
@jsntcy, @msyyc : as code owners, could you review the PR and unblock the merge? Thanks.

**Review by jsntcy — APPROVED** [review]

**Review by msyyc — APPROVED** [review]

**Pull request merged**
