### PR TITLE
[Core] Allow opt-in retry of MSI auth on connection or timeout error

### PR DESCRIPTION
**Pull request by doubleyewdee**
**Related command**
Many commands utilize the MSI wrapper.

**Description**
This PR provides environment variables to enable retrying retryable errors when performing MSI authentication. Three variables are provided:
- $AZURE_CLI_MSI_RETRY_ENABLED (default off)
- $AZURE_CLI_MSI_RETRY_COUNT (default 3)
- $AZURE_CLI_MSI_RETRY_DELAY (default 15)

This is desirable because we have observed many issues where we use the az CLI within ACI instances to perform operations which fail due to seemingly transient network issues. We believe retrying on (e.g.) 'broken pipe' errors or timeouts is both safe and will ensure fewer deployment fails. We have observed this dozens of times in the last two to three weeks and believe many other teams are negatively impacted.

**Testing Guide**
Unclear -- this code's unit tests all override the class being modified. However, this code should be easily testable by simply setting $AZURE_CLI_MSI_RETRY_ENABLED to `true` and utilizing any commands which require MSI auth.

**History Notes**
[Core] Add environment variables to control attempts to retry MSI authentication. $AZURE_CLI_MSI_RETRY_ENABLED = 'true' enables retries, and $AZURE_CLI_MSI_RETRY_COUNT and $AZURE_CLI_MSI_RETRY_DELAY control the number of retries, and seconds between retries respectively.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Core

**Comment by jiasli** [comment]
We plan to migrate Managed Identity's implementation from `msrestazure` to MSAL (https://github.com/Azure/azure-cli/issues/25860). You may submit a feature request at https://github.com/AzureAD/microsoft-authentication-library-for-python.

**Comment by doubleyewdee** [comment]
@jiasli what's the timeframe for the ADAL migration? We're having pretty widespread issues today with (e.g.) broken pipe errors across many pipelines that force manual retries/user intervention, and I believe that this is widespread. The item you linked is open and from several months ago. I am concerned that a migration timeline (along with adding resilience in the ADAL Python library) will lead to significant delays in addressing this behavior.

**Comment by jiasli** [comment]
@doubleyewdee, we no longer rely on ADAL and will drop it soon.

Even if we migrate to MSAL for managed identity authentication, if MSAL doesn't add the retry mechanism, Azure CLI won't have it either.

If this issue is urgent, I would recommend contacting ACI service team and let them investigate the network issue. Managed Identity should be reliable. It is not really the client's responsibility to retry. cc @rayluo

**Comment by jiasli** [comment]
> I would push back a little that clients shouldn't also participate in retries. It's not actually possible to have a 100% reliable network (either client or server side), and retries are routinely valuable for tail reliability

Sorry I didn't make it clear. I don't mean a client shouldn't retry, but the client shouldn't take the main responsibility.

> Back to my question, what's the timeline for the MSAL library migration?

We are working on https://github.com/Azure/azure-cli/issues/25860, but there is currently so specific ETA yet. I will bring this ask to our Product Managers.

> When should we be on the lookout for behavior here and whether we might want to ask for retry options in the MSAL lib?

My personal opinion is that MSAL lib is a better place to add the retry logic, as other tools using MSAL can benefit from it.

**Comment by doubleyewdee** [comment]
@jisali thanks for the updates and linked item! we'll wait for the MSAL migration and follow the items you've linked.

**Comment by rayluo** [comment]
> My personal opinion is that MSAL lib is a better place to add the retry logic, as other tools using MSAL can benefit from it.

For the record, the default retry logic does already happen in MSAL lib. It is just that "how (many times) to retry" configuration is owned by calling app, because there is unlikely to be a one-size-fits-all configuration here. For that reason, MSAL also exposes an API to customize that retry behavior, it is just that the API is not in the form of `retry_count` (or `retry_delay`, for that matter).

**Comment by doubleyewdee** [comment]
@rayluo I'd like to get this exposed in a manner roughly similar to what this PR suggested (not clear if delay/etc need to be supported vs. simply supplying a count) but will need to wait for the actual az MSAL migration it seems.

My team is going to attempt to wrap all our `az` calls with retries in the interim, but we're being bitten very badly here by some combination of Azure-owned things (e.g. in certain regions we have 10%+ failure rates here at times) so I think we need a holistic solution for both our 1P and 3P customers that is superior to what's on offer today.

**Pull request closed without merging**
