### PR TITLE
Decorate commands that support --no-wait with g.wait_command('wait')

### PR DESCRIPTION
**Pull request by BrianBlum**
There are no customer facing changes.
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by tjprescott** [comment]
Adding `wait` commands would be a customer-facing change :)

**Comment by tjprescott** [comment]
@BrianBlum looks like you need to add help text for your three new wait commands :)

**Comment by BrianBlum** [comment]
@tjprescott The wait command on streaming-locator should not have been there. None of the streaming-locator commands support no-wait so I removed it.
Added help for the other new wait commands.

**Comment by BrianBlum** [comment]
@tjprescott Thanks Travis

**Pull request merged**
