### PR TITLE
[AKS] `aks mesh upgrade rollback/complete`: Add `--yes` parameter to support not prompting the users to confirm the operation

### PR DESCRIPTION
**Pull request by deveshdama**
**Related command**
`az aks mesh upgrade rollback -g myResourceGroup -n myCluster --revision asm-1-20`
`az aks mesh upgrade complete -g myResourceGroup -n myCluster`

**Description**
This change allows customers to suppress warnings while using `az aks mesh upgrade rollback` and `az aks mesh upgrade complete` commands. This is particularly helpful with automation of service mesh upgrade revisions.

**Testing Guide**
`az aks mesh upgrade rollback -g myResourceGroup -n myCluster --revision asm-1-20 --yes`
`az aks mesh upgrade complete -g myResourceGroup -n myCluster --yes`
both the above commands should not prompt the users to confirm the operation.

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Review by SanyaKochhar — APPROVED** [review]

**Comment by yonzhan** [comment]
Please fix CI issues

**Pull request closed without merging**
