### PR TITLE
[Security] - Add secure score commands

### PR DESCRIPTION
**Pull request by giromm2ms**
**Description**
Added Security Center's Secure Score related CLIs  

**Testing Guide**

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Security

**Review by haroldrandom — CHANGES_REQUESTED** [review]
Could you resolve the CI errors first?

**Comment by giromm2ms** [comment]
> Could you resolve the CI errors first?

Hi @haroldrandom ,
Can you review? 
I couldn't find the failed tests in Security module.

**Comment by giromm2ms** [comment]
> Could you resolve the CI errors first?

All CI errors fixed.
Waiting for final approval

**Review by haroldrandom — APPROVED** [review]

**Pull request merged**
