### PR TITLE
[AKS] `az aks create`: Add new parameter `--network-dataplane` to support creating Cilium clusters

### PR DESCRIPTION
**Pull request by wedaly**
**Related command**
`az aks create`

**Description**
Add the `--network-dataplane` flag to `az aks create` so users can enable [Azure CNI powered by Cilium](https://learn.microsoft.com/en-us/azure/aks/azure-cni-powered-by-cilium).

**Testing Guide**
`az aks create -n testcluster -g testgroup--network-plugin=azure --network-dataplane=cilium --network-plugin-mode=overlay`

**History Notes**

[AKS] `az aks create`: Add new parameter `--network-dataplane` to support creating Cilium clusters

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by wedaly** [comment]
Depends on changes in these PRs:
* https://github.com/Azure/azure-cli/pull/25944
* https://github.com/Azure/azure-cli/pull/25932

Will keep this PR as draft until those are merged

**Comment by wedaly** [comment]
Related PR in the azure-cli-extensions repo for AKS 2023-02-02preview API: https://github.com/Azure/azure-cli-extensions/pull/6064

**Comment by yonzhan** [comment]
AKS

**Comment by wedaly** [comment]
Rebased to include latest changes from https://github.com/Azure/azure-cli/pull/25932

**Comment by yonzhan** [comment]
Please resolve the conflicting files.

**Comment by wedaly** [comment]
Rebased onto origin/dev and resolved conflicts

**Review by FumingZhang — APPROVED** [review]
LGTM

Queued a [live test pipeline](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=70930260&view=results) to verify the change.

**Comment by FumingZhang** [comment]
And for the CI failure about PR title, it suggested to change the title to 
[AKS] `az aks create`: Add `--network-dataplane` to support creating Cilium clusters

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
