### PR TITLE
CI: Check package dependencies aren’t broken for all modules

### PR DESCRIPTION
**Pull request by derekbekoe**

### CODE REVIEW

**Comment by derekbekoe** [comment]
Thanks for review.

So this would work except for the fact that we currently have some dependency mismatches which causes the PR to fail CI!
```
+ pip check
azure-mgmt-trafficmanager 0.30.0rc6 has requirement azure-common[autorest]==1.1.4, but you have azure-common 1.1.5.
azure-mgmt-redis 1.0.0 has requirement azure-common[autorest]==1.1.4, but you have azure-common 1.1.5.
azure-mgmt-keyvault 0.30.0 has requirement azure-common[autorest]==1.1.4, but you have azure-common 1.1.5.
azure-mgmt-iothub 0.2.1 has requirement azure-common[autorest]==1.1.4, but you have azure-common 1.1.5.
azure-mgmt-dns 1.0.0 has requirement azure-common[autorest]==1.1.4, but you have azure-common 1.1.5.
azure-mgmt-authorization 0.30.0rc6 has requirement azure-common[autorest]==1.1.4, but you have azure-common 1.1.5.
azure-keyvault 0.1.0 has requirement azure-common[autorest]==1.1.4, but you have azure-common 1.1.5.
azure-graphrbac 0.30.0rc6 has requirement azure-common[autorest]==1.1.4, but you have azure-common 1.1.5.
```

I'll extend this PR to support some allowed dependency incompatibilities.

**Comment by derekbekoe** [comment]
@tjprescott can you take another look?

**Comment by derekbekoe** [comment]
@tjprescott yep!
Which is why these dependency conflicts can cause issues.
In this case though, the change was backwards compatible.

**Comment by tjprescott** [comment]
LGTM.

**Pull request merged**
