### PR TITLE
[AKS] add ephemeral os functionality

### PR DESCRIPTION
**Pull request by alexeldeib**
**Description**  

adds ephemeral os functionality for aks, port of https://github.com/Azure/azure-cli-extensions/pull/2344 from the extension

**Testing Guide**  

samples included in PR

**History Notes** 

[AKS] add ephemeral os functionality
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by alexeldeib** [comment]
last failure seems unrelated?

**Review by arrownj — APPROVED** [review]
LGTM

**Comment by alexeldeib** [comment]
@arrownj seems like the ci agent is trying to use make on windows and failing? 

```
File "setup.py", line 159, in run
      raise Exception("ERROR: The 'make' utility is missing from PATH")
  Exception: ERROR: The 'make' utility is missing from PATH
```

also looks like it's missing openssl? 

this pr is code complete for me, just wanted to make sure you weren't waiting.

**Pull request merged**
