### PR TITLE
[DigitalTwins] Adds support for private endpoint connections to DigitalTwins

### PR DESCRIPTION
**Pull request by c-ryan-k**
**Description**
Adds Azure DigitalTwins provider namespace to `az network` private-endpoint-connection and private-link-resources commands

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
DigitalTwins

**Review by kairu-ms — APPROVED** [review]

**Review by msyyc — APPROVED** [review]

**Comment by msyyc** [comment]
@c-ryan-k  Should the PR be merged by the end of S182(2021/02/03)?

**Comment by c-ryan-k** [comment]
@msyyc That would be great, thanks!

**Pull request merged**
