### PR TITLE
Enabled the restore test again 

### PR DESCRIPTION
**Pull request by akamath46297**
**Description of PR (Mandatory)**  
Added the restore test back with predictability 

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S168

**Comment by yonzhan** [comment]
add to S170

**Comment by yonzhan** [comment]
add to S171

**Comment by Juliehzl** [comment]
@akamath46297  Thanks for the test update. Can you resolve all conflicts and take a look at CI failures?

**Comment by yonzhan** [comment]
add to S172

**Pull request closed without merging**
