### PR TITLE
[FunctionAPP] `az functionapp plan`: Update the max_val of `--max-burst` to 100

### LINKED ISSUE #21225: Incorrect max-burst limit with az functionapp plan
## Describe the bug
[Documentation for the EastUS2 region my Windows EP3 Azure Function Premium Plan is running in](https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan?tabs=portal#region-max-scale-out) says that I should be able to set the maximum instances up to 100. The Azure Portal allows me to do this successfully. When I try to use the Azure CLI to set any value about 20, however, it fails every time.

**Command Name**
`az functionapp plan update`

**Errors:**
```
Usage error: --max-burst is expected to be between 0 and 20 (inclusive)

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az functionapp plan update --name {} --resource-group {} --max-burst {}`

## Expected Behavior
The command should allow values above 20 up to the actual limit for the location.

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.8.9
Installer: MSI

azure-cli 2.29.1 *

Extensions:
application-insights 0.1.14
cosmosdb-preview 0.10.0
front-door 1.0.16

```

### PR DESCRIPTION
**Pull request by navba-MSFT**
As per below article for PremiumPlan Max scale out is 100. 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-premium-plan?tabs=portal#region-max-scale-out

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change.
[Component Name 2] `az command b`: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

Fixes #21225

### CODE REVIEW

**Comment by yonzhan** [comment]
FunctionAPP

**Review by wangzelin007 — APPROVED** [review]

**Comment by navba-MSFT** [comment]
@panchagnula @jsntcy @zhoxing-ms Could you please review and approve this once you get a chance ?

**Comment by navba-MSFT** [comment]
Fixes #21225

**Review by zhoxing-ms — APPROVED** [review]

**Comment by panchagnula** [comment]
@navba-MSFT the limit is 20 for Linux, so this change is incorrect.

**Pull request merged**
