### PR TITLE
{AKS} Add error message for nodepool add w/o os type for Windows SKU's

### PR DESCRIPTION
**Pull request by SaurabhSharma-MSFT**
**Related command**
`az aks nodepool add -g {} --cluster-name {} --os-sku Windows2019 -n {} (w/o --os-type Windows)`

**Description**
Add error message for nodepool add w/o os type for Windows SKU's
`az aks nodepool add -g {} --cluster-name {} --os-sku Windows2019 -n {} (w/o --os-type Windows)`
Fixes GitHub Issue [24966](https://github.com/Azure/azure-cli/issues/24966)

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by zhoxing-ms** [comment]
@SaurabhSharma-MSFT Could you please fix the code style issues?

**Comment by zhoxing-ms** [comment]
Please note that since we will launch the release of this sprint the day after tomorrow. If you cannot address all the comments by tomorrow, we will have to postpone the release of this PR to the next sprint (02-07)

**Comment by zhoxing-ms** [comment]
> Running flake8 on modules...
ERROR: /mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py:510:59: W291 trailing whitespace
/mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py:512:21: E123 closing bracket does not match indentation of opening bracket's line
/mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py:510:59: W291 trailing whitespace
/mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/acs/agentpool_decorator.py:512:21: E123 closing bracket does not match indentation of opening bracket's line
2     E123 closing bracket does not match indentation of opening bracket's line
2     W291 trailing whitespace

Please fix these CI issues

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
