### PR TITLE
[AKS] az aks create: Add support for Windows

### PR DESCRIPTION
**Pull request by AbelHu**
**Description**  
This will allow cx to create a k8s cluster and then add Windows agent pools without aks-preview.

**Testing Guide**  
AZURE_CLI_TEST_DEV_SP_NAME=1f3a7c5e-1812-4aa7-bffe-b5ef651cbab2 AZURE_CLI_TEST_DEV_SP_PASSWORD='6997d05f-3cae-4bcc-95f0-b74cf5444860' CAZURE_CLI_TEST_MODULES=acs azdev test test_aks_create_with_windows --discover --live

**History Notes**  
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yungezz** [comment]
HI @arrownj could you pls review? thanks

**Comment by AbelHu** [comment]
Thanks for the help, @arrownj . Please do not merge this. I will update add-node-pool with setting default node vm size for windows but not raise an error.

**Comment by AbelHu** [comment]
Updated src\azure-cli\azure\cli\command_modules\acs\custom.py and added `add/delete windows node pool' in test_aks_commands.py
Change Line 2826
```
    if node_vm_size is None:
        if os_type.lower() == "windows":
            raise CLIError('Windows nodepool is not supported')
        node_vm_size = "Standard_DS2_v2"
```
=>
```
    if node_vm_size is None:
        if os_type == "Windows":
            node_vm_size = "Standard_D2s_v3"
        else:
            node_vm_size = "Standard_DS2_v2"
```

**Comment by arrownj** [comment]
Hi @AbelHu , is this ready to merge ? Code looks good to me.

**Comment by AbelHu** [comment]
@arrownj . It is ready now. Expect your help to merge it. Thanks.

**Pull request merged**
