### PR TITLE
[AKS] az aks create/update: Add LicenseType support for Windows

### PR DESCRIPTION
**Pull request by AbelHu**
**Description**  

This will allow cx to create/update AKS Clusters to enable Azure Hybrid User Benefit (AHUB) for all AKS Windows nodes.

**Testing Guide**  

image

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Review by arrownj — APPROVED** [review]
Hi @AbelHu , the code is good to me, could you please help fix the CI error ?

**Comment by AbelHu** [comment]
> Hi @AbelHu , the code is good to me, could you please help fix the CI error ?

Yes. Will update it soon.

**Comment by AbelHu** [comment]
@arrownj Is it ok to merge this PR? We expect that it can be included in next azure-cli official release. Thanks.

**Comment by AbelHu** [comment]
@arrownj Do you know when this can be included in the azure-cli official release?

**Pull request merged**
