### PR TITLE
[Network] Add/Remove VMs to/from Load Balancer

### LINKED ISSUE #3551: [Network] Can't create internal Load Balancer without subnet
### Description
I'm trying to create an internal load balancer, but I don't want a public ip address.
When I do it using the azure portal or using templates I get it, but using the next command:

**az network lb create --resource-group $MyResourceGroup --location $MyLocation --name $MyLoadBalancerName --frontend-ip-name $MyFrontEndIP_name --backend-pool-name $MyBackendPool_name --private-ip-address $myPrivateIP_address --public-ip-address ""**

I get the next error:

_At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details. {
  "error": {
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request.",
    "details": [
      {
        "code": "MissingJsonReferenceId",
        "message": "Value for reference id is missing. Path properties.frontendIPConfigurations[0].properties.subnet."
      }
    ]
  }
}  Correlation ID: 03ddc706-6c74-4121-9b74-b6f8cc2b56ca_

looking at lb help I find the next:

> --public-ip-address           : Name or ID of the public IP address, or '' for none. Uses
>                                     existing resource if available or will create a new resource
>                                     with defaults if omitted.

I don't know if I'm doing something wrong or it doesn't works.

**CLI Version:** What version of the CLI and modules are installed? (Use `az --version`)  

**OS Version:** What OS and version are you using?  
Answer here:
_az --version_
**azure-cli (2.0.7)**

acr (2.0.5)
acs (2.0.7)
appservice (0.1.7)
batch (3.0.0)
billing (0.1.0)
cdn (0.0.3)
cloud (2.0.3)
cognitiveservices (0.1.3)
command-modules-nspkg (2.0.0)
component (2.0.5)
configure (2.0.7)
consumption (0.1.0)
core (2.0.7)
cosmosdb (0.1.7)
dla (0.0.7)
dls (0.0.7)
feedback (2.0.3)
find (0.2.3)
interactive (0.3.3)
iot (0.1.6)
keyvault (2.0.5)
lab (0.0.5)
monitor (0.0.5)
**network (2.0.7)**
nspkg (3.0.0)
profile (2.0.5)
rdbms (0.0.2)
redis (0.2.4)
resource (2.0.7)
role (2.0.5)
sf (1.0.2)
sql (2.0.4)
storage (2.0.7)
vm (2.0.7)

Python (Linux) 3.6.1 (default, May 30 2017, 16:59:26) 
[GCC 4.8.4]

Python location '/opt/az/bin/python3'

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Answer here:
 using bash

### PR DESCRIPTION
**Pull request by tjprescott**
Partially addresses #3748. Closes #3551, #2586.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [x] Each command and parameter has a meaningful description.
- [x] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by tjprescott** [comment]
```
(env) C:\Users\trpresco\Documents\github\azure-cli>az network lb address-pool add-vm -h

Command
    az network lb address-pool add-vm: Add virtual machines to a backend address pool.
        Under the hood, this is accomplished by associating the IP configuration of a VM's NIC with
        the backend pool.

Arguments
    --resource [Required]: Names or IDs or Virtual Machines to add to the backend pool.
        Only the primary NIC will be used, and VMs whose primary NIC has multiple IP configurations
        will be ignored.
    --ip-config-name
    --resource-type      : Allowed values: availabilitySets, virtualMachines.  Default:
                           virtualMachines.

Resource Id Arguments
    --ids                : One or more resource IDs (space delimited). If provided, no other
                           'Resource Id' arguments should be specified.
    --lb-name            : The load balancer name.
    --name -n            : Name of the backend address pool. Can be omitted if only a single address
                           pool exists.
    --resource-group -g  : Name of resource group. You can configure the default group using `az
                           configure --defaults group=<name>`.

Examples
    Add a VM to a load balancer's default backend address pool.
        az network lb address-pool add-vm -g myRG --lb-name myLB --vm myVM
```

**Comment by tjprescott** [comment]
cc/ @johanste @iainfoulds

**Comment by iainfoulds** [comment]
I like the implementation based on the command examples. Thanks @tjprescott

**Comment by johanste** [comment]
I would suggest changing the name of the command *or* remove the --resource-type parameter. The current name strongly implies adding a VM, and not an availability set (although, yes, the actual implementation adds all the VMs from an availability set into the LBs backend pool).

**Comment by tjprescott** [comment]
I would like to keep the implementation limited for convenience. A power user can always use the `az network nic ip-config address-pool add` command to hook up non-primary NICs for a multi-NIC VM. I expose the ability to add an availability set (really just a loop on all the VMs in the availability set) because the portal does so.

Would the strongly typed parameters `--vm` and `--availability-set` be preferable (getting rid of `--resource` and `--resource-type`?

**Comment by tjprescott** [comment]
Temporarily closing this PR since I want this to go in in fairly close succession with some other issues related to LB and app gateway feature work has bumped up in priority.

**Pull request closed without merging**
