### PR TITLE
Removing unused CI configuration files.

### PR DESCRIPTION
**Pull request by marstr**
We haven't used Jenkins or Appveyor in a long while! Time to clean up. :)

### CODE REVIEW

**Comment by marstr** [comment]
> Are there partner teams that may be using these files?

I checked with the configured GitHub services, and neither Jenkins nor AppVeyor are listed as being allowed to integrate with our repository. Now, that is not necessarily bullet-proof as there could just be a chron-job that pulls the repo and reads those files, but it's a good place to start.

**Comment by JamieMagee** [comment]
@zikalino @marstr Is there any will to get this merged? It looks like the Travis CI build has been flaky recently, and if it's not being actively maintain I can't see a reason to keep it around.

**Comment by yonzhan** [comment]
@zikalino  please help deal with this PR.

**Comment by haroldrandom** [comment]
@marstr Pleas merge the latest commit to your branch first, the problem Travis CI maybe solved already.

**Comment by marstr** [comment]
Not on the top of my list these days. :) Enjoy, folks.

**Pull request merged**
