### PR TITLE
webapp: az webapp up code refactoring

### LINKED ISSUE #9955: `az webapp up` does not target existing web apps as expected
**Describe the bug**
`az webapp up` does not behave as expected when attempting to target an existing web app for deployment.

**To Reproduce**
Target an existing web app with `--name` and `--resource-group`, which are enough to disambiguate/fully specify in most `az` commands. The command will find the resource group, but will then create a new App Service plan without checking to see if the app already exists. Then, it will try to create the app and fail with the confusing error message "Cannot update the site <sitename> because it uses AlwaysOn feature which is not allowed in the target compute mode."

The same behavior occurs if specifying an existing web app by its resource id with `--id`.

**Expected behavior**
The existing app should be detected and targeted.

**Environment summary**
Cloud shell:
Linux-4.15.0-1050-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Shell: bash
azure-cli 2.0.68 *

**Additional context**
The only way I've gotten this to work is by explicitly specifying all of `--name`, `--resource-group`, `--plan` and `--sku`.

### PR DESCRIPTION
**Pull request by panchagnula**
---
fixes #9955, #9788
This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by panchagnula** [comment]
@yugangw-msft can I get a PR on this?

**Comment by yonzhan** [comment]
@qwordy  please review.

**Comment by qwordy** [comment]
> 
> 
> @qwordy please review.

OK

**Comment by qwordy** [comment]
Looks good to me.

**Comment by panchagnula** [comment]
@qwordy / @yonzhan we'd like to get this PR merged however the status of the build is not getting updated blocking the merge.

**Comment by uvizcaino-hub** [comment]
Well,  the version I am using it is still NOT working after all the incredible back and forth from you guys.

**Comment by uvizcaino-hub** [comment]
I am trying to deploy to a Linux VM sku B1 plan ""ASP-ASCRG1-908a (B1: 1)"  - Any ideas?

**Pull request merged**
