### PR TITLE
{AKS} Monitoring Addon - Bug fixes related to --ampls-resource-id and --enable-high-log-scale-mode options

### PR DESCRIPTION
**Pull request by ganga1980**
Related command

Enable monitoring addon with high log scale mode

az aks create --resource-group rgName --name clusterName --enable-addons monitoring --enable-high-log-scale-mode

az aks enable-addons -a monitoring -g rgName -n clusterName --workspace-resource-id "workspaceResourceId" --enable-high-log-scale-mode

Enable monitoring addon with azure monitor private link scope resource id

az aks create --resource-group rgName --name clusterName --enable-addons monitoring --ampls-resource-id "amplsResourceId"

az aks create --resource-group rgName --name clusterName --enable-addons monitoring --workspace-resource-id "workspaceResourceId" --ampls-resource-id "amplsResourceId"

az aks enable-addons -a monitoring -g rgName -n clusterName --workspace-resource-id "workspaceResourceId" --ampls-resource-id "amplsResourceId"

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by ganga1980** [comment]
@zhoxing-ms , @FumingZhang , can you guys please review this PR and I would like to get this PR merged as part of upcoming release?

**Review by FumingZhang — COMMENTED** [review]
Queued [live test](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=97030525&view=results) to validate the change
- test_aks_create_with_private_cluster_with_monitoring_aad_auth_msi_with_ampls
- test_aks_create_with_monitoring_aad_auth_with_highlogscale

**Comment by FumingZhang** [comment]
> Queued [live test](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=97030525&view=results) to validate the change
> 
> * test_aks_create_with_private_cluster_with_monitoring_aad_auth_msi_with_ampls
> * test_aks_create_with_monitoring_aad_auth_with_highlogscale

live test failed
> azure.cli.core.azclierror.HTTPError: Not Found({"error":{"code":"ResourceNotFound"}})
> azure.cli.testsdk.exceptions.JMESPathCheckAssertionError: Query 'properties.dataCollectionEndpointId' doesn't yield expected value '/subscriptions/79a7390d-3a85-432d-9f6f-a11a703c8b83/resourceGroups/clitest53hk5b2fvz/providers/Microsoft.Insights/dataCollectionEndpoints/MSCI-westus2-cliakstestmj2fhw', instead the actual value is 'None'.

**Comment by ganga1980** [comment]
@FumingZhang , Fixed test failures and verified running live tests locally works. can you please re-review this change and would like to get this merged, and get this change going in upcoming 2.62.0 release?

**Comment by ganga1980** [comment]
Hi, @yanzhudd , @FumingZhang , @zhoxing-ms , can you help on reviewing and merging this PR?

**Comment by yanzhudd** [comment]
Hi @ganga1980 
please note that CLI only takes responsible for code style and specification but not business logic, so it is better to have @FumingZhang approved first.

**Comment by ganga1980** [comment]
@FumingZhang , can you please approve this PR?

**Comment by FumingZhang** [comment]
> @FumingZhang , Fixed test failures and verified running live tests locally works. can you please re-review this change and would like to get this merged, and get this change going in upcoming 2.62.0 release?

Requeued [live test](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=97176348&view=results)
- test_aks_create_with_monitoring_aad_auth_with_highlogscale
- test_aks_create_with_private_cluster_with_monitoring_aad_auth_msi_with_ampls
- test_aks_create_with_private_cluster_with_monitoring_aad_auth_msi_with_ampls_with_highlogscale

**Review by FumingZhang — APPROVED** [review]

**Comment by ganga1980** [comment]
Hi, @yanzhudd ,  Can you please on helping merging this PR now since it got reviewed and approved by @FumingZhang ?

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
