### PR TITLE
added plan information

### PR DESCRIPTION
**Pull request by huzferd**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [ ] Each command and parameter has a meaningful description.
- [ ] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by tjprescott** [comment]
I believe @yugangw-msft added the plan support, and intentionally hid these arguments.

**Comment by yugangw-msft** [comment]
Correct. CLI plumbs those information through behind the scene so those less used arguments won't clutter the command interface

**Comment by tjprescott** [comment]
@huzferd is there a scenario you have in mind that doesn't work today?

**Comment by huzferd** [comment]
@tjprescott. Yes. 
Scenario:
1. Create Data Science VM using templates.
1. Create Image from DSVM.
1. Restore DSVM from Image.
1. Have an error:
```json
{
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "VMMarketplaceInvalidInput",
        "message": "Creating a virtual machine from Marketplace image requires Plan information in the request. OS disk name is 'test1_disk1'."
      }
    ]
  }
}
```
This is necessary for the [educational process](https://github.com/MSFTImagine/computerscience).

**Comment by yugangw-msft** [comment]
Let me confirm with CRP folks why the plan information was not captured at step 2

**Comment by huzferd** [comment]
Hello @yugangw-msft, are there any news?

**Comment by yugangw-msft** [comment]
@huzferd, still in discussion and will post update. Since we are at it, one question, did you test out the VM creation works with your change? And you are not getting the error like 
```bash
.[{"Legal terms have not been accepted for this item on this subscription. To accept legal terms, please go to the Azure portal (http://go.microsoft.com/fwlink/?LinkId=534873) and configure programmatic deployment for the Marketplace item 
```

**Comment by huzferd** [comment]
@yugangw-msft, No, there was not.
I enabled programmatic deployment from Azure portal.
And it working with my changes.

**Comment by yugangw-msft** [comment]
To get this PR merged, please do the following
1. In the `_params.py`, please add description, and make sure with wording `...only needed for self-made custom image with separate billing information`
2. In the `_validators.py`, please skip this [whole chunk](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/azure/cli/command_modules/vm/_validators.py#L160-L185) if the `--plan` is supplied through command arguments

**Comment by tjprescott** [comment]
@yugangw-msft it might be more prudent to reject this PR, open an issue quoting the scenario he describes, and then having us create a PR that handles the finer points dealing with validators, etc.

**Comment by yugangw-msft** [comment]
Agreed we should do the work. @huzferd, are you okay with that?

**Comment by huzferd** [comment]
@yugangw-msft, Yes. I agree with @tjprescott.

**Comment by tjprescott** [comment]
Thanks @huzferd I've opened issue #4233 if you need to provide any further clarification and for your tracking purposes when this is officially fixed.

**Pull request closed without merging**
