### PR TITLE
{SQLVM} Update SQL VM Python version to 1.0.0b2

### PR DESCRIPTION
**Pull request by ai-abhinav**
**Description**

1 - Update SQL Virtual machine python version from 1.0.0b1 to 1.0.0b2
1.0.0b1 used api version 2017-03-01-preview
1.0.0b2 uses api version 2021-11-01

Links for reference: https://pypi.org/project/azure-mgmt-sqlvirtualmachine/1.0.0b2/ & 
https://github.com/Azure/sdk-release-request/issues/2465

**Testing Guide**

Test recordings have been updated. Ran live tests.
azdev style sqlvm
azdev linter sqlvm

azdev test sqlvm --live --no-exitfirst

Test on modules: sqlvm

RUNNING TESTS LIVE
The tests are set to run against current profile "latest"
=========================================================================================================== test session starts ============================================================================================================
platform win32 -- Python 3.10.1, pytest-7.1.1, pluggy-1.0.0 -- E:\azcli\azure-cli\env\Scripts\python.exe

src\azure-cli\azure\cli\command_modules\sqlvm\tests\latest\test_sqlvm_commands.py::SqlVmScenarioTest::test_sqlvm_create_and_delete
src\azure-cli\azure\cli\command_modules\sqlvm\tests\latest\test_sqlvm_commands.py::SqlVmScenarioTest::test_sqlvm_mgmt
src\azure-cli\azure\cli\command_modules\sqlvm\tests\latest\test_sqlvm_commands.py::SqlVmScenarioTest::test_sqlvm_update_license_and_sku
src\azure-cli\azure\cli\command_modules\sqlvm\tests\latest\test_sqlvm_commands.py::SqlVmAndGroupScenarioTest::test_sqlvm_add_and_remove
src\azure-cli\azure\cli\command_modules\sqlvm\tests\latest\test_sqlvm_commands.py::SqlVmGroupScenarioTest::test_sqlvm_group_mgmt
[gw3] [ 20%] PASSED src\azure-cli\azure\cli\command_modules\sqlvm\tests\latest\test_sqlvm_commands.py::SqlVmGroupScenarioTest::test_sqlvm_group_mgmt
[gw2] [ 40%] PASSED src\azure-cli\azure\cli\command_modules\sqlvm\tests\latest\test_sqlvm_commands.py::SqlVmScenarioTest::test_sqlvm_update_license_and_sku
[gw1] [ 60%] PASSED src\azure-cli\azure\cli\command_modules\sqlvm\tests\latest\test_sqlvm_commands.py::SqlVmScenarioTest::test_sqlvm_mgmt
[gw0] [ 80%] PASSED src\azure-cli\azure\cli\command_modules\sqlvm\tests\latest\test_sqlvm_commands.py::SqlVmScenarioTest::test_sqlvm_create_and_delete
[gw4] [100%] PASSED src\azure-cli\azure\cli\command_modules\sqlvm\tests\latest\test_sqlvm_commands.py::SqlVmAndGroupScenarioTest::test_sqlvm_add_and_remove

------------------------------------------------------------------------ generated xml file: C:\Users\abhaga\.azdev\env_config\azcli\azure-cli\env\test_results.xml ------------------------------------------------------------------------
====================================================================================================== 5 passed in 2430.52s (0:40:30) ======================================================================================================

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

-- No New az command added. Hence, not a customer facing change.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by ai-abhinav** [comment]
@yonzhan are the test files under recordings manually generated or auto generated?
Do you know when I would have to change the fields / what the difference is between:
"AZURECLI/2.33.0" vs "AZURECLI/2.28.0" 
and 
"Python/3.8.9" vs "Python/3.7.9"

Is this just to specify the client used for the specific test? if so, when would these need to be updated?

**Comment by yonzhan** [comment]
Add @evelyn-ys to help with

**Comment by evelyn-ys** [comment]
All the yaml files are autogenerated. You can't change them manually to fake real http request.

See https://github.com/Azure/azure-cli/blob/dev/doc/authoring_tests.md#recording-tests

**Comment by ai-abhinav** [comment]
@evelyn-ys thanks for your response. i will revert these yaml changes and try to record new tests if needed.

**Comment by ai-abhinav** [comment]
@evelyn-ys could you help me with generating test recordings? I see that we have the tests located at : \src\azure-cli\azure\cli\command_modules\sqlvm\tests\latest\test_sqlvm_commands.py
azdev test is unable to find the module sqlvm / any test name I provide. 
Do you know what module I would need to specify / how i can load it?

**Comment by evelyn-ys** [comment]
try running `azdev test` with `--discover`

**Comment by ai-abhinav** [comment]
That does not work unless I specify the right module. Do you know what command needs to be run for recording / running sqlvm tests?

**Comment by evelyn-ys** [comment]
To run with record mode: `azdev test sqlvm`
To run with live mode: `azdev test sqlvm --live`
If azdev can't find sqlvm: `azdev test sqlvm --discover`

I suddenly think of: have you ran `azdev setup -c` first?

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
