### PR TITLE
{AKS} `az aks addon enable`: Update help message

### PR DESCRIPTION
**Pull request by mtrilbybassett**
**Related command**

az aks addon enable

**Description**

Remove erroneous indent on long summary 972-982. Docs services was unable to process format correctly:
https://learn.microsoft.com/en-us/cli/azure/aks/addon?view=azure-cli-latest#az-aks-addon-enable 

From bug: https://dev.azure.com/ceapex/Engineering/_workitems/edit/891668

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by yonzhan** [comment]
AKS

**Review by FumingZhang — APPROVED** [review]
LGTM

Please update PR title to something like
```{AKS}: Update _help.py```

**Comment by mtrilbybassett** [comment]
> LGTM
> 
> Please update PR title to something like `{AKS}: Update _help.py`

@FumingZhang PR title updated

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
