### PR TITLE
Update adls gen1 module to 0.0.48

### PR DESCRIPTION
**Pull request by akharit**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
@Juliehzl  please help with this PR.

**Comment by Juliehzl** [comment]
@akharit Let's talk about this after Ignite.

**Comment by akharit** [comment]
@Juliehzl  I am fine with merging this later when you have cycles. Please ping me so I can resolve any merge conflicts.

**Comment by Juliehzl** [comment]
@akharit  Can you resolve all conflicts? If CI is green, I will agree.

**Comment by akharit** [comment]
@Juliehzl CI is all green. Can you merge this?

**Comment by Juliehzl** [comment]
> @Juliehzl CI is all green. Can you merge this?

Sorry for the delay. Could you rebase dev again and let CI pass? I will merge for you ASAP. If dropped, please ping me.

**Pull request merged**
