### PR TITLE
{KeyVault} Use absolute references instead of relative references

### PR DESCRIPTION
**Pull request by bim-msft**
Fix: #15144 

Using absolute references would benefit our packaging and debugging work.

FYI, PEP 8 states:
> Absolute imports are recommended, as they are usually more readable and tend to be better behaved (or at least give better error messages) if the import system is incorrectly configured (such as when a directory inside a package ends up on sys.path)

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
KeyVault

**Comment by bim-msft** [comment]
@arrownj I have a `vendored_sdks` folder and I didn't change anything on it in this PR, do I need to replace all relative references in it as well?

**Review by arrownj — APPROVED** [review]
👍

**Review by yungezz — APPROVED** [review]

**Review by fengzhou-msft — APPROVED** [review]

**Pull request merged**
