### PR TITLE
Add a check for linux version consistency 

### PR DESCRIPTION
**Pull request by yorek**
Followin up #5747

### CODE REVIEW

**Comment by yorek** [comment]
changed code to comply with pyling rules. Had to get rid of deprecated function.

**Comment by derekbekoe** [comment]
In the last call to logger.warning, can you add `current_linux_dist_name.strip()`?

I just tried it and I see this.
```
az extension add -n webapp 
Linux distro check: Mismatch distribution name in /etc/apt/sources.list.d/azure-cli.list file
Linux distro check: If command fails, install the appropriate package for your distribution or change the above file accordingly.
Linux distro check: /etc/apt/sources.list.d/azure-cli.list has 'wheezy', current distro is 'xenial
'
An error occurred. Pip failed with status code 1. Use --debug for more information.
```

As you can see, the last `'` ends up on a new line.

**Comment by derekbekoe** [comment]
Same with `Linux distro check: Reported by API: ...` message.
So might be best to do `return rel.strip()` in `get_lsb_release`.

**Comment by derekbekoe** [comment]
I verified that `return rel.strip()` would resolve the issue.

**Comment by derekbekoe** [comment]
Thanks for the contribution @yorek

**Comment by yorek** [comment]
You're welcome :)

**Pull request merged**
