### PR TITLE
[ACR] `az acr build` and `az acr task`: Highlight the difference between arguments in the description

### PR DESCRIPTION
**Pull request by yuehaoliang**
**Related command**
`az acr build` and `az acr task`

**Description**
#28269

**Testing Guide**
`az acr build --help` and `az acr task create --help` should output the updated description.

**History Notes**

[Component Name 1] `az acr build` and `az acr task`: Highlight the difference between arguments in the description

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
ACR

**Comment by yuehaoliang** [comment]
Looks there's one check failed: [Build #20240511.8](https://dev.azure.com/azclitools/public/_build/results?buildId=157384&view=results)
```
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/8a/6a/19e9fe04fca059ccf770861c7d5721ab4c2aebc539889e97c7977528a53b/pip-24.0-py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fa0865077c0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```
How to re-run it?

**Review by wju-MSFT — APPROVED** [review]
LGTM

**Comment by yuehaoliang** [comment]
@yonzhan @zhoxing-ms Hi, I got the approval from ACR team. Could you please take a look?

**Comment by yonzhan** [comment]
Please fix CI issues

**Comment by yuehaoliang** [comment]
@yonzhan @zhoxing-ms Hi, CI checks passed, could you please approve?

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
