### PR TITLE
[Backup] Added VM tests

### PR DESCRIPTION
**Pull request by sambitratha**
**Description**  

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by sambitratha** [comment]
Fix for https://github.com/Azure/azure-cli/issues/14270

**Comment by yonzhan** [comment]
Backup

**Comment by yungezz** [comment]
hi @qwordy could you pls review the issue? thanks

**Comment by qwordy** [comment]
Thank you for rerunning and fixing the tests. I will approve when all checks are passed.

**Comment by sambitratha** [comment]
hi @qwordy  i'm seeing errors in some other tests which are not part of this PR. Can you please confirm and look into this?

**Comment by qwordy** [comment]
> 
> 
> hi @qwordy i'm seeing errors in some other tests which are not part of this PR. Can you please confirm and look into this?

Yes. wepapp error. I also observed it in other PRs.

**Pull request merged**
