### PR TITLE
[ServiceConnector] `az webapp connection`: Add command `create sql/webpubsub` to support more target resources 

### PR DESCRIPTION
**Pull request by ChenTanyi**
**Description**

Adds supports for more target resources: sql and webpubsub.
* `az webapp connection create sql`
* `az webapp connection create webpubsub`

**Testing Guide**

add test: test_webapp_sql_e2e, test_webapp_webpubsub_e2e

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Review by yungezz — APPROVED** [review]

**Comment by yonzhan** [comment]
ServiceConnector

**Review by houk-ms — APPROVED** [review]
Should be a customer facing feature, use `[ServiceConnector]` in title.

**Comment by ChenTanyi** [comment]
@houk-ms done.
@kairu-ms Internal Approved. Please help to review and merge the PR when you think it's ready.

**Review by kairu-ms — APPROVED** [review]

**Comment by jiasli** [comment]
There should be a space between **Service Connector** like 

- https://github.com/Azure/azure-cli/pull/21766

Otherwise, there will be 2 items **Service Connector** and **ServiceConnector** in history notes.

**Pull request merged**
