### PR TITLE
[AKS] add post-download help message to `az aks install-cli`

### PR DESCRIPTION
**Pull request by mboersma**
Since landing a binary in an appropriate location is tricky, esp. on Windows, this should provide some help for users.

Refs #5446 #5374

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [X] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [X] Each command and parameter has a meaningful description.
- [X] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/5511
This is an **experimental preview** for @microsoft users.

**Comment by tjprescott** [comment]
Is it not an option to simply add the download location to PATH?  cc/ @derekbekoe

**Comment by derekbekoe** [comment]
@tjprescott Not really. Especially in a way that's reliable and cross-platform.

**Comment by mboersma** [comment]
> Especially in a way that's reliable and cross-platform.

Exactly--the recipes I know of for modifying the Path on Windows require `win32api` native stuff which we wouldn't want to bring into `az`. I still have some ideas about how to make this UX better, but this seemed like the quickest way to avoid confusion for now.

**Pull request merged**
