### PR TITLE
[DNM] Adding support for Private DNS Public Preview

### PR DESCRIPTION
**Pull request by muwaqar**
This PR is a continuation of https://github.com/Azure/azure-cli/pull/5757 which accidentally got closed.

This PR adds support for creating/updating Private DNS zones for the public preview release. It is based on the Python SDK PR https://github.com/Azure/azure-sdk-for-net/pull/4109 which in turn is based on Swagger version 2018-03-01-preview https://github.com/Azure/azure-rest-api-specs/pull/2587.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [x] Each command and parameter has a meaningful description.
- [x] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/5763
This is an **experimental preview** for @microsoft users.

**Comment by muwaqar** [comment]
Please do NOT merge the PR until the relevant Swagger and Python SDK PRs have been merged.

**Comment by muwaqar** [comment]
@tjprescott : Please have a look at the PR, and if you don't have any comments, then please merge it at your earliest convenience.

**Comment by tjprescott** [comment]
LGTM

**Pull request merged**
