### PR TITLE
Container Instance: Add Better ACR Registry Creds Experience

### PR DESCRIPTION
**Pull request by samkreter**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/5997
This is an **experimental preview** for @microsoft users.

**Comment by derekbekoe** [comment]
@samkreter If this is for the next release, please fix CI so we can merge by EOD.

**Comment by derekbekoe** [comment]
@samkreter The change looks good but I just merged https://github.com/Azure/azure-cli/pull/6010 and there's a conflict.
If this needs to be in the next release, please fix ASAP.

**Comment by derekbekoe** [comment]
If it's not merged by EOD, it'll be part of the next release a month from now.

**Pull request merged**
