### PR TITLE
move acs commands from vm module to acs module.

### PR DESCRIPTION
**Pull request by brendandburns**

### CODE REVIEW

**Comment by yugangw-msft** [comment]
@brendandburns 
Please get CI pass and I will review. The current failure can be fixed by moving over several file entries in the [setup file](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-vm/setup.py#L67).

**Comment by yugangw-msft** [comment]
@brendandburns, I think this PR is addressing #1329, correct? The work is important to have command modules fully decoupled. Please prioritize it

**Comment by troydai** [comment]
The `master` branch is moving fast recently. Therefore a lot of merge conflicts have been introduced. Please rebase this branch. Thanks.

**Comment by troydai** [comment]
@yugangw-msft are you blocked? Do you want me to take a look?

**Comment by yugangw-msft** [comment]
@brendandburns, do you want @troydai help out?

**Comment by brendandburns** [comment]
I'd love to have help here.  Sorry this has lingered.  I can start again from HEAD...

**Comment by yugangw-msft** [comment]
//cc @troydai @vishrutshah, @tjprescott, who might have cycles to help out

**Comment by vishrutshah** [comment]
@yugangw-msft Sure, I can help with the review here. 

@brendandburns. Could you please add me in the reviewers list on this PR and then please resolve the merge commits and I'll complete review. :)

**Comment by yugangw-msft** [comment]
@vishrutshah, my understanding is you are expected help out the implementations

**Comment by vishrutshah** [comment]
This PR is getting replaced by https://github.com/Azure/azure-cli/pull/2098

**Comment by troydai** [comment]
It seems that @vishrutshah has moved the changes. I'll close this PR.

**Pull request closed without merging**
