### PR TITLE
[ACR] Add default timeout of 5 minutes for any requests to ACR

### PR DESCRIPTION
**Pull request by yugangw-msft**
**Description**  
Add a timeout for any requests to ACR to avoid hang

**Testing Guide**  
unit test + manual test

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yugangw-msft** [comment]
@djyou, the timeout here means 
>if the server has not issued a response for timeout seconds (more precisely, if no bytes have been received on the underlying socket for timeout seconds)

I am adding a default 5 minutes for all operations but let me know if you feel we should only do it for `helm` command. It is your call. If you agree we do it for all, do we need longer timeout for "az ace repository list"?

**Comment by yugangw-msft** [comment]
@fengzhou-msft @yungezz, could you please merge the PR? We might have a CI problem here

**Comment by yungezz** [comment]
sure @yugangw-msft I saw you triggered a new CI, will merge it after it's done

**Pull request merged**
