### PR TITLE
[OpenShift] update of az openshift deprecation warning

### PR DESCRIPTION
**Pull request by dbradish-microsoft**
**Description**
Per request, the deprecation warning for az openshift reference content needs to be updated.

### CODE REVIEW

**Comment by yonzhan** [comment]
OpenShift

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls add openshift command owner for review also? thanks

**Comment by dbradish-microsoft** [comment]
@jiasli , @fengzhou-msft , Please see email thread with subject "Breadth Coverage baseline RP review" and modify this PR as you see fit.  I don't take PRs in this repo any further than 'ready for review'.

**Comment by fengzhou-msft** [comment]
@olga-mir can you help review this PR?

**Review by fengzhou-msft — APPROVED** [review]

**Comment by fengzhou-msft** [comment]
Added deprecate_info so that when running an openshift command, the following warning will be shown:

> This command is implicitly deprecated because command group 'openshift' is deprecated and will be removed in a future release. Use 'aro' instead.

**Comment by fengzhou-msft** [comment]
@jim-minter can you help review this PR?

**Comment by jim-minter** [comment]
@dbradish-microsoft please sync with @sakthi-vetrivel on this - it's her call.

**Comment by dbradish-microsoft** [comment]
@sakthi-vetrivel , this PR has been approved by the Azure CLI engineering team.  We'll move forward to merge it early next week unless you request updates.

Kindly,

Delora

**Pull request merged**
