### PR TITLE
[Network] Private link add `Microsoft.Kusto/clusters` provider

### PR DESCRIPTION
**Pull request by ohaty**
**Description**

* added pe support for kusto clusters

* added pe test for kusto clusters

Co-authored-by: Ohad Tayler <t-ohadtayler@microsoft.com>

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
kusto

**Review by kairu-ms — APPROVED** [review]

**Comment by necusjz** [comment]
@ohaty, please refine the PR title via: https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#format-pr-title, and make sure the testing recordings are working.

**Comment by ohaty** [comment]
Hey, I have changed the PR title. As well I have tested the recording locally

**Review by necusjz — APPROVED** [review]

**Pull request merged**
