### PR TITLE
[App Service] `az webapp create`: Provide support `--https-only` flag

### LINKED ISSUE #19415: WebApp:az webapp create does not support --https-only flag
**Is your feature request related to a problem? Please describe.**
Due to Azure Policy we need to enable https by default on the webapp (who wouldn't want that?) and not via az webapp update.

**Describe the solution you'd like**
`az webapp create -g MyResourceGroup -p MyPlan -n MyUniqueAppName **--https-only**`

**Describe alternatives you've considered**
`az webapp update` has been tried, but the original create command will be blocked by policy.

**Additional context**
https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az_webapp_create
https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az_webapp_update

### PR DESCRIPTION
**Pull request by Kotasudhakarreddy**
issue #19415
**Description**

Due to Azure Policy we need to enable https by default on the webapp (who wouldn't want that?) and not via az webapp update.
**Testing Guide**

`az webapp create -g MyResourceGroup -p MyPlan -n MyUniqueAppName --https-only`
**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change.
[Component Name 2] `az command b`: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AppService

**Review by StrawnSC — APPROVED** [review]
LGTM. The `--https-only` feature works for me when I try it

@zhoxing-ms it looks like the CI test failures are unrelated since the failing tests are in the `monitor` and `network` command modules

**Comment by zhoxing-ms** [comment]
> it looks like the CI test failures are unrelated since the failing tests are in the monitor and network command modules

@StrawnSC This CI issue has been fixed by PR #21304. I'll I'll trigger the pipeline again

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
