### PR TITLE
{Core} Rename mock.py

### PR DESCRIPTION
**Pull request by fengzhou-msft**
**Description**  

We are working on running tests for installed `azure-cli` packages. When running pytest for tests in `azure-cli-core` in MSI installed `azure-cli`, it will insert `C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\Lib\\site-packages\\azure\\cli\\core` in the beginning of `sys.path`. For `import mock`, it finds and returns `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\core\mock.pyc` instead of `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\mock`.

This PR renames `mock.py` to `mock_cli.py` to avoid the import conflicts.

**Testing Guide**  

Pull the changes:
`git pull https://github.com/fengzhou-msft/azure-cli.git fix_core_mock`

On Git Bash:
`cd azure-cli`
`. scripts/ci/build.sh`

This script builds `azure-cli` related wheels including the `azure_cli_testsdk-0.2.4.dev*-py3-none-any.whl` and `azure_cli_fulltest-1.0.0.dev*-py2.py3-none-any.whl` in `azure-cli\artifacts\build`. The latter one includes all the tests from `azure-cli` repository.

On a Powershell with Admin privilege:

`& 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe' -m pip install pytest`

`& 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe' -m pip install \path\to\azure-cli\artifacts\build\azure_cli_testsdk-0.2.4.dev*-py3-none-any.whl`

`& 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe' -m pip install  \path\to\azure-cli\artifacts\build\azure_cli_fulltest-1.0.0.dev*-py2.py3-none-any.whl`

`& 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe' -m pytest -x -v 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\core\tests\test_cloud.py::TestCloud::test_add_get_cloud_with_hybrid_profile' -s`

Without this PR, you'll see the error:

> AttributeError: module 'mock' has no attribute 'patch'

With this PR, the test would pass.

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Core

**Comment by haroldrandom** [comment]
Why `C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\Lib\\site-packages\\azure\\cli\\core` is ahead of system built-in search path in sys.path? Is a design?

**Comment by qwordy** [comment]
Does this bug only happen in testing?

**Comment by fengzhou-msft** [comment]
> Why `C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\Lib\\site-packages\\azure\\cli\\core` is ahead of system built-in search path in sys.path? Is a design?

I think it's inserted by pytest.

**Comment by fengzhou-msft** [comment]
> Does this bug only happen in testing?

Yes. It is only used in tests files. I installed the tests files in MSI installed location and run pytest with MSI-bundled python, this issue occurs.

In azdev test with source code, this issue does not occur because the path inserted in `sys.path` is `.../azure-cli/src/azure-cli-core` and `mock.py` can only be imported with the full `azure.cli.core.mock`.

**Comment by jiasli** [comment]
According to [`sys.path`](https://docs.python.org/3/library/sys.html#sys.path)


> As initialized upon program startup, the first item of this list, `path[0]`, is the directory containing the script that was used to invoke the Python interpreter. If the script directory is not available (e.g. if the interpreter is invoked interactively or if the script is read from standard input), `path[0]` is the empty string, which directs Python to search modules in the current directory first. Notice that the script directory is inserted before the entries inserted as a result of PYTHONPATH.

**Comment by jiasli** [comment]
I did a test by adding `print(sys.path)` in `test_endpoint_none`:

```
class TestCloud(unittest.TestCase):

    def test_endpoint_none(self):
        import sys
        print(sys.path)

```

Then run
```
python -m pytest D:\cli\azure-cli\src\azure-cli-core\azure\cli\core\tests\test_cloud.py::TestCloud::test_endpoint_none -s

> python -m pytest D:\cli\azure-cli\src\azure-cli-core\azure\cli\core\tests\test_cloud.py::TestCloud::test_endpoint_none -s
========================================================== test session starts ==========================================================
platform win32 -- Python 3.8.3, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: D:\cli\azure-cli\src\azure-cli-core
plugins: asyncio-0.10.0, cov-2.8.1, forked-1.2.0, timeout-1.3.4, xdist-1.32.0
collected 1 item

azure-cli\src\azure-cli-core\azure\cli\core\tests\test_cloud.py ['D:\\cli\\azure-cli\\src\\azure-cli-core', 'D:\\cli', 'C:\\Users\\xxx\\AppData\\Local\\Programs\\Python\\Python38\\python38.zip',
```

Only `D:\\cli\\azure-cli\\src\\azure-cli-core` is injected.

**Comment by fengzhou-msft** [comment]
> I did a test by adding `print(sys.path)` in `test_endpoint_none`:
> 
> ```
> class TestCloud(unittest.TestCase):
> 
>     def test_endpoint_none(self):
>         import sys
>         print(sys.path)
> ```
> 
> Then run
> 
> ```
> > python -m pytest D:\cli\azure-cli\src\azure-cli-core\azure\cli\core\tests\test_cloud.py::TestCloud::test_endpoint_none -s
> ========================================================== test session starts ==========================================================
> platform win32 -- Python 3.8.3, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
> rootdir: D:\cli\azure-cli\src\azure-cli-core
> plugins: asyncio-0.10.0, cov-2.8.1, forked-1.2.0, timeout-1.3.4, xdist-1.32.0
> collected 1 item
> 
> azure-cli\src\azure-cli-core\azure\cli\core\tests\test_cloud.py ['D:\\cli\\azure-cli\\src\\azure-cli-core', 'D:\\cli', 'C:\\Users\\xxx\\AppData\\Local\\Programs\\Python\\Python38\\python38.zip',
> ```
> 
> Only `D:\\cli\\azure-cli\\src\\azure-cli-core` is injected.

According to [pytest import mechanisms and sys.path/PYTHONPATH](https://docs.pytest.org/en/stable/pythonpath.html). Pytest will search from the test file upwards until it can find the last folder which still contains an `__init__.py` file in order to find the package root. To load the module, it will insert root/ to the front of `sys.path` (if not there already). This is the case in your test and in `azdev test azure-cli-core` for source code testing. 

Unfortunately, it seems pytest is not treating `__init__.pyc` as an equivalent of  `__init__.py` and since MSI installed azure-cli uses pyc as the file fomat, the path stops search at `C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\Lib\\site-packages\\azure\\cli\\core`.

Another workaround to avoid the import conflicts is to delete the `__init__.py` file under `tests/`. Then the path inserted becomes `C:\\Program Files (x86)\\Microsoft SDKs\\Azure\\CLI2\\Lib\\site-packages\\azure\\cli\\core\\tests`. But deleting the `__init__.py` file may cause issues in `azdev test`, needs further investigation.

**Comment by fengzhou-msft** [comment]
I found another workaround to avoid the `import mock` issue, which is to use [`--import-mode=append`](https://docs.pytest.org/en/latest/pythonpath.html#import-modes), it appends the file path to `sys.path` instead of the default prepend action.

**Pull request closed without merging**
