### PR TITLE
{packaging} Update argcomplete to 2.0.0

### PR DESCRIPTION
**Pull request by major**
**Description**
Version 2.0.0 of argcomplete was recently released and many Linux
distributions are updating to that version now.

This patch replaces azure/azure-cli#20259

**Testing Guide**
No changes to existing tests.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
packaging

**Comment by jiasli** [comment]
Thanks @major, but we currently don't have time to test if `argparse` is compatible with the currently CLI because it is a major version change. I am afraid I need to put this PR on hold.

**Comment by pdecat** [comment]
@major Oops, you probably shouldn't have closed #20259 that fast, sorry about that!

**Comment by major** [comment]
> Thanks @major, but we currently don't have time to test if `argparse` is compatible with the currently CLI because it is a major version change. I am afraid I need to put this PR on hold.

Understood. This is working fine in Fedora 36 (rawhide) currently, but that's a sample size of one. 😉

I'm able to build the RPM package and run the same tests that I run for all of the other releases.

**Comment by major** [comment]
> @major Oops, you probably shouldn't have closed #20259 that fast, sorry about that!

It's okay, @pdecat. 👍🏻

**Pull request closed without merging**
