### PR TITLE
[AKS] update containerservice package

### PR DESCRIPTION
**Pull request by marwanad**
**Description**  

This updates the containerservice SDK version to fix bug

**Testing Guide**  
Manually validated create and update operations with the new package.

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S168

**Comment by yungezz** [comment]
hi @marwanad could you pls run full live test to make sure no regression? thanks

**Comment by marwanad** [comment]
yup, i'll run the suite

**Comment by marwanad** [comment]
@yungezz this should be ready to go 😄

**Pull request merged**
