### PR TITLE
[Compute] Shared VM extension & shared VM extension version

### PR DESCRIPTION
**Pull request by qwordy**
**Description**  

https://github.com/Azure/azure-cli/issues/11219

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Compute

**Comment by grizzlytheodore** [comment]
this needs to be moved to a private repository. Corresponding swagger/sdk/powershell cmdlets are in private and will not be available to the public

**Comment by qwordy** [comment]
OK. I will move it to a private repository.

**Comment by qwordy** [comment]
I moved it here https://github.com/Azure/azure-cli-pr/pull/91 and I deleted the old branch.
But it seems I cannot delete this PR. I don't find a button.

**Pull request closed without merging**
