### PR TITLE
[AppService] `az functionapp`: Use the sku from the function app to validate if on a flex plan

### LINKED ISSUE #28741: `az functionapp` requires new IAM permissions in v2.59.0
### Describe the bug

After upgrading from v2.58.0 to v2.59.0 (latest at time of writing), the `az functionapp` deployment command suddenly began failing due to the authenticated identity not having permissions to read the App Service Plan. (See full authorization error in the _Errors_ section.) The identity never had this permission nor needed it before to do successful deployments via the CLI.

Downgrading back to `v2.58.0` OR staying on `v2.59.0` but granting the authenticated identity `Reader` permission over the ASP resolved the issue.

It looks like #28001 introduced a [pre-flight validation check](https://github.com/Azure/azure-cli/pull/28001/files#diff-335eb5f7ca32eba6e60e55af7ab1e404f19c4300681155fecaf3997f673d3739R143) that does a net-new read of the ASP. Since this call wasn't there in prior versions of the CLI, the least-privileged identity our CI uses to do the deployment did not have the permission.

This change was unexpected and ideally should be called out in the release notes or updated such that it fails gracefully to the old behavior of not needing this permission.

NB: When repro'ing make sure the identity (whether it's a Service Principal or Managed Identity) does *not* have Reader permission over the entire Subscription otherwise you won't be able to reproduce. The gist of the repro is:

1. Create a new function app.
2. Create a Service Principal or Managed Identity.
3. Give the identity Contributor permission over the Function App.
4. Using v2.58.0, run the deployment command below. It should succeed.
5. Upgrade to v2.59.0, run the deployment command below. Observe the Error message.
6. Give the identity Reader permission on the ASP and retry (6). It should now succeed.

### Related command

```
az functionapp deployment source config-zip --subscription <subscription-id> --resource-group <resource-group> --name <fnapp-name> --src deploy.zip
```

### Errors

```
> az functionapp deployment source config-zip --subscription <subscription-id> --resource-group <resource-group> --name <fnapp-name> --src deploy.zip
(AuthorizationFailed) The client '<client-id>' with object id '<client-id>' does not have authorization to perform action 'Microsoft.Web/serverfarms/read' over scope '/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Web/serverfarms/ASP-myasp' or the scope is invalid. If access was recently granted, please refresh your credentials.
Code: AuthorizationFailed
Message: The client '<client-id>' with object id '<client-id>' does not have authorization to perform action 'Microsoft.Web/serverfarms/read' over scope '/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Web/serverfarms/ASP-myasp' or the scope is invalid. If access was recently granted, please refresh your credentials.
```

### Issue script & Debug output

-

### Expected behavior

The command does not fail when it does not have the permission to read the ASP since this was the old behavior and is not strictly needed to do the deployment.

### Environment Summary

BROKEN: azure-cli                         2.59.0
WORKING: azure-cli                         2.58.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kamperiadis**
**Related command**
`az functionapp deployment source config-zip`

**Description**
Resolves #28741 by not making calls to the Microsoft.Web/serverfarms API to determine if a function app is on a flex plan

**History Notes**

[AppService] `az functionapp deployment source config-zip`: Users with no Microsoft.Web/serverFarm read privileges should still be able to deploy function apps

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AppService

**Comment by khkh-ms** [comment]
Is there any other change in custom.py file apart from moving of the code into the try/catch block? Just want to make sure that I am not missing anything?

**Comment by kamperiadis** [comment]
> Is there any other change in custom.py file apart from moving of the code into the try/catch block? Just want to make sure that I am not missing anything? Please point to the specific change in the file .

Yes. Please see commit https://github.com/Azure/azure-cli/pull/28845/commits/aa99a118f62bffaf969f8b2a969ecbaebf96b778 That resolves https://github.com/Azure/azure-cli/issues/28741

**Comment by khkh-ms** [comment]
Closing this PR. Created a new one without merge conflicts. 
https://github.com/Azure/azure-cli/pull/28899

**Pull request closed without merging**
