### PR TITLE
[ACR] Fix #14768: `az acr login`: Add environment Variable for docker command

### LINKED ISSUE #14768: ACR login does not work with podman
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
 az acr login --name registry
You may want to use 'az acr login -n registry --expose-token' to get an access token, which does not require Docker to be installed.
An error occurred: DOCKER_COMMAND_ERROR
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg

**To Reproduce**
install: `podman`, `podman-docker` emulator for CLI

**Expected behavior**
az acr login to work

**Environment summary**
RHEL8. Rhel8 does not have docker anymore. 
If you do `dnf install docker` it will install `podman` and `podman-docker` for CLI backwards compatibility. 

**Additional context**
With growing podman addition would be good for this to work out of the box. With or without `podman-docker` package.

### PR DESCRIPTION
**Pull request by git001**
**Related command**

```
DOCKER_COMMAND=podman \
az acr login --name myacr --subscription mySubscription
```

**Description**

This PR enables the feature to set the docker command via the environment Variable `DOCKER_COMMAND` and address the issue #14768 . The reason for that pull request is that some systems have not anymore a docker command.

Fix #14768

**Testing Guide**

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
acr

**Comment by git001** [comment]
@zhoxing-ms any Update on that PR?

**Comment by yanzhudd** [comment]
please fix the CI issues.

**Comment by git001** [comment]
> please fix the CI issues.

That's not very funny.
The first commit and test say that `import os` is not neccessary and now after removing the import is the statement that `os` is not know.

Do you want that people contribute to the azure-cli?

**Comment by yanzhudd** [comment]
> > please fix the CI issues.
> 
> That's not very funny. The first commit and test say that `import os` is not neccessary and now after removing the import is the statement that `os` is not know.
> 
> Do you want that people contribute to the azure-cli?

According to the error log, the failure is caused by reimporting os in **line 430**. So I am pretty sure that removing the "import os" in line 430 instead of 8 will work.

**Comment by git001** [comment]
> > > please fix the CI issues.
> > 
> > 
> > That's not very funny. The first commit and test say that `import os` is not neccessary and now after removing the import is the statement that `os` is not know.
> > Do you want that people contribute to the azure-cli?
> 
> According to the error log, the failure is caused by reimporting os in **line 430**. So I am pretty sure that removing the "import os" in line 430 instead of 8 will work.

Well no.
I have removed it and commited it and you can see in the run https://dev.azure.com/azclitools/public/_build/results?buildId=141727&view=logs&j=36dd4138-4d53-5e46-00d9-e5cd9744be05&t=1cf3879c-0a42-5ccd-7693-7a4781d739d8 that the ci fails.

**Comment by yanzhudd** [comment]
> Well no.
> I have removed it and commited it and you can see in the run https://dev.azure.com/azclitools/public/_build/results?buildId=141727&view=logs&j=36dd4138-4d53-5e46-00d9-e5cd9744be05&t=1cf3879c-0a42-5ccd-7693-7a4781d739d8 that the ci fails.

But I saw that the line you removed is line 8: https://github.com/Azure/azure-cli/pull/28443/commits/7f0edbd807a7cb304ff2d510c813c66d0970df9d

In fact, you should remove line 430 instead.

**Comment by git001** [comment]
@yanzhudd looks like the CI run was passed without errors. Is there any chance to get this PR into the next release?

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
