### PR TITLE
{AKS} `az aks create`: do not set `network_plugin` based on the Python SDK

### PR DESCRIPTION
**Pull request by tyler-lloyd**
**Related command**

az aks create

**Description**

the CLI should not own defaulting the network
profile properties. Defaulting should be owned
completely by AKS RP, so if a customer does
not set the `network_plugin` field then the CLI
should treat it as `None`.

Today, the default provided from the SDK
is `kubenet` but in the future, the AKS RP
will change this default value when omitted.
This means that other clients (ARM, bicep,
etc.) that do not set `network-plugin` will
get a different behavior than the CLI because
those clients won't set anything but the CLI
will continue to include the default from the
SDK.

**Testing Guide**

az aks create - without providing a `--network-plugin` should succeed and AKS RP will set the default.

**History Notes**

[AKS] `az aks create`: Not set the `--network-plugin` based on the default from the Python SDK

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by tyler-lloyd** [comment]
related PR where we've already done this in the `aks-preview` extension: https://github.com/Azure/azure-cli-extensions/pull/7766

**Comment by FumingZhang** [comment]
Requeued another [live test](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=98236519&view=results)

**Review by FumingZhang — APPROVED** [review]
LGTM

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
