### PR TITLE
{IOT} Iot central track 2 migration

### PR DESCRIPTION
**Pull request by abalogun-dev**
**Description**
Updated IoT Central module from track 1 to track 2. Also, ran tests in live mode
**Testing Guide**
Ran the following  commands
o	“azdev style iot”
o	“azdev linter iot”
o	“azdev test iot --no-exitfirst”,
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ x ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ x ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ x ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
IOT

**Comment by zhoxing-ms** [comment]
@abalogun-dev Hi, please run related tests in live mode , such as `azdev test iot --no-exitfirst --live`

**Comment by abalogun-dev** [comment]
> @abalogun-dev Hi, please run related tests in live mode , such as `azdev test iot --no-exitfirst --live`

i already did that before i pushed up my changes

**Comment by zhoxing-ms** [comment]
@abalogun-dev  Well. Why is there no recorded file here? Is it because these tests are all `@live_only()`?

**Comment by abalogun-dev** [comment]
> y is there no recorded file here? I

I'm not sure.... i ran the command while on the phone with Kai Ru and made sure to commit any changes after the command was done

**Comment by zhoxing-ms** [comment]
@abalogun-dev Hi, I've added the yaml file of those tests that you don't have permission. https://github.com/Azure/azure-cli/pull/18717/commits/51bff7eb8509f6277db3aa1368966075b722de52

Please submit the yaml files of the rest related tests as well

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
