### PR TITLE
[ARM] Hotfix: Fix deserialization issue in ARM template What-If formatter

### PR DESCRIPTION
**Pull request by shenglol**
**Description**

The What-If formatter doesn't work in Azure CLI 2.24.0. There seems to be behavior changes in deserialization which breaks the What-If formatter. The PR fixes it.

**Testing Guide**
`az deployment what-if ...`

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
ARM

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@shenglol May I ask what's your expected time for hotfix?

**Comment by shenglol** [comment]
Would it be possible to release it today / tomorrow (assuming there's no other pending hotfix PRs).

**Comment by zhoxing-ms** [comment]
@shenglol In fact, we have other PR that need hotfix，so we may launch hotfix next Monday or Tuesday, is this in line with your expectations?

**Comment by shenglol** [comment]
Sounds good to me. Thanks for the quick response!

**Pull request merged**
