### PR TITLE
[Redis Enterprise] az redisenterprise: Add new CLI module

### PR DESCRIPTION
**Pull request by greenms**
**Description**
New Azure CLI module

**Testing Guide**
- az redisenterprise create
    - Create a Redis Enterprise cache with a default database
- az redisenterprise create --no-database
    - Create a Redis Enterprise cache without a database
- az redisenterprise database create
    - Create a Redis Enterprise database.  You need to call this if you created a Redis Enterprise cache without a database because a cache without a database cannot hold data.
- az redisenterprise list
    - List all caches with all of their associated databases
- az redisenterprise show
    - List a cache with all of its associated databases
- az redisenterprise database list
    - List all databases associated with a cache
- az redisenterprise database show
    - List a database associated with a cache
- az redisenterprise database list-keys
    - List all access keys for a database
- az redisenterprise database regenerate-key
    - Regenerate an access key for a database
- az redisenterprise database delete
    - Delete a single database
- az redisenterprise delete
    - Delete a cache along with all of its databases

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Redis Enterprise

**Comment by qiaozha** [comment]
@fengzhou-msft Could you take a look at this full test failure ? It doesn't seems to be caused by redisenterprise service

**Comment by fengzhou-msft** [comment]
There are 2 files named `test_redisenterprise_scenario.py`, it may cause problems. @changlong-liu to review and give advice.

**Comment by greenms** [comment]
@fengzhou-msft @changlong-liu Instructions here show it's okay to have two files named `test_redisenterprise_scenario.py`: https://github.com/Azure/autorest.az/blob/master/doc/04-scenario-test-configuration.md#customize-step-functions

**Comment by changlong-liu** [comment]
It's fine that there are test_redisenterprise_scenario.py in both tests and manual/tests folder

**Comment by Juliehzl** [comment]
@greenms could we close the PR if it is not required any more as we already support the feature in extension?

**Pull request closed without merging**
