### PR TITLE
[Core] az cloud show: add application insights endpoint for China/US cloud

### PR DESCRIPTION
**Pull request by arrownj**
This is a PR to achieve the request of #12185 .

Currently, only application insight channel endpoint is needed. As the offical document only have China/US cloud's endpoints, so we only add these 2 regions for user as they required.

**History Notes:**  
(Fill in the following template if multiple notes are needed, otherwise PR title will be used for history note.)

[Component Name 1] (BREAKING CHANGE:) (az command:) make some customer-facing change.  
[Component Name 2] (BREAKING CHANGE:) (az command:) make some customer-facing change.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by jiasli** [comment]
1. Without corresponding code usage of `app_insights_telemetry_channel_resource_id`, no command except for `az cloud show` will be affected. Is this intended?
2. Don't we need to add `app_insights_telemetry_channel_resource_id` to `AzureCloud` as well? I think it should be `https://dc.services.visualstudio.com/v2/track` according to https://docs.microsoft.com/en-us/azure/azure-monitor/faq#example-applicationinsightsconfig-with-default-endpoints. Better to confirm with Application Insight service team

**Comment by arrownj** [comment]
> Without corresponding code usage of app_insights_telemetry_channel_resource_id, no command except for az cloud show will be affected. Is this intended?
> Don't we need to add app_insights_telemetry_channel_resource_id to AzureCloud as well? I think it should be https://dc.services.visualstudio.com/v2/track according to https://docs.microsoft.com/en-us/azure/azure-monitor/faq#example-applicationinsightsconfig-with-default-endpoints. Better to confirm with Application Insight service team

1. yes, user just want to get the output of `az cloud show`. I think besides `az cloud show`, it also impact the output of `az cloud list`.

2. yes, Kin give me this link before, as it is not an official way, I didn't add it to AzureCloud. Your suggestion is very useful. I will send an email to app insights team to get their confirmation.

**Comment by jiasli** [comment]
In that case, let's merge it for now and add `app_insights_telemetry_channel_resource_id` to `AzureCloud` in the future.

**Comment by fengzhou-msft** [comment]
Do we need to change code in application insight extension as well?

**Comment by MyronFanQiu** [comment]
Can you share the context with me offline in case I need to do something for application insight extension. Based on my understanding, this PR just have impact on az cloud show/list command.

**Pull request merged**
