### PR TITLE
GeoRegion support for 'az webapp deleted' commands

### PR DESCRIPTION
**Pull request by Nking92**
Adds support for the distributed location based API for undelete commands. Functionally the commands will be the same, however the resource ID of deleted apps will now contain a location. This will allow the APIs to be more fault tolerant.

https://github.com/Azure/azure-cli/issues/9607

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by panchagnula** [comment]
CC: @naveedaz

**Comment by marstr** [comment]
I believe you fell victim to https://github.com/Azure/azure-cli/issues/9648. Please rebase on top of [`dev`](https://github.com/Azure/azure-cli/tree/dev) (d2cf98f) to adopt the newest changes to CI, which should unblock your contribution.

**Comment by Nking92** [comment]
Thanks, rebasing fixed the issues.

**Comment by tjprescott** [comment]
@Nking92 please resolve the file conflict so we can merge.

**Pull request merged**
