### PR TITLE
Upgrade a log from info to warning so that it is always printed.

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes https://github.com/Azure/azure-cli/issues/2700

### CODE REVIEW

**Comment by mjrousos** [comment]
This fixes the issue, but are there any side-effects of calling those messages warnings when they're not really indicating anything wrong?

**Comment by brendandburns** [comment]
@mjrousos I defer to @derekbekoe @yugang-msft and others.

I don't fully understand how/why they are using the python logging package in the CLI, but there are numerous examples:

https://github.com/Azure/azure-cli/blob/5caebb94e286a44ab20c6cbe922210959d6b2af3/src/command_modules/azure-cli-acs/azure/cli/command_modules/acs/_actions.py#L75

https://github.com/Azure/azure-cli/blob/269f4b4cb5f0754025d2607924d8b7e3b1703fb7/src/azure-cli-core/azure/cli/core/cloud.py#L288

Where `logger.warning` is used for non-warning messages.

@tjprescott @derekbekoe @yugang-msft can you comment on the right way to use the logger in the CLI?

**Comment by derekbekoe** [comment]
`logger.warning` is appropriate to use for this scenario.

We use the standard Python logging levels - https://docs.python.org/2/library/logging.html#logging-levels.

We opted to not change the name `warning` to something else.

In the CLI:
error - Error messages that typically result in a non-zero exit code.
warning - Messages to be shown to users that are useful in an interactive scenario.
info - Standard log messages. Will be shown to user if `--verbose` specified.
debug - Debug log messages. Will be shown to user if `--debug` specified.

All log messages go to stderr.

**Comment by mjrousos** [comment]
Got it. Thanks for clarifying, @derekbekoe. LGTM.

**Pull request merged**
