### PR TITLE
Change generated.py files to commands.py

### PR DESCRIPTION
**Pull request by tjprescott**
This has confused almost every person who has attempted to onboard new commands. Everyone assumes that the `generated.py` file is... well... generated, which is not the case. This updates the file names, references and help doc to make this clear.

### CODE REVIEW

**Comment by derekbekoe** [comment]
I have actually made this change in https://github.com/Azure/azure-cli/pull/1059 but I'm fine with this PR going in then I can resolve conflicts.

**Comment by derekbekoe** [comment]
It might mean I have less conflicts to deal with later :)

**Comment by tjprescott** [comment]
@derekbekoe any issues with me merging this?

**Comment by derekbekoe** [comment]
LGTM

**Comment by derekbekoe** [comment]
Other open PRs may have to be rebased before merging though.

**Pull request merged**
