### PR TITLE
Changing CLI for azure-consumption reflecting the new api-version

### PR DESCRIPTION
**Pull request by sandeepnl**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [x] Each command and parameter has a meaningful description.
- [x] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by sandeepnl** [comment]
@lmazuel for reviewing

**Comment by sandeepnl** [comment]
@derekbekoe  I see a non 'consumption' api issue in the failed leg. What is the action here?

Verified READMEs of all modules successfully.
Verify package versions
Version 2.0.21 of azure-cli-core is already available on PyPI! Update the version.
Error(s) on azure-cli-core
Version 2.0.21 of azure-cli is already available on PyPI! Update the version.
Error(s) on azure-cli
The following modules have invalid versions:
azure-cli-core
azure-cli
See above for the full warning/errors
The command "./scripts/ci/test_static.sh" exited with 1.

**Comment by lmazuel** [comment]
@troydai Seems CI is failing not related to this code. Should the PR be done on the "dev" branch?

**Comment by derekbekoe** [comment]
Please open another PR against the dev branch instead of master. That's why you're seeing that particular error message.

**Comment by sandeepnl** [comment]
@derekbekoe Sure. One feedback I have here -  it would have been nice if either you, when you got assigned, had told me about this branch thing or at least have it in your documentation somewhere. I just don't want other devs waste a valuable dev day like I did :)

**Comment by derekbekoe** [comment]
Great thanks.
I understand and I'll be sure to point that out next time!

**Pull request closed without merging**
