### PR TITLE
[AKS] az aks: Add aad session key support.

### PR DESCRIPTION
**Pull request by JunSun17**
This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by JunSun17** [comment]
This is for addressing #9585

**Comment by jluk** [comment]
@qwordy can we get a merge on this?

**Comment by JunSun17** [comment]
Please do not merge this PR yet. It will be changed to implement in a different way.

**Comment by JunSun17** [comment]
This PR has been tested and ready for merge.

**Pull request merged**
