### PR TITLE
[Iot Hub] BREAKING CHANGE: az iot hub job: Remove deprecated job commands

### PR DESCRIPTION
**Pull request by anusapan**
**Description**  
This PR is for the removal of deprecated hub Job Commands and the data plane SDK because only Job commands were using this.

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Iot Hub

**Comment by anusapan** [comment]
> Iot Hub

Seems there is an error related to azure-cli-testsdk. Or could you give me a hint to solve this.
image

**Comment by haroldrandom** [comment]
@anusapan This warning won't effect the CI failure, just an deprating warning given by pytest.

**Pull request merged**
