### PR TITLE
{Network} `az network application-gateway url-path-map create`: Update document

### PR DESCRIPTION
**Pull request by necusjz**
**Related command**

**Description**

Resolve: https://github.com/Azure/azure-cli/issues/25889

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Network

**Review by kairu-ms — APPROVED** [review]

**Comment by rnautiyal** [comment]
@kairu-ms -  Please check the documentation I shared. As these updates need to move to different sections. Currently, default-address-pool and default-HTTP-setting both are under optional parameters. These need to move under "Required Parameters" with corrections that you have already made.

https://microsoft-my.sharepoint.com/:w:/p/rnautiyal/EZADAhQMm81KgLKMxrWW8WQB-a9Y96Ok1QHrh5MkDjIeZQ?e=HhgreP

**Comment by necusjz** [comment]
@rnautiyal As I said, we CANNOT mark these two parameters as mandatory. Because from client side, it'll break the behavior of users who don't use these parameters before (even if only "redirection" type will happen).

And, I've added info related to this in the help message:
image

For breaking change, Azure CLI only allows releases in the breaking change window, not this sprint.

**Comment by rnautiyal** [comment]
@necusjz - When should we see this change reflected in public document.

**Pull request merged**
