### PR TITLE
{packaging} Update argcomplete to 3.0.8

### LINKED ISSUE #26375: Please bump argcomplete dependency to support 3.0.0 or higher
The `azure-cli-core` component still depends on `argcomplete>=2.0,<3.0` while 3.0.0 has been available since March.

Could you bump the version for `argcomplete` so that we can get the added benefits of full zsh support and various other bug fixes?

Just the same as https://github.com/Azure/azure-cli/issues/23222

### PR DESCRIPTION
**Pull request by thehappydinoa**
Closes #26375

argcomplete added full zsh support in 3.0.0

This is the same as #24903

**Related command**

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
packaging

**Comment by thehappydinoa** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by bebound** [comment]
Thanks for your contribution. I'll check this update does not break anything later.
I will give this a low priority:
1. [2.0](https://packages.fedoraproject.org/pkgs/python-argcomplete/python3-argcomplete/) still the latest version in Fedora, we update it in #24903 because older versions of argcomplete are no longer available.
2. Current version works on Zsh. In 3.0 _Fully support zsh. Argcomplete now supports completion descriptions and global completion in zsh._

**Comment by bebound** [comment]
Close as https://github.com/Azure/azure-cli/pull/26684 is merged

**Pull request closed without merging**
