### PR TITLE
{Core} Ping azure-mgmt-core version setup.py

### PR DESCRIPTION
**Pull request by kairu-ms**
**Description**

The pipeline of extension install pre version of packages https://github.com/Azure/azure-cli-extensions/blob/a0b24e846c3a9d74a5deddac5289753d5187869b/scripts/ci/test_source.sh#L6.

Recently this [PR](https://github.com/Azure/azure-cli-extensions/pull/3374) triggered a issue that the azure-mgmt-core 1.3.0b1 (preview version) conflict with azure-core 1.14.0 (stable version).

image

This PR will ping the version of azure-mgmt-core <= 1.3.0 in setup.py to workaround above issue.

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Core

**Review by jsntcy — APPROVED** [review]

**Comment by glaubitz** [comment]
Is there an issue to track the actual fix for this incompatibility?

**Comment by kairu-ms** [comment]
> Is there an issue to track the actual fix for this incompatibility?

```
cannot import name `ChallengeAuthenticationPolicy`
```

**Comment by jiasli** [comment]
```diff
- ping
+ pin
```

**Comment by jiasli** [comment]
`pip` won't install beta versions without `--pre`, how does `azure-mgmt-core` 1.3.0b1 get installed?

**Pull request merged**
