### PR TITLE
[Containerapp] `az containeapp ingress enable`: Fix issue about labels being deleted

### PR DESCRIPTION
**Pull request by Greedygre**
**Related command**

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by Greedygre** [comment]
Hi @yonzhan  @zhoxing-ms 

The CI test failed due to following cases, not related to containerapp.
Can you help to take a look? Thanks.

```
============================= slowest 10 durations =============================
0.32s call     azure/cli/command_modules/botservice/tests/latest/test_bot_commands.py::BotTests::test_botservice_registration_bot_create_userassignedmsi_type
0.20s call     azure/cli/command_modules/botservice/tests/latest/test_bot_commands.py::BotTests::test_botservice_registration_bot_create_multitenant_type
0.20s call     azure/cli/command_modules/botservice/tests/latest/test_bot_commands.py::BotTests::test_botservice_registration_bot_create_singletenant_type
0.20s call     azure/cli/command_modules/botservice/tests/latest/test_bot_commands.py::BotTests::test_botservice_registration_bot_create_specific_location
0.19s call     azure/cli/command_modules/botservice/tests/latest/test_channel_commands.py::ChannelTests::test_botservice_create_channel_specific_location
0.13s call     azure/cli/command_modules/botservice/tests/latest/test_authsetting_commands.py::AuthSettingTests::test_auth_setting
0.12s call     azure/cli/command_modules/botservice/tests/latest/test_channel_commands.py::ChannelTests::test_skype_channel
0.11s call     azure/cli/command_modules/botservice/tests/latest/test_channel_commands.py::ChannelTests::test_directline_channel
0.11s call     azure/cli/command_modules/botservice/tests/latest/test_channel_commands.py::ChannelTests::test_msteams_channel
0.09s call     azure/cli/command_modules/botservice/tests/latest/test_channel_commands.py::ChannelTests::test_botservice_update_directline

```

**Comment by Greedygre** [comment]
I will rerun the related tests to fix the CI issue.

**Review by ShichaoQiu — APPROVED** [review]

**Review by Juliehzl — APPROVED** [review]

**Comment by Greedygre** [comment]
Hi @zhoxing-ms @yanzhudd 
This PR has been reviewed and approved. Can you help to review and approve it when you have chance? Thanks!

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
