### PR TITLE
Update __init__.py in SQL VM to suppress extension if installed.

### PR DESCRIPTION
**Pull request by yareyes**
Updated the init to remove extension if customer has already installed.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by tjprescott** [comment]
Thanks @yareyes!

**Comment by yareyes** [comment]
@tjprescott is this blocked somehow? I see the license/cla has not completed, but everything has passed.

**Comment by tjprescott** [comment]
Hi @yareyes I have restarted the CI. Will merge when it finishes. Not sure what happened.

**Comment by adewaleo** [comment]
Seems like the build didn't kick off.

**Pull request merged**
