### PR TITLE
{docs} Add code generation link in developer setup

### PR DESCRIPTION
**Pull request by kairu-ms**
Add code generation in developer setup

**Related command**

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Review by jsntcy — APPROVED** [review]

**Comment by yonzhan** [comment]
docs

**Review by yonzhan — APPROVED** [review]

**Review by jiasli — APPROVED** [review]

**Comment by jiasli** [comment]
CI job `Verify src/azure-cli/requirements.py3.Darwin.txt` failed:

https://dev.azure.com/azclitools/public/_build/results?buildId=12468&view=logs&jobId=537f1e04-c6d5-53b2-3a1f-f7387cc6e02d&j=537f1e04-c6d5-53b2-3a1f-f7387cc6e02d&t=cae9a690-b596-5b1d-0d0e-9efe890cb6db
```
python -m azure.cli self-test
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: argument _command_package: conflicting subparser: self-test
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 565, in execute
    self.parser.load_command_table(self.commands_loader)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/azure/cli/core/parser.py", line 100, in load_command_table
    command_parser = subparser.add_parser(command_verb,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/argparse.py", line 1185, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument _command_package: conflicting subparser: self-test
To check existing issues, please visit: https://github.com/Azure/azure-cli/issues
```

**Comment by jiasli** [comment]
It's better to have source branch from a forked repo.

**Review by necusjz — APPROVED** [review]

**Comment by kairu-ms** [comment]
> It's better to have source branch from a forked repo.

I see. I will remove it after merge.

**Pull request merged**
