### PR TITLE
{ACR} Migrate to Track 2

### LINKED ISSUE #18903: "az acr task timer remove" fails after upgrading to cli 2.26.1
## Describe the bug

**Command Name**
`az acr task timer remove`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
'TasksOperations' object has no attribute 'create'
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.26.1/libexec/lib/python3.8/site-packages/azure/cli/command_modules/acr/task.py", line 804, in acr_task_timer_remove
    return client.create(resource_group_name=resource_group_name,
AttributeError: 'TasksOperations' object has no attribute 'create'

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az acr task timer remove -n {} -r {} -g {} --timer-name {}`

This is failing on my local computer runnning mac os. It is also failing on the ubuntu-18.04 agent in VSTS.

## Expected Behavior

The command should remove the schedule

## Environment Summary
```
macOS-11.4-x86_64-i386-64bit
Python 3.8.11
Installer: HOMEBREW

azure-cli 2.26.1

```
## Additional Context

This was working until upgrading to azure cli 2.26.1. Was previously running 2.25.x

### PR DESCRIPTION
**Pull request by rosanch**
**Description**
Fixes #18903 #18949 #18881 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
trackV2

**Review by northtyphoon — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@rosanch  The change from this PR should not be written into the release note, right? Please help confirm whether the PR title I modified is appropriate

**Comment by zhoxing-ms** [comment]
@rosanch Could you test these changes in live mode?

**Comment by jsntcy** [comment]
@rosanch, We'll release Azure CLI the day after tomorrow, please ensure you test the changes before that time.

**Comment by rosanch** [comment]
@zhoxing-ms these issues happened because these changes are not covered in the CLI automated tests. So there's really no point in running that test. I did however test the changes manually in my environment.

**Comment by zhoxing-ms** [comment]
Let's merge this PR first this time. Please add relevant test cases in the future~

**Pull request merged**
