### PR TITLE
[App Service] Fix #21728: `az webapp deployment github-actions add`: Allow passing in runtime with colon delimiter

### LINKED ISSUE #21728: Runtimes documentation slightly misleading
> 
> --runtime -r
> 
> Canonicalized web runtime in the format of Framework|Version, e.g. "PHP|5.6". Use "az webapp list-runtimes" for available list.
> 

The documentation is subtly misleading here - I read it to mean I could take the output from `az webapp list-runtimes` and use that output in the `github-actions add` call - however, I need to change the colon to a pipe.

```
az webapp list-runtimes
{
  "linux": [
    "DOTNETCORE:6.0",              // Note name listed here uses colon, not pipe.
    "DOTNETCORE:5.0",
    "DOTNETCORE:3.1",
...
```

Mistakenly using `DOTNETCORE:6.0` fails as follows:
```
az webapp deployment github-actions add --name <name>--repo <repo> --resource-group <resource group> --branch development --token <ghp_xxx> --runtime "DOTNETCORE:6.0"
Verified GitHub repo and branch
The app runtime: {app_runtime_string} does not match the runtime specified: {runtime}. Using the specified runtime {runtime}.
Runtime DOTNETCORE:6.0 is not supported for GitHub Actions deployments.
```

Using the correct format `DOTNETCORE|6.0` succeeds:
```
az webapp deployment github-actions add --name <name>--repo <repo> --resource-group <resource group> --branch development --token <ghp_xxx> --runtime "DOTNETCORE|6.0"
```

I wonder if either this could be made clearer in the documentation, or perhaps the az cli commands could be made consistent?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b397bce-4a07-9d15-d36c-ebed2f8bcc4e
* Version Independent ID: f31c415e-bb0f-14f3-b19f-e3496d816101
* Content: [az webapp deployment github-actions](https://docs.microsoft.com/en-us/cli/azure/webapp/deployment/github-actions?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/webapp/deployment/github-actions.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/webapp/deployment/github-actions.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

### PR DESCRIPTION
**Pull request by StrawnSC**
**Description**

Fixes #21728

**Testing Guide**

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
App Service

**Review by wangzelin007 — APPROVED** [review]

**Comment by panchagnula** [comment]
@calvinsID can you review the PR. @StrawnSC is there a mock test we can add to ensure that we catch such issues in the future?

**Comment by StrawnSC** [comment]
@panchagnula we don't have any mocked tests covering `webapp deployment github-actions add`. I'll go ahead and add one to cover this

**Review by calvinsID — APPROVED** [review]
Looks good!

**Comment by zhoxing-ms** [comment]
@StrawnSC Could you please resolve those CI issues?

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
