### PR TITLE
[Cognitive Services] Support identity management and BYOX for Cognitive Services.

### PR DESCRIPTION
**Pull request by yangyuan**
**Description**  
Add identity management for Cognitive Services.
Identity support is necessary for using user owned storage or encryption.

**Testing Guide**  
`az cognitiveservices account identity show` show the identity of an account, empty object will be displayed if no identity has been assigned.
`az cognitiveservices account identity assign` assign an identity to an account.
`az cognitiveservices account identity remove` remove the identity from an account, should still pass if account has no identity.

**History Notes**  

[Cognitive Services] az cognitiveservices account identity: Add identity management for Cognitive Services.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S171

**Comment by yangyuan** [comment]
Hi @haroldrandom, there is one test failure, but seems to be totally not related to Cognitive Services. And only in Python36 test CI. Can we skip that and merge the change?
This feature is part of JEDI and we would like this to be release soon.

**Pull request merged**
