### PR TITLE
{Service Fabric} Remove `OpenSSL.crypto.loads_pkcs12`

### PR DESCRIPTION
**Pull request by mwesigwaguma**
**Related command**

**Description**

Removing `crypto.load_pkcs12` function as it's getting deprecated

Related PR: https://github.com/Azure/azure-cli/pull/28306

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by jiasli — DISMISSED** [review]

**Comment by bebound** [comment]
`test_update_settings_and_reliability` fails, please check your recording.

**Comment by mwesigwaguma** [comment]
> `test_update_settings_and_reliability` fails, please check your recording.

@bebound please approve and merge changes

**Comment by bebound** [comment]
Style check fails
```
ERROR: /mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/servicefabric/custom.py:1397:47: E261 at least two spaces before inline comment
/mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/servicefabric/custom.py:1397:47: E261 at least two spaces before inline comment
2     E261 at least two spaces before inline comment
```

**Comment by mwesigwaguma** [comment]
> Style check fails
> 
> ```
> ERROR: /mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/servicefabric/custom.py:1397:47: E261 at least two spaces before inline comment
> /mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/servicefabric/custom.py:1397:47: E261 at least two spaces before inline comment
> 2     E261 at least two spaces before inline comment
> ```

@bebound please approve and merge

**Review by bebound — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@mwesigwaguma Could you please ask the engineers from your team to also approve this PR?

**Review by a-santamaria — APPROVED** [review]

**Pull request merged**
