### PR TITLE
[Iot Hub] az iot hub create: Remove check for name availability call (#7792)

### LINKED ISSUE #7792: IoT Hub Create is not idempotent
**Describe the bug**
CLI command guidelines require CREATE commands to be idempotent:
https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md

`iot hub create` has a client-side check for name availability that will cause the command to fail if run twice. This client-side check should be removed.

**To Reproduce**
Run `az iot hub create ...` twice with the same parameters. An error will be thrown.

**Expected behavior**
The second call should succeed.

### PR DESCRIPTION
**Pull request by montgomp**
**Description**  
Fix #7792: az iot hub create is not idempotent

**History Notes**  
[IoT] az iot hub create: Remove check name availability call so that create flow is idempotent.   

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
IoT

**Comment by zhoxing-ms** [comment]
@montgomp Hi, the incorrect format of PR title affects CI. 
I suggest that it might be better to change the PR title, like: `[Iot Hub] az iot hub create: Remove check for name availability call (#7792)`
PR title writing guide: [link](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests)

**Comment by zhoxing-ms** [comment]
ADO rerun

**Comment by zhoxing-ms** [comment]
pipeline rerun

**Comment by zhoxing-ms** [comment]
@montgomp Hi, there are still some tests that fail. You need to execute the relevant tests in live mode locally and submit the generated record file.
So please execute the following command locally:
azdev test test_iot_hub --live 
azdev test test_iot_hub --live --profile 2019-03-01-hybrid

**Comment by zhoxing-ms** [comment]
Replaced by PR #14449

**Pull request closed without merging**
