### PR TITLE
Changed "digitaltwin" command group name to PnP

### PR DESCRIPTION
**Pull request by anusapan**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by anusapan** [comment]
This PR is an update of https://github.com/Azure/azure-cli/pull/9549
and this needs to be added in milestone 66

**Comment by tjprescott** [comment]
Agree w/ @yugangw-msft. Please see: https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#deprecating-commands-and-arguments

**Comment by yugangw-msft** [comment]
And the guideline to mark it as preview is [here](https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/authoring_commands.md#preview-commands-and-arguments)

**Comment by anusapan** [comment]
@yugangw-msft marked `az iot pnp` as preview

**Pull request merged**
