### PR TITLE
Chore: move CredScansuppressions.json to codeownder guarded folder

### PR DESCRIPTION
**Pull request by haroldrandom**
Move CredScanSuppressions.json to a codeownder guarded folder for the sake of awearnes when others modify it without codeowner or recklessness of reviewers

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by fengzhou-msft** [comment]
Chore in title?

**Comment by haroldrandom** [comment]
> Chore in title?

Similate this https://github.com/Azure/aks-engine/pulls?

**Comment by fengzhou-msft** [comment]
> > Chore in title?
> 
> Simulate this https://github.com/Azure/aks-engine/pulls?

I mean typo.

**Comment by haroldrandom** [comment]
> > > Chore in title?
> > 
> > 
> > Simulate this https://github.com/Azure/aks-engine/pulls?
> 
> I mean typo.

Updated

**Pull request merged**
