### PR TITLE
[Monitor] Bug fix - diagnostic settings create does not accept logs/metrics from show commands

### PR DESCRIPTION
**Pull request by vishrutshah**
Fixes https://github.com/Azure/azure-cli/issues/2913
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [ ] Each command and parameter has a meaningful description.
- [ ] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by vishrutshah** [comment]
@tjprescott Are you referring to use https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/azure/cli/core/util.py#L94 ?

**Comment by tjprescott** [comment]
@vishrutshah yes, that would be the generic thing that does this... however, more to the point, I don't think that the "JSON object" easy-out is the way to go with this command.

**Comment by vishrutshah** [comment]
@tjprescott I agree that we need a better way to handle JSON. 

I am not targeting that work as part of this PR, the goal i am having is to fix the bug and then we can definitely make the better commands because based on the our last discussion with the Rajesh, he mentioned that there are many things can be improved including metrics, logs and other surface area. I'd like to work with them on customer usage pattern before i can make this better as separate work item. 

What are your thoughts?

**Comment by vishrutshah** [comment]
Thanks for the review!!

**Pull request merged**
