### PR TITLE
Update galleries API version to 2019-07-01

### PR DESCRIPTION
**Pull request by qwordy**
Update galleries API version to 2019-07-01
Issue #10716

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by MyronFanQiu** [comment]
@qwordy Just one question. Why don't you increase the whole vm's API-version to 2019-07-01?

**Comment by qwordy** [comment]
> 
> 
> @qwordy Just one question. Why don't you increase the whole vm's API-version to 2019-07-01?

I don't want to involve more risks.

**Comment by MyronFanQiu** [comment]
> > @qwordy Just one question. Why don't you increase the whole vm's API-version to 2019-07-01?
> 
> I don't want to involve more risks.

Well. finally, on some day in the future, you will need to bump the whole version. Anyway, it's up to you.

**Comment by qwordy** [comment]
> 
> 
> > > @qwordy Just one question. Why don't you increase the whole vm's API-version to 2019-07-01?
> > 
> > 
> > I don't want to involve more risks.
> 
> Well. finally, on some day in the future, you will need to bump the whole version. Anyway, it's up to you.

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01

There is no other content other than gallery here. So we can't update vm version.

**Pull request merged**
