### PR TITLE
{Packaging} Update homebrew formula_template for Python 3.9

### PR DESCRIPTION
**Pull request by bsiegel**
**Description**
Python 3.9 support was landed in azure-cli 2.24.0. This PR updates the MacOS Homebrew formula template to bump the python dependency to 3.9.

**Testing Guide**
- Generate the template locally and install it in your `homebrew-core/Formula` directory (or, make the same changes to the existing copy of the azure-cli.rb formula located in that directory)
- Test the updated formula as usual:
  - `brew uninstall --force azure-cli`
  - `brew install --build-from-source azure-cli`
  - `brew test azure-cli`
  - `brew audit --strict azure-cli`
  - `brew style azure-cli`

**History Notes**
{Packaging}: Update homebrew formula_template for Python 3.9

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Packaging

**Comment by jiasli** [comment]
We are recently in the process of reorg and knowledge transition. We will review and test this PR as soon as we have bandwidth.

**Comment by bsiegel** [comment]
Hey @jiasli, @yonzhan - any update on this? It's a one-line change which unblock a significant improvement for Homebrew users on Mac. Python 3.9 support was merged in #17368 and the tracking issue #16611 is closed, so little in the way of testing should need to be performed.

**Comment by ionutbalutoiu** [comment]
> Hey @jiasli, @yonzhan - any update on this? It's a one-line change which unblock a significant improvement for Homebrew users on Mac. Python 3.9 support was merged in #17368 and the tracking issue #16611 is closed, so little in the way of testing should need to be performed.

I strongly agree with this! I am waiting since a while to have this PR merged, so I can use Azure CLI with Homebrew.

I have an M1 machine, and only Python >= 3.9 runs natively. So, there's no way I'm going to install Python 3.8.

Also, since Azure CLI got Python 3.9 support, I'm running it from a manual virtual environment, and I had no problems at all! But, I want to be able to cleanly use Azure CLI with Homebrew, without needing a separate virtual environment that I need to take care of.

Please prioritize this!

**Review by jiasli — APPROVED** [review]

**Comment by jiasli** [comment]
Tried changing to

https://github.com/Azure/azure-cli/blob/e7db62369acbb66b9ad5a3315fbad5c6424f7719/scripts/release/homebrew/docker/run.sh#L15

so that formula is built from local template:

https://github.com/Azure/azure-cli/blob/f8c072cca8854264360dbf3e4f1a52eef895af40/scripts/release/homebrew/docker/formula_template.txt#L20

The CI shows no problem with Python 3.9. 🎉

https://dev.azure.com/azure-sdk/public/_build/results?buildId=1047088&view=logs&j=ebe8970d-a8af-5d7e-4086-8f4ce0be006b&t=3f22f999-770c-5d06-3bb8-1a936f5d8384&l=335

```
2021-08-13T13:26:14.4517640Z echo == Az Version ==
2021-08-13T13:26:14.4521530Z az --version
2021-08-13T13:26:14.4522720Z == Az Version ==
2021-08-13T13:26:15.3657670Z WARNING: You have 2 updates available. Consider updating your CLI installation with 'az upgrade'
2021-08-13T13:26:15.3659380Z 
2021-08-13T13:26:15.5209650Z Please let us know how we are doing: https://aka.ms/azureclihats
2021-08-13T13:26:15.5212130Z and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
2021-08-13T13:26:15.5926120Z azure-cli                         2.27.0 *
2021-08-13T13:26:15.5927580Z 
2021-08-13T13:26:15.5928770Z core                              2.27.0 *
2021-08-13T13:26:15.5929990Z telemetry                          1.0.6
2021-08-13T13:26:15.5930830Z 
2021-08-13T13:26:15.5932370Z Python location '/usr/local/Cellar/azure-cli/2.27.0/libexec/bin/python'
2021-08-13T13:26:15.5934030Z Extensions directory '/Users/runner/.azure/cliextensions'
2021-08-13T13:26:15.5934920Z 
2021-08-13T13:26:15.5936010Z Python (Darwin) 3.9.6 (default, Jun 29 2021, 06:20:32) 
2021-08-13T13:26:15.5937530Z [Clang 12.0.0 (clang-1200.0.32.29)]
2021-08-13T13:26:15.5938380Z 
2021-08-13T13:26:15.5939430Z Legal docs and information: aka.ms/AzureCliLegal
2021-08-13T13:26:15.5940270Z 
2021-08-13T13:26:15.5941290Z 
2021-08-13T13:26:15.6332000Z 
2021-08-13T13:26:15.6334900Z echo == Run Self-Test ==
2021-08-13T13:26:15.6336640Z az self-test
2021-08-13T13:26:15.6337680Z == Run Self-Test ==
2021-08-13T13:26:17.1824470Z WARNING: This command has been deprecated and will be removed in a future release.
2021-08-13T13:26:43.0390660Z Running CLI self-test.
2021-08-13T13:26:43.0392590Z 
2021-08-13T13:26:43.0393790Z Loading all commands and arguments...
2021-08-13T13:26:43.0395060Z Commands loaded OK.
2021-08-13T13:26:43.0397610Z 
2021-08-13T13:26:43.0399350Z Retrieving all help...
2021-08-13T13:26:43.0400590Z Help loaded OK.
2021-08-13T13:26:43.0401400Z 
2021-08-13T13:26:43.0403000Z CLI self-test completed: OK
```

**Comment by jiasli** [comment]
Merging this PR so that https://github.com/Homebrew/homebrew-core/pull/83088 can be merged.

**Comment by jiasli** [comment]
@bsiegel, @ionutbalutoiu, Thank you so much for your contribution! Truly glad we are in such an excellent community!

**Comment by carlocab** [comment]
> I have an M1 machine, and only Python >= 3.9 runs natively.

Python 3.8 also runs natively on ARM when installed via Homebrew. That said, you need not wait for much longer. See Homebrew/homebrew-core#83088.

**Pull request merged**
