### PR TITLE
[Compute] Upgrade VMAccessAgent version to 2.4

### PR DESCRIPTION
**Pull request by qwordy**
#12633
Version 2.0 is out-of-date.

**History Notes:**  
(Fill in the following template if multiple notes are needed, otherwise PR title will be used for history note.)

[Component Name 1] (BREAKING CHANGE:) (az command:) make some customer-facing change.  
[Component Name 2] (BREAKING CHANGE:) (az command:) make some customer-facing change.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by qwordy** [comment]
> 
> 
> any doc update? how to test it?

No. This extension is used in more than one comands. The user in the incident is using `az vm user update`.
I updated test.

**Comment by qwordy** [comment]
> 
> 
> yes, seems this is a BREAKING CHANGE, it changes the behaviors of previous commands. And can we add tests for the scenarios we already know ?

The UI doesn't change. But version changes. It remains to be discussed whether it should be considered as a breaking change.
I updated test.

**Comment by yungezz** [comment]
> > yes, seems this is a BREAKING CHANGE, it changes the behaviors of previous commands. And can we add tests for the scenarios we already know ?
> 
> The UI doesn't change. But version changes. It remains to be discussed whether it should be considered as a breaking change.
> I updated test.

how to notify user about the change since there's no interface change, and no doc change so far? Is there any doc about this?

**Comment by axelgMS** [comment]
+ need to fix doc [10755](https://github.com/Azure/azure-powershell/pull/10755)

**Comment by yungezz** [comment]
> * need to fix doc [10755](https://github.com/Azure/azure-powershell/pull/10755)

HI @axelgMS the linked issue in azure powershell repo.

**Comment by qwordy** [comment]
> 
> 
> > > yes, seems this is a BREAKING CHANGE, it changes the behaviors of previous commands. And can we add tests for the scenarios we already know ?
> > 
> > 
> > The UI doesn't change. But version changes. It remains to be discussed whether it should be considered as a breaking change.
> > I updated test.
> 
> how to notify user about the change since there's no interface change, and no doc change so far? Is there any doc about this?

I'll notify user in `vm user update` command. But problem is there is no central way to announce the change. This extension is used in more than one commands.

**Comment by yungezz** [comment]
> 

got it. How about add detail in help message of this command? Any other suggestion?

**Pull request merged**
