### PR TITLE
[App Service] `az functionapp create`: Only allow apps with functions version 4

### PR DESCRIPTION
**Pull request by kamperiadis**
**Related command**
`az functionapp create`

**Description**
Created to resolve this: https://github.com/Azure/azure-cli/issues/25340
We need to only allow function version 4 during app creation. 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AppService

**Review by arroyc — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
> Only allow apps with functions version 4

I would like to confirm if this change will cause breaking changes for the customer?

**Comment by zhoxing-ms** [comment]
@kamperiadis Could you please resolve these conflicts?

**Comment by kamperiadis** [comment]
> > Only allow apps with functions version 4
> 
> I would like to confirm if this change will cause breaking changes for the customer?

Hi @zhoxing-ms These changes only apply to new function apps that are being created so customers with existing function apps should not be affected. For those customers who have the `az functionapp create` command in a script, we already have documentation [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=isolated-process%2Cv4&pivots=programming-language-java#retired-versions) that informs them that previous versions are no longer supported.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
