### PR TITLE
[Security] Fix update alert command and support new value

### PR DESCRIPTION
**Pull request by yibirnba**
**Description**

Fix update alert command and support new value 'Resolved'

**Testing Guide**

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yibirnba** [comment]
Hi @haroldrandom  ,
Can you please review this PR? It is open but no one is assigned

**Comment by yonzhan** [comment]
@haroldrandom please help with this.

**Comment by haroldrandom** [comment]
@yibirnba It's blocked by new pip issue, we are aware of it and trying to work it out

**Comment by yibirnba** [comment]
Thanks @haroldrandom , will it run again automatically when issue fixed? (I just want to have enough time to current milestone before the code freeze arrives)

**Review by haroldrandom — APPROVED** [review]

**Pull request merged**
