### PR TITLE
[AKS] `az aks upgrade`: Show warning if the Kubernetes version isn't supplied

### PR DESCRIPTION
**Pull request by paulgmiller**
**Related command**

az aks upgrade 

**Description**

Warn on an aks [nodepool] upgrade if k8s version is supplied it will retry upgrade to same version.  User was confused when upgrade without version didn't take them to "newer version"

**Testing Guide**

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by zhoxing-ms** [comment]
@paulgmiller Could you please resolve the conflicts?

**Comment by zhoxing-ms** [comment]
Could you please refer to the document [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests) to refine the PR title

**Comment by zhoxing-ms** [comment]
Please note that since we will launch the release of this sprint the day after tomorrow. If you cannot address all the comments tomorrow, we will have to postpone the release of this PR to the next sprint (02-07)

**Comment by paulgmiller** [comment]
Pushed a merge

**Comment by zhoxing-ms** [comment]
> Running flake8 on modules...
ERROR: /mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/acs/custom.py:2120:1: W293 blank line contains whitespace
/mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/acs/custom.py:2120:1: W293 blank line contains whitespace
2     W293 blank line contains whitespac

@paulgmiller Could you please resolve the code style issue today? If not, we will postpone this PR to the next sprint (02-07)

**Comment by paulgmiller** [comment]
I ran out of time to fix the whitespace and honestly I'm a little confused by the line numbers 
2120 in the difff and locall is
            "Node pool {} doesnt exist, use 'aks nodepool list' to get current node pool list".format(nodepool_name))
            
            which is neither blank nor has  trailing whitepae. 
           
So I just went through all added blank lines and found it.

**Review by FumingZhang — APPROVED** [review]
LGTM

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
