### PR TITLE
On-board Management Partner

### PR DESCRIPTION
**Pull request by jeffrey-ACE**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [x] Each command and parameter has a meaningful description.
- [x] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/5648
This is an **experimental preview** for @microsoft users.

**Comment by jeffrey-ACE** [comment]
This is the previous PR: https://github.com/Azure/azure-cli/pull/5545, because it has too many commits, aborted it and create this new one.

**Comment by derekbekoe** [comment]
@jeffrey-ACE This file should not be checked in `src/command_modules/azure-cli-managementpartner/.vscode/settings.json`

**Comment by yugangw-msft** [comment]
The command hierarchy looks good to me

**Comment by derekbekoe** [comment]
@tjprescott to review.

**Comment by tjprescott** [comment]
Closing in favor of the extensions PR.

**Pull request closed without merging**
