### PR TITLE
Improve UX for Management Lock delete

### PR DESCRIPTION
**Pull request by brendandburns**
This isn't strictly necessary, but it improves the user UX.

If the user asks us to delete a lock that we can find in a different scope, print better error messages to help the user do the right thing.

Addresses:

https://github.com/Azure/azure-cli/issues/2688

### CODE REVIEW

**Comment by tjprescott** [comment]
@brendandburns could you rebase this and fix the linter checks so we can merge this?

**Comment by brendandburns** [comment]
@tjprescott rebased.

Thanks

**Comment by tjprescott** [comment]
@brendandburns it still fails the CI because of linter errors.

**Comment by brendandburns** [comment]
oops, I missed a merge conflict. fixed and re-pushed.

Thanks
--brendan

**Pull request merged**
