### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by rich-zilla**
Fix Typo

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- N/A Each command and parameter has a meaningful description.
- N/A Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/5723
This is an **experimental preview** for @microsoft users.

**Comment by tjprescott** [comment]
Because this is the first change to the profile module post-release, it needs a version bump.

**Comment by tjprescott** [comment]
This is why we need #5955...

**Comment by derekbekoe** [comment]
Closing this as it needs to be rebased in favor of https://github.com/Azure/azure-cli/pull/6151

**Pull request closed without merging**
