### PR TITLE
{Functions} Fix dotnet-isolated 5 settings

### PR DESCRIPTION
**Pull request by pragnagopa**
**Description**

change netFrameworkVersion from v5.0 to v4.0

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by pragnagopa** [comment]
cc @safihamid @fabiocav @anthonychu @gzuber

**Comment by yonzhan** [comment]
Functions

**Comment by wangzelin007** [comment]
Change [] to {}, {} means this change is not customer-facing and the message will NOT be included in HISTORY.rst.

**Review by wangzelin007 — APPROVED** [review]
LGTM

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
