### PR TITLE
{ACR} Fix "Message: The subscription '00000000-0000-0000-0000-000000000000' could not be found." test error by waiting for operation

### PR DESCRIPTION
**Pull request by nguyenm2151**
**Related command**

```
az acr agentpool delete
az acr connected-registry delete
```
**Description**

Fix  "Message: The subscription '00000000-0000-0000-0000-000000000000' could not be found." test error by waiting for delete operation to finish. Addressing these two issues https://github.com/Azure/azure-cli/pull/18853#discussion_r1810260089 and https://github.com/Azure/azure-cli/pull/18611#discussion_r1810284183 following this solution https://github.com/Azure/azure-cli/pull/17185

**Testing Guide**

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by zhoxing-ms** [comment]
Could you please recover the tests which was disabled in this PR? https://github.com/Azure/azure-cli/pull/30164/files

**Comment by zhoxing-ms** [comment]
Why did you recover so many tests when only two tests were disabled in this PR https://github.com/Azure/azure-cli/pull/30164 ?

**Comment by nguyenm2151** [comment]
@zhoxing-ms I saw in this comment that all tests skipped in this PR are all related to the acr bug. Let me know if this is correct. If not, I can recover only the two acr tests. https://github.com/Azure/azure-cli/pull/30164#issuecomment-2436716669

**Review by zhoxing-ms — APPROVED** [review]

**Comment by bebound** [comment]
@nguyenm2151  `test_acr_connectedregistry` still fails with same error.

Ref: https://dev.azure.com/azclitools/public/_build/results?buildId=202957&view=logs&jobId=6e72cc3a-a00a-59be-9f4b-e33f56a1b1f5&j=4a070aa6-03ff-5caf-6490-ded6aca0ca24&t=9afa7565-c847-5b45-dd7a-f91034321474

**Pull request merged**
