### PR TITLE
Improve batch module load performance on Knach

### PR DESCRIPTION
**Pull request by troydai**
In A0 machine, reduce load time from 0.8s to 0.07s. This change delay the operation hander fetching.

This is a concept need more rigorous testing.

### CODE REVIEW

**Comment by tjprescott** [comment]
The CI complains about an undefined `op_handler` in your code.

**Comment by annatisch** [comment]
Yes, op_handler is used again to make the request around line 495:
`result = op_handler(client, **kwargs)`

**Comment by troydai** [comment]
Will fix. Aside from that, @annatisch, does the change look good to you?

**Comment by troydai** [comment]
Updated.

**Comment by annatisch** [comment]
Yup @troydai - LGTM

**Comment by troydai** [comment]
Great. @tjprescott the `AzureBatchDataPlaneCommand` doesn't inherit the `AzCliCommand` therefore it doesn't have an access to the `command_loader`. We may want to revisit the design later.

**Comment by troydai** [comment]
Automation failed, but no new tests fail comparing to the KnackFinal branch. I'll therefore merge this to the `KnachFinal_2.0.24` branch soon.

**Pull request merged**
