### PR TITLE
[IoT] Deprecated command group 'iot hub job'

### PR DESCRIPTION
**Pull request by anusapan**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by anusapan** [comment]
image

**Expected output when someone uses these commands.**

**Comment by digimaun** [comment]
Please hold off on merging this for a bit, we have a couple issues to work out on the go forward.

**Comment by yonzhan** [comment]
add to S164.

**Comment by digimaun** [comment]
Thank you for waiting on this. We are good to move forward with the deprecation. @anusapan as fyi.

**Comment by qwordy** [comment]
Is this PR ready to merge?

**Comment by anusapan** [comment]
@qwordy Yes, It is ready to merge.
@digimaun FYI

**Pull request merged**
