### PR TITLE
[Container] Update container cmdlets to use 2024-05-01-preview version API

### PR DESCRIPTION
**Pull request by drishtipeshwani09**
**Related command**
az container 

**Description**

- We are in process of releasing some new features, one of them is a new azure resource called ContainerGroupProfile.
- For that, added a new command group called az container container-group-profile, this includes commands related to various resource operations like create,list,show,delete and operations related to revisions.
- Modified the az container create command to include new container group properties.
- Additionally, added the required test scenarios. 

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Review by kaushik-ms — APPROVED** [review]

**Comment by yonzhan** [comment]
Please fix CI issues

**Comment by kaushik-ms** [comment]
> Please fix CI issues

The pr title has been changed.
The checks till points to previous title.
The --deployment-resource-group is not from our pr

**Comment by kaushik-ms** [comment]
for the option_length_too_long, exceptions are already added in linter)eexclusions.yml

**Comment by kaushik-ms** [comment]
AzureCLI-FullTest

**Comment by jrathore-msft** [comment]
@zhoxing-ms - can you please re-trigger the build so the checks can run again on the latest changes so that all checks are successful

**Comment by zhoxing-ms** [comment]
image

@jrathore-msft Please resolve these CI issues

**Comment by yanzhudd** [comment]
replaced by a new PR: https://github.com/Azure/azure-cli/pull/30260

**Pull request closed without merging**
