### PR TITLE
Introduce azure.cli.core.api to provide unified interfaces module

### PR DESCRIPTION
**Pull request by troydai**
Refactory the core code. Consolidate the utility methods and remove unnecssary `_`-initialzed module.

### CODE REVIEW

**Comment by troydai** [comment]
@tjprescott I fixed all the references to this method in the CLI.

**Comment by tjprescott** [comment]
I'm thinking specifically about partner team tooling like VSCode extensions or anything that might be relying on that import path.  You should be able to relocate it, update the CLI references, but ensure the old import path still works. Whether you want to do that is up to you, but it is something to consider.

**Comment by troydai** [comment]
This shouldn't be a problem. The original module is actually private, so depends on it is not a good idea by itself. I will check the extension repo and VS code repo.

**Comment by troydai** [comment]
* https://github.com/Microsoft/vscode-azurecli/search?q=get_config_dir&unscoped_q=get_config_dir
* https://github.com/Azure/azure-cli-extensions/search?q=get_config_dir&unscoped_q=get_config_dir

**Comment by troydai** [comment]
Repurpose this PR.

**Comment by troydai** [comment]
@tjprescott ?

**Pull request merged**
