### PR TITLE
{Doc} Fix spelling (mySubscrpitionId)

### PR DESCRIPTION
**Pull request by scovetta**
**Description**
Documentation change, fixes misspelling "mySubscrpitionId".

**Testing Guide**
n/a

**History Notes**

[Container] Fix misspelling in `az container create` CLI example text.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
container

**Review by fengzhou-msft — APPROVED** [review]

**Review by jiasli — APPROVED** [review]
Thanks for the contribution.

**Comment by jiasli** [comment]
Found a similar typo here:

https://github.com/Azure/azure-sdk-for-python/blob/2154e14af164617b309fe49c6eb9d626fcb93772/sdk/servicebus/azure-mgmt-servicebus/tests/test_cli_mgmt_servicebus_topic.py#L30

```py
def test_subscrpition_and_rule(self, resource_group):
```

**Review by yungezz — APPROVED** [review]

**Pull request merged**
