### PR TITLE
[ARO] Fail if resource doesn't exist on delete

### PR DESCRIPTION
**Pull request by bennerv**
**Description**
If someone calls `az aro delete` on a non-existing resource, print out a helpful error instead of a stack trace.  
#18501 

**Testing Guide**
`az aro delete -g non-existing -n non-existing` should now raise a ResourceNotFoundError

### CODE REVIEW

**Comment by bennerv** [comment]
cc @mjudeikis @jewzaam

**Comment by yonzhan** [comment]
ARO

**Comment by kairu-ms** [comment]
Please fix ci issues.

**Comment by bennerv** [comment]
@kairu-ms 
> Please fix ci issues.

It keeps erroring out on quota issues.  Is there a way to increase quota for this to not happen?  I've attempted to amend and repush the same commit over 7 times now and it has failed every time on quota issues. 

> Resource quota of standardDSv3Family exceeded. Maximum allowed: 500, Current in use: 482, Additional requested: 36.

**Comment by kairu-ms** [comment]
> @kairu-ms
> 
> > Please fix ci issues.
> 
> It keeps erroring out on quota issues. Is there a way to increase quota for this to not happen? I've attempted to amend and repush the same commit over 7 times now and it has failed every time on quota issues.
> 
> > Resource quota of standardDSv3Family exceeded. Maximum allowed: 500, Current in use: 482, Additional requested: 36.

I think this error message is from service response. Was this test passed in live mode on your machine?

**Comment by bennerv** [comment]
> > @kairu-ms
> > > Please fix ci issues.
> > 
> > 
> > It keeps erroring out on quota issues. Is there a way to increase quota for this to not happen? I've attempted to amend and repush the same commit over 7 times now and it has failed every time on quota issues.
> > > Resource quota of standardDSv3Family exceeded. Maximum allowed: 500, Current in use: 482, Additional requested: 36.
> 
> I think this error message is from service response. Was this test passed in live mode on your machine?

@kairu-ms 
That was it.  Could've sworn they were all green when I pushed them originally.  Thanks for the help! :+1:

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
