### PR TITLE
[Network] Fix issue with `--dns-servers` on VNET update

### LINKED ISSUE #4745: Impossible to `az network vnet update --dns-servers` if you haven't first set a Custom DNS server from the portal.
Hello all, I have recently tried to `az network vent update --dns-servers` a vnet that was using the default Azure DNS Servers. Upon doing so, the following stacktrace appears:

```
Dir: /home/tj/git/Movere.Dev.Builder [master] 
Usr: tj - Tue 24,  1:10PM > az network vnet update --name mov-dev-we-vnet --resource-group movere-dev-we --dns-servers 172.17.32.4 8.8.8.8
'NoneType' object has no attribute 'dns_servers'
Traceback (most recent call last):
  File "/usr/bin/azure-cli/lib/python3.6/site-packages/azure/cli/main.py", line 36, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/bin/azure-cli/lib/python3.6/site-packages/azure/cli/core/application.py", line 212, in execute
    result = expanded_arg.func(params)
  File "/usr/bin/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 377, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/bin/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 450, in handler
    raise ex
  File "/usr/bin/azure-cli/lib/python3.6/site-packages/azure/cli/core/commands/arm.py", line 405, in handler
    instance = custom_function(instance, **custom_func_args)
  File "/usr/bin/azure-cli/lib/python3.6/site-packages/azure/cli/command_modules/network/custom.py", line 1672, in update_vnet
    instance.dhcp_options.dns_servers = dns_servers
AttributeError: 'NoneType' object has no attribute 'dns_servers'
```

However, executing that command once you have set any arbitrary custom DNS server from the portal will succeed. This seems like a bug, but may not be based on the verb `az network UPDATE`. But I'm not sure. 

If this is not the supported method to specify a DNS server for a vnet from the command line for the first time, please advise on how this should correctly be done.

### PR DESCRIPTION
**Pull request by tjprescott**
Fix #4745.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [X] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [X] Each command and parameter has a meaningful description.
- [N/A] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by zimmertr** [comment]
@tjprescott when will this fix make its way into an official packaged release?

**Comment by tjprescott** [comment]
It will be in this week's release.

**Comment by zimmertr** [comment]
@tjprescott are you referring to azure-cli-2.0.21 that came out yesterday? Or yet another upcoming release this week? 

Based on the commits to that release it's likely the one pushed out yesterday?

**Comment by tjprescott** [comment]
Yes it should be released now. Please give it a try.

**Pull request merged**
