### PR TITLE
{Eventhub} API-Version for all `az eventhubs` cmdlets updated to 2023-01-01-preview

### PR DESCRIPTION
**Pull request by schaudhari6254888**
**Related command**

**Description**
In this PR, all cmdlets are upgraded to api-version=2023-01-01-preview. To eliminate inconsistency and avoid cross-api-version issues, this PR updated all cmdlets to the most recent API version.  

**Testing Guide**

**History Notes**

{EventHub} API-Version for all `az eventhubs` cmdlets are updated to 2023-01-01-preview

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Eventhub

**Comment by evelyn-ys** [comment]
PR looks good to me in general. But please refine title and PR description following https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests

**Comment by schaudhari6254888** [comment]
> PR looks good to me in general. But please refine title and PR description following https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests

Hey @evelyn-ys, I have added the PR description & modified the title as well.

**Review by evelyn-ys — DISMISSED** [review]

**Comment by necusjz** [comment]
@schaudhari6254888 `src/azure-cli/azure/cli/command_modules/network/tests/loa1.pdf` should not be summited

**Comment by schaudhari6254888** [comment]
> @schaudhari6254888 `src/azure-cli/azure/cli/command_modules/network/tests/loa1.pdf` should not be summited

Removed!

**Review by necusjz — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
