### PR TITLE
[App Service] Fix #20757: `az webapp up`:  Fix list index out of range when no `--plan` argument passed

### LINKED ISSUE #20757: WebApp:az webapp up fails when providing --name without --plan parameter
## Describe the bug

**Command Name**
`az webapp up`

**Errors:**
```
The command failed with an unexpected error. Here is the traceback:
list index out of range
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 713, in _run_job
    return cmd_copy.exception_handler(ex)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/commands.py", line 38, in _ex_handler
    raise ex
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/custom.py", line 3953, in webapp_up
    plan = get_plan_to_use(cmd=cmd,
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/_create_util.py", line 385, in get_plan_to_use
    return _determine_if_default_plan_to_use(cmd, _default_asp, resource_group_name, loc, sku, create_rg)
  File "/opt/homebrew/Cellar/azure-cli/2.31.0/libexec/lib/python3.10/site-packages/azure/cli/command_modules/appservice/_create_util.py", line 404, in _determine_if_default_plan_to_use
    _asp_generic = plan_name[:-len(plan_name.split("_")[4])]
IndexError: list index out of range

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az webapp up -n {} -g {} -l {} --dryrun --debug`

## Environment Summary
```
macOS-12.0.1-arm64-arm-64bit, Darwin 21.1.0
Python 3.10.1
Installer: HOMEBREW

azure-cli 2.31.0

Extensions:
connectedk8s 1.2.0
k8s-extension 1.0.0
customlocation 0.1.3
containerapp 0.2.0
azure-dev 0.0.1b38

```

### PR DESCRIPTION
**Pull request by StrawnSC**
**Description**

Fixes #20757 

**Testing Guide**

`azdev test --live test_webapp_up_no_plan_e2e `

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by StrawnSC** [comment]
Also fixes: 
https://github.com/Azure/azure-cli/issues/20729
https://github.com/Azure/azure-cli/issues/20686

**Comment by panchagnula** [comment]
@StrawnSC thanks for fixing this - this looks like a regression - how did we miss this? I understand az webapp up tests need to run live - but did the existing tests not cover this?

**Comment by StrawnSC** [comment]
@panchagnula yep this is definitely a regression from https://github.com/Azure/azure-cli/pull/20157 -- that's my bad, sorry about that 

As far as I could tell, all the existing `az webapp up` tests (which I recall running live at the time) create an app service plan and pass in an argument for `--plan`. It appears that the tests authors were mainly testing for OS and runtime coverage 

I added a test to the testing suite that doesn't pass in a value for `--plan`

**Review by panchagnula — APPROVED** [review]
Approved

**Comment by yonzhan** [comment]
App Service

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
