### PR TITLE
{network} Add tests for vnet-gateway revoked-cert create and delete

### PR DESCRIPTION
**Pull request by YuanyuanNi**
**Description**

Add tests for vnet-gateway revoked-cert create and delete, below test will be affected:
test_vpn_client_package
**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
network

**Review by wangzelin007 — CHANGES_REQUESTED** [review]
Please re record these tests in live mode.

**Comment by YuanyuanNi** [comment]
It does not have new yaml after running in live mode.

**Comment by wangzelin007** [comment]
> It does not have new yaml after running in live mode.
Please use `class NetworkVpnClientPackageScenarioTest(ScenarioTest):` to re record these tests in live mode, `LiveScenarioTest` is live only.

**Review by wangzelin007 — APPROVED** [review]

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
