### PR TITLE
[Network] `az network vnet subnet list-available-ips`: Get list of available IPs for subnet 

### LINKED ISSUE #13853: Get List of Available IP for Subnet
Azure CLI recently added this command: 

```
az network vnet list-available-ips -g [resource group] -n [vnet name]
```

This works great but only seems to return some ip addresses in the VNet. 

Can we leverage the jmeshquery --query to specify some ip range or a subnet to narrow this down? 

**Is your feature request related to a problem? Please describe.**
Yes, the list-available-ips command doesnt return all available ip's 

For example you may have 192.168.0.0/16 and you may have a bunch of subnets, can we filter to a given subnet, or get all available ip's from the vnet. 

**Describe the solution you'd like**
Option 1 - Possibly use --query to specify the ip range of the subnet or subnet name

Option 2 - Add the same list-available-ips command for az network vnet subnet 

If there is a way to do this, maybe we can document it and update the CLI Docs with an example. 

**Describe alternatives you've considered**
Manually typing random ip's in a range to see if they are consumed. 

**Additional context**
We did this for VNet level but that only returns some of the available ip's.

### PR DESCRIPTION
**Pull request by ZengTaoxu**
**Related command**

az network vnet subnet list-available-ips
**Description**

close #13853 
Add new command 'az network vnet subnet list-available-ips' 
**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Network

**Review by necusjz — APPROVED** [review]

**Comment by webmandman** [comment]
you guys rock. this is perfect timing.

**Comment by webmandman** [comment]
Why does it list only some of the available ips?

image

**Comment by webmandman** [comment]
@necusjz I was expecting this new command to report on all available IPs. Should I create an issue for this?

**Comment by necusjz** [comment]
@webmandman, actually `az network vnet subnet list-available-ips` implemented a functionality similar to `az network vnet list-available-ips` (but at different levels). It'll list **some** available IPs in the VNet.

For your needs, we already have [a similar issue](https://github.com/Azure/azure-cli/issues/22814) for that. Does it meet your expectation? It'll return the number only (not the specific IPs).

Or could you explain the usage scenario for returning all IPs. We need to evaluate the feasibility. Thanks.

**Comment by webmandman** [comment]
@necusjz no you are right. I actually do not need to know all available IPs. I thought maybe this limit was overlooked. Thanks.

**Pull request merged**
