### PR TITLE
Declarative api versions for cli_command

### PR DESCRIPTION
**Pull request by derekbekoe**
Moved from doing:
```
if supported_api_version(ResourceType.MGMT_NETWORK, min_api='2016-09-01'):
    cli_command(...)
```

To:
```
cli_command(..., version_constraint=VersionConstraint(ResourceType.MGMT_NETWORK, min_api='2016-09-01'))
```

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [n/a] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [n/a] Each command and parameter has a meaningful description.
- [n/a] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by derekbekoe** [comment]
Would like some feedback on which you prefer.
The current method or how it would look after this PR is merged.
@tjprescott @troydai @yugangw-msft @johanste

**Comment by derekbekoe** [comment]
@tjprescott I agree that this looks more complex than what we currently have.
Regarding your second point, not sure how feasible it is to include API version info in the command table for these reasons:
- All commands for all API versions would now be in the command table and currently the command table is where we see our biggest perf. hits.
- There are cases where there are multiple implementations of a command based on the API version (e.g. ['storage account create'](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-storage/azure/cli/command_modules/storage/commands.py#L62)). The command table is a dict with key being command name so big changes to our command table would have to be made to support this.

For now, going to leave this PR open to get more feedback but may close eventually.

**Comment by johanste** [comment]
While I agree that the current *implementation* doesn't add the version information to the command table, it would be a simple non-breaking infrastructure change to make it so.

**Comment by tjprescott** [comment]
@johanste I agree--I'm just said without that infrastructure change, I don't see a valid tradeoff. This definitely makes the command authoring process more burdensome and we should only do that if we are gaining something. Without the infrastructure change, we don't gain anything.

@derekbekoe what do you see as the benefit for this implementation over the current method?

**Comment by derekbekoe** [comment]
@tjprescott Don't see a benefit with this PR as is.
Don't see how it will be a simple non-breaking infrastructure change to include this given my longer comment above though.

**Comment by derekbekoe** [comment]
Closing this for now.

**Pull request closed without merging**
