### PR TITLE
[Servicebus] `az servicebus namespace authorization-rule keys renew/list` `az servicebus topic authorization-rule keys renew/list` `az servicebus queue authorization-rule keys renew/list`: Parameter `-n` added to create auth_rule_name

### PR DESCRIPTION
**Pull request by schaudhari6254888**
**Related command**

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Servicebus bug fix

**Comment by schaudhari6254888** [comment]
I have added the `-n` parameter that I have missed in servicebus namespace authorization-rule keys renew/list, servicebus queue authorization-rule keys renew/list, servicebus topic authorization-rule keys renew/list cmdlets.
please take a look & review is.
Sorry for the mistake last time.

**Comment by evelyn-ys** [comment]
@schaudhari6254888 Just want to confirm that you don't need hotfix release, right? It's fine to make this PR included in next normal release?

**Review by evelyn-ys — APPROVED** [review]

**Comment by damodaravadhani** [comment]
We do not have a customer report this bug yet, even if they have, the quickest mitigation here is using "--name" and this seems to be alright for now and can wait for the official release. @evelyn-ys

**Pull request merged**
