### PR TITLE
Fix aliasing issues with expand and ignore

### LINKED ISSUE #5481: expand on a property does not allow to rename its label
Not able to provide "--sku" as parameter label to sku.name in the below object model, because, by default sku has the same label when we do .expand('sku').

For context, here is what the object looks like:
```
{
              name: …
              id: …
              type: …
              properties: { … }
              sku: {
                            name: …
              }
}
```

-	Problem 1: after expanding “sku”, now there are 2 colliding properties in the namespace named “name”
-	Problem 2: “sku” gets default options-list “--sku”, so sku.name cannot have same options-list “—sku”

---

### Environment summary

Install Method (e.g. pip, interactive script, apt-get, Docker, MSI, edge build) / CLI version (`az --version`) / OS version / Shell Type (e.g. bash, cmd.exe, Bash on Windows)  

```
```

### PR DESCRIPTION
**Pull request by tjprescott**
Fixes #5481 and updates knack dependency.

Change ensures that the parameter that is the target of "expand" or "ignore" is aliased to an unusable option so that subsequent calls to "argument" can use the long option names that would have otherwise been claimed. This simplifies the `params.py` file and avoids irritating alias name conflicts.

cc/ @praveenbarli, @rohit-joy 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [n/a] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [n/a] Each command and parameter has a meaningful description.
- [n/a] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/5765
This is an **experimental preview** for @microsoft users.

**Comment by tjprescott** [comment]
ping @derekbekoe

**Comment by derekbekoe** [comment]
Can we make the change in knack then just consume it in the CLI since it seems like a new knack feature.

**Comment by tjprescott** [comment]
@rohit-joy because the test files and recording directory for all modules should not be found under the `latest` directory.

**Comment by tjprescott** [comment]
@derekbekoe is expand in Knack?  If so, I'd be okay with that.

**Comment by derekbekoe** [comment]
Knack doesn't have expand but then it seems like https://github.com/Microsoft/knack/issues/74 has been resolved in this PR but not in knack itself?

**Comment by tjprescott** [comment]
@derekbekoe that's right.  Instead of calling into Knack's ignore, this PR just does what knack's ignore does but adds the mangling.

**Comment by derekbekoe** [comment]
@tjprescott I have released 0.3.2 of knack.

**Comment by tjprescott** [comment]
@derekbekoe sweet. I'll update the PR accordingly. Thanks!

**Comment by tjprescott** [comment]
@derekbekoe can you take a second look?

**Pull request merged**
