### PR TITLE
[AppConfig] Stop overwriting KeyVault reference content type during import

### PR DESCRIPTION
**Pull request by avanigupta**
**Description**

While importing Key Vault references from AppService or AppConfig, we were overwriting the KVR content type with user specified content type. If the source key-value is recognized as a Key Vault reference, we should preserve it in destination too.

**Testing Guide**

`az appconfig kv import -s appconfig -n store2 --src-name store1 --content-type text`

This command would import everything from store1 to store2 with content-type 'text'. All Key Vault References in store1 would be converted to regular key-values in store2 with content-type 'text'.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by avanigupta** [comment]
cc @shenmuxiaosen

**Comment by yonzhan** [comment]
AppConfig

**Review by shenmuxiaosen — APPROVED** [review]
:shipit:

**Comment by avanigupta** [comment]
@zhoxing-ms, could you help review this PR?

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
