### PR TITLE
[DMS] Track1 to track2 and MySQL removal

### PR DESCRIPTION
**Pull request by temandr**
**Description**
- Adding change to support track2 for DMS. 
- Removing MySQL online scenario as that is deprecated.
- Re-enabling the service tests and resolving issues associated with the subnet.

**Testing Guide**
No new tests added. Modified existing tests to remove online MySQL scenario and fixed existing subnet issue

**History Notes**

[DMS]  az dms project create/az dms project task create: Removing MySQL projects/tasks for online migrations since they are no longer supported.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
DMS

**Comment by temandr** [comment]
@yonzhan Looks like the full tests that are failing are failing due to other command modules.

**Review by jsntcy — APPROVED** [review]

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
