### PR TITLE
[Core] Codegen v2 support

### PR DESCRIPTION
**Pull request by kairu-ms**
**Description**

- Day1: Command, CommandGroup and Operation: [Meeting Record](https://microsoftapc-my.sharepoint.com/:v:/g/personal/kairu_microsoft_com/Eaq70THklplGhipxVDmWgoUB1ziAAT0k7j49II3XohoYbw)
- Day2: Field type, Field value and data: [Meeting Record](https://microsoftapc-my.sharepoint.com/:v:/g/personal/kairu_microsoft_com/EQ6LUkHyzMJGrogrYHO6nogBGSwwovLRExlEXox88l2LEA)

image

- Day3: Argument, ArgumentAction and Shorthand Syntax: [Meeting Record](https://microsoftapc-my.sharepoint.com/:v:/g/personal/kairu_microsoft_com/EUMhmyBo3GVNiYvJTPntVRYBTGVp8icypGqg_B2FjKkjZQ)
- Day4: ArgBrowser, ContentBuilde, Client, Paging and LongRunningOperation: [Meeting Record](https://microsoftapc-my.sharepoint.com/:v:/g/personal/kairu_microsoft_com/EV31kEqD3LlCnRnEdXAjoQgBrQQyaKFrvXvI98b0yUZh3Q)

**[Examples for generated Atomic Commands by CodeGen V2](https://github.com/kairu-ms/azure-cli/pull/1/files)**

https://github.com/kairu-ms/azure-cli/pull/1

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by jsntcy** [comment]
@kairu-ms, could you please add some details (such as why/what is your changes) in PR description to help the reviewers to understand the changes.

**Review by jiasli — APPROVED** [review]

**Pull request merged**
