### PR TITLE
Handle missing profile-name with clierror

### PR DESCRIPTION
**Pull request by devigned**
* Added docstrings and `exception_handler` for command method and parent methods.
* Added better exception handling for the scenario when listing endpoints when a profile doesn't exist.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [x] Each command and parameter has a meaningful description.
- [x] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by devigned** [comment]
@troydai rebased. Please check once more.

**Comment by derekbekoe** [comment]
Please hold off merging this until after the release...

**Comment by devigned** [comment]
@derekbekoe will do. Let me know when it's 200 OK.

**Comment by derekbekoe** [comment]
@devigned There's a conflict after the release. Apart from that, okay to merge!

**Comment by troydai** [comment]
@derekbekoe if it is ok to merge please remove the "Do Not Merge" label

**Comment by troydai** [comment]
@devigned @derekbekoe I solved the merge conflict. Please take another look, I'll merge after CI passes.

**Comment by troydai** [comment]
@devigned I solve the conflict, if you now approve my change, I can merge this PR.

**Comment by devigned** [comment]
@troydai LGTM! Thank you for rebasing it.

**Pull request merged**
