### PR TITLE
[backup] Optional parameter 'backup-management-type' in 'backup protectable-item list' command

### PR DESCRIPTION
**Pull request by hiaga**
**Description**
Adding optional parameter 'backup-management-type' in 'backup protectable-item list' command

**Testing Guide**

az backup protectable-item list -v "vaultName" -g "rgName" --workload-type MSSQL --container-name "containerName" -o table --protectable-item-type "SQLDatabase" --backup-management-type "AzureWorkload"

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by hiaga** [comment]
@yungezz , @qwordy , @fengzhou-msft  Can you pls review this PR.

**Review by qwordy — APPROVED** [review]

**Comment by qwordy** [comment]
Some checks were not successful

**Comment by hiaga** [comment]
@fengzhou-msft , @qwordy : failures do not seem to be related to changes in this PR - can you pls check

**Comment by qwordy** [comment]
It still fails. We are investigating.

**Comment by qwordy** [comment]
@hiapa, could you pull code from dev branch and push?

**Pull request merged**
