### PR TITLE
[IoTHub] Fixed regression bug

### PR DESCRIPTION
**Pull request by anusapan**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by anusapan** [comment]
@digimaun Could you review this PR.

**Comment by anusapan** [comment]
@Juliehzl Could you review the PR

**Comment by digimaun** [comment]
@anusapan , I approved but can you double check no other default properties are overridden.

Also, it would be valuable to add a test similar to the included screenshot one which validates all default options for iot hub create, and ensures its output is similar to pre 2.0.76 output.

image

**Comment by digimaun** [comment]
@anusapan , feel free to cut another PR for this but lets change the default partition count to 4 instead of 2, so CLI is aligned with Portal on defaults

**Comment by anusapan** [comment]
@haroldrandom Could you review the PR?

**Comment by Juliehzl** [comment]
LGTM. Only minor change

**Pull request merged**
