### PR TITLE
resource: support resource id for generic resource update

### PR DESCRIPTION
**Pull request by yugangw-msft**
//cc:@davidebbo.
Samples:
```bash
az resource update --id /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/yugangw3/providers/Microsoft.Web/sites/yugangw3-webapp/logs --set properties.applicationLogs.fileSystem.level=Information
az resource update --id /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/yugangw3/providers/Microsoft.Web/sites/yugangw3-webapp/config/web --set properties.phpVersion=5.6
az resource update --id /subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/yugangw3/providers/Microsoft.Network/virtualNetworks/yugangw3-vnet --set properties.addressSpace.addressPrefixes[0]=11.0.0.0/16
```

### CODE REVIEW

**Comment by davidebbo** [comment]
Great!

As I think about it, the one thing that's a little sticky is that using this requires hard coding the sub ID. e.g. today people write:

    az account set --subscription MSDN

And then everything else magically works on that sub. But here, while you obviously has full power over the path, you lose a bit of that simplicity. Not a deal breaker, but just a comment.

**Comment by yugangw-msft** [comment]
@davidebbo, you can still use individual args like `resource group`, `parent`, `resource type` to access and update any resources under current subscription. This PR let you copy and paste the id from any `get`/`list` operations and use it to update.
Are you talking about having the resource id arg be a bit flexible by not requiring the full path, rather a relative one and then the command will prefix it based on current active subscription?

**Comment by yugangw-msft** [comment]
@davidebbo, please also reference to `az resource show -h` for how to use individual args to access a resource. The `resource update` is updated to follow the same pattern. Let me know if you have any questions.

**Comment by davidebbo** [comment]
> Are you talking about having the resource id arg be a bit flexible by not requiring the full path, rather a relative one and then the command will prefix it based on current active subscription?

Yes, I was thinking along those lines. It doesn't have to happen now, it can always be enhanced later. e.g. via some token replacement:

    az resource update --id $sub/resourceGroups/yugangw3/providers/Microsoft.Web/sites/yugangw3-webapp/logs --set properties.applicationLogs.fileSystem.level=Information

Note that we can't always assume there is a sub in the path, as some resources exist outside of subs (e.g. `/providers/Microsoft.Web/sourcecontrols/OneDrive`).

**Comment by yugangw-msft** [comment]
> Note that we can't always assume there is a sub in the path, as some resources exist outside of subs (e.g. /providers/Microsoft.Web/sourcecontrols/OneDrive).

@davidebbo, my understanding is this is not a resource, so `az resource` commands might not the right commands to handle this. I figure we can let #2607 to handle this?

**Comment by davidebbo** [comment]
Ok, if we're guaranteed that it only targets resources that have a sub, then it wouldn't be too farfetched to prepend the sub if it's not there (or maybe just in the starting slash is missing).

**Comment by yugangw-msft** [comment]
Yes,  and we should do it across all resource commands, `delete`, `show`, and `update`

**Pull request merged**
