### PR TITLE
acs module fix help messages

### PR DESCRIPTION
**Pull request by rjtsdl**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [x] Each command and parameter has a meaningful description.
- [x] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by rjtsdl** [comment]
@brendandburns , this is trying to clarify the new added options/features, just before cli get published. If you approve, may help merge as well. thx

**Comment by rjtsdl** [comment]
@brendandburns, made the change accordingly. I need you to help me merge. :)

**Comment by brendandburns** [comment]
LGTM.

**Comment by brendandburns** [comment]
Merged.

**Pull request merged**
