### PR TITLE
[backup] Support new operations for MUA

### PR DESCRIPTION
**Pull request by zubairabid**
**Related command**

`az backup`

**Description**

Three new resource-guard protected scenarios: Vault Immutability turned off, Stop Protection, and Policy RPO increase.

**Testing Guide**

**History Notes**

[backup] `az backup vault update`: Now supports `--tenant-id` as input, and for the vault immutability scenario triggers a resourceguard check
[backup] `az backup protection disable`: Now supports `--tenant-id` as input, and for the stop protection scenario triggers a resourceguard check

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
backup

**Comment by zubairabid** [comment]
PR work is still in progress (Code work is completed, but tests need to be run). Raising PR as this needs to go in this month's release (April). The new SDKs required for this PR will be released out-of-cycle by the 22nd.

image

**Comment by zubairabid** [comment]
> Hi @zubairabid, Since the current milestone time is less than 7 days, this pr will be reviewed in the next milestone.

@zhoxing-ms this PR will be completed by the milestone date, we need it to be reviewed for release within this cycle.

**Comment by yonzhan** [comment]
Please fix CI issues.

**Comment by zhoxing-ms** [comment]
> PR work is still in progress (Code work is completed, but tests need to be run). Raising PR as this needs to go in this month's release (April). The new SDKs required for this PR will be released out-of-cycle by the 22nd.

This PR seems urgent, so you hope to release it in time for this sprint, right? Because CLI team is not responsible for reviewing your business logic, but only reviewing your code specifications, so could you please ask your team members to help review and approve this PR first?

**Pull request merged**
