### PR TITLE
{CognitiveServices} Remove Face attestation and Bing notice.

### PR DESCRIPTION
**Pull request by yangyuan**
**Related command**
`az cognitiveservices account create`

**Description**
Remove Face attestation and Bing notice.

**Testing Guide**
`az cognitiveservices account create` will no longer show Face attestation and Bing notice.

**History Notes**

{CognitiveServices} `az cognitiveservices account create` will no longer show Face attestation and Bing notice.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
cognitiveservices

**Comment by kairu-ms** [comment]
Please fix CI issues

**Comment by kairu-ms** [comment]
@yangyuan please fix other style issues.

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
