### PR TITLE
[AKS] Update CLI documentation for `az aks update`

### PR DESCRIPTION
**Pull request by jbpaux**
The example will update an existing cluster, not create a cluster (a faulty copy/paste I guess)

**Related command**
`az aks update --help` and search for : `az aks update -g MyResourceGroup -n MyManagedCluster --load-balancer-outbound-ips <ip-resource-id-1,ip-resource-id-2>`

**Description**
Documentation is wrong (updating instead of creating)

**Testing Guide**
`az aks update --help` shouldn't have "Create a cluster"

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by jbpaux** [comment]
@wangzelin007 I've updated the PR title so the format is correct.

**Review by wangzelin007 — APPROVED** [review]

**Comment by wangzelin007** [comment]
Sorry for the inconvient, the `Check the Format of Pull Request Title and Content` pipeline will only fire on commits.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
