### PR TITLE
[ARM] `az stack`: Update to API version `2024-03-01`, add new `validate` subcommand, and updates to `create` & `delete` subcommands

### PR DESCRIPTION
**Pull request by kalbert312**
**Related command**

`az stack group create`
`az stack sub create`
`az stack mg create`
`az stack group delete`
`az stack sub delete`
`az stack mg delete`
`az stack group validate`
`az stack sub validate`
`az stack mg validate`

**Description**
- Updates CLI to use the first stable GA API version `2024-03-01` for `Microsoft.Resources/deploymentStacks`.
- BREAKING CHANGE: Remove the deprecated `--delete-all`, `--delete-resources`, and `--delete-resource-groups` flags for stack create and delete commands. These are replaced by the already existing parameter `--action-on-unmanage/--aou <value>`.
- Add new `az stack <scope> validate` commands to perform preflight validation on a deployment stack deployment. This allows validating a stack's deployment before creating it or updating an existing one.
- The `az stack group create` and `az stack sub create` commands have been modified to perform validation immediately before creating or updating the stack. This is how `az deployment <scope> create` commands already behave. This does not yet apply to the `az stack mg create` command due to a backend bug with ARM and a fix that is currently awaiting deployment. This will be resolved in an upcoming bugfix release.
- Add correlation id property to stack create command output.
- Add new `--bypass-stack-out-of-sync-error` parameter to `stack create` and `stack delete` subcommands designed to unblock stacks in a stuck state due to resource sync errors.

**Testing Guide**

`az stack validate`: new command, see E2E tests for inputs
`az stack <group/sub/mg> <create/delete>`: test all variants of `--action-on-unmanage <detachAll/deleteResources/deleteAll>`, E2E tests cover this

**History Notes**

[ARM] BREAKING CHANGE: `az stack group/sub/mg create/delete`: Remove the deprecated `--delete-all`, `--delete-resources`, and `--delete-resource-groups` flags. Use the `--action-on-unmanage <value>`/`--aou <value>` parameter instead. Previously with no `--delete-*` flags specified, the default behavior was "detachAll" which can be represented with `--action-on-unmanage detachAll`
[ARM] `az stack group/sub/mg validate`: Add new `validate` command to preform preflight validation on a stack deployment.
[ARM] `az stack group/sub create`: Validation of a stack will now occur before a stack is created or updated. This is the same operation carried out by `az stack <scope> validate`. This will come to `az stack mg create` in a future bugfix release. 
[ARM] `az stack group/sub/mg create/delete`: Action on unmanage behavior for stack managed management groups can now be configured. 
[ARM] `az stack group/sub/mg create`: The correlation ID of the create operation is now returned as a property of the stack
[ARM] `az stack group/sub/mg create/delete`: Add new flag `--bypass-stack-out-of-sync-error`/`--bse` that will bypass errors related to the resource list of a stack being out of sync. 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
ARM

**Comment by kalbert312** [comment]
@zhoxing-ms this PR is now ready for review.

**Comment by zhoxing-ms** [comment]
Sorry, I am super busy now. @yanzhudd Could you please help review this PR when you have time?

**Comment by yanzhudd** [comment]
> 
> **History Notes**
> 
> 
> [ARM] BREAKING CHANGE: `az stack <group/sub/mg> <create/delete>`: Remove the deprecated `--delete-all`, `--delete-resources`, and `--delete-resource-groups` flags. Use the `--action-on-unmanage <value>`/`--aou <value>` parameter instead. There is no default behavior, so this new parameter is required. Previously with no `--delete-*` flags specified, the default behavior was "detachAll" which can be represented with `--action-on-unmanage detachAll`
> [ARM] `az stack`: Stacks commands now use stacks GA API version `2024-03-01` (was `2022-08-01-preview`)
> [ARM] `az stack <group/sub/mg> validate`: Add new `validate` command to preform preflight validation on a stack deployment. This command accepts nearly the same parameters as the `create` command. See release notes for `az stack <scope> create` commands to see how this also now applies to the `create` command
> [ARM] `az stack <group/sub> create`: Validation of a stack will now occur before a stack is created or updated. This is the same operation carried out by `az stack <scope> validate`. This will come to `az stack mg create` in a future bugfix release. This is how `az deployment <scope> create` works currently
> [ARM] `az stack <group/sub/mg> <create/delete>`: Action on unmanage behavior for stack managed management groups can now be configured. Use `--action-on-unmanage deleteAll` to delete newly unmanaged management groups. All other values to `--action-on-unmanage` will result in detachment of newly unmanaged management groups
> [ARM] `az stack <group/sub/mg> create`: The correlation ID of the create operation is now returned as a property of the stack
> [ARM] `az stack <group/sub/mg> <create/delete>`: Add new flag `--bypass-stack-out-of-sync-error`/`--bse` that will bypass errors related to the resource list of a stack being out of sync. This is designed to be used as a fallback in the case that a stack is stuck due to these types of errors
> 

1. It is not necessary to use `<>` characters in commands and parameters, e.g., use `az stack group/sub/mg validate` instead of `az stack <group/sub/mg> validate`, and use `--action-on-unmanage` instead of `--action-on-unmanage <value>`
2. For each item, please describe the change (in one sentence) as briefly as possible. If there are multiple changes, please split it into several items.
3. `[]` is used for customer-facing change, and `{}` is for non-customer-facing. Therefore, the changes like upgrading API version should use `{}`.

You can refer to the doc [submitting pull requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests) for more details.

**Comment by yanzhudd** [comment]
Since this PR also updates the core module, @zhoxing-ms could you please help to review it as well?

**Comment by yanzhudd** [comment]
please note that we will freeze CLI codes at 05/14/2024 10:00 UTC for the upcoming release train. If you want to catch this release train, please resolve the comments asap, otherwise it has to be postponed to the next sprint (07-02).

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
> It is not necessary to use <> characters in commands and parameters, e.g., use az stack group/sub/mg validate instead of az stack <group/sub/mg> validate, and use --action-on-unmanage instead of --action-on-unmanage <value>
For each item, please describe the change (in one sentence) as briefly as possible. If there are multiple changes, please split it into several items.
[] is used for customer-facing change, and {} is for non-customer-facing. Therefore, the changes like upgrading API version should use {}.

I have optimized the PR description for you, please see if it meets your expectations @kalbert312

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
