### PR TITLE
{Packaging} Bump PyNaCl from 1.4.0 to 1.5.0 to support arm64 wheel installation

### LINKED ISSUE #7368: Support arm64 Linux builds
**Is your feature request related to a problem? Please describe.**

azure-cli is available for amd64 through Microsoft's official repos for Debian, Ubuntu, and OpenSUSE.

See Debian and Ubuntu repo at https://packages.microsoft.com/repos/azure-cli/dists/.

However, azure-cli is not available for arm64 on any of those systems.

**Describe the solution you'd like**

Add arm64 builds to Microsoft's official repos for Linux and WSL.

**Describe alternatives you've considered**

I have considered re-building each release for arm64 anew each time.

### PR DESCRIPTION
**Pull request by tbugfinder**
**Description**

* bump PyNaCl from 1.4.0 to 1.5.0 to support arm64 wheel installation.

Ref:
https://github.com/Azure/azure-cli/issues/7368

PyNaCl 1.5.0 provides pre-built wheel installation also form arm64 architecture, so the installation is more efficient than building it every time needed.

**Testing Guide**

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Packaging

**Comment by jiasli** [comment]
@tbugfinder, thanks a lot for the contribution!

**Review by jiasli — APPROVED** [review]

**Comment by jiasli** [comment]
PyNaCl is used by https://github.com/Azure/azure-cli/blob/11b2de2e047abe374902563ef7f3b0f0be294d50/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L22

@panchagnula @jsntcy @zhoxing-ms, please help verify if the latest version of PyNaCl works correctly.

**Review by wangzelin007 — APPROVED** [review]

**Review by jsntcy — APPROVED** [review]

**Comment by calvinsID** [comment]
> from nacl import encoding, public

Confirmed new version is working

**Pull request merged**
