### PR TITLE
[WIP] support az acs scale on multiple agent pools

### PR DESCRIPTION
**Pull request by rjtsdl**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [x] Each command and parameter has a meaningful description.
- [x] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by rjtsdl** [comment]
@brendandburns @JackQuincy TAL

**Comment by JackQuincy** [comment]
specifying the agent pools seems fine. What I'm unsure about currently is the api version. Only 2017-07-01 allows multiple agent pools and last we checked the scale command was using 2017-01-31.

**Comment by rjtsdl** [comment]
Synced offline with @JackQuincy, let's hold on this PR for now.

**Comment by derekbekoe** [comment]
@rjtsdl marked as DNM for now.

**Comment by derekbekoe** [comment]
Closing PR as not updated in a while and it has conflicts.

**Pull request closed without merging**
