### PR TITLE
[AKS] `az aks update`: Promte outbound type migration to azure-cli/acs

### PR DESCRIPTION
**Pull request by MartinForReal**
**Related command**

`az aks update`

**Description**

Promote outbound type migration feature to azure-cli/acs module. 

**Testing Guide**

**History Notes**

[AKS] `az aks update`: Support cluster outbound type migration

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by FumingZhang** [comment]
Queued [live test](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=76999935&view=results) to validate the change.

**Review by FumingZhang — APPROVED** [review]
LGTM

**Comment by zhoxing-ms** [comment]
@MartinForReal Could you please address this CLI style issue?

**Comment by MartinForReal** [comment]
@zhoxing-ms All tests are passed. PTAL. Thanks！

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
