### PR TITLE
[ServiceBus] Fix #24741: Remove invalid arguments for entity update commands

### LINKED ISSUE #24741: `az servicebus queue create` and `az servicebus queue update` ignore --enable-partitioning
## Describe the bug

When creating the servicebus queue with `az servicebus queue create` and the parameter --enable-partitioning is set to true this is ignored by the cli and the setting is still disabled in portal.

Furthermore when using `az servicebus queue update` to enable partitioning bad request is returned.

**Command Name**
`az servicebus queue create`
`az servicebus queue update`

**Errors:**
```
(MessagingGatewayBadRequest) <Error><Code>400</Code><Detail>SubCode=40000. Partitioning cannot be changed for Queue. To know more visit https://aka.ms/sbResourceMgrExceptions. TrackingId:545e4894-b18d-4b96-9ed6-00ab14a406bd_G1, SystemTracker:sb-bof-nlst-rc.servicebus.windows.net:clearance-processing, Timestamp:2022-11-25T11:55:39</Detail></Error>
Code: MessagingGatewayBadRequest
Message: <Error><Code>400</Code><Detail>SubCode=40000. Partitioning cannot be changed for Queue. To know more visit https://aka.ms/sbResourceMgrExceptions. TrackingId:545e4894-b18d-4b96-9ed6-00ab14a406bd_G1, SystemTracker:sb-bof-nlst-rc.servicebus.windows.net:clearance-processing, Timestamp:2022-11-25T11:55:39</Detail></Error>

```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az servicebus queue create --name {} --namespace-name {} --resource-group {} --enable-session --enable-batched-operations --max-size {} --enable-partitioning {} --lock-duration {} --max-delivery-count {} --debug`
- look in portal --> partitioning is disabled
- `az servicebus queue update --name {} --namespace-name {} --resource-group {} --enable-session --enable-batched-operations --max-size {} --enable-partitioning {} --lock-duration {} --max-delivery-count {} --debug`

## Expected Behavior
should work as documented [here](https://learn.microsoft.com/en-us/cli/azure/servicebus/queue?view=azure-cli-latest#az-servicebus-queue-create) and [here ](https://learn.microsoft.com/en-us/cli/azure/servicebus/queue?view=azure-cli-latest#az-servicebus-queue-update)

## Environment Summary
```
Windows-10-10.0.22621-SP0
Python 3.10.8
Installer: MSI

azure-cli 2.42.0

Extensions:
account 0.2.5
application-insights 0.1.16
azure-devops 0.25.0

Dependencies:
msal 1.20.0
azure-mgmt-resource 21.1.0b1
```

### PR DESCRIPTION
**Pull request by PramodValavala-MSFT**
**Related command**

```sh
az servicebus queue update --resource-group {} --namespace-name {} --name {} --enable-partitioning --enable-duplicate-detection --enable-session
az servicebus topic update --resource-group {} --namespace-name {} --name {} --enable-partitioning --enable-duplicate-detection
az servicebus topic subscription update --resource-group {} --namespace-name {} --name {} --enable-session
```

**Description**

The following properties of an entity cannot be updated post creation but the update the commands for entities have these arguments, which are invalid and fail as such

- Partitioning (Queues & Topics)
- Duplicate Detection (Queues & Topics)
- Sessions (Queues & Subscriptions)

This PR removes the arguments for the update commands.

resolves #24741

**Testing Guide**

```sh
az servicebus queue update --resource-group {} --namespace-name {} --name {} --enable-partitioning --enable-duplicate-detection --enable-session
az servicebus topic update --resource-group {} --namespace-name {} --name {} --enable-partitioning --enable-duplicate-detection
az servicebus topic subscription update --resource-group {} --namespace-name {} --name {} --enable-session
```

The above commands currently fail with a 400 Bad Request, which is expected due to the invalid arguments that can't be updated post entity creation. With this PR, they should be removed from the documentation, command help, and error as invalid arguments directly.

**History Notes**

[ServiceBus] `az servicebus queue update`: Remove invalid arguments for queue update command
[ServiceBus] `az servicebus topic update`: Remove invalid arguments for topic update command
[ServiceBus] `az servicebus topic subscription update`: Remove invalid arguments for subscription update command

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
ServiceBus

**Comment by damodaravadhani** [comment]
Hi @PramodValavala-MSFT , thanks for working on this. There might need to be testcase updates that need to be made to this, I can take this from here if you invite me as a collaborator on your azure-cli fork.

**Comment by PramodValavala-MSFT** [comment]
@damodaravadhani Sure. I've added you as a contributor to my fork. Let me know what tests you have in mind and I could help out too, if needed.

**Comment by evelyn-ys** [comment]
Hi @PramodValavala-MSFT ,  this is breaking change and we only allow breaking change twice a year. Can you add deprecation and warnings for now and totally remove them in next breaking change window?

**Comment by evelyn-ys** [comment]
Oh I've already seen #24937 adding the deprecation warning. I'll close this PR then

**Pull request closed without merging**
