### PR TITLE
[AKS] Add az aks nodepool get-upgrades command

### PR DESCRIPTION
**Pull request by gtxistxgao**
**Description**  

This PR add the command to support customer get the available upgrade versions  for an agent pool of the managed Kubernetes cluster. The corresponding REST API entry: https://docs.microsoft.com/en-us/rest/api/aks/agentpools/getupgradeprofile

az aks get-upgrades --resource-group MyResourceGroup --cluster-name MyManagedCluster --nodepool-name MyNodePool

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by zqingqing1** [comment]
You need to bump the version and also add sentence about what is brought in the histroy.md

**Comment by arrownj** [comment]
Hi @gtxistxgao , is it OK to merge this PR now ?

**Pull request merged**
