### PR TITLE
[AKS] `az aks update`: Add support for updating kubelet identity with `--assign-kubelet-identity`

### PR DESCRIPTION
**Pull request by FumingZhang**
**Related command**

`az aks update`

**Description**

`az aks update`:  Add support for updating kubelet identity with `--assign-kubelet-identity`. Sync PR [#4740](https://github.com/Azure/azure-cli-extensions/pull/4740) from aks-preview. Also a revision of PR [#22467](https://github.com/Azure/azure-cli/pull/22467).

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by FumingZhang** [comment]
Queued a [pipeline](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=55511086&view=results) to test `test_aks_custom_kubelet_identity`.

**Review by norshtein — APPROVED** [review]
LGTM

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
