### PR TITLE
[App Service] Fix #23603: `az functionapp config set`: Add new parameter to set PowerShell version

### LINKED ISSUE #23603: Include option for PowerShell in az functionapp config set
Per the documentation, seems like it is currently not possible to set Function App **PowerShell** version using **az functionapp config set**. There are options for java, php, python, but not for  PS.

image

Please add a parameter for PowerShell under az functionapp config set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d09a3700-4b7b-6720-bec4-2d07ff96ef23
* Version Independent ID: 7d06e377-4659-b3c5-4b7f-8448cc0c102f
* Content: [az functionapp config](https://docs.microsoft.com/en-us/cli/azure/functionapp/config?view=azure-cli-latest)
* Content Source: [latest/docs-ref-autogen/functionapp/config.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/functionapp/config.yml)
* Service: **azure-functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

### PR DESCRIPTION
**Pull request by PramodValavala-MSFT**
**Related command**

```
az functionapp config set
```

**Description**

PowerShell Function Apps have a configurable version configuration that can be set from the Azure Portal but isn't exposed in Azure CLI. This PR adds the option for the same.

resolves #23603

**Testing Guide**

```
az functionapp config set --resource-group {} --name {} --powershell-version 7.2
```

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AppService

**Review by StrawnSC — DISMISSED** [review]

**Comment by zhoxing-ms** [comment]
@PramodValavala-MSFT Could you please add a test for this new parameter?

**Comment by zhoxing-ms** [comment]
@PramodValavala-MSFT Please note that since we will launch the release of this sprint the day after tomorrow. If you cannot address all the comments tomorrow, we will have to postpone the release of this PR to the next sprint **(03-07)**

**Comment by PramodValavala-MSFT** [comment]
@zhoxing-ms Apologies for the delay here! I just pushed in a test. Hope I made it in time.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
