### PR TITLE
[AppConfig] Support enabling/disabling PublicNetworkAccess during store creation

### PR DESCRIPTION
**Pull request by avanigupta**
**Description**  

We updated our management plane swagger to add some properties in store object for private endpoint feature. Although to add private endpoint, we leverage network CLI, there is one feature we need to support for publicNetworkAccess in our side. 

Like some existing store properties (sku, tags), publicNetworkAccess is another one to allow public data plane access even though private endpoint has been turned on. 

This PR will add support for enabling/disabling publicNetworkAccess with "az appconfig create" command.

**Testing Guide**  

This will create a new store called MyStore, with publicNetworkAccess enabled:
`az appconfig create -n MyStore -g ResourceGroupName -l westus --enable-public-network`

This will create a new store called MyStore, with publicNetworkAccess disabled:
`az appconfig create -n MyStore -g ResourceGroupName -l westus --enable-public-network false`

This will create a new store called MyStore, with publicNetworkAccess null (current behavior is to keep default as null):
`az appconfig create -n MyStore -g ResourceGroupName -l westus`

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by avanigupta** [comment]
Hi @recao can you help review this PR?

**Comment by yonzhan** [comment]
AppConfig

**Comment by qwordy** [comment]
Please write a description. Thanks.

**Comment by yungezz** [comment]
hi @avanigupta is this PR ready to merge?

**Comment by avanigupta** [comment]
Hi @yungezz , yes, this PR can be merged. Thanks!

**Pull request merged**
