### PR TITLE
{Role} Fix typo for `az role assignment create --help`

### PR DESCRIPTION
**Pull request by TeamDman**
**Related command**

```
az role assignment create --help
```

**Description**

fix typo, currently:

```
--name -n                     : A GUID for the role assignment. It must be unique and different
                                    for each role assignment. If omitted, a new GUID is generetd.
```
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Misc.

**Review by yonzhan — APPROVED** [review]

**Review by yonzhan — APPROVED** [review]

**Comment by yonzhan** [comment]
Please fix CI issues

**Comment by jiasli** [comment]
My bad. The typo was written by me: https://github.com/Azure/azure-cli/pull/24324.

**Review by jiasli — APPROVED** [review]

**Pull request merged**
