### PR TITLE
[App Service] `az webapp config ssl create/upload/import`: Allow user to specify certificate name with `--certificate-name`

### LINKED ISSUE #15421: webapp: Change name assigned to app service managed certificates
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Free Certificates are named after their custom domain. This is causing issues with traffic manager domains, as multiple free certs cannot be issued to to the same domain. 

**To Reproduce**
Trying to create a two free certificates for the same domain will result in a naming conflict ARM error. 

**Expected behavior**
We need to change the name assigned to free certs, so that more than one can be issued to traffic manager domains in the same resource group. Maybe appending a number, or the site name, 

**Environment summary**

**Additional context**

### PR DESCRIPTION
**Pull request by haroonf**
**Related command**
`az webapp config ssl create`
`az webapp config ssl upload`
`az webapp config ssl import`

**Description**
Fixes #15421 and #16464

Adding option for customers to create certificates with custom certificate names. Default logic left as-is.

**Testing Guide**
`azdev test test_webapp_ssl_import test_webapp_ssl --live`

**History Notes**

`az webapp config ssl create/upload/import`: Allow user to specify certificate name with `--certificate-name`

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
App Service

**Comment by haroonf** [comment]
Addresses #15421 and #16464

**Review by zhoxing-ms — DISMISSED** [review]

**Comment by zhoxing-ms** [comment]
@haroonf Could you please resolve these conflicts?

**Comment by zhoxing-ms** [comment]
Please note that we will launch the release for this sprint tomorrow morning, please address the above comments in time today, otherwise we have to postpone the release time of this PR to the next sprint **(04-04)**

**Comment by haroonf** [comment]
@zhoxing-ms Fixed merge conflicts. Thanks!

**Review by StrawnSC — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
