### PR TITLE
{IoT} Refactor KeyReplacer folder structure

### PR DESCRIPTION
**Pull request by zhoxing-ms**
**Related command**

**Description**

Issue background: https://github.com/Azure/azure-cli/pull/28427/files/6a7ac3ae7a96fe122e7a1c2bbcc6a1b78eed3ef4#r1503570453
Similar as: #19285 #17817

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Core

**Review by yonzhan — DISMISSED** [review]

**Comment by zhoxing-ms** [comment]
@c-ryan-k @digimaun Please note that this PR is to address the CI issue caused by the lack of `__init__.py` ([comment link](https://github.com/Azure/azure-cli/pull/28427/files/6a7ac3ae7a96fe122e7a1c2bbcc6a1b78eed3ef4#r1503570453)).  If you have time to review it, please help review it. If not, in order to avoid blocking the build process of CLI, we will merge it first as it does not affect business logic of IoT module

**Review by jiasli — DISMISSED** [review]

**Review by yanzhudd — APPROVED** [review]

**Review by c-ryan-k — APPROVED** [review]

**Comment by jiasli** [comment]
CI still fails with the same error:

https://dev.azure.com/azclitools/public/_build/results?buildId=134051&view=logs&j=a92c0e78-c951-523a-85be-a933049bed50&t=6e78b194-5635-5321-0acd-26471375c5ca

```
/opt/az/lib/python3.11/site-packages/azure/cli/command_modules/iot/tests/latest/test_iot_dps_commands.py:13: in <module>
    from azure.cli.command_modules.iot.tests.utils.recording_processors import KeyReplacer
E   ModuleNotFoundError: No module named 'azure.cli.command_modules.iot.tests.utils'
```

From the CI script, we can see only the `azure.cli.command_modules.$name.tests` folder is included as `packages`:

https://github.com/Azure/azure-cli/blob/a5198b578b17de934e15b1c92e369e45323e9658/scripts/ci/build.sh#L130-L138

as this `setup.py` doesn't use `find_packages`, `azure.cli.command_modules.$name.tests.utils` will not be included.

I suggest putting `src/azure-cli/azure/cli/command_modules/iot/tests/utils/recording_processors.py` directly under `azure.cli.command_modules.$name.tests` as `util.py`, such as

https://github.com/Azure/azure-cli/blob/261c6d53a3ce205291ef08e85cf487ae1b97bcbb/src/azure-cli/azure/cli/command_modules/role/tests/util.py#L1-L10

**Review by jiasli — APPROVED** [review]

**Review by c-ryan-k — APPROVED** [review]

**Review by digimaun — APPROVED** [review]

**Comment by jsntcy** [comment]
@zhoxing-ms, do we need rerun the related tests to avoid regression?

**Pull request merged**
