### PR TITLE
[ACR] Add top and orderby parameters for show-manifests

### PR DESCRIPTION
**Pull request by djyou**
Fixes https://github.com/AzureCR/azure-cli/issues/150

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/6401
This is an **experimental preview** for @microsoft users.

**Comment by djyou** [comment]
Example: list the latest 10 manifests ordered by timestamp:
```
>az acr repository show-manifests -n registry --repository repository --top 10 --orderby timedesc -o table
Digest                                                                   Timestamp
-----------------------------------------------------------------------  --------------------
sha256:592fa129310a8e3313357b7bc4fb77009961b9c68c4bef4dc7c8291b000deafc  2017-10-18T17:57:02Z
sha256:6f64ea126b3c8d4fe94e0518818d1456bc91b240f29e0c0df4e8a762e2a8ed4c  2017-10-18T17:56:45Z
sha256:1444dbb817f3160f76f9ba23631b9bb02e23afc27cf62c8552a530d305fc5aeb  2017-10-18T17:56:29Z
sha256:3b6b38fffc06c5d99dbd8912e453e6bfdfdef771e9285d7184bdcb48b36a7e30  2017-10-18T17:56:13Z
sha256:3d19de026dd2fede352de614db667478ce2b616789ef75941f0e58c71b7a462b  2017-10-18T17:55:53Z
sha256:29e9dc19e76f30897390c613b8a3f13b2a15544d029b53c90ff0e1e3fdaba7fd  2017-10-18T17:55:34Z
sha256:4d2eb13eab39b44924b1a21bdc692ca111d92880e0901966a0cbbb8f20fd7c66  2017-10-18T17:55:18Z
sha256:f16ec99bcb3300010a7e21352369c2e7fb74f9607c2ae507125c15a5ab627b3d  2017-10-18T17:54:54Z
sha256:e516c2d6962f4849aa0479ab3ba3a30f9b90738662e03e006851cf782834e702  2017-10-18T17:54:43Z
sha256:6893f9acd5c178c06cca435ba060ab9b463df958a2d8f3dc579bf1f17852bb59  2017-10-18T17:54:28Z
```

**Comment by djyou** [comment]
@troydai Could you please also review and include this in the next release? /cc @derekbekoe @tjprescott

**Pull request closed without merging**
