### PR TITLE
{dls} Update azure-datalake-store dependency

### PR DESCRIPTION
**Pull request by akharit**
**Related command**

az dls fs *

**Description**

Update the azure-datalake-store version to 0.0.53. 

Main reason is to removes the dependency on adal and uses msal. There are other small changes that can be found in the change history at https://github.com/Azure/azure-data-lake-store-python/blob/master/HISTORY.rst 

**Testing Guide**

azdev test dls --live
Tests the dls command tests with a live account. Please ask me for any needed access.

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ NA] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ NA] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
ADLS Gen1

**Comment by akharit** [comment]
Addresses https://github.com/Azure/azure-cli/issues/29276

**Comment by jiasli** [comment]
I would prefer the PR title as 

> {dls} Update `azure-datalake-store` dependency

1. `dls` is fine, but `Data Lake Store` is actually the full service name: https://learn.microsoft.com/en-us/cli/azure/dls?view=azure-cli-latest. The PR title is not customer-facing anyway.
2. There is no need to explain the reason of this PR in the PR title. Putting it in the description is enough.

Also, there is no need to add a history note, as this change is not customer-facing.

**Review by evelyn-ys — APPROVED** [review]

**Comment by evelyn-ys** [comment]
@akharit Can you also help update `azure-mgmt-datalake-store` for similar reason of dropping ADAL?

**Comment by evelyn-ys** [comment]
Though `azure-datalake-store 0.0.53` has dropped ADAL but it's still generated using track1 SDK framework which uses `signed_session()` interface for auth. This blocks us to drop track1 support #29631 

@akharit Can you help migrate the data plane SDK to track2? Thanks a lot!

**Pull request merged**
