### PR TITLE
[Recoveryservices Backup]  Added Soft-delete features

### PR DESCRIPTION
**Pull request by sambitratha**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by qwordy** [comment]
Weird error in travis.

```
WARNING: The following packages cannot be authenticated!

  libssl-dev libssl1.0.0

E: There were unauthenticated packages and -y was used without --allow-unauthenticated
apt-get.diagnostics

apt-get install failed

The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install libssl-dev libffi-dev python-dev" failed and exited with 100 during
```

**Comment by yonzhan** [comment]
add to S163.

**Pull request merged**
