### PR TITLE
[WIP] [draft] dynamic command indexing.

### PR DESCRIPTION
**Pull request by adewaleo**
Exploring dynamical command indexing to reduce command load time and CI times.

Had an idea and decided to try it....

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by tjprescott** [comment]
Can you be more clear in the title and description what it is you are seeking to optimize?

**Comment by adewaleo** [comment]
> Can you be more clear in the title and description what it is you are seeking to optimize?

Will do @tjprescott. This was originally a draft PR. I made it a regular one thinking that's what will make the CI run, but I can't switch the pr back.

**Comment by tjprescott** [comment]
@adewaleo do you still need this PR open?

**Comment by adewaleo** [comment]
> @adewaleo do you still need this PR open?

@tjprescott, I don't need it open for now, I just wanted to try out something using the CI. I will close it and reopen if I ever need it. Thanks!

**Pull request closed without merging**
