### PR TITLE
{ServiceBus} `az servicebus georecovery-alias authorization-rule` `az servicebus georecovery-alias break-pair/delete/list/fail-over/set/exists/show`: Migrating servicebus georecovery-alias cmdlets to AAZ

### PR DESCRIPTION
**Pull request by schaudhari6254888**
**Related command**
`parameters` argument is removed from `az servicebus georecovery-alias fail-over` cmdlets in this release.

**Description**

**Testing Guide**

**History Notes**

[ServiceBus] BREAKING CHANGE: `az servicebus georecovery-alias fail-over`: Removed `--parameters` argument

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
ServiceBus

**Review by kairu-ms — CHANGES_REQUESTED** [review]
Please rename the file name in snackcase.

**Comment by schaudhari6254888** [comment]
> Please rename the file name in snackcase.

Done

**Review by kairu-ms — COMMENTED** [review]
Please resolve conflicts

**Review by kairu-ms — APPROVED** [review]

**Review by evelyn-ys — CHANGES_REQUESTED** [review]
As you mentioned in PR description:

> parameters argument is removed from az servicebus georecovery-alias fail-over cmdlets in this release.

There should be a breaking change notes in release history

**Comment by schaudhari6254888** [comment]
> Please rename the file name in snackcase.

Hey @kairu-ms I have resolved the conflicts

**Comment by kairu-ms** [comment]
> > Please rename the file name in snackcase.
> 
> Hey @kairu-ms I have resolved the conflicts

Please add this release note next time
image

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
