### PR TITLE
{sqlvm} Re-running sql vm tests that were failing. 

### PR DESCRIPTION
**Pull request by yareyes**
**Description**  
This PR has been created to address the issue: https://github.com/Azure/azure-cli/issues/14291 
sql vm tests where not properly running. Removing the unit test skipping and adding the yaml files with the new recordings. 

Please note that there are no command changes. Just created the storage account initially a StorageV2 instead of setting it later on. This unblocked the one error we were seeing on one of the tests. The other test was just re-run without issues. 

**Testing Guide**  
This is internal, no external CLI changes. 

**History Notes**  
{sqlvm} running failed tests and adding new recordings. 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yareyes** [comment]
adding @qwordy

**Comment by yonzhan** [comment]
sqlvm

**Comment by qwordy** [comment]
Thank you so much!

**Comment by yareyes** [comment]
@yonzhan could you help us merge this PR?

**Comment by yonzhan** [comment]
@qwordy could you help with this PR？

**Pull request merged**
