### PR TITLE
[acr] update sdk version / requirements.*.txt

### PR DESCRIPTION
**Pull request by adewaleo**
**Description of PR (Mandatory)**  
(Why this PR? What is changed? What is the effect? etc. A high-quality description can accelerate the review process)

**Testing Guide**  
(Example commands with explanations)

**History Notes:**  
(Fill in the following template if multiple notes are needed, otherwise PR title will be used for history note.)

[Component Name 1] (BREAKING CHANGE:) (az command:) make some customer-facing change.  
[Component Name 2] (BREAKING CHANGE:) (az command:) make some customer-facing change.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by fengzhou-msft** [comment]
@adewaleo do you want a hotfix release? If so, please submit a PR to merge into release branch.

**Comment by rosanch** [comment]
Fixes #12819

**Comment by fengzhou-msft** [comment]
I will submit a new PR to merge into release branch.

**Comment by rosanch** [comment]
can you please tag me to follow up @fengzhou-msft ?
Thank you.

**Pull request closed without merging**
