### PR TITLE
[ACR] Deprecate preview command group and implement same commands in parent command group

### PR DESCRIPTION
**Pull request by mabenedi**
**Description**

This PR deprecates the preview `az acr manifest metadata` command group and moves the 3 commands into the parent `az acr manifest` command group. This is essentially a renaming or reorganization of the commands after receiving customer feedback.  **There is no new functionality added**, just name changes.

 
**Testing Guide**

helps['acr manifest show-metadata'] = """
type: command
short-summary: Get the metadata of an artifact in an Azure Container Registry.
examples:
  - name: Get the metadata of the tag 'hello-world:latest'.
    text: az acr manifest show-metadata -r MyRegistry -n hello-world:latest
  - name: Get the metadata of the tag 'hello-world:latest'.
    text: az acr manifest show-metadata MyRegistry.azurecr.io/hello-world:latest
  - name: Get the metadata of the manifest referenced by digest 'hello-world@sha256:abc123'.
    text: az acr manifest show-metadata -r MyRegistry -n hello-world@sha256:abc123
"""

helps['acr manifest list-metadata'] = """
type: command
short-summary: List the metadata of the manifests in a repository in an Azure Container Registry.
examples:
  - name: List the metadata of the manifests in the repository 'hello-world'.
    text: az acr manifest list-metadata -r MyRegistry -n hello-world
  - name: List the metadata of the manifests in the repository 'hello-world'.
    text: az acr manifest list-metadata MyRegistry.azurecr.io/hello-world
"""

helps['acr manifest update-metadata'] = """
type: command
short-summary: Update the manifest metadata of an artifact in an Azure Container Registry.
examples:
  - name: Update the metadata of the tag 'hello-world:latest'.
    text: az acr manifest update-metadata -r MyRegistry -n hello-world:latest --write-enabled false
  - name: Update the metadata of the tag 'hello-world:latest'.
    text: az acr manifest update-metadata MyRegistry.azurecr.io/hello-world:latest --write-enabled false
  - name: Update the metadata of the artifact referenced by digest 'hello-world@sha256:abc123'.
    text: az acr manifest update-metadata -r MyRegistry -n hello-world@sha256:abc123 --write-enabled false
"""
**History Notes**

[ACR] Deprecate `az acr manifest metadata` command group
[ACR] `az acr manifest`: Add `show-metadata`, `list-metadata`, and `update-metadata` commands

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
acr

**Review by wangzelin007 — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
Could you add some tests for those commands?

**Comment by mabenedi** [comment]
> Could you add some tests for those commands?

They're already tested. The functions that actually execute haven't changed and are tested in this file - https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/tests/latest/test_acr_commands_mock.py

**Comment by zhoxing-ms** [comment]
@mabenedi Why are there no `ScenarioTest` for these commands?

**Comment by mabenedi** [comment]
> Why are there no `ScenarioTest` for these commands?

They're all data-plane and setting up a scenario would be reliant on external clients like docker etc. None of our commands in `az acr repository` command group have scenariotests for the same reason

**Review by zhoxing-ms — APPROVED** [review]

**Comment by mabenedi** [comment]
Anything else I need to do to get this merged?

**Pull request merged**
