### PR TITLE
[AKS] BREAKING CHANGE: `az aks create/update`: Remove `--uptime-sla` and `--no-uptime-sla` options

### PR DESCRIPTION
**Pull request by xiangwei36**
**Related command**
` az aks create `
` az aks update `

**Description**
`--uptime-sla` and `--no-uptime-sla` options will be removed after 18 moths of deprecation.

**Testing Guide**

**History Notes**

[AKS] BREAKING CHANGE: `--uptime-sla` and `--no-uptime-sla `: Will be removed

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by FumingZhang — COMMENTED** [review]
LGTM, queued ~~[live test](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=106990059)~~ [live test](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=107166230&view=results) to validate the change.

- test_aks_create_with_paid_sku
- test_aks_create_with_paid_sku_msi

Please update PR title to something like
```
[AKS] BREAKING CHANGE: `az aks create/update`: xxx
```
to fix the failed CI check.

**Comment by FumingZhang** [comment]
push an empty commit or ask cli team member to comment `/azp run`

**Comment by xiangwei36** [comment]
@FumingZhang The live test failed https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=106990059&view=logs&j=b162b355-d59d-5864-ce0f-0a70f12dd28b&t=dc59ccd1-231f-538b-777f-33a592c7ca57&l=2203
is it because I need to re-do the recordings?

**Comment by FumingZhang** [comment]
requeued the test, the pipeline variable of the previous run was set incorrectly

**Review by FumingZhang — APPROVED** [review]
LGTM

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
