### PR TITLE
[RDBMS] Added tests for flexible server team pipeline

### PR DESCRIPTION
**Pull request by DaeunYim**
**Description**
No customer facing changes. 
Added tests for Flexible Server stability check testing pipeline. 

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by DaeunYim** [comment]
Will prioritize this before another RDBMS pending PR. 
Thank you!!

**Comment by yonzhan** [comment]
RDBMS

**Comment by DaeunYim** [comment]
Trigger the pipeline please..!

**Comment by jsntcy** [comment]
#16860 will continue after this PR is merged?

**Comment by DaeunYim** [comment]
> #16860 will continue after this PR is merged?

Yes I have to. Please trigger the pipeline again.. Let me try completing this soon and move on to the migration PR...

**Comment by jsntcy** [comment]
@DaeunYim, please fix tests first.

**Comment by DaeunYim** [comment]
> @DaeunYim, please fix tests first.

On the pipeline it worked differently than my local.
Tried fixing it again. Please trigger the pipeline again. 

By when can I automatically trigger the pipeline..? Is it a planned work?

**Comment by jsntcy** [comment]
@DaeunYim, you can add `/azp run` in comment to trigger the build.

**Comment by DaeunYim** [comment]
> @DaeunYim, you can add `/azp run` in comment to trigger the build.

Oh now I'm allowed! Sorry to having bothered you! Thanks for letting me know :)

**Comment by DaeunYim** [comment]
> @DaeunYim, you can add `/azp run` in comment to trigger the build.

@jsntcy  Looks like I don't have the right to do this as a commenter. Would you mind assigning me (as a owner or reviewer) to this and the SDK migration PR for convenience? Minor things are keep failing the CI tests and I don't want to bother your team every time I fix small thing (also considering the time zone!)

**Comment by evelyn-ys** [comment]
@DaeunYim You can ping me from teams when you need to trigger CI. Github notifications may be drowned in tons of emails😄

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
