### PR TITLE
[AKS] update for changes in SDK

### PR DESCRIPTION
**Pull request by mboersma**
Changes in Azure/azure-rest-api-specs#1956 to use `x-ms-client-flatten` implied some minor changes here in the CLI. ~~Note that this will fail until `azure-mgmt-containerservice` 3.0.0 is available.~~ (avaiable now)

Requires Azure/azure-sdk-for-python#1699

### CODE REVIEW

**Comment by derekbekoe** [comment]
@mboersma Looks like there are user-facing changes here?
If so can you update HISTORY.rst?

**Comment by mboersma** [comment]
@derekbekoe the only thing a user would notice is that I bumped the example Kubernetes versions in the help text to slightly newer ones. Should that go in HISTORY.rst?

**Comment by derekbekoe** [comment]
That change is fine.
I was referring to the flattening. Now the JSON output of the modified commands won't have some `'properties'` fields?

**Comment by mboersma** [comment]
Good point--I mentioned that in HISTORY.rst now.

**Pull request merged**
