### PR TITLE
AKS: Remove preview flag for --network-policy

### PR DESCRIPTION
**Pull request by feiskyer**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by feiskyer** [comment]
@mboersma  How could we get this merged?

**Comment by yugangw-msft** [comment]
Reopening to trigger the CI

**Comment by feiskyer** [comment]
seems azcli-CI still didn't start

**Comment by feiskyer** [comment]
@tjprescott @yugangw-msft Could you help to check why azcli-CI is not running?

**Comment by feiskyer** [comment]
@yugangw-msft thanks. What else should we do to get this merged? We're expecting this to be included in milestone Sprint 60 (BUILD).

**Pull request merged**
