### PR TITLE
[Mysql] `az mysql flexible-server create/restore/replica create/geo restore`: Add `--storage-redundancy` parameter to support HA storage with zone redundancy

### PR DESCRIPTION
**Pull request by linyudoa**
**Related command**

**Description**
Supported `--storage-redundancy` pamameter in `az mysql flexible-server create/restore/replica create/geo restore` commands for business critical tier, so the customers can choose HA storage with zone redundancy. 
Updated the mysql sdk version to the latest version.

**Testing Guide**

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by honghr — APPROVED** [review]

**Comment by yonzhan** [comment]
Please fix conflicting files

**Comment by evelyn-ys** [comment]
Pls format PR title and PR description following https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests

**Comment by evelyn-ys** [comment]
@linyudoa Sry for merging late, Can you pls resolve conflicts now

**Comment by linyudoa** [comment]
> @linyudoa Sry for merging late, Can you pls resolve conflicts now

**Review by evelyn-ys — APPROVED** [review]

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
