### PR TITLE
{Synapse} Fix test fail in yum package

### PR DESCRIPTION
**Pull request by evelyn-ys**
**Description**

`test_notebook` fails in [Test Yum Package](https://dev.azure.com/azure-sdk/public/_build/results?buildId=837520&view=logs&j=1e6fba43-bdcf-51f0-a062-3712c33fbb51&t=a1e787eb-ec67-5c3d-79ec-0c68f4f59d65)

It might caused because the operation system ADO used can't deal with `ipynb` file. This PR changed `ipynb` file in test to `json` file.

**Testing Guide**

`azdev test test_notebook`

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Review by Juliehzl — APPROVED** [review]

**Comment by Juliehzl** [comment]
is *.ipynb required to test?

**Comment by idear1203** [comment]
It doesn't quite make sense to me about this file extension renaming fix.
1. this is just file renaming, while file content doesn't change. It's strange your pipeline works with .json but not with .ipynb
2. we would like to name this file as .ipynb, which is a well known file format in Notebook world.

I think we should dig further and figure out the exact reason why the test case fails

**Comment by evelyn-ys** [comment]
@fengzhou-msft Could you help take a look why it only fails in yum package?

**Comment by evelyn-ys** [comment]
Closed since It fails infrequently.
image

**Comment by evelyn-ys** [comment]
Resolved in https://github.com/Azure/azure-cli/pull/17704

**Pull request closed without merging**
