### PR TITLE
[AKS] sdk update

### PR DESCRIPTION
**Pull request by haitch**
**Description**

To bump AKS SDK dependency version, future PR will consume this newer version of SDK.

**Testing Guide**

update all recordings, existing test are working fine.

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by northtyphoon** [comment]
@haitch, does the pr include any change related to ACR? If yes, can you point me to the code?

**Review by fengzhou-msft — APPROVED** [review]

**Comment by xfz11** [comment]
Hi, the PR caused aks-preview extension test failed. Pls take a look

**Comment by FumingZhang** [comment]
@haitch, @xfz11  the updated sdk version (11.2.0) make delete request with api version **2021-03-01** now, however the recordings in aks-preview records request with api version **2021-02-01**. So this pr change is breaking aks-preview tests

**Comment by xfz11** [comment]
@yungezz

**Comment by yungezz** [comment]
> @haitch, @xfz11 the updated sdk version (11.2.0) make delete request with api version **2021-03-01** now, however the recordings in aks-preview records request with api version **2021-02-01**. So this pr change is breaking aks-preview tests

hi @haitch this PR caused Azure CLI extension repo CI test failed, it blocks PRs in extension repo. Could you pls fix aks extension tests to make CI pass?

**Comment by haitch** [comment]
We have a fix PR pending to be merged: https://github.com/Azure/azure-cli-extensions/pull/3378 

> > @haitch, @xfz11 the updated sdk version (11.2.0) make delete request with api version **2021-03-01** now, however the recordings in aks-preview records request with api version **2021-02-01**. So this pr change is breaking aks-preview tests
> 
> hi @haitch this PR caused Azure CLI extension repo CI test failed, it blocks PRs in extension repo. Could you pls fix aks extension tests to make CI pass?

**Pull request merged**
