### PR TITLE
[EventHubs] Migrate to track2 SDK

### PR DESCRIPTION
**Pull request by v-Ajnava**
**Description**

>Migrate to Track2 changes and Added require_infrastructure_encryption parameter to namespace update command
>Added disable-local-auth parameter to namespace create and update command
>Added new private-endpoint-connection and private-link-resource commands for namespace

**Testing Guide**  
### Approve 

> az eventhubs namespace private-endpoint-connection approve
example: 
az eventhubs namespace private-endpoint-connection approve -g myRg --namespace-name mynamespace --name myconnection

### Delete 

> az eeventhubs namespace private-endpoint-connection delete
example: 
az eventhubs namespace private-endpoint-connection delete -g myRg --namespace-name mynamespace --name myconnection

### Delete 

> az eeventhubs namespace private-endpoint-connection reject
example: 
az eventhubs namespace private-endpoint-connection reject -g myRg --namespace-name mynamespace --name myconnection

### show

> az eventhubs namespace private-endpoint-connection show
example: 
az eventhubs namespace private-endpoint-connection show -g myRg --namespace-name mynamespace --name myconnection

### show

> az eventhubs namespace private-link-resource show
example: 
az eventhubs namespace private-link-resource show --namespace-name mynamespace -g MyResourceGroup

**History Notes**

[EventHub] 'az eventhubs namespace update' : Add `--infra-encryption` for encryption (enable-require-infrastructure-encryption).
[EventHub] 'az eventhubs namespace create/update' : Add `--disable-local-auth` to enable or disable  SAS authentication.
[EventHub] Added new private-endpoint-connection and private-link-resource commands for namespace

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
EventHubs

**Comment by v-Ajnava** [comment]
Hi @evelyn-ys , the failing test are from SQL and Iot hub which uses Eventhub, can you please help me on it?

**Comment by evelyn-ys** [comment]
> Hi @evelyn-ys Yishi Wang FTE , the failing test are from SQL and Iot hub which uses Eventhub, can you please help me on it?

Hi @v-Ajnava, You have to rerun all eventhubs related tests even if it's from other modules. Use `azdev test the_specific_test_name --live` and commit the yaml changes~

**Comment by v-Ajnava** [comment]
Hi @evelyn-ys , all CI passed. can  you please review ?

**Review by evelyn-ys — APPROVED** [review]

**Comment by v-Ajnava** [comment]
Hi @kairu-ms, can you please review the PR ? I have added Private endpoint commands

**Review by kairu-ms — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Comment by jiasli** [comment]
The history notes incorrectly uses single quotes `'` rather than backticks `` ` ``:

```
History Notes

[EventHub] 'az eventhubs namespace update' : Add --infra-encryption for encryption (enable-require-infrastructure-encryption).
[EventHub] 'az eventhubs namespace create/update' : Add --disable-local-auth to enable or disable SAS authentication.
[EventHub] Added new private-endpoint-connection and private-link-resource commands for namespace
```

**Pull request merged**
