### PR TITLE
[sql] `az sql midb move/copy`: Add new commands for Managed Database Move/Copy feature

### PR DESCRIPTION
**Pull request by ReneaMoso**
**Related command**
These are new commands

**Description**

In this PR I introduce new commands to support SQL Managed Database Move/Copy feature. Managed databases can be moved/copied across managed instances (and resource groups) that whose vNets fulfill certain networking requirements.

The commands that are introduced are:

`az sql midb move start` - Start a managed database moveoperation from source instance to target instance 
`az sql midb move complete` - Complete a move operation
`az sql midb move cancel` - Cancel a move operation
`az sql midb move list` - List move operations from given instance and resource group (can also additionally be filtered by target rg and instance, and filtered to only include latest operation per managed database)
`az sql midb copy start` - Start a managed database copy operation from source instance to target instance
`az sql midb copy complete` - Complete a copy operation
`az sql midb copy cancel` - Cancel a copy operation
`az sql midb copy list` - List copy operations (same as list move operations)

**Testing Guide**

You can test operations by copying/moving managed database across managed instances in the same subnet (peering will be established and move/copy will work).

Some examples of commands:
`az sql midb move start --ids {id_of_database_to_move} --target-mi {name_of_target_mi}`
`az sql midb move complete --ids {id_of_database_to_move} --target-mi {name_of_target_mi}`
`az sql midb move cancel--ids {id_of_database_to_move} --target-mi {name_of_target_mi}`

Copy command are equivalent, instead of `move` use `copy`.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
sql midb

**Comment by ReneaMoso** [comment]
Hi @evelyn-ys, is there any additional steps I should take to have this PR reviewed for the upcoming release?

**Review by evelyn-ys — APPROVED** [review]
PR looks good to me.

But for new commands or new features *(especially for atomic commands)*, we strongly recommend that you try our advanced code generation tools [CodeGen - AAZ](https://azure.github.io/aaz-dev-tools/)

This tool is easy to use and can bring you the following benefits:
- It can improve your development efficiency and reduce manual effort.
- It can ensure the style and consistency of code, so it also reduces the burden of PR review.
- It can improve code quality and reduce the occurrence of bugs.
......

If you are interested in it and would like to learn more, please contact our CodeGen expert @kairu-ms

**Comment by ReneaMoso** [comment]
@evelyn-ys thanks for the review! I am good to merge this if you are.

**Pull request merged**
