### PR TITLE
[Lab] Fix for issue #7904 date validation bug in lab vm creation

### LINKED ISSUE #7904: az lab vm create does not parse --expiration-date correctly
**Describe the bug**
`--expiration-date` is neither documented nor parsed correctly. Documentation says "The expiration date in UTC(YYYY-mm-dd) for the VM." In reality, it's an ISO 8601 timestamp. When providing a time a few hours in the future, the command returns an error.

**To Reproduce**
```
$ TZ=UTC date '+%Y-%m-%dT%H:%M:%SZ'
2018-11-22T15:30:11Z

$ az lab vm create -g $rg --lab-name $lab --name vm1 --formula $formula --saved-secret VmPassword --expiration-date $(TZ=UTC date -v+2H '+%Y-%m-%dT%H:%M:%SZ')
Expiration date '2018-11-22T17:30:21Z' must be in future.
```

**Expected behavior**
VM should be created without an error.

**Environment summary**
homebrew azure-cli v2.0.51

### PR DESCRIPTION
**Pull request by Gladdstone**
**Description**  

Current documentation marks this as a naive UTC date. 

**Testing Guide**  

`az lab vm create --lab-name {LabName} -g {ResourceGroup} --name {VMName} --image "Ubuntu Server 16.04 LTS" --image-type gallery --expiration-date {YYYY-MM-DDThh:mm:ss}`
* current datetime +2 hours
* vm should be created without error

**History Notes**  

[Component Name 1] Fix #7904: az lab vm create: Fix date validation

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S170

**Comment by yungezz** [comment]
hi @Gladdstone @qwordy is this PR ok to merge?

**Comment by qwordy** [comment]
"connect reset by peer" error

**Pull request merged**
