### PR TITLE
functionapp: Add support for app service plan creation (With EP)

### PR DESCRIPTION
**Pull request by ankitkumarr**
\cc @ahmedelnably @panchagnula @Nking92  @jeffhollan 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by ahmedelnably** [comment]
Also cc/ @jeffhollan to advice on when this should be available publicly?

**Comment by jeffhollan** [comment]
@ahmedelnably Feb 6 is when would be best to get out public. Do have a small window before and after though. Let me know if that works.

**Comment by ahmedelnably** [comment]
So this would go out with Sprint 54, which should be out by 2/12 <-- @jeffhollan does that work?
The other option is Sprint 53, which will be out on 1/29
Link to milestone times: https://github.com/Azure/azure-cli/milestones

**Comment by jeffhollan** [comment]
@ahmedelnably I think 2/12 should be ok.  I'm wondering if better to hit 1/29 though and just not have documentation about this new command for 7 days.  That way I don't have to write CLI docs that include installing the extension.  If we can squeeze it in for 1/29 let's do it.  If we can't I can make 2/12 work

**Comment by tjprescott** [comment]
LGTM. @jeffhollan one question: are these just aliases for the `appservice plan` commands or are function app plans actually a different thing?

**Comment by ahmedelnably** [comment]
@yugangw-msft from a customer messaging Functions and app service are two different products, the goal is for the functions user to only use az functionapp xyz to manage their app, it should be transparent to them the app service part. Also having a functionapp specific command allow us to remove the extra offerings that do not apply for functions ex. Hyper-v, we will have more commands that manage functionapps that we traditionally pointed users to use the webapp command. In summary, we are reacting to the fact that the two products are different, and want to give the users a consistent experience. HTH

**Comment by jeffhollan** [comment]
Yes this is more us addressing feedback that while from an implementation and API point of view this has strong overlap with App Service Plans, from a marketing and product point of view this is a seperate plan specific for function apps.  This plan would not support web apps or other app service plan resources, so moved to the functionapp section.

Also given some hiccups we are having with the Azure portal we really do need this out in the 1/29 release. Let me know if that won't be possible. Happy to jump on a call to answer any other questions as well as needed.  Appreciate the help

**Pull request merged**
