### PR TITLE
[AKS] `az aks`: Add oidc issuer support

### PR DESCRIPTION
**Pull request by karataliu**
**Related command**
az aks

**Description**
Support AKS oidc issuer feature

**Testing Guide**
```
az aks create --enable-oidc-issuer
az aks update --enable-oidc-issuer
az aks oidc-issuer rotate-signing-keys
```

**History Notes**

[AKS] `az aks create/update`: Add new parameter `--enable-oidc-issuer` to support enabling oidc issuer feature
[AKS] `az aks oidc-issuer rotate-signing-keys`: Add new command to support rotating oidc issuer service account signing keys

---
This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by karataliu** [comment]
Needs to hold, pending 2022-09-01 SDK update

**Comment by yonzhan** [comment]
AKS

**Comment by zhoxing-ms** [comment]
> Needs to hold, pending 2022-09-01 SDK update

OK, I'll make the `Do Not Merge` label first. Please notify us when the PR is ready, thanks~

**Comment by FumingZhang** [comment]
SDK with 2022-09-01 API is updated in PR [#24388](https://github.com/Azure/azure-cli/pull/24388).

Queued a [pipeline](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=62817053&view=results) to test the newly added test cases.

**Review by zhoxing-ms — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
