### PR TITLE
[DoNotMerge] CLI changes for BoundaryScaling

### PR DESCRIPTION
**Pull request by ravindrakreddy**
This PR contains the CLI changes specific to Boundary scaling for update

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/6311
This is an **experimental preview** for @microsoft users.

**Comment by ravindrakreddy** [comment]
@rohit-joy , @QingqingYuan  please review

**Comment by rohit-joy** [comment]
@derekbekoe, Please review.

**Comment by rohit-joy** [comment]
@ravindrakreddy, Please update changelog in history.rst.

**Comment by troydai** [comment]
Label as do not merge. Please advise when this PR is ready.

**Comment by QingqingYuan** [comment]
The backend deployment is ongoing. Expected WW time is May 23rd. Will come back asking for merge once that's finished. Thanks!

**Comment by troydai** [comment]
@QingqingYuan can we have a status update regarding this PR? If the service is not going to be ready in near-term, how about we close this PR for now?

**Comment by QingqingYuan** [comment]
This gets delayed a little bit. The backend is ready in some regions and supposed to complete WW 6/2. We should be able to merge on that day.

**Comment by troydai** [comment]
Note that 6/2 is the beginning of the next release. The release date will be two weeks away from today.

**Comment by QingqingYuan** [comment]
@troydai , Thanks for reminding! We have to wait for next release then, as we don't want to break customer experience.

**Comment by troydai** [comment]
@ravindrakreddy I will close this PR because it is months old and in no shape to be reviewed nor merged. Please feel free to update the changes on top of the latest `dev` and create new PR.

**Pull request closed without merging**
