### PR TITLE
Clarifying language for az network lb create

### PR DESCRIPTION
**Pull request by johnwildes**
Adjusted the language for the second example of the az network lb create to specifically highlight that the command will create a new lb on a NEW vnet and subnet, and not create a new lb on a specific vnet and subnet that already exists.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by johnwildes** [comment]
@tjprescott updated the language to reflect requested changes.

**Comment by tjprescott** [comment]
Conflict must be resolved in order to merge.

**Comment by yugangw-msft** [comment]
@MyronFanQiu, when you have time can you please port the change over by creating a new PR and then close this one?

**Comment by MyronFanQiu** [comment]
@yugangw-msft No problem.

**Comment by MyronFanQiu** [comment]
@yugangw-msft Hello. I have rebased this branch to our dev. I think we can merge it now.

**Pull request merged**
