### PR TITLE
appservice: support updating configuration through json

### LINKED ISSUE #5228: webapp:Support passing a JSON file for appsettings
Ex. az webapp config appsettings set -n <appname> -g <rgname> --settings-file <path-json-file>

### LINKED ISSUE #5734: [Webapp] Webapp config set: Provide a way to pass JSON
The List option can easily provide the existing settings, please provide a way to pass that JSON output to the set method to easily configure the site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30f2ae52-2c7f-7e7e-8a62-f1b614f281d3
* Version Independent ID: 9f23ff17-14e0-7800-0094-fb50a5fa91d6
* [Content](https://docs.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest#az_webapp_config_appsettings_set)
* [Content Source](https://github.com/Azure/azure-docs-cli-python/blob/live/latest/docs-ref-autogen/webapp/config/appsettings.yml)
* Service: app-service-web

### PR DESCRIPTION
**Pull request by yugangw-msft**
Fix #5734  Fix #5228

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yugangw-msft** [comment]
Samples:
``` bash
az webapp config set -g MyResourceGroup -n MyUniqueApp --generic-configurations "{\"alwaysOn\": true}"
az webapp config set -g MyResourceGroup -n MyUniqueApp --generic-configurations @mySiteConfig1.json
az webapp config appsettings set -g MyResourceGroup -n MyUniqueApp --settings mySetting=value @moreSettings.json
```

**Comment by markheath** [comment]
Thanks for this. Will this also work for
`az functionapp config appsettings set`?

**Comment by yugangw-msft** [comment]
@markheath, yes, `appsettings set` will also work. The only difference on `appsettings set` is it also supports to take the output of `appsettings list`.
You can verify now with using dev builds, particularly the docker image https://github.com/azure/azure-cli#docker

**Comment by markheath** [comment]
thanks for the tip on using docker - a nice way to try out the latest bits. I was actually wondering whether equivalent **functionapp** commands have also picked up the same behaviour.

**Comment by yugangw-msft** [comment]
Yes, `functionapp`  shares the same implementation

**Pull request merged**
