### PR TITLE
[AKS] Monitoring addon MSI auth - use existing tags on container insights extension dcr for PUT

### PR DESCRIPTION
**Pull request by ganga1980**
**Description**

For MSI auth of Monitoring addon, there will be DCR created  with format MSCI-<clusterName>-<clusterRegion>. If the customer tags and this resource exists, in case of customer try to re-onboard the monitoring addon with MSI auth, existing tags (if any) will be used for the PUT to retain the customer tags.

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Review by FumingZhang — COMMENTED** [review]
Please make sure the changes won't break aks-preview, which refers the code from azure-cli.

**Comment by zhoxing-ms** [comment]
> Please make sure the changes won't break aks-preview, which refers the code from azure-cli.
@ganga1980 Could you please reply this question?

**Comment by zhoxing-ms** [comment]
@ganga1980   Could you address these comments and  refer to [submitting-pull-requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests) to modify the PR title by tomorrow? 
If not, this PR will not be able to catch up with the release of the sprint, and it can only be postponed to the next sprint (**05-24**)

**Comment by FumingZhang** [comment]
Rebased the branch from dev and queued a [pipeline](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=55463585&view=results) to check some live test cases involving the monitoring addon.

**Review by FumingZhang — APPROVED** [review]
All the live tests passed, LGTM.

**Comment by zhoxing-ms** [comment]
@ganga1980 Is this change perceptible to users? If not, please use `{}` in the PR title so that it will not be written in the history note

**Comment by ganga1980** [comment]
> > Please make sure the changes won't break aks-preview, which refers the code from azure-cli.
> 
> @ganga1980 Could you please answer this question?

> yes, these changes have been validated with aks-preview.

**Pull request merged**
