### PR TITLE
[AppService] fix #11698- Apply access restriction to resources in different resource groups

### LINKED ISSUE #11698: webapp: Apply access restriction to resources in different resource groups
I'd like to add VNET access restriction to Azure Function App. Azure Function App is located in RG1 and VNET is located in RG2.
I can't get it to work even with IDs.
Command:
`
az webapp config access-restriction add 
  --priority 100 
  --action Allow 
  --name $newParameters.FunctionAppName 
  --rule-name "APIm" 
  --subnet $newParameters.APImSubnetName 
  --vnet-name $newParameters.VnetName
`
Error message:
The Resource 'Microsoft.Network/virtualNetworks/dev-deploy-vnet' under resource group 'dev-deploy-rg-dev' was not found.

Command:
`az webapp config access-restriction add 
  --priority 100 
  --action Allow 
  --rule-name "APIm" 
  --ids $b, $c
`
Message:
/subscriptions/xxx/resourceGroups/dev-deploy-rg-dev/providers/Microsoft.Web/sites/dev-deploy-fadev,: "(ResourceNotFound) The Resource 'Microsoft.Web/sites/dev-deploy-vnet' under resource group 'dev-deploy-rg' was not found."
/subscriptions/xxx/resourceGroups/dev-deploy-rg/providers/Microsoft.Network/virtualNetworks/dev-deploy-vnet: "(ResourceNotFound) The Resource 'Microsoft.Web/sites/dev-deploy-fadev,' under resource group 'dev-deploy-rg-dev' was not found.

It's possible through Azure Portal.
Any suggestions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c788e908-cee3-ae46-fac4-956d0606ad76
* Version Independent ID: 2ed69bfd-bb05-3d09-072e-00e505856fba
* Content: [az webapp config access-restriction](https://docs.microsoft.com/en-us/cli/azure/webapp/config/access-restriction?view=azure-cli-latest#az-webapp-config-access-restriction-set)
* Content Source: [latest/docs-ref-autogen/webapp/config/access-restriction.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/access-restriction.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

### PR DESCRIPTION
**Pull request by Kotasudhakarreddy**
fix #11698 

**Description**  

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by Kotasudhakarreddy** [comment]
@madsd - please review this PR, as it is related to `az webapp config access-restriction add`
@panchagnula - FYI

**Comment by madsd** [comment]
There is a problem with this implementation - it will pick a "random" vNet, as this does not have a unique name, and you could have several vNets with the same name and subnet name across resource groups and subscriptions

**Comment by Kotasudhakarreddy** [comment]
> There is a problem with this implementation - it will pick a "random" vNet, as this does not have a unique name, and you could have several vNets with the same name and subnet name across resource groups and subscriptions

will work on it.

**Comment by Kotasudhakarreddy** [comment]
Closing this PR as I need to rewrite my logic based on design decision taken.

**Pull request closed without merging**
