### PR TITLE
[SQL] `az sql mi create`, `az sql mi update`: Add `--service-principal-type` parameter to support Win Auth (Kerberos)

### PR DESCRIPTION
**Pull request by rmosho**
**Description**
Adding Service Principal parameter to _az sql mi update_ and _az sql mi create_ command for Windows Authentication for MI feature.

**Testing Guide**
A scenario test has been added for update of MI with service principal.
For manual testing: use _az sql mi update_ and _az sql mi create_ with --service-principal-type SystemAssigned

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
SQL

**Comment by evelyn-ys** [comment]
It seems not following our guideline for managed identity: https://github.com/Azure/azure-cli/blob/dev/doc/managed_identity_command_guideline.md

**Comment by rmosho** [comment]
@evelyn-ys It appears that the existing command already doesn't follow the guidelines. I have not added a new command, only added a new parameter to existing command, as per PM's request for this feature. We are not looking to change the command at this time because this feature is supposed to be released soon.

**Comment by rmosho** [comment]
@evelyn-ys @zhoxing-ms Could someone please review and approve this PR? The snap is in less than a week and I have not heard from anyone in a while?

**Review by evelyn-ys — COMMENTED** [review]
LGTM

Since we have not had best practice for `--service-principal-type` so I'd consider this PR isn't violating our guideline. I prefer to approve this PR @zhoxing-ms

**Review by evelyn-ys — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]
In fact, we have only formulated guidelines for managed identity [managed_identity_command_guideline](https://github.com/Azure/azure-cli/blob/dev/doc/managed_identity_command_guideline.md) but there is no design guidelines for service principal at present. So I personally think it is not necessary to only make the service principal parameters refer to the guidelines of managed identity, especially when the identity parameter itself does not follow the guideline of managed identity.

In addition, I think the service principal also needs to formulate it's own guidelines, if it's usage is similar to managed identity, then it can refer to managed identity guideline. + service principal owner @jiasli please be aware.

**Pull request merged**
