### PR TITLE
{Bicep} Update the URL for Bicep downloads link

### PR DESCRIPTION
**Pull request by davidcho23**
**Related command**

**Description**

Updated URL for Bicep Downloads link to use new Bicep CDN: https://github.com/Azure/bicep/issues/3689

**Testing Guide**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Bicep

**Review by majastrz — APPROVED** [review]
:shipit:

**Comment by zhoxing-ms** [comment]
@shenglol please help review this PR

**Review by shenglol — APPROVED** [review]
LGTM!

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
