### PR TITLE
Updating to preserve line breaks

### PR DESCRIPTION
**Pull request by DuncanmaMSFT**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DuncanmaMSFT__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (duncanma). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by JasonRShaver** [comment]
by breaking text into multiple lines, you can no longer cut and paste them, which is kind of important for a CLI help file.  We could use something like

```
$ az long command \
that is more than one line
```

but this would not work for Windows users (Windows uses ^).  Obviously this is not a new issue, but breaking a 2-line item into a 6-line item makes it worse... 
 
I think this might need to be handled by the doc importer, but there might be some benefit to keeping the CLI web content focused on cut-paste-able content.

**Comment by DuncanmaMSFT** [comment]
Jason, if I add the \ in, can we go with that for now? Alternatively, mid to long term, we can wrap on the client... and provide a 'copy' button that puts it on the clipboard with no line breaks, but for right now (for appearances), I'd like to show the \

**Comment by DuncanmaMSFT** [comment]
I've updated the code sample, if you have time to 're-review' @JasonRShaver

**Comment by JasonRShaver** [comment]
Updated to escape out the `\`

**Comment by bradygaster** [comment]
@JasonRShaver is it possible we could get this PR merged to trigger your build process so we're solid tomorrow? cc @DuncanmaMSFT

**Comment by yugangw-msft** [comment]
Please check out #1006, the format issues is not fully addressed, so the change was reverted

**Pull request merged**
