### PR TITLE
[API Management] - az apim: New subgroups

### PR DESCRIPTION
**Pull request by kevinhillinger**
**Additional API Management Module Updates (Preview)**  

included subgroup operations in the **apim** module for this PR:

- API
- API Policy
- Policy
- Product
- Subscription

Due to the number of subgroup operations in **apim** module, it's been structured to have each subgroup in its own folder under ```apim/operations```. There was an existing implementation for API subgroup, which was moved from the 'main' files (_custom, _params, etc.) and into ```apim/operations/api```

The specific commands supported with this PR:

-  **apim api**   { create, delete, list, show, update }  
-  **apim api policy**  { create, delete, list, show, update }  
-  **apim policy**  { create, delete, list, show, update }  
-  **apim product**  { create, delete, list, show, update }  
-  **apim subscription**  { create, delete, list, show, update, regenerate-key }  
-  **apim subscription keys**  { list, regenerate }  

**External Breaking Changes**
The command **az apim api import** has been removed in favor a streamlined **create** command to handle everything, given there is a lot of overlap in the options when importing an API.

Contributors on the team for this PR:

- @nikkiconley
- @petertuton 
- @perktime 
- @jonlester
- @franklin8705
- @JerryMSFT

The apim module was also updated to use the azure-mgmt-apimanagement==0.2.0 SDK, from 0.1.0

### CODE REVIEW

**Comment by yonzhan** [comment]
API Management

**Comment by MyronFanQiu** [comment]
@RupengLiu Is this PR duplicate with yours?

**Comment by kevinhillinger** [comment]
RE: Failing Credential Scan

The scenario test for the API subgroup uses a storage account to upload test XML files for creating APIs using URLs for WSDL and OpenAPI.

To keep the files private, there's a sas token that's used as part of the value when setting test variables for the urls. This gets captured in the recording and gets flagged.

Is there a preferred way around this?

**Comment by kevinhillinger** [comment]
**Changes due to merge**

Due to prior work that overlapped with this PR, I identified the changes and structured the code to this large commit. Here are the details:

Moved code into ```operations/``` directory, isolating them for clean code and testability isolation:

- api release
- api revision
- api version set
- named value
- product api

I updated CLI commands as follows:

**API Version Set**
The existing command was defined as ```apim api versionset```. I updated it to adhere to CLI standards and because version set is not a subgroup command of API. 

It's now been defined as ```apim api-version-set```.

**Named Value**
The existing command was defined as ```apim nv```. To match more closely with CLI authoring standards, it's been changed to ```apim named-value```, providing clarity and readability on the subgroup command.

**API**
There are changes to the API command options, and I'm reviewing the diff more closely.

**Comment by haroldrandom** [comment]
Could you resolve the conflicts if the PR is still active?

**Comment by haroldrandom** [comment]
Could you resolve the conflicts first?

**Comment by kevinhillinger** [comment]
I will try and work on removing the conflicts, but given the time that's passed, I'll review changes in light of current state and follow up here.

**Comment by yonzhan** [comment]
Please resolve the conflicts first.

**Comment by kevinhillinger** [comment]
Due to 2 years being outdated, the merge update was too great to handle. The Fork was reset to HEAD and the changes migrated over. 

New PR #23690

**Pull request merged**
