### PR TITLE
Merge AKS post release changes.

### PR DESCRIPTION
**Pull request by troydai**

### CODE REVIEW

**Comment by troydai** [comment]
@mboersma you can list the changes you want to make and I will add it to this PR and get it merged together.

**Comment by troydai** [comment]
@mboersma if you have text now, you can send it to me and I will append it to this PR. This way we can save an additional PR. Your call.

**Comment by mboersma** [comment]
@troydai how about this for /src/command_modules/azure-cli-acs/HISTORY.rst:


unreleased
++++++

* call "agent" a "node" in AKS to match documentation

**Comment by troydai** [comment]
Cool, will do.

**Comment by troydai** [comment]
History is updated. Rebased on latest dev as well. Pending CI.

**Pull request merged**
