### PR TITLE
Standardize action verbs in command module descriptions.

### PR DESCRIPTION
**Pull request by twitchax**
Addresses #6166.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by twitchax** [comment]
@yugangw-msft, do we upgrade command module versions when docs are updated?

**Comment by yugangw-msft** [comment]
//cc: @troydai, I think so, but I know we might have a CI issue on-going regarding the version check
as #6572 also has a similar error

**Comment by twitchax** [comment]
Thanks, just let me know if I need to make version edits.

**Comment by tjprescott** [comment]
@twitchax you do need to make the version bumps.  Also @sptramer should review.

**Pull request merged**
