### PR TITLE
[AppService] Unhide Python 3.9 in functionapp create

### PR DESCRIPTION
**Pull request by Hazhzeng**
**Description**

Azure Functions team plan to release Python 3.9 preview. We want to unhide the --runtime-version 3.9 in `functionapp create --help`.

**Testing Guide**

Test with `az functionapp create --help`. The help content contains
```
    --runtime-version                    : The version of the functions runtime stack. Allowed
                                           values for each --runtime are: node -> [8, 10, 12, 14
                                           (preview)], java -> [8, 11], powershell -> [7.0], python
                                           -> [3.6, 3.7, 3.8, 3.9 (preview)].
```

**History Notes**

[AppService] Allow customer to create Python 3.9 function app

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by Hazhzeng** [comment]
cc: @anirudhgarg @vrdmr @pragnagopa

**Comment by pragnagopa** [comment]
please send PR to https://github.com/pragnagopa/azure-functions-supported-runtime-stacks

**Review by pragnagopa — APPROVED** [review]

**Review by qwordy — APPROVED** [review]

**Comment by yonzhan** [comment]
AppService

**Comment by yungezz** [comment]
hi @Hazhzeng could you pls look at CI failure, after CI passed we can move forward to merge the PR? thanks

**Comment by Hazhzeng** [comment]
Hi @yungezz @qwordy, sorry for the late reply.
I've merged the latest updates on the dev branch and the PR now passes the tests.
Please merge this PR to dev and mark this into **S181**. Thanks

**Comment by qwordy** [comment]
Official Release: 12/29/2020

**Pull request merged**
