### PR TITLE
[RDBMS] `az postgres flexible-server migration create`: Fix bugs while passing in MigrationRuntimeResourceId to Migration Parameters, now need to be provided within properties json file

### PR DESCRIPTION
**Pull request by nasc17**
**Related command**
az postgres flexible-server migration create

**Description**
BUG FIX. The migration runtime resource id was not being passed in as a parameter when creating the migration.

Include the migration runtime resource ID only as a JSON property and not as a main command line argument.

**Testing Guide**
Manually
image

PS C:\home\azureCLI\azure-cli> az postgres flexible-server migration create --subscription sub --resource-group rgroup --name pe-cli-flexible --migration-name nasc_test5 --properties "C:\home\migration_test2.json"
Checking the existence of the resource group 'rgroup'...
Resource group 'rgroup' exists ? : True 
Creating PostgreSQL Migration for server 'pe-cli-flexible' in group 'rgroup' and subscription 'sub'...
{
  "cancel": null,
  "currentStatus": {
    "currentSubStateDetails": null,
    "error": null,
    "state": "InProgress"
  },
  "dbsToCancelMigrationOn": null,
  "dbsToMigrate": [
    "postgres"
  ],
  "dbsToTriggerCutoverOn": null,
  "id": "/subscriptions/sub/resourceGroups/rgroup/providers/Microsoft.DBforPostgreSQL/flexibleServers/pe-cli-flexible/migrations/nasc_test5",
  "location": "eastus",
  "migrateRoles": null,
  "migrationId": "07a67ddd-7c5e-4113-bda7-0c7cdf8cff7b",
  **"migrationInstanceResourceId": "/subscriptions/sub/resourceGroups/rgroup/providers/Microsoft.DBforPostgreSQL/flexibleServers/vnet-flex-test-cli",**
  "migrationMode": "Offline",
  "migrationOption": "ValidateAndMigrate",
  "migrationWindowEndTimeInUtc": null,
  "migrationWindowStartTimeInUtc": "2024-06-05T21:16:16.780666+00:00",
  "name": "nasc_test5",
  "overwriteDbsInTarget": "True",
  "resourceGroup": "rgroup",
  "secretParameters": null,
  "setupLogicalReplicationOnSourceDbIfNeeded": "False",
  "sourceDbServerFullyQualifiedDomainName": null,
  "sourceDbServerMetadata": null,
  "sourceDbServerResourceId": "/subscriptions/sub/resourceGroups/rgroup/providers/Microsoft.DBforPostgreSQL/servers/test-restore12",
  "sourceType": "PostgreSQLSingleServer",
  "sslMode": "VerifyFull",
  "startDataMigration": null,
  "systemData": null,
  "tags": null,
  "targetDbServerFullyQualifiedDomainName": null,
  "targetDbServerMetadata": null,
  "targetDbServerResourceId": "/subscriptions/sub/resourceGroups/rgroup/providers/Microsoft.DBforPostgreSQL/flexibleServers/pe-cli-flexible",
  "triggerCutover": "True",
  "type": "Microsoft.DBforPostgreSQL/flexibleServers/migrations"
}

**History Notes**

az postgres flexible-server migration create: Allow private endpoint migrations by setting migration runtime resource ID as a configuration defined for the migration properties.

---

### CODE REVIEW

**Comment by yonzhan** [comment]
RDBMS

**Comment by evelyn-ys** [comment]
This is an breaking change and CLI only allows breaking change twice a year. I know it's a newly added parameter, Can you check the parameter usage first?

**Comment by nasc17** [comment]
Good morning,

This is the same command discussed in Out of Band thread from yesterday. We viewed usage 52 times from 2 users in the same subscription.

Should I bring up the change of wanting the argument to be JSON property only in that Teams chat?


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by evelyn-ys — APPROVED** [review]

**Comment by evelyn-ys** [comment]
Since there's quite few usage with only 1 subscription and even this subscription can't work properly, so approved as it won't break existing scripts

**Pull request merged**
