### PR TITLE
AKS support for SLB+VMSS

### PR DESCRIPTION
**Pull request by xuto2**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by zikalino** [comment]
Looks good in general, but a few comments:
- could we also support public ip name if the same resource group for instance? I think passing is too complex
- I think it would be good to improve documentation and define what's the relationship between new parameters

**Comment by zikalino** [comment]
I think it's ok to merge as is, some improvements could be made in the future

**Comment by xuto2** [comment]
Thanks a lot for the comments, @zikalino . Will take your suggestion into the consideration in the next release(should not be too far).

**Comment by xuto2** [comment]
@qwordy , can you take a look ?

**Pull request merged**
