### PR TITLE
[App Service] BREAKING CHANGE: `az appservice ase create`: Update the default App Service Environment to V3

### PR DESCRIPTION
**Pull request by seligj95**
**Related command**

az appservice ase create

**Description**

Currently default ASE kind is set to ASEv2. ASEv2 is retiring in August 2024 and creates of ASEv2 will be blocked starting in January. So we need the default to be updated to ASEv3 to prevent errors and ensure customers are getting onto the latest version.

**Testing Guide**

az appservice ase create -g <rg> -n <asename> --vnet-name <vnet> --subnet <subnet> : use this to create an ASEv3 since the default is now set to ASEv3. You no longer need to include the kind parameter for ASEv3 creates.

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
App Service

**Comment by zhoxing-ms** [comment]
@seligj95 Could you please address this comment? https://github.com/Azure/azure-cli/pull/27485#issuecomment-1791802651

**Comment by zhoxing-ms** [comment]
Please note that we are launching the release for this sprint this week. Please resolve all comments by Tomorrow, otherwise the release of this PR will have to be postponed to the next sprint **(on 12-05)**

**Comment by seligj95** [comment]
> Please note that we are launching the release for this sprint this week. Please resolve all comments by Tomorrow, otherwise the release of this PR will have to be postponed to the next sprint **(on 12-05)**

Having trouble with the scenario tests. Working on it, will reach out if I need some assistance.

**Comment by seligj95** [comment]
> Please note that we are launching the release for this sprint this week. Please resolve all comments by Tomorrow, otherwise the release of this PR will have to be postponed to the next sprint **(on 12-05)**

@zhoxing-ms - I spoke with my counterpart who has worked on CLI commands for this same module in the past. For this command, we only have mock tests, not scenario tests. So they don't generate the recordings from the scenario tests because there are no scenario tests. Since I'm just making minor updates to existing commands to change the default resource type, I believe the mock test updates should be enough to satisfy the needs for this PR. Please let me know if any issues with this.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
