### PR TITLE
{CI} Update azure-client-tools-bot's auto-reply to be more friendly

### PR DESCRIPTION
**Pull request by furnivall**
**Description**
Just to make it a little less aggressive when telling you to upgrade if you are not physically able to do so.

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by furnivall** [comment]
@wangzelin007 should I close this PR? afaict it's still impossible to upgrade az cli to 2.51.0 from 2.50.0_1 on macOS/brew...

**Comment by wangzelin007** [comment]
> @wangzelin007 should I close this PR? afaict it's still impossible to upgrade az cli to 2.51.0 from 2.50.0_1 on macOS/brew...

Yes, I suggest you close this PR first, I didn't consider the correlation with the operating system when I detected the user version. This can't be solved by just modifying the description, I will add the OS association. As you said, the latest cli versions are not the same for different OS.

**Comment by furnivall** [comment]
> > @wangzelin007 should I close this PR? afaict it's still impossible to upgrade az cli to 2.51.0 from 2.50.0_1 on macOS/brew...
> 
> Yes, I suggest you close this PR first, I didn't consider the correlation with the operating system when I detected the user version. This can't be solved by just modifying the description, I will add the OS association. As you said, the latest cli versions are not the same for different OS.

It still might be worth saying that the bot's existing text is pretty rude to send to someone who is trying to help you improve the system if it's physically impossible for them to upgrade. 

You could alter the bot's text to be more polite *and* add the OS association.

Otherwise you might send an accidentally rude message to someone who is trying to flag an issue to you through poor choice of words, which could perhaps prevent them from wanting to contribute in the future. 

Just sayin'

**Review by wangzelin007 — APPROVED** [review]

**Comment by wangzelin007** [comment]
> > > @wangzelin007 should I close this PR? afaict it's still impossible to upgrade az cli to 2.51.0 from 2.50.0_1 on macOS/brew...
> > 
> > 
> > Yes, I suggest you close this PR first, I didn't consider the correlation with the operating system when I detected the user version. This can't be solved by just modifying the description, I will add the OS association. As you said, the latest cli versions are not the same for different OS.
> 
> It still might be worth saying that the bot's existing text is pretty rude to send to someone who is trying to help you improve the system if it's physically impossible for them to upgrade.
> 
> You could alter the bot's text to be more polite _and_ add the OS association.
> 
> Otherwise you might send an accidentally rude message to someone who is trying to flag an issue to you through poor choice of words, which could perhaps prevent them from wanting to contribute in the future.
> 
> Just sayin'

Sorry for making you feel bad, I have merged this PR, and we will add the OS association in the future.

**Pull request merged**
