### PR TITLE
[Sql] `az sql db ltr-policy/ltr-backup`: Add support for backup storage access tier

### PR DESCRIPTION
**Pull request by CelinaJiangJXY**
Change ltr-policy and ltr-backup related commands to include new property "backup-storage-access-tier".

**Related command**

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Sql

**Review by rebeccaxu-ms — APPROVED** [review]
lgtm, nit could be to make the change Yishi mentioned but otherwise seems fine

**Comment by yonzhan** [comment]
Please fix CI issues.

**Comment by evelyn-ys** [comment]
Please fix linter failure:
`ERROR: /mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/sql/custom.py:3018:112: W291 trailing whitespace`

**Pull request merged**
