### PR TITLE
Append AZURE_HTTP_USER_AGENT to the user agent

### PR DESCRIPTION
**Pull request by troydai**
Enable the user of the CLI to specify a value to the AZURE_HTTP_USER_AGENT environment variable so as to append additional information to the user agent header.

### CODE REVIEW

**Comment by tjprescott** [comment]
@troydai what's the use case for this?

**Comment by troydai** [comment]
Explained offline. The major usage is for a 3rd party user of the CLI to have their own mark in telemetry.

**Comment by johanste** [comment]
Can you please verify that we are adding the UA string for data planes as well?

**Comment by troydai** [comment]
Good point. Let me take a look after this is merged.

**Pull request merged**
