### PR TITLE
[Cognitive Services] Update SDK to use latest API version

### PR DESCRIPTION
**Pull request by yangyuan**
**Related command**
az cognitiveservices usage list
az cognitiveservices model list

**Description**
Regular SDK/API update which came with new APIs

**Testing Guide**
`az cognitiveservices usage list`
`az cognitiveservices model list`
`az cognitiveservices account deployment create` will accept sku and capacity parameters

**History Notes**

[CognitiveServices] `az cognitiveservices account deployment create` now accept sku and capacity parameters
[CognitiveServices] New command `az cognitiveservices usage list`
[CognitiveServices] New command `az cognitiveservices model list`

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Cognitive Services

**Comment by kairu-ms** [comment]
Hi @yangyuan, It's not breaking change window. there's a breaking change in your PR. 
image

**Comment by yangyuan** [comment]
@kairu-ms breaking change was not necessary, fixed.

**Comment by kairu-ms** [comment]
> @kairu-ms breaking change was not intended/necessary, fixed.
> 
> One test failed but its unrelated to our service. (Its KV's tests)

Glad our tool detected this unexpected problem. Good job @AllyW @wangzelin007

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
