### PR TITLE
{Misc.} Add CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by Jacekey23**
CODE_OF_CONDUCT.md Standard
[aka.ms/opensource/moderation-support](https://aka.ms/opensource/moderation-support)

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by yonzhan — APPROVED** [review]

**Review by jiasli — APPROVED** [review]

**Comment by jiasli** [comment]
It's better to a create a PR from a forked repo's branch.

**Comment by bebound** [comment]
`CODE_OF_CONDUCT.md` requirement is mentioned in https://docs.opensource.microsoft.com/releasing/

**Review by bebound — APPROVED** [review]

**Pull request merged**
