### PR TITLE
[ACR] az acr connected-registry: Minor bug fixes

### PR DESCRIPTION
**Pull request by rosanch**
**Description**
Fixes a few mistakes with the help and error output. 

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Review by northtyphoon — APPROVED** [review]
LGTM

**Comment by yonzhan** [comment]
ACR

**Review by Juliehzl — APPROVED** [review]
LGTM, but please fix style error, which is blocking the merge

**Comment by Juliehzl** [comment]
Hi @rosanch , I help you resolve the style issue as it is close to build

**Pull request merged**
