### PR TITLE
[SQL] Add Per DB CMK scenarios

### PR DESCRIPTION
**Pull request by viparek**
**Related command**

**Description**
This PR adds new parameters to create, update, restore and copy a database with per database CMK

**Testing Guide**
Added tests to cover the new scenarios in database create/update

**History Notes**

[SQL] `az sql db tde-key revalidate/revert`: New commands to revert and revalidate the TDE protector key for the database and SQL server
[SQL] `az sql db create/update/show`: Add `--keys`, `--encryption-protector`, `--assign-identity`, `--user-assigned-identity-id` parameters to support Per DB CMK

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
SQL

**Comment by viparek** [comment]
@yonzhan / @evelyn-ys  can you please help me in fixing this error that is failing the pipeline:

how to get past this error: 2023-02-21T21:01:39.0226521Z src/azure-cli/azure/cli/command_modules/sql/custom.py:1694:0: R0914: Too many local variables (28/25) (too-many-locals)

**Comment by evelyn-ys** [comment]
Can you edit the history notes to tell CLI customers what's new in the format of:
[SQL] `az sql aaa/bbb`: New commands to balabala
[SQL] `az sql xxx`: Add `--parameter` to support balabala

**Comment by viparek** [comment]
> Can you edit the history notes to tell CLI customers what's new in the format of: [SQL] `az sql aaa/bbb`: New commands to balabala [SQL] `az sql xxx`: Add `--parameter` to support balabala

Done

**Review by evelyn-ys — APPROVED** [review]

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
