### PR TITLE
{Iot Hub} Removed remaining PnP parts

### PR DESCRIPTION
**Pull request by anusapan**
**Description**  
Removing the remaining legacy parts of the PnP as this is unused and the commands has already been moved to the extension.

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Iot Hub

**Comment by zhoxing-ms** [comment]
@anusapan May I ask will these deletions cause breaking changes to customers?

**Comment by anusapan** [comment]
> @anusapan May I ask will these deletions cause breaking changes to customers?

No, these are the files which aren't in use anymore

**Comment by zhoxing-ms** [comment]
@anusapan This code looks like SDK code, just be curious, may I ask why was it put in CLI before?

**Comment by anusapan** [comment]
> @anusapan This code looks like SDK code, just be curious, may I ask why was it put in CLI before?

@zhoxing-ms Adding SDK here, was a long time back, but now we are doing some data-plane operations, So we have planned to move this out to iot-extension. Everything already moved to the extension and this PR is for removing the remaining files which are no longer in use

**Comment by zhoxing-ms** [comment]
> @anusapan This code looks like SDK code, just be curious, may I ask why was it put in CLI before?
> 
> @zhoxing-ms Adding SDK here, was a long time back, but now we are doing some data-plane operations, So we have planned to move this out to iot-extension. Everything already moved to the extension and this PR is for removing the remaining files which are no longer in use

Got it~ Thanks

**Review by MyronFanQiu — APPROVED** [review]

**Comment by Juliehzl** [comment]
Because there is no code owner, nobody could merge the PR now @yonzhan

**Comment by zhoxing-ms** [comment]
@digimaun Could you please help to review and merge this PR?

**Pull request merged**
