### PR TITLE
{Packaging} Remove azure-devtools as a dependency

### PR DESCRIPTION
**Pull request by fengzhou-msft**
**Description**  

MSI package building failed in CI caused by building the latest `yarl` and `multidict` packages from source. Details in below [comment](https://github.com/Azure/azure-cli/pull/15508#issuecomment-708127006).

These 2 packages are implicitly downloaded as they are in the dependency tree of `azure-devtools`. `azure-devtools` is only needed for development and testing and should be removed as a dependency in `requirements.txt` for building `azure-cli` packages. The `setup.py` for `azure-cli` does not contain `azure-devtools`.

`yarl` is used in [`storage-blob-preview`](https://github.com/Azure/azure-cli-extensions/blob/master/src/storage-blob-preview/azext_storage_blob_preview/vendored_sdks/azure_storage_blob/v2019_12_12/_shared/authentication.py#L17), but the code has [workaround](https://github.com/Azure/azure-cli-extensions/blob/master/src/storage-blob-preview/azext_storage_blob_preview/vendored_sdks/azure_storage_blob/v2019_12_12/_shared/authentication.py#L80-L87) when `yarl` is not available. So it's OK to remove it. Besides, if users install through `pip install azure-cli`, `yarl` is not installed either and we haven't received relative issues.

**Testing Guide**  

Packages tested in `build_test` branch: https://dev.azure.com/azure-sdk/public/_build/results?buildId=573646&view=results

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Packaging

**Comment by jiasli** [comment]
Any reason why pinning these 2 dependencies fixes the issue?

**Comment by fengzhou-msft** [comment]
> Any reason why pinning these 2 dependencies fixes the issue?

The new versions introduced some changes for python 3.9 to prebuild wheel: https://github.com/aio-libs/yarl/issues/526
The ADO may need extra settings for that.

**Review by yungezz — APPROVED** [review]

**Comment by jiasli** [comment]
When using `yarl==1.6.0`, `pip` is downloading `yarl-1.6.0-cp36-cp36m-win32.whl` ([link](https://dev.azure.com/azure-sdk/public/_build/results?buildId=572344&view=logs&j=78898306-33c5-5664-2f1b-a3010f777c49&t=69f9f981-48c0-5646-dd49-dca4323702d8&l=574)), but now it seems `yarl` has [dropped `win32` support](https://pypi.org/project/yarl/#files), causing `pip` to download source code `yarl-1.6.2.tar.gz` ([link](https://dev.azure.com/azure-sdk/public/_build/results?buildId=572297&view=logs&j=78898306-33c5-5664-2f1b-a3010f777c49&t=69f9f981-48c0-5646-dd49-dca4323702d8&l=595)) and build a wheel which requires `Python.h` which doesn't exit on the build agent ([link](https://dev.azure.com/azure-sdk/public/_build/results?buildId=572297&view=logs&j=78898306-33c5-5664-2f1b-a3010f777c49&t=69f9f981-48c0-5646-dd49-dca4323702d8&l=694)).

**Review by jiasli — APPROVED** [review]

**Pull request merged**
