### PR TITLE
[AKS] always create SPN with 5 years expiration time

### PR DESCRIPTION
**Pull request by rjtsdl**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/5914
This is an **experimental preview** for @microsoft users.

**Comment by rjtsdl** [comment]
@tjprescott please merge :)

**Comment by yugangw-msft** [comment]
I suggest you update the history file to call this out. Defaulting from 1 year to 5 years is not a trivial thing

**Comment by rjtsdl** [comment]
@yugangw-msft added

**Pull request merged**
