### PR TITLE
[ACR] Support pushing helm packages with path reference

### PR DESCRIPTION
**Pull request by djyou**
Fixes https://github.com/Azure/azure-cli/issues/7357

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by troydai** [comment]
Tests?

**Comment by troydai** [comment]
Feedback:
1. Add tests
2. Bump ACR command module version

**Comment by troydai** [comment]
Please add tests.

**Comment by djyou** [comment]
Will do. Thank you.

**Pull request merged**
