### PR TITLE
{AppConfig} Migrate to Track 2 Mgmt SDK

### PR DESCRIPTION
**Pull request by avanigupta**
**Description**
This PR upgrades the **azure-mgmt-appconfiguration** library to version **1.0.1**, which is the new track 2 management plane SDK.

Changes in Track 2 SDK:
- `ErrorException` has been removed. The SDK now throws `HttpResponseError` instead.
- Most client APIs exposed by the SDK now start with `begin_`.
- `id` cannot be passed directly to `regenerate_key` method. It needs to be wrapped in the new model `RegenerateKeyParameters`.
- List/regenerate credentials returns an `ApiKey` object, which does not need to be converted to JSON object. 

**Testing Guide**

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by avanigupta** [comment]
@shenmuxiaosen can you please help review these changes?

**Review by shenmuxiaosen — APPROVED** [review]
:shipit:

**Comment by yonzhan** [comment]
AppConfig

**Comment by qwordy** [comment]
@avanigupta I am writing a document of how to migrate to Track 2 SDK. You are welcome to contribute to it.
https://github.com/Azure/azure-cli/pull/16330

**Review by qwordy — APPROVED** [review]

**Comment by qwordy** [comment]
Wait for @shenmuxiaosen's comment

**Review by qwordy — APPROVED** [review]

**Pull request merged**
