### PR TITLE
[IoT] Track 2 SDK updates for DPS and IoT Central

### PR DESCRIPTION
**Pull request by c-ryan-k**
**Description**

Update SDKs for IoT Central and IoT Device Provisioning Service to track 2. 
This also bumps the API-version for DPS from `2018-01-22` to `2020-03-01`

**Testing Guide**

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
IoT

**Comment by c-ryan-k** [comment]
@yonzhan / @zhoxing-ms  just a heads up - this is an initial PR just to get our track 2 changes going, we're waiting on some new stable api-version SDK updates for DPS and Hub in order to add a few more changes to this PR

**Comment by yonzhan** [comment]
@c-ryan-k Thanks for the update. Please let us know when the PR is ready for review

**Comment by jsntcy** [comment]
@c-ryan-k, is this PR ready for review?

**Comment by c-ryan-k** [comment]
@jsntcy sorry this one's gonna get split up into two different PRs  - our SDKs aren't quite ready yet for the features this update will support - I'll close this for now and have a new PR later. Apologies for letting it sit.

**Comment by jsntcy** [comment]
@c-ryan-k, so you will create a PR only for track 2 migration?

**Pull request closed without merging**
