### PR TITLE
role: fix live tests

### PR DESCRIPTION
**Pull request by yugangw-msft**
- [na] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/6192
This is an **experimental preview** for @microsoft users.

**Comment by troydai** [comment]
@yugangw-msft needs some touch on the CI.

**Comment by yugangw-msft** [comment]
@troydai @derekbekoe, is it a known issue that the `test_integration.sh` could timeout in travis ci. I don't think my test-only change could regress on this. 
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

**Comment by derekbekoe** [comment]
@yugangw-msft: @tjprescott also ran in to this though not clear why.
Maybe go ahead and merge as Travis did on Friday?

**Pull request merged**
