### PR TITLE
shasum fallback to sha256sum

### PR DESCRIPTION
**Pull request by KThompso**
Add sha256sum(1) as a backup for shasum(1) when verifying checksum; shasum is not included by default in some linux distros (e.g. redhat).

Modify shasum check to use the command(1) builtin.

Refactor command checks not to rely on value of `$?`.

### CODE REVIEW

**Comment by KThompso** [comment]
Any  thoughts on why this build failed?

> travis_time:end:02470c00:start=1495729365518532650,finish=1495729887751239711,duration=522232707061
> 0K
> The command "./scripts/build.sh" exited with 0.
> 
> Done. Your build exited with 0.
>
>
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
> 
> The build has been terminated

**Comment by derekbekoe** [comment]
@KThompso I'm rerunning the tests

**Comment by KThompso** [comment]
@derekbekoe thanks for your help.  Third time's the charm I guess.  I wonder why it hangs...

**Comment by derekbekoe** [comment]
I will take a look at testing this on different OSs and platforms later today.
The PR looks good but I want to make sure it doesn't inadvertently break on one of our supported platforms.

**Comment by derekbekoe** [comment]
Thanks for the PR @KThompso!
I verified the change on macOS, Ubuntu 14.04/16.04, Debian 7/8, CentOS 7.1/7.2, RedHat 7.2, OpenSUSE 13.2, Bash on Windows.
The install script will be updated in the next release (mid next week).

**Pull request merged**
