### PR TITLE
[Core] ADAL to MSAL migration

### LINKED ISSUE #18944: ADAL to MSAL migration
As [ADAL has been deprecated](https://github.com/AzureAD/azure-activedirectory-library-for-python):

> This library, ADAL for Python, will no longer receive new feature improvements. Instead, use the new library
[MSAL for Python](https://github.com/AzureAD/microsoft-authentication-library-for-python).

Azure CLI needs to be migrated from ADAL to MSAL. 

### Reference

- [Microsoft Authentication Library (MSAL) for Python](https://github.com/AzureAD/microsoft-authentication-library-for-python)
- [Microsoft Azure Active Directory Authentication Library (ADAL) for Python](https://github.com/AzureAD/azure-activedirectory-library-for-python)
- [Migrate applications to the Microsoft Authentication Library (MSAL)](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-migration)
- https://github.com/Azure/azure-cli/issues/12946

### PR DESCRIPTION
**Pull request by jiasli**
Close #18944

## Description

As [ADAL has been deprecated](https://github.com/AzureAD/azure-activedirectory-library-for-python), Azure CLI needs to be migrated from ADAL to MSAL.

## How CLI authentication works

During initialization:

```
             _get_mgmt_service_client 
             /                      \
          1 /    CredentialAdaptor   \ 2
           v                          v
get_login_credential                SDK client
```

1. The client factory `azure.cli.core.commands.client_factory._get_mgmt_service_client` calls `azure.cli.core._profile.Profile.get_login_credentials` to get an instance of `CredentialAdaptor`.
2. `_get_mgmt_service_client` feeds the `CredentialAdaptor` instance into the SDK client.

During invocation:

```
           Track 1/2 SDK client
                    |
                    v     signed_session/get_token
            CredentialAdaptor
                    |    
                    v     get_token
UserCredential / ServicePrincipalCredential    
```

### `CredentialAdaptor`

1. When Track 2 SDK client makes an HTTP call, `azure.core.pipeline.policies._authentication.BearerTokenCredentialPolicy` calls the `get_token` method on the `CredentialAdaptor`.
2. When Track 1 SDK client makes an HTTP call, `msrest.pipeline.requests.RequestsCredentialsPolicy` calls the `signed_session` method on the `CredentialAdaptor`, `signed_session` calls `get_token`.

### `UserCredential`/`ServicePrincipalCredential`

Since Azure Identity has been dropped for User and Service Principal authentication, the MSAL integration is implemented in `src/azure-cli-core/azure/cli/core/auth/msal_authentication.py`.

There are 2 kinds of credentials:

1. `UserCredential` (inherit from `PublicClientApplication`)
2. `ServicePrincipalCredential` (inherit from `ConfidentialClientApplication`)

They all expose `get_token` so that they implement `azure.core.credentials.TokenCredential`.

## Cross-tenant authentication

Cross-tenant authentication is implemented by simply adding header `x-ms-authorization-auxiliary` by `_prepare_mgmt_client_kwargs_track2`.

There were asks (https://github.com/Azure/azure-sdk-for-python/issues/8313, https://github.com/Azure/azure-sdk-for-python/issues/17764) on Python SDK to implement cross-tenant authentication but it hasn't been implemented. 

Previously, CLI considered implementing a custom policy `ExternalAuthenticationPolicy` to achieve it, but is not implemented either due to its unnecessary complexity. Querying long-running operation result doesn't need auxiliary token, so no need to implement the `get_token` callback. 

## BREAKING CHANGES

- `az account show`/`az ad sp create-for-rbac`: `--sdk-auth` is removed (https://github.com/Azure/azure-cli/pull/19414).
- ADAL token cache and service principal secrets are no longer written to `~/.azure/accessTokens.json`

Changes on following objects are not considered breaking changes, but they may be used by end users or libraries:

- `azure.cli.core.adal_authentication` is removed, including
  - `AdalAuthentication`
    - `_token_retriever`
    - `_external_tenant_token_retriever`

If you depend on them, consider using public methods:

- `azure.cli.core._profile.Profile.get_raw_token`
- `azure.cli.core._profile.Profile.get_login_credentials`

### Test for different account types

- User
  - auth code flow
  - device code flow 
  - username password flow
- Service Principal
  - secret
  - certificate
  - client assertion (federated token)
- Managed Identity
  - clientId
  - objectId
  - resourceId

### Test for different SDK scenarios

- mgmt plane SDK client
  - resource
  - storage account
  - vm
  - network
  - ...
- data plane SDK client
  - storage: blob, table, ...
  - keyvault: keys, secrets, ...
  - ...
- cross-tenant operations
  - resource: template deployment
  - network: vnet peering

### Test for different clouds

- AzureCloud
- Sovereign clouds
- Azure Stack
  - AAD authentication
  - ADFS authentication

## References

- {Identity} Identity new features: https://github.com/Azure/azure-cli/pull/14690
- Old PRs related to Azure Identity and MSAL integration: https://github.com/Azure/azure-cli/pulls?q=is%3Apr+label%3AMSAL
- ADAL to MSAL migration guide for Python: https://docs.microsoft.com/en-us/azure/active-directory/develop/migrate-python-adal-msal

### CODE REVIEW

**Comment by yonzhan** [comment]
MSAL migration

**Comment by jiasli** [comment]
GitHub Action team will help test MSAL-based Azure CLI as tracked in https://github.com/Azure/github/issues/104.

**Comment by jiasli** [comment]
If you are curious, the token cache and service principal entries are saved under `~/.azure` folder:

| | encrypted | plaintext |
| - | - | - |
| MSAL token cache | `msal_token_cache.bin` | `msal_token_cache.json` |
| Service principal entries | `service_principal_entries.bin` | `service_principal_entries.json` |


### ⚠ They are private to Azure CLI. Please don’t decrypt or read from them in any way.

We don’t use Azure Identity’s shared token cache `~\AppData\Local\.IdentityService\msal.cache` anymore because we have dropped Azure Identity.

**Comment by jiasli** [comment]
## Why Azure Identity is dropped in the migration

Azure Identity has several limitations:

### No logout

Azure Identity doesn't have a logout functionality which is required by `az logout`. Azure CLI has to directly talk to MSAL to call `ClientApplication.remove_account`.

### No `data` parameter

Azure Identity can't pass `data` parameter to `get_token` method. This parameter is used to get VM SSH certificate.

- Azure Identity moved the functionality of passing `data` argument to `get_token` for user account: https://github.com/Azure/azure-sdk-for-python/pull/16323#discussion_r566565254
- Azure Identity rejected the proposed change of passing `data` argument to `get_token` for service principal: https://github.com/Azure/azure-sdk-for-python/pull/16397

Because of this limitation, Azure CLI has to directly talk to MSAL to get VM SSH certificate. As getting a certificate is a superset of setting an access token, once getting certificate with MSAL is implemented, there is no need to use Azure Identity to get access token. Doing so will make Azure CLI dual-stack and hard to maintain.

### Not able to turn off token encryption

There are scenarios where encryption is available but not working as expected. Azure Identity uses the `allow_unencrypted_storage` approach which makes it impossible to force unencrypted token cache. Application using Azure Identity will be blocked in such case with no workaround.

Azure CLI adds an option `core.token_encryption` to disable token encryption so that Azure CLI can run without encryption (https://github.com/Azure/azure-cli/issues/19506).

**Pull request merged**
