### PR TITLE
[AMS] Change az ams transform create and az ams content-key-policy create to reflect Dec 2019 swagger changes

### PR DESCRIPTION
**Pull request by hivyas**
**Description**  

Updating ams module to reflect [Dec 2019 swagger](https://github.com/Azure/azure-rest-api-specs/commit/8911f4e6dd0582c4c9246adff0d25d2205835ab1#diff-a33af42cc1a6b85ed96cc19b1ee6adb8). 
This includes updating azure-mgmt-media to 2.1.0, adding functionality to create a FairPlay content key policy with an offline rental configuration, and creating a transform with a FaceDetector preset. 
**Testing Guide**  

To create a transform with a FaceDetector preset use the following command: 
az ams transform create --account-name [accountName] --resource-group [resourceGroup] --preset FaceDetector --resolution ['SourceResolution' , 'StandardResolution']

To create a Fairplay content key policy with an offline rental configuration use the following command: 
az ams content-key-policy create --account-name [accountName] --resource-group [resourceGroup] --name [ContentKeyName] --policy-option-name [PolicyOptionName] --ask [ask] --fair-play-pfx [pfxFile] --fair-play-pfx-password [password] --rental-and-lease-key-type DualExpiry --fp-playback-duration-seconds [seconds] ----fp-storage-duration-seconds [seconds
**History Notes**  

[AMS] Change: az ams transform create: Added ability to create a transform with a FaceDetector preset 
[AMS] CHange: az ams content-key-policy create : Added ability to create a FairPlay content key policy with an offline rental configuration 
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S169

**Comment by yungezz** [comment]
hi @arrownj could you pls help to review since BIn is oof? thanks

**Comment by bquantump** [comment]
requirements.py3.* need updated to match the updates for azure-mgmt-media and azure-mgmt-monitor in the setup.py

**Comment by bim-msft** [comment]
@hivyas Is this ready to merge or you have addtional commits to push?

**Comment by hivyas** [comment]
@bim-msft This is ready to merge. Thanks

**Pull request merged**
