### PR TITLE
added clarity to get-credentials

### PR DESCRIPTION
**Pull request by JasonRShaver**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/6106
This is an **experimental preview** for @microsoft users.

**Comment by tjprescott** [comment]
Needs rebase on the latest dev... @derekbekoe maybe we still need #5955 after all (though this is a different scenario)

**Comment by tjprescott** [comment]
@derekbekoe can you take a look at the CI failure... We may have exchanged one problem for another?

**Comment by derekbekoe** [comment]
The PR was against master branch when it should have been dev.

**Comment by derekbekoe** [comment]
Now it looks a lot cleaner!

**Comment by troydai** [comment]
I will make changes to this branch to get the CI passes. /cc @JasonRShaver

**Pull request merged**
