### PR TITLE
{Compute} Adopt track2 SDK, azure-mgmt-servicebus==6.0.0

### PR DESCRIPTION
**Pull request by BigCat20196**
**Description**

Here are main changes for Servicebus migration to track2:

- LRO operations are renamed to `begin_xxx_xxx`, for example in track1, the name is delete; while in track2, the name is `begin_delete.
- For generic update of LRO, set setter_name to `begin_create_or_update`.
- In track2, SDK parameters are not flattened, so we need pass object parameter instead of flattened parameters to SDK.
- In track2, use `HttpResponseError` instead of `CloudError`.
- In track2, add the `--config-name` parameter for the migration operation . Its default value is $default. 
- Fix some tests due to changes in track2.
- Run live tests and re-record tests.

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yungezz** [comment]
@BigCat20196 great progress, thank you!

**Comment by qwordy** [comment]
I run live test for this PR.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=863247&view=results

**Comment by qwordy** [comment]
@v-Ajnava Could you have a look at this PR? It upgrades Python SDK version.

**Comment by qwordy** [comment]
The results look good. https://clitestresultstac.blob.core.windows.net/20210427-042651-649458/servicebus.report.parallel.html

**Comment by yungezz** [comment]
hi @qwordy, what's status of this PR? seems CI passed

**Comment by qwordy** [comment]
> 
> 
> hi @qwordy, what's status of this PR? seems CI passed

Code owner review required. No response yet. We can merge it.

**Review by qwordy — APPROVED** [review]

**Review by yungezz — APPROVED** [review]

**Pull request merged**
