### PR TITLE
[AKS] Remove legacy aci connector actions

### PR DESCRIPTION
**Pull request by gossion**
**Description**  

AKS has managed ACI (via `virtual-node` addon) available for a while, the legacy ACI connection actions (`install-connector` & `remove-connector` & `upgrade-connector`) should be retired.

**Testing Guide**  

**History Notes**  

[AKS] BREAKING CHANGE: az aks install-connector/upgrade-connector/remove-connector is removed as they are not functional anymore.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
aks

**Review by arrownj — COMMENTED** [review]
Is there any test case which relate to this before ?

**Comment by gossion** [comment]
> Is there any test case which relate to this before ?

@arrownj , No, I don't see any test for these actions.

**Comment by gossion** [comment]
@feiskyer @jluk can you have a look at the PR? I am going to retire the ACI connector related actions.

**Comment by yungezz** [comment]
is there any command in aks-preview extension, if yes, will they be deleted together? Is there existing user using the command?

**Comment by jluk** [comment]
@gossion thanks for driving this removal, LGTM but we'll need to do the same cleanup the cli-extension as well.

cc @robbiezhang for review

**Comment by robbiezhang** [comment]
cli extension doesn't override these 3 commands.
@yungezz , these commands are mostly client only commands to install a helm chart to an AKS cluster. So, there is no AKS service call to track the usage. Is there a telemetry collected by the CLI?

**Review by robbiezhang — APPROVED** [review]

**Review by arrownj — APPROVED** [review]

**Pull request merged**
