### PR TITLE
[AKS] Remove max pods validation from CLI and let preflight handle it

### PR DESCRIPTION
**Pull request by marwanad**
**Description**  

This is the same change brought by: https://github.com/Azure/azure-cli-extensions/pull/2068

This validation is outdated and is done on the backend so there's no point keep this check in CLI.

Closes https://github.com/Azure/azure-cli/issues/12723

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by marwanad** [comment]
@arrownj hmm I fixed the style check but not sure why the automation ones are failing. I looked at the logs but no clue what's failing there. Any pointers?

**Comment by arrownj** [comment]
> @arrownj Xiaojian Xu FTE hmm I fixed the style check but not sure why the automation ones are failing. I looked at the logs but no clue what's failing there. Any pointers?

Did the test pass in you local environment ? Try to run `azdev test acs` and make sure all these tests are passed before pushing the code.

**Comment by marwanad** [comment]
@arrownj yup, I forgot to check-in a change. The test case for `max-pods` is no longer relevant since no CLI error is generated now and its server-side checks.

**Comment by marwanad** [comment]
Can we add this to the S174 milestone?

**Comment by yungezz** [comment]
hi @marwanad although backend did the validation, it will be very helpful to your azure cli users to at least add validation rule in help message.

**Pull request merged**
