### PR TITLE
[Bot Service] `az bot create`: Add location as specified by user to bot creation for regionality/EUDB

### PR DESCRIPTION
**Pull request by jocrafts**
**Description**

Previously the location parameter as specified by the user in the az bot create command was not actually used. This was okay previously because all bot resources are global. However due to EU data boundary work, we now support creation of Europe and United States regional bots and guarantee data residency for such bots. Because this is not a breaking change, and the lack of propagation of this property is technically a bug, we would prefer to take this change as a hotfix.

**Testing Guide**

Test cases:
To validate existing functionality
- run az bot create without a location
- run az bot create with "global" as the specified location
- (can only be included when the ARM manifest is able to be updated in January for the service) run az bot create with "westeurope" or "westus2" as the location parameter

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by jocrafts** [comment]
The label "customer-reported" was added, but fyi in case this is unclear I work in the bot service team and this is a needed change for EU regionality in Q1

**Comment by yonzhan** [comment]
Bot Service

**Review by stevengum — APPROVED** [review]
@munozemilio FYI

Yikes! This looks good to me.

**Comment by stevengum** [comment]
@jiasli friendly ping

**Comment by stevengum** [comment]
FYI @jiasli, @munozemilio is the new maintainer for the Bot Service Command Module (`az bot`).

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@stevengum Hi, as the Chinese Spring Festival is coming, it is a holiday season for Chinese team, so we expect to release this PR in **02-08**. Do you think this time is acceptable? 
If so, please submit this PR into the remote dev branch
If not, please give the justification that this PR is urgent

**Comment by jocrafts** [comment]
hi @zhoxing-ms that timeframe is fine, I have switched over to target dev

**Pull request merged**
