### PR TITLE
Allow other cloud/environments to make data plane operations in azure-cli-cosmosdb

### PR DESCRIPTION
**Pull request by dmakwana**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/5891
This is an **experimental preview** for @microsoft users.

**Comment by dmakwana** [comment]
@moderakh Can you have a look?

**Comment by moderakh** [comment]
I requested the changes offline from Digvijay. It looks good to me now. Thanks @dmakwana

**Comment by dmakwana** [comment]
@derekbekoe Should be fine

**Pull request merged**
