### PR TITLE
[Network] Fix #21716: `az network private-dns zone import`: Allow hyphenated SRV records

### LINKED ISSUE #21716: DNS zone import fails for hyphenated SRV record targets
**Describe the bug**
When attempting to import a DNS zone file, (e.g. via `az network private-dns zone import`) it will fail if you have any SRV records where the targets contain hyphens.

**To Reproduce**
Take the valid zone file `db.example.com`:
```
@                 3600 IN SOA  ns admin ( 2014010800 ; Serial
                                          3600       ; Refresh
                                          3600       ; Retry
                                          3600       ; Expire
                                          300 )      ; Minimum TTL

_sip._tcp.pool 300 IN SRV 20 10 5060 valid-target-1
_sip._tcp.pool 300 IN SRV 20 10 5060 valid-target-2
_sip._tcp.pool 300 IN SRV 20 10 5060 valid-target-3
```
and import it using:  `az network private-dns zone import --resource-group <RG NAME> --name example.com --file-name db.example.com`

The following output is produced:
```
	== BEGINNING ZONE IMPORT: example.com ==
	
	(1/4) Imported 1 records of type 'soa' and name '@'
	(BadRequest) The list of record sets of type 'SRV' may not contain multiple entries with the same '(priority, weight, target)'.
	Code: BadRequest
	Message: The list of record sets of type 'SRV' may not contain multiple entries with the same '(priority, weight, target)'.
	
	== 1/4 RECORDS IMPORTED SUCCESSFULLY: 'example.com' ==
```

**Expected behavior**
The DNS SRV record `_sip_tcp.pool.example.com` should be created, with three targets (`valid-target-1.example.com`, `valid-target-2.example.com`, `valid-target-3.example.com`)

**Environment summary**
Linux-5.10.60.1-microsoft-standard-WSL2-x86_64-with-glibc2.29, Ubuntu 20.04.2 LTS
Python 3.8.12
Installer: DEB

**Additional context**
This is down to an incorrect regular expression in the zone file parser.  I've got a fix for this bug, and will submit a PR.

### PR DESCRIPTION
**Pull request by huws**
**Description**
This is necessary to allow hyphenated SRV records targets to be successfully imported.  Today, such imports fail, as described in #21716 

**Testing Guide**
Without the fix, importing this valid zone file (`db.example.com`) will fail:
```
@                 3600 IN SOA  ns admin ( 2014010800 ; Serial
                                          3600       ; Refresh
                                          3600       ; Retry
                                          3600       ; Expire
                                          300 )      ; Minimum TTL

_sip._tcp.pool 300 IN SRV 20 10 5060 valid-target-1
_sip._tcp.pool 300 IN SRV 20 10 5060 valid-target-2
_sip._tcp.pool 300 IN SRV 20 10 5060 valid-target-3
```

Failure output from import using `az network private-dns zone import --resource-group <RG NAME> --name example.com --file-name db.example.com`:
```
== BEGINNING ZONE IMPORT: example.com ==
	
	(1/4) Imported 1 records of type 'soa' and name '@'
	(BadRequest) The list of record sets of type 'SRV' may not contain multiple entries with the same '(priority, weight, target)'.
	Code: BadRequest
	Message: The list of record sets of type 'SRV' may not contain multiple entries with the same '(priority, weight, target)'.
	
	== 1/4 RECORDS IMPORTED SUCCESSFULLY: 'example.com' ==
```

With the fix, this import succeeds with the output:

```
	== BEGINNING ZONE IMPORT: example.com ==
	
	(1/4) Imported 1 records of type 'soa' and name '@'
	(4/4) Imported 3 records of type 'srv' and name '_sip._tcp.pool'
	
	== 4/4 RECORDS IMPORTED SUCCESSFULLY: 'example.com' ==
```

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Network

**Comment by necusjz** [comment]
@huws Overall LGTM, but please refine the PR title and rebase with the latest changes from dev branch.

**Review by necusjz — APPROVED** [review]

**Comment by necusjz** [comment]
@huws, I was aware that this PR introduced too many others' commits, i.e., too many unrelated file changes. So, please make it clean and only introduce related changes. Thanks.

**Review by necusjz — CHANGES_REQUESTED** [review]
@huws, I was aware that this PR introduced too many others' commits, i.e., too many unrelated file changes. So, please make it clean and only introduce related changes. Thanks.

**Comment by huws** [comment]
Apologies - not sure what happened, there.  The PR is now clean - just my one commit.

**Comment by necusjz** [comment]
@huws never mind, our CI was also down at that moment.

**Review by necusjz — APPROVED** [review]

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
