### PR TITLE
[AKS]Add PPG support

### PR DESCRIPTION
**Pull request by tilnl**
**Description**  

Add PPG support as part of GA work item

**Testing Guide**  

az aks create --name test-cluster --resource-group test-rg --load-balancer-sku standard --ppg "/subscriptions/{subid}/resourceGroups/test-rg/providers/Microsoft.Compute/proximityPlacementGroups/test-ppg" --location centralus
**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Review by xizhamsft — APPROVED** [review]

**Review by arrownj — APPROVED** [review]
LGTM

**Comment by arrownj** [comment]
Hi @tilnl , could you please fix the Automation Test failure ?

**Comment by tilnl** [comment]
Sure. I will do it.

**Comment by tilnl** [comment]
@arrownj , test is fixed. Thanks!

**Pull request merged**
