### PR TITLE
{Redis} Updating Redis api version in Private endpoint configuration

### PR DESCRIPTION
**Pull request by gorandom**
**Description**
Updating the Redis api version to the latest in private endpoint configuration

**Testing Guide**
Test private endpoint commands over redis resources
example: az network private-endpoint-connection list --id /subscriptions/{subscriptionID}/resourceGroups/{ResourceGroupName}/providers/Microsoft.Cache/Redis/{AzureCacheName}

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Redis

**Comment by gorandom** [comment]
@evelyn-ys I see some failures in PR check which is not related to my change.

**Comment by evelyn-ys** [comment]
@gorandom Can you sync with latest `dev` branch?

**Review by calvinhzy — APPROVED** [review]

**Comment by gorandom** [comment]
@evelyn-ys @kairu-ms Can you check and merge this PR?

**Review by wangzelin007 — APPROVED** [review]

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
