### PR TITLE
[App Service] BREAKING CHANGE: `az functionapp create`: Remove support for EOL Node 8 and 10

### PR DESCRIPTION
**Pull request by gzuber**
**Description**

Node 8 and 10 are EOL and should be removed from list of possible node runtime versions.

**Testing Guide**

Tests that relied on Node 8 or 10 have been updated

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
functionapp

**Comment by gzuber** [comment]
This should be good for review/merge -- was hoping to get this in for [S189](https://github.com/Azure/azure-cli/milestone/107), thanks!

**Comment by yonzhan** [comment]
@panchagnula could you sign off this PR first?

**Comment by Juliehzl** [comment]
@gzuber please get approval from @panchagnula  first.
Then please also update the PR title with active voice and influenced command name, e.g.
`[App Service] BREAKING CHANGE: [command] : Remove ...`

**Review by panchagnula — APPROVED** [review]
LGTM

**Comment by gzuber** [comment]
> @gzuber please get approval from @panchagnula first.
> Then please also update the PR title with active voice and influenced command name, e.g.
> `[App Service] BREAKING CHANGE: [command] : Remove ...`

Hi @Juliehzl I think I changed the title correctly but let me know if I need to correct anything, thanks!

**Pull request merged**
