### PR TITLE
[Batch] `az batch account`: Add warnings about secrets being outputted

### PR DESCRIPTION
**Pull request by wiboris**
**Related command**
`az batch keys renew`
`az batch keys list`
`az batch account identity show`
 
**Description**
Add help text to highlight these commands output secrets

**Testing Guide**
Verified help output

**History Notes**

[Batch] `az batch keys renew`: Update help with security warning
[Batch] `az batch keys list`: Update help with security warning
[Batch] `az batch account identity show`: Update help with security warning

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by yonzhan — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Comment by jiasli** [comment]
I will integrate this change into https://github.com/Azure/azure-cli/pull/27690 in the next sprint.

**Comment by jiasli** [comment]
I think these commands should also show a warning during execution:

```py
    from azure.cli.core.commands.constants import OUTPUT_WITH_SECRET
    logger.warning(OUTPUT_WITH_SECRET)
```

#27690 shows an example.

**Comment by jiasli** [comment]
This PR should be reverted once generic credential detection is enabled.

**Pull request merged**
