### PR TITLE
{Compute} Fix tests, test_vmss_disk_encryption_e2e, test_image_build_managed_image, test_image_build_shared_image

### PR DESCRIPTION
**Pull request by qwordy**
**Description**  

{Compute} Fix tests, test_vmss_disk_encryption_e2e, test_image_build_managed_image, test_image_build_shared_image

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Compute

**Review by arrownj — APPROVED** [review]
👍

**Comment by qwordy** [comment]
Loading AKS extension fails.

**Pull request merged**
