### PR TITLE
{AKS} revert to use old region mapping

### PR DESCRIPTION
**Pull request by bragi92**
Currently talking across multiple teams to align with one consistent naming experience.

**Description**

Reverting the changes made in this PR: https://github.com/Azure/azure-cli/pull/16377/ since we're currently talking with the LA, AppInsights and Alerts team and bringing consistency to the naming experience for the new regions.

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by bragi92** [comment]
@fengzhou-msft Reverting the changes made in this PR: https://github.com/Azure/azure-cli/pull/16377/ since the shortcode mapping list I was following was not consistent. I'll create another PR to update this with the new regions once we have a consistent naming convention.

**Comment by yonzhan** [comment]
acs

**Review by yungezz — APPROVED** [review]

**Comment by yungezz** [comment]
> @fengzhou-msft Reverting the changes made in this PR: #16377 since the shortcode mapping list I was following was not consistent. I'll create another PR to update this with the new regions once we have a consistent naming convention.

hi @bragi92 could you pls have someone else to review this since this pure business logic? thanks

**Comment by bragi92** [comment]
@fengzhou-msft Can you have a look at this PR? Its reverting the change I made in https://github.com/Azure/azure-cli/pull/16377 since we're still talking with the other teams (I should have the new PR ready by end of this week)

Also do you know how I can run the build pipeline again ~ the PR title wasn't properly formatted but I've fixed it now.

**Review by fengzhou-msft — APPROVED** [review]

**Pull request merged**
