### PR TITLE
Substituted get_yaml_and_values with get_yaml_template

### LINKED ISSUE #9398: [ACR] 'az acr run --cmd' doesn't render the built-in values properly
**Describe the bug**
`az acr run -r myregistry --cmd "bash echo {{.Run.Registry}}" /dev/null`

**Expected behavior**
The output shows `myregistry.azurecr.io` 

**Actual behavior**
The output shows `{{.Run.Registry}}`

### PR DESCRIPTION
**Pull request by ggonzalere**
Fixes #9398

### CODE REVIEW

**Comment by northtyphoon** [comment]
LGTM

**Comment by ehotinger** [comment]
CI seems flaky and needs to be requeued


```
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/wheel/ |  
-- | --
  | WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/wheel/ |  
  | WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/wheel/ |  
  | WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/wheel/ |  
  | WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/wheel/ |  
  | ERROR: Could not find a version that satisfies the requirement wheel (from versions: none) |  
  | ERROR: No matching distribution found for wheel


```

**Comment by tjprescott** [comment]
Re-running the failed CI stage.

**Comment by ehotinger** [comment]
@tjprescott can we merge this, CI is passing

**Comment by tjprescott** [comment]
Re-running since there have been changes to CI since this passed. Added current milestone so it will be merged as part of this release  when it passes.

**Pull request merged**
