### PR TITLE
{Compute} Update help message Change the term "Low Priority" to "Spot"

### PR DESCRIPTION
**Pull request by mimckitt**
**Description**  

We have changed the term "Low Priority" to "Spot". We have already updated the PowerShell commands and now we need to rename the two items in CLI from "Low Priority" to "Spot"

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Compute

**Comment by qwordy** [comment]
Thank you for the contribution!

**Comment by yungezz** [comment]
hi @qwordy could you pls help on the CI failure then we can merge this PR? thanks

**Comment by qwordy** [comment]
This test fails, test_role_assignment_handle_conflicted_assignments.
Could you run "git pull upstream dev" and then push?

**Comment by mimckitt** [comment]
Anything I need to do in order to get this merged?

**Comment by qwordy** [comment]
> 
> 
> Anything I need to do in order to get this merged?

After the CI checks pass. It's a simple change. Merge from dev branch and push your commit.

**Pull request merged**
