### PR TITLE
[Network] `az network private-dns link vnet`: Support resolution policy for virtual network link

### PR DESCRIPTION
**Pull request by pranavpnair**
**Related command**

network private-dns link vnet create
network private-dns link vnet delete
network private-dns link vnet list
network private-dns link vnet show
network private-dns link vnet update
network private-dns link vnet wait

**Description**

In this change, we add a new property to (private dns) vnet link resources: resolutionPolicy. This will be an optional parameter in CLI. It is an enum that consists of two possible values - "Default" or "NxDomainRedirect". 
For example, to create a new vnet link with resolutionPolicy property set to "NxDomainRedirect", one can run the following command:
`az network private-dns link vnet create -g myResourceGroup -n myLink -z privatelink.consoto.com -v {vnet-resourceId} -e True/False --resolution-policy NxDomainRedirect`

This property has already been added to swagger and other language SDKs and publicly released.

Swagger change: https://github.com/Azure/azure-rest-api-specs/pull/29470

New property can be found [here](https://github.com/Azure/azure-rest-api-specs/blob/cf9f241708ed82f2dad218fed3c09ca5fd191311/specification/privatedns/resource-manager/Microsoft.Network/stable/2024-06-01/privatedns.json#L1480)

.NET sdk reference documentation can be found [here](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.privatedns.virtualnetworklinkdata.privatednsresolutionpolicy?view=azure-dotnet)

Pull request on Aaz repo: https://github.com/Azure/aaz/pull/591

**Testing Guide**

Added new tests and generated yaml files. 

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by pranavpnair** [comment]
Pushed a commit to re-record broken tests in mysql and postgres that were using privatedns resources. Can you please help with restarting the Azure pipeline executions? Seems I do not have sufficient privileges when I tried to use /azp run

**Review by necusjz — APPROVED** [review]

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
