### PR TITLE
[SQL] BREAKING CHANGE: Fix response for backup storage redundancy param name and value for MI

### PR DESCRIPTION
**Pull request by petrajkogit**
**Description**  
Fix response for backup storage redundancy param name and value for MI.

Since there is a difference in parameter name that is used by API (storageAccountType), and parameter name we are using to specify backup storage redundancy (backupStorageRedundancy), and the values we externally show (Geo, Local Zone) with this PR we are using transformation of output object, in order to show the expected parameter name and values for it, for better customer experience.

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
SQL

**Comment by petrajkogit** [comment]
@Juliehzl Hi Zunli, can you take a look at this PR? It is small change, and is open for some time. Thanks!

**Comment by Juliehzl** [comment]
Hi @petrajkogit , your changes are minor but I have concern for changing output because there are too many usages for `sql mi` command and your change will cause breaking change for automation task.

**Comment by petrajkogit** [comment]
> Hi @petrajkogit , your changes are minor but I have concern for changing output because there are too many usages for `sql mi` command and your change will cause breaking change for automation task.
> 
> There are at lease 403 unique subscriptions for `sql mi` in the past 30 days.

@Juliehzl Yes, however, this parameter is relatively new in response (from last release at end of September: https://github.com/Azure/azure-cli/releases/tag/azure-cli-2.12.0), so impact will not be that big. What is the alternative here, we would like to just show the correct name for output parameter (since the name from api response can be misleading)

**Comment by Juliehzl** [comment]
Hi @petrajkogit , thanks for your information. Checked the telemetry again, there are 6 subscriptions usage in the past 90 days.
If you are fine with such change for your module, I am fine with it but you need to make it as breaking change in title.

**Comment by petrajkogit** [comment]
> Hi @petrajkogit , thanks for your information. Checked the telemetry again, there are 6 subscriptions usage in the past 90 days.
> If you are fine with such change for your module, I am fine with it but you need to make it as breaking change in title.

Yes we are fine. SQL DB already went with this change and we need to match the experience between SQL DB and SQL MI. I added the Breaking change tag to the PR title.

**Review by Juliehzl — APPROVED** [review]
Approved for service team request

**Pull request merged**
