### PR TITLE
{Packaging} upgrade wheel to 0.34.2

### PR DESCRIPTION
**Pull request by kapilt**
addresses #12582 

**History Notes:**  

[azure-cli-core]: upgrade wheel package

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S167

**Comment by yungezz** [comment]
this is related to issue  #12582

**Comment by haroldrandom** [comment]
Hi, @kapilt, appreciated the contribution!

Could you give us some context about the upgrade of wheel?
We found the wheel version is not consistent inside several Azure CLI repos, also want to make it consistency.

**Comment by kapilt** [comment]
its causing spurious upgrades/downgrades for projects with azure-cli-core as a dependency.

the underlying wheel api here is public and stable so its unclear why its pinned at all.

probably the bigger issue, its also unclear why its being listed as an install dep since its not used by the library just the wheel packaging.

**Comment by haroldrandom** [comment]
We should all the wheel version for all packages inside Azure/azure-cli.
Also, we shall align the wheel version of Azure/azure-cli-extensions and Azure/azure-cli-dev-tools with this.
At least the should be the same.

**Comment by fengzhou-msft** [comment]
Original PR to pin wheel to 0.30.0: https://github.com/Azure/azure-cli/pull/8896. As long as the issue no longer exists, we should upgrade wheel probably with 'wheel~=0.34.2' or even unpin it.

**Comment by haroldrandom** [comment]
Add context https://github.com/Azure/azure-cli-extensions/issues/128

**Comment by haroldrandom** [comment]
Sorry, upgrade of wheel needs to involve our infrasturre of how to identify Python package. It needs a bit effort to refactor.
But we will plan to relex the restriction ASAP. Sorry for the inconvenience.

**Comment by haroldrandom** [comment]
Relaxed the limit in #12782.

**Comment by haroldrandom** [comment]
plan changed, since relax this need more tests, unpining wheel would be available in the next releases. Won't be late before Azure CLI 3.0

**Pull request closed without merging**
