### PR TITLE
{RDBMS} Update Python SDK for PostgreSQL flexible servers to version API to 2024-11-01-preview

### PR DESCRIPTION
**Pull request by nasc17**
**Related command**

**Description**
Update CLI to use latest Python SDK version using new package import from https://pypi.org/project/azure-mgmt-postgresqlflexibleservers/1.1.0b1/

**Testing Guide**
Integration test run

**History Notes**

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by evelyn-ys — APPROVED** [review]

**Review by evelyn-ys — APPROVED** [review]

**Comment by kairu-ms** [comment]
please fix the linter issues:
image

**Pull request merged**
