### PR TITLE
{CI} Remove brjohnstmsft from the auto-responder policy

### PR DESCRIPTION
**Pull request by brjohnstmsft**
**Related command**

n/a

**Description**

Removing myself since I am no longer on the Azure Cognitive Search team.

**Testing Guide**

n/a

**History Notes**

n/a

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by brjohnstmsft** [comment]
@wangzelin007 Please review. It's a very small PR.

**Comment by brjohnstmsft** [comment]
@wangzelin007 Can you please review and merge this?

**Review by wangzelin007 — APPROVED** [review]

**Comment by wangzelin007** [comment]
> @wangzelin007 Can you please review and merge this?



> @wangzelin007 Can you please review and merge this?

Hi @brjohnstmsft 
Are you no longer responsible for these issues with the Search label?

**Comment by brjohnstmsft** [comment]
> > @wangzelin007 Can you please review and merge this?
> 
> Hi @brjohnstmsft Are you no longer responsible for these issues with the Search label?

That is correct.

**Pull request merged**
