### PR TITLE
[AppService] Fix webapp/slot creation for Windows Containers

### PR DESCRIPTION
**Pull request by vinisoto**
**Description**  
Creating Windows Container webapps and slots using non-public container images (e.g. images in ACR or in a Docker Hub private repository) is currently broken because an image validation is performed at creation time (e.g. ensure the image exist, ensure it is a supported OS version, ensure the right credentials provided, etc.) which requires container registry credentials and, before this PR, the creation from az webapp create (and az deployment slot create) was performed in two steps:

1. Create the webapp/slot with no container registry credentials
2. Update the container registry credentials

With this change, we ensure that container registry credentials are passed at creation time (step 1 above)

**Testing Guide**  
Existing commands suffer no change as part of this PR:

`az webapp create --name myWebsite --plan myAppServicePlan --resource-group myResourceGroup --deployment-container-image-name https://mycontainerregistry.azurecr.io/mycontainerimage:latest --docker-registry-server-user <<some user name>> --docker-registry-server-password <<some password>>`

`az webapp deployment slot create --name myWebsite --resource-group myResourceGroup --slot my-new-slot --configuration-source myWebsite`

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by vinisoto** [comment]
FYI @jvano, @panchagnula

**Comment by jvano** [comment]
Looks good to me, :shipit:

**Comment by panchagnula** [comment]
Looks like this test is failing access-restrictions-slot test is failing please re-record it by running adzev test <testname> --live and  include  the yaml(recording) that should get the build working

**Comment by panchagnula** [comment]
@vinisoto is this something we need to fix on Powershell as well? Thanks for taking care of this.

**Comment by vinisoto** [comment]
Thanks @panchagnula. Will re-record the tests. Re: powershell, I'm not sure if it is broken but it is next on my list.

**Comment by yonzhan** [comment]
AppService

**Comment by vinisoto** [comment]
All checks have passed after updating test recordings.

Thanks

**Comment by vinisoto** [comment]
kindly requesting to merge this PR

**Comment by vinisoto** [comment]
@panchagnula `az webapp config container set` was also broken.

**Pull request merged**
