### PR TITLE
[RDBMS] `az postgres flexible-server replica create`: Add support for `--tags` parameter

### PR DESCRIPTION
**Pull request by mattboentoro**
**Related command**
az postgres flexible-server replica create

**Description**
Add support for --tags parameter

**Testing Guide**
Manual testing

**History Notes**

[RDBMS] `az postgres flexible-server replica create`: Add support for `--tags` parameter

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
RDBMS

**Review by nasc17 — APPROVED** [review]

**Comment by nasc17** [comment]
@evelyn-ys PR is good, please review

**Comment by evelyn-ys** [comment]
will review after current 10-08 release

**Comment by mattboentoro** [comment]
@yonzhan @evelyn-ys do you mind reviewing this PR?

**Review by evelyn-ys — APPROVED** [review]

**Comment by evelyn-ys** [comment]
@mattboentoro Pls resolve conflicts

**Comment by mattboentoro** [comment]
@evelyn-ys conflict resolved

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
