### PR TITLE
[Network] az network nat gateway: support create empty resource without public ip or public ip prefix

### PR DESCRIPTION
**Pull request by khannarheams**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by MyronFanQiu** [comment]
@khannarheams Hello. Could you share me some context about this PR? Why do we delete the verification logic?

**Comment by khannarheams** [comment]
Hi Fan,

We want the ability to enable empty resource creation. This is the standard for all azure resources.

Best Regards
Rhea

**Comment by MyronFanQiu** [comment]
@khannarheams so you mean currently, can server support empty resource creation? Could you add a single command test into this PR and update History.rst?

**Comment by haroldrandom** [comment]
Also, there is a small PEP9 error, please remove unused import statement. 

Which in src/azure-cli/azure/cli/command_modules/natgateway/custom.py:9:0: W0611: Unused CLIError imported from knack.util (unused-import)

**Comment by yonzhan** [comment]
@khannarheams please take a look at the comments and refine the code accordingly before the PR is merged.

**Comment by khannarheams** [comment]
@yonzhan changes are updated. could you help approve?

**Comment by MyronFanQiu** [comment]
@khannarheams Hello. Could you add a test for your change, such as creating an empty nat-gateway.

**Comment by yonzhan** [comment]
@MyronFanQiu  please help with this PR.

**Comment by MyronFanQiu** [comment]
@khannarheams Hello. Could you add a single test for this PR?

**Comment by yonzhan** [comment]
add to S165.

**Comment by yonzhan** [comment]
@khannarheams any update for this PR?

**Pull request merged**
