### PR TITLE
[App Service] `az webapp config appsettings` settings are registered as Deployment slot setting anytime when using `--slot-settings`

### PR DESCRIPTION
**Pull request by mag-chang**
**Related command**
az webapp config appsettings set

**Description**
Settings are registered as Deployment slot setting anytime when using "--slot-settings" though there are designated "slotSetting=false" in a Json file.
The official document mentions the option of "--slot-settings" will mark as Deployment slot setting ***by default***, however current behavior is the user cannot choose Deployment slot setting or not if using "--slot-settings".
https://learn.microsoft.com/en-us/cli/azure/webapp/config/appsettings?view=azure-cli-latest#az-webapp-config-appsettings-set-optional-parameters

Also, I think the expected behavior before until this [PR](https://github.com/Azure/azure-cli/pull/17895/files#diff-76cc90184fe3a5df817ac304d5929231658bef52748a4560dabf51ee18bf8f02L261-R265) was merged is the user can choose whether Deployment slot setting or not by Json file even if using the option of "--slot-settings".

**Testing Guide**
1. create a json file.
For example:
```json
[
  {
    "name": "TEST_SETTING1",
    "value": "test_value1",
    "slotSetting": false
  },
  {
    "name": "TEST_SETTING2",
    "value": "test_value2",
    "slotSetting": true
  }
]
```
2. az webapp config appsettings set -g <resource_group> -n <resource_name> --slot-settings @<created_file>
3. If needed, you can test with a slot name.
az webapp config appsettings set -g <resource_group> -n <resource_name> -s <slot_name> --slot-settings @<created_file>

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
App Service

**Comment by zhoxing-ms** [comment]
> AssertionError: Can't overwrite existing cassette ('/mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/appservice/tests/latest/recordings/test_update_webapp_settings_thru_json.yaml') in your current record mode ('once').
E           No match for the request (<Request (PUT) [https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_webapp_json000001/providers/Microsoft.Web/serverfarms/webapp-config-plan000003?api-version=2022-03-01>](https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_webapp_json000001/providers/Microsoft.Web/serverfarms/webapp-config-plan000003?api-version=2022-03-01%3E)) was found.
E           Found 13 similar requests with 1 different matcher(s) :
E           
E           1 - (<Request (PUT) [https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_webapp_json000001/providers/Microsoft.Web/serverfarms/webapp-config-plan000003?api-version=2020-12-01>).](https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_webapp_json000001/providers/Microsoft.Web/serverfarms/webapp-config-plan000003?api-version=2020-12-01%3E).)
E           Matchers succeeded : ['method', 'scheme', 'host', 'port', 'path']
E           Matchers failed :
E           _custom_request_query_matcher - assertion failure :
E           None

Please update the code from the remote dev branch and then re-record the yaml file for `test_update_webapp_settings_thru_json`

**Comment by zhoxing-ms** [comment]
@mag-chang Please address these CI issues

**Comment by zhoxing-ms** [comment]
Please note that since we will launch the release of this sprint the day after tomorrow. If you cannot address all the comments tomorrow, we will have to postpone the release of this PR to the next sprint (02-07)

**Comment by mag-chang** [comment]
@zhoxing-ms Thank you for your suggestion. I changed the base branch into dev and re-create testing yaml for my test. However, I cannot resolve the error at CI though these tests are success on my local machine.
I suspect my environment and CI are different anything. I am going to try again for resolution.

**Comment by zhoxing-ms** [comment]
@mag-chang Any update?
Please note that since we will launch the release of this sprint the day after tomorrow. If you cannot address all the comments tomorrow, we will have to postpone the release of this PR to the next sprint **(03-07)**

**Comment by mag-chang** [comment]
@zhoxing-ms Sorry for late. I'm struggling for fixing. I will try to resolve today, but I may request to postpone this PR if I cannot fix in tomorrow.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
