### PR TITLE
[Containerapp] `az containerapp env certificate upload`: Fix usage of deleted OpenSSL.crypto.load_pkcs12()

### PR DESCRIPTION
**Pull request by Nautigsam**
**Related command**

`az containerapp env certificate upload`

**Description**

When uploading a PFX file, I got this error:
```
Failed to load the certificate file. This may be due to an incorrect or missing password. Please double check and try again.
Error: module 'OpenSSL.crypto' has no attribute 'load_pkcs12'
```
`OpenSSL.crypto.load_pkcs12` was indeed [removed in version 23.3.0](https://www.pyopenssl.org/en/stable/changelog.html#id3). I changed it with its equivalent from `cryptography` package.

**Testing Guide**

```
az containerapp env certificate upload -n my-env -c my-cert -f cert.pfx -p '' 
```

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Containerapp

**Comment by Greedygre** [comment]
Hi @Nautigsam 

Which version did you get this error?
```
Failed to load the certificate file. This may be due to an incorrect or missing password. Please double check and try again.
Error: module 'OpenSSL.crypto' has no attribute 'load_pkcs12'
```

Seems it still using version `pyOpenSSL==23.2.0`

**Comment by Nautigsam** [comment]
@Greedygre I am using version 2.57.0 from [AUR](https://aur.archlinux.org/packages/azure-cli).

By looking harder at it, it may be a packaging issue.
The package uses the [`install.py`](https://github.com/Azure/azure-cli/blob/dev/scripts/curl_install_pypi/install.py) script from the sources, but it does not enforce the Python version. On current Arch it uses Python 3.11 for example. But I still don't understand how it installs the dependencies, since it only pulls the `azure-cli` package from pip.

**Comment by Greedygre** [comment]
> @Greedygre I am using version 2.57.0 from [AUR](https://aur.archlinux.org/packages/azure-cli).
> 
> By looking harder at it, it may be a packaging issue. The package uses the [`install.py`](https://github.com/Azure/azure-cli/blob/dev/scripts/curl_install_pypi/install.py) script from the sources, but it does not enforce the Python version. On current Arch it uses Python 3.11 for example. But I still don't understand how it installs the dependencies, since it only pulls the `azure-cli` package from pip.

Can you use command: `pip show pyOpenSSL`
and show me the result? Thanks.

**Comment by Nautigsam** [comment]
I got into the install dir of the package and the version of `pyOpenSSL` is `24.0.0`. I don't understand how it got pulled, maybe I missed something in `install.py` script.

**Comment by Greedygre** [comment]
Hi @Nautigsam 

You can open an issue about this. Thanks! I cannot repro it on my side.
 And my PR about fix `load_pkcs12` will be available in next release for `azure-cli`.

**Comment by Nautigsam** [comment]
Okay I think we can close this issue then, sorry for the inconvenience.

**Comment by Nautigsam** [comment]
For anyone reading this and using Arch Linux, I tested with the other package `azure-cli-bin` from AUR and I don't reproduce the issue with this one.

**Pull request closed without merging**
