### PR TITLE
{SQL VM} Update sqlvm api version

### PR DESCRIPTION
**Pull request by ai-abhinav**
**Description**

1- Update SQL Virtual Machine API Version from 2017-03-01-preview to 2021-11-01
2- Update SQL Virtual Machine Python client sdk version from 1.0.0b1 to 1.0.0b2

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
SQL VM

**Comment by ai-abhinav** [comment]
@evelyn-ys is there something I can do to resolve the conflict against the dev branch? This is my first PR in the repository.

**Comment by evelyn-ys** [comment]
merge your develp branch with upstream/dev branch

**Comment by ai-abhinav** [comment]
Abandoning and recreating pull request merged with upstream dev

**Pull request closed without merging**
