### PR TITLE
Fix dependency mismatches with Azure SDK

### PR DESCRIPTION
**Pull request by derekbekoe**
Some of the allowed errors are no longer required.

If the CI passes, we know we can safely remove them.

Closes https://github.com/Azure/azure-cli/issues/4300
Helps us address https://github.com/Azure/azure-cli/issues/643

### CODE REVIEW

**Comment by lmazuel** [comment]
@derekbekoe To fix: 'AuthorizationManagementClientConfiguration' has no 'api_version', get it from 'AuthorizationManagementClient' instead. Newer Autorest generation removed completely 'api_version' from 'Configuration', and put it in the client instead.

**Comment by lmazuel** [comment]
For Redis, they almost rewrite the Swagger...

**Comment by yugangw-msft** [comment]
@derekbekoe,  I believe a few graph tests will need to re-recorded as the api-version is changed, so grab me if you run into any problems

**Comment by lmazuel** [comment]
@derekbekoe If this can help, this was my Redis update:
https://github.com/Azure/azure-sdk-for-python/commit/d8b6ceb7536d49174ed3e7611dcc176df60fd1b0

**Comment by troydai** [comment]
Three approves and CI failed. What a shame.

**Pull request merged**
