### PR TITLE
Add sql server & firewall-rule examples

### LINKED ISSUE #6396: [SQL] SQL firewall-rule needs examples
Please, always add sample

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ed8c3b-f42d-2421-a563-d09ec7b67ac0
* Version Independent ID: bcdaeb1b-e343-2336-d394-e32f8d867ab2
* Content: [az sql server firewall-rule](https://docs.microsoft.com/en-us/cli/azure/sql/server/firewall-rule?view=azure-cli-latest#az_sql_server_firewall_rule_create)
* Content Source: [src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py](https://github.com/Azure/azure-cli/blob/master/src/command_modules/azure-cli-sql/azure/cli/command_modules/sql/_help.py)
* Service: **sql-database**
* Product: **unspecified**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

### PR DESCRIPTION
**Pull request by jaredmoo**
Fixes #6396 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/6403
This is an **experimental preview** for @microsoft users.

**Comment by williexu** [comment]
rebase to get the update from https://github.com/Azure/azure-cli/pull/6407 please

**Comment by jaredmoo** [comment]
Done

**Comment by troydai** [comment]
Waiting @sptramer

**Pull request merged**
