### PR TITLE
Show error

### PR DESCRIPTION
**Pull request by v-jizhang**
… found

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by v-jizhang** [comment]
@BrianBlum, @sanbhatt, Fixed AMS show commands when resource not found.

**Comment by v-jizhang** [comment]
@Juliehzl

**Comment by v-jizhang** [comment]
Hi all,
My last day with AMS is Monday, September 30th. Could everybody expedite the review process?

Thanks
Jinlin

**Comment by yonzhan** [comment]
@haroldrandom please help with this PR.

**Comment by haroldrandom** [comment]
The command's tyle is not in line with [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md)， closed until fixed.

Feel free to reopen and open a fresh new one

**Comment by BrianBlum** [comment]
@haroldrandom, when you say that the command's style is not in line with the Command Guidelines, do you mean that the commands should return None when a resource is not found?

**Comment by haroldrandom** [comment]
Sorry, I made a mistake, the style is fine. I will review your code ASAP.

**Comment by haroldrandom** [comment]
@BrianBlum Sorry for the late reply. Our team is too busy to other things the other day, just focusing to switch to close PRs just now. We are so sorry about your PR not reviewed in time.

This code looks fine to me. But just confilicts there due to long time no merge, some bugs may fixed.
Again, sorry about that.

Could you please make sure that this changes are okay with the latest commit of `dev` branch by rebasing your code? (I am afraid a lack of knowledge about AMS module of me cannot resolve the confilts that involved in this month.)
 
If rebase is fine, then I will start to merge it. Thanks~

**Comment by BrianBlum** [comment]
@haroldrandom, I'll take another look at this PR. I was using the production CLI yesterday and it looks like it addresses the same issues that this PR was trying to address, namely, posting a message if a resource is not found. If there are any gaps, I'll submit a new PR.

**Comment by yonzhan** [comment]
@haroldrandom how about this PR ?

**Comment by haroldrandom** [comment]
@BrianBlum Any update?

**Comment by haroldrandom** [comment]
Closed as discussion. Feel free to reopen.

**Pull request closed without merging**
