### PR TITLE
Fixing update and create failover group command to accept Manual failover policy

### PR DESCRIPTION
**Pull request by maboja-msft**
If customer was trying to create Failover Group with Manual failover policy or update it to Manual for already existing Failover Group, the operation was being blocked. This PR is fixing it and updating tests to reflect this scenario.

The issue got raised up here: https://github.com/Azure/azure-cli/issues/7215

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by maboja-msft** [comment]
@jaredmoo can you please take a look?

**Comment by jaredmoo** [comment]
You should also update HISTORY.rst.

**Comment by maboja-msft** [comment]
I think it is qualifying into minor fixes, so no need for HISTORY.rst change

**Comment by jaredmoo** [comment]
This was reported by a customer so I think customers will care that it works now. Anyway I think the build forces you to bump the version and add history entry for the new version ( https://travis-ci.org/Azure/azure-cli/jobs/437381307#L769 )

**Comment by maboja-msft** [comment]
> This was reported by a customer so I think customers will care that it works now. Anyway I think the build forces you to bump the version and add history entry for the new version ( https://travis-ci.org/Azure/azure-cli/jobs/437381307#L769 )

Yeah, I also realized it now - will add it.

**Pull request merged**
