### PR TITLE
[App Service] `az staticwebapp create` : Update help text with guidance for repos in Github organizations

### PR DESCRIPTION
**Pull request by StrawnSC**
**Description**

Updates the help text for `az staticwebapp create` with additional guidance for using creating a static web app from a Github repo in a Github organization. 

**Testing Guide**

N/A

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by StrawnSC** [comment]
I'm not sure why the CI test are failing here. I only changed one line of help text, but the CI tests are failing at the `azdev setup` step on the script `build_scripts/windows/scripts/remove_unused_api_versions.py`

**Comment by yonzhan** [comment]
@zhoxing-ms to help with

**Review by wangzelin007 — APPROVED** [review]

**Comment by wangzelin007** [comment]
@StrawnSC rerun can fix~

**Comment by StrawnSC** [comment]
@wangzelin007 thanks for the help

**Review by panchagnula — APPROVED** [review]
LGTM

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
