### PR TITLE
Remove hardcoded en-us locale in docs links.

### PR DESCRIPTION
**Pull request by sptramer**
This should touch docstring and related content only.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yugangw-msft** [comment]
Re-targetting to the Dev branch.  @Juliehzl, please review and merge

**Comment by Juliehzl** [comment]
@sptramer Looks good in general. You want the docs link display different languages according user regions, right? 
But I prefer hard-coded en-us locale to some extend, which have the most accurate description. If you confirm you want to do such change, there is no problem for me to approve and merge it.

**Comment by Juliehzl** [comment]
@zikalino The target branch already changed, but the travis CI still regard master as target branch.

**Comment by sptramer** [comment]
@Juliehzl Yes, please remove the `en-us` links. That will direct the user to whatever the language setting for their browser is. I understand that en-us is often the best source of information (and canonical) but we can't make the assumption that international users will know English.

**Comment by zikalino** [comment]
looks good!

**Pull request merged**
