### PR TITLE
{AKS} Fix spacing issues in cmd construction for tests

### PR DESCRIPTION
**Pull request by pfrcks**
**Related command**

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Review by zhoxing-ms — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@pfrcks Please address the conflict

**Comment by zhoxing-ms** [comment]
Please note that since we will launch the release of this sprint the day after tomorrow. If you cannot address all the comments tomorrow, we will have to postpone the release of this PR to the next sprint (02-07)

**Comment by zhoxing-ms** [comment]
@pfrcks Please note that since we will launch the release of this sprint the day after tomorrow. If you cannot address all the comments tomorrow, we will have to postpone the release of this PR to the next sprint *(03-07)*

**Comment by zhoxing-ms** [comment]
@pfrcks Any update?

**Comment by zhoxing-ms** [comment]
@FumingZhang Could you please summit another PR to fix this test issue? Since this PR has not received a response for a long time, I will close it first

**Pull request closed without merging**
