### PR TITLE
[ACR] Return patch response directly for acr repository update

### PR DESCRIPTION
**Pull request by djyou**
Fixes https://github.com/Azure/acr/issues/212

Also remove deprecated classic registry error handling

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by djyou** [comment]
@tjprescott Please include this fix in the May 29th release https://github.com/Azure/azure-cli/milestone/65 but not earlier since this also requires a server side fix and deployment.
/cc @sajayantony @yuwaMSFT2

**Comment by djyou** [comment]
@adewaleo There is no user-facing change. We are not deprecating classic registry support either, this just removed client side logic and will print whatever server returns from now on.

**Comment by sajayantony** [comment]
LGTM 👍

**Comment by yuwaMSFT2** [comment]
Need to wait for server side to finish deployment. Just FYI.

**Comment by adewaleo** [comment]
> Need to wait for server side to finish deployment. Just FYI.

This should be fine, our release begins this thursday for next tuesday the 4th of may.

**Pull request merged**
