### PR TITLE
Add azure-cli-managedservices

### PR DESCRIPTION
**Pull request by rajivnandivada**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by rajivnandivada** [comment]
@yugangw-msft could you review this PR? Thank you!

**Comment by tjprescott** [comment]
@rajivnandivada has this been through a CLI-team command review? Is there someone you have been working with on the CLI team?

**Comment by rajivnandivada** [comment]
> This requires a command review.

Could you let me know what the process for that is?

**Comment by rajivnandivada** [comment]
@tjprescott what is the process for getting the commands reviewed?

**Comment by tjprescott** [comment]
Please email Yugang Wang (alias yugangw) and he'll pair you with a dev for review.

**Comment by rajivnandivada** [comment]
I messed up branch so Im closing this PR. https://github.com/Azure/azure-cli/pull/9690 is the new one.

**Pull request closed without merging**
