### PR TITLE
{Packaging} Bump `humanfriendly` to 10.0

### PR DESCRIPTION
**Pull request by jiasli**
**Description**

The stale [`pyreadline`](https://pypi.org/project/pyreadline/) (last released at Sep 16, 2015) causes failure in PyCharm when using `pytest`:

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.2.3\plugins\python-ce\helpers\pycharm\_jb_pytest_runner.py", line 51, in <module>
    sys.exit(pytest.main(args, plugins_to_load + [Plugin]))
  File "D:\cli\py310\lib\site-packages\_pytest\config\__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  ...
  File "D:\cli\py310\lib\site-packages\pyreadline\modes\basemode.py", line 162, in _bind_key
    if not callable(func):
  File "D:\cli\py310\lib\site-packages\pyreadline\py3k_compat.py", line 8, in callable
    return isinstance(x, collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'
```

`pyreadline` is required by the old `humanfriendly`:

```
> pipdeptree -p pyreadline -r
pyreadline==2.1
  - humanfriendly==9.1 [requires: pyreadline]
    - azure-cli-core==2.30.0 [requires: humanfriendly>=4.7,<10.0]
      - azure-cli==2.30.0 [requires: azure-cli-core==2.30.0]
```

In new `humanfriendly`, it uses `pyreadline3` (https://github.com/xolox/python-humanfriendly/commit/9f9f271a9d39c7088ddfd4a1af62a997b1c6d7eb).

### CODE REVIEW

**Comment by yonzhan** [comment]
Packaging

**Review by calvinhzy — APPROVED** [review]

**Comment by jiasli** [comment]
@evelyn-ys, please help test the new `humanfriendly` as it is used by progress bar.

**Review by evelyn-ys — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]
Have tested progress bar, LGTM

**Comment by glaubitz** [comment]
Thanks for fixing this. Could you release a new version of `azure-cli` and `azure-cli-core`, so I can pick up the fixed versions in openSUSE?

**Comment by jiasli** [comment]
Next release would be 12/07/2021 (https://github.com/Azure/azure-cli/milestone/112) due to the holiday season.

**Comment by glaubitz** [comment]
Wouldn't it be possible to make a minor release to address this issue? Otherwise, I will have to patch the package in openSUSE locally now.

**Comment by jiasli** [comment]
Unfortunately, our release schedule is fixed and this issue is considered as low business impact. Thanks for your understanding.

**Pull request merged**
