### PR TITLE
{App Service} Change help text for az webapp commands

### PR DESCRIPTION
**Pull request by seligj95**
**Description**

Related to feedback from this study: https://hits.microsoft.com/Insight/1251147. 

**Testing Guide**

`az webapp config container --help`
`az webapp config container delete --help`
`az webapp config container set --help`
`az webapp config container show --help`
`az webapp deployment slot swap --help`
`az webapp list --help`
`az webapp config set --help`

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
App Service

**Review by panchagnula — COMMENTED** [review]
Do we need to do similar update for the function app equivalent as well?

**Comment by seligj95** [comment]
> Do we need to do similar update for the function app equivalent as well?

@panchagnula which commands need updates? I'm not too familiar with the function app commands but can make the updates for this PR. I updated 2 quick ones that I saw. Anymore?

**Comment by panchagnula** [comment]
> > Do we need to do similar update for the function app equivalent as well?
> 
> @panchagnula which commands need updates? I'm not too familiar with the function app commands but can make the updates for this PR. I updated 2 quick ones that I saw. Anymore?

@seligj95 - ever az webapp command has an equivalent az functionapp command, so my ask to check the equivalent az functionapp command in help & update those as well, if needed.

**Review by panchagnula — APPROVED** [review]
Approved.

**Pull request merged**
