### PR TITLE
{CDN} Deprecate CDN WAF related commands

### PR DESCRIPTION
**Pull request by t-bzhan**
**Related command**

az cdn waf

**Description**

Deprecate CDN WAF related commands

**Testing Guide**

az cdn waf policy custom-rule list -g afdx-bugbash --policy-name CDBWAFbug

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
CDN

**Review by necusjz — CHANGES_REQUESTED** [review]
Please fix style checks.

**Review by necusjz — APPROVED** [review]

**Review by necusjz — APPROVED** [review]

**Comment by t-bzhan** [comment]
Hi @necusjz , could you help to merge the PR? Another question, will the doc update for https://docs.microsoft.com/en-us/cli/azure/cdn/waf?view=azure-cli-latest requires another release for CLI?

**Comment by necusjz** [comment]
> Another question, will the doc update for https://docs.microsoft.com/en-us/cli/azure/cdn/waf?view=azure-cli-latest requires another release for CLI?

Yes, it is.

**Review by necusjz — APPROVED** [review]

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
