### PR TITLE
{Packaging} fix removal of networking package 2018-08-01

### PR DESCRIPTION
**Pull request by novinc**
remove deletion of networking package 2018-08-01 from azure-cli.spec

**Description**  
https://github.com/Azure/azure-cli/pull/15082 removed some networking packages as unused, this broke the ACI package as it has a dependency on one of those versions. 

https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/container/_client_factory.py#L57

**Testing Guide**  

**History Notes**  

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Packaging

**Comment by yungezz** [comment]
hi @fengzhou-msft could you pls help to look at this? there're several issues related with this api version.  thanks.

**Review by fengzhou-msft — APPROVED** [review]

**Pull request merged**
