### PR TITLE
{CI} replace 2019-07-01 with 2020-06-01

### PR DESCRIPTION
**Pull request by MyronFanQiu**
https://github.com/Azure/azure-cli/pull/14233/files The CI in this PR didn't sync with resource's latest change. The api-version in three recording files are not correct.

### CODE REVIEW

**Comment by qwordy** [comment]
Did you modify yaml files directly?

**Comment by MyronFanQiu** [comment]
> Did you modify yaml files directly?

Yes. Let's have a test first. We can discuss whether we should merge it or not.

**Comment by qwordy** [comment]
I rerun it lively and got
```
knack.util.CLIError: Name clitest.rg3hdo26ksbqcrbem7cwwqll4z2p5pyv26gwhroglddmnbyz5v4prss6snz4laex5aq is not valid.
```

**Comment by MyronFanQiu** [comment]
> I rerun it lively and got
> 
> ```
> knack.util.CLIError: Name clitest.rg3hdo26ksbqcrbem7cwwqll4z2p5pyv26gwhroglddmnbyz5v4prss6snz4laex5aq is not valid.
> ```

I met same errors. It's return from web app service. I don't know what's the root cause for it. That's why I open this PR.

**Comment by yungezz** [comment]
agree to the temp fix to unblock CI. Issue https://github.com/Azure/azure-cli/issues/14623 is tracking webapp issue.

**Pull request merged**
