### PR TITLE
get_vault_base_url_type and vault_name

### PR DESCRIPTION
**Pull request by WiseMack**
I made an issue https://github.com/Azure/azure-cli/issues/8172, a couple hours ago, and found myself without anything to do, so I thought why not try fixing it myself, this is my attempt to fix the underlying code of Azure CLI.

What little I understood of the code told me that there were some problems with variable use
vault_name being used for some things and vault_base_url for others

so I got to playing spot the variable that doesn't belong and voila! 

I believe I got them all, but I'm not sure.

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by WiseMack** [comment]
About
  The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see Modifying change log).
where exactly is the HISTORY.rst?
I believe I changed a few help='Name of the {}. Required if --id is not specified.' attributes and teoretically this means that this would count as a customer-facing change

**Comment by tjprescott** [comment]
@schaabs can you take a look?

**Comment by schaabs** [comment]
I'm reviewing this now.

**Comment by tjprescott** [comment]
Hi @WiseMack thank you for posting an issue and thank you doubly for taking time to submit a potential fix. In this case, the underlying error was caused by a difference in how you specify arguments in CLI and the Powershell cmdlets. If you use `--name $your_var` or `-n $your_var` you will find that it should work.

**Pull request closed without merging**
