### PR TITLE
webapp: expose traffic-routing command to configure static routing

### LINKED ISSUE #2067: [App Service] Support configuring traffic routing between slots
It would be great if the CLI allowed configuring the traffic routing %'s between slots, so that you can do release flighting/tests in production. This capability is exposed in the portal underneath the `Development Tools | Testing in production` blade, but doesn't appear to be available in the `az appservice web deployment slot` command group (apologies if I missed it!).

### PR DESCRIPTION
**Pull request by yugangw-msft**
Fix #2067 

- [x] The PR has modified HISTORY.rst with an appropriate description of the change (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [x] Each command and parameter has a meaningful description.
- [x] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by yugangw-msft** [comment]
Command was named to be in line with portal
```portal
Command
    az webapp production-test: Test in production, including configuring static routings.

Arguments
    --static-routings [Required]: Space separated slot routings in a format of <slot-
                                  name>=<percentage> e.g. staging=50. Unused traffic percentage will
                                  go to the Production slot.
```

**Comment by lostintangent** [comment]
@yugangw-msft Maybe it's just me, but the naming of this command "feels" a little strange. Also, how would someone check what the current traffic routing rules are from the CLI (e.g. am I currently sending any traffic to `staging`)?

Would it make sense to create a new command group (maybe called `traffic-routing` to match the heading in the portal?) that included `set` and `show` (and maybe `delete`) commands, which would match the existing convention of the `az webapp config container` (among others)? The following seems kind of nice (assuming you have a default group and web app set):

```shell
# Begin routing 50% of traffic to the staging slot
az webapp traffic-routing set --distribution staging=50

# Display the current distribution of traffic across slots
az webapp traffic-routing show

# Reset the routing rules to send 100% to production
az webapp traffic-routing delete
```

**Comment by yugangw-msft** [comment]
@lostintangent, it is not just you. It just didn't cross my mind that `show` is also important. Thanks for the ideas which looks reasonable.

**Comment by lostintangent** [comment]
@yugangw-msft Sounds good. I'm excited to have this be available in the CLI 👍

**Comment by yugangw-msft** [comment]
@lostintangent, I took almost all you suggested, except I use `clear` instead of `delete` as usually `delete` takes a key pointing to the entity to delete, but here we are just clearing all of them

**Comment by lostintangent** [comment]
@yugangw-msft Looks awesome!

**Pull request merged**
