### PR TITLE
[RDBMS] `az postgres flexible-server private-endpoint-connection / private-link-resource / server-logs / virtual-endpoint list`: Fix linter issue and not exposing IDs parameter on the list command

### PR DESCRIPTION
**Pull request by mattboentoro**
**Related command**

- az postgres flexible-server private-endpoint-connection list
- az postgres flexible-server private-link-resource list
- az postgres flexible-server server-logs list
- az postgres flexible-server virtual-endpoint list

**Description**

Fix linter issue and not exposing IDs parameter on the list command

**Testing Guide**

Local testing

**History Notes**

[RDBMS] BREAKING CHANGE: `az postgres flexible-server private-endpoint-connection / private-link-resource / server-logs / virtual-endpoint list`: Fix linter issue and not exposing IDs parameter on the list command

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by nasc17** [comment]
@evelyn-ys We saw this issue come up when linter check is done; is it considered a breaking change to fix?
image

**Comment by evelyn-ys** [comment]
@wangzelin007 @AllyW Do you have knowledge of `no_ids_for_list_command` restriction in `azdev linter`? Commands in this PR have `--ids` parameter for quite long time, not sure why linter requires change, and it causes breaking changes

**Comment by evelyn-ys** [comment]
@nasc17 I don't suggest breaking changes. You can add linter exclusion rules instead

**Comment by mattboentoro** [comment]
ok, I'll abandon this PR, and try using the exclusion rules instead

**Pull request closed without merging**
