### PR TITLE
[Core] Fix resolution of client_arg_name

### LINKED ISSUE #5509: Extensions that vendor their SDKs require client_arg_name to be specified
See https://github.com/Azure/azure-cli-extensions/pull/49/files#r166705871
The same applies to generic update.

https://github.com/Azure/azure-cli/commit/6808e6b023721c49c8661d5d55b1de3ab97bf25e#diff-103131eb32c8ff55661bc902248c80a6R322

https://github.com/Azure/azure-cli/blob/dev/src/azure-cli-core/azure/cli/core/commands/arm.py#L368

### PR DESCRIPTION
**Pull request by tjprescott**
Fix #5509.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [X] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [N/A] Each command and parameter has a meaningful description.
- [N/A] Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/5553
This is an **experimental preview** for @microsoft users.

**Comment by derekbekoe** [comment]
This looks good but it's making an assumption that my custom command handlers will be in `custom.py`.
I believe there may be cases where the custom handlers are spread over multiple files (?).
Is there an approach that doesn't have this assumption?

**Comment by tjprescott** [comment]
@derekbekoe that's a great point (and why I don't like when custom commands are spread over multiple files).  I'll try another approach.

**Comment by tjprescott** [comment]
@derekbekoe please take another look at the updated heuristic.  Should work if extension developers adhere to our guidelines.

**Comment by tjprescott** [comment]
Verified using the subscription extension that this fixes the issue.

**Pull request merged**
