### PR TITLE
[Synapse]spark configuration conversion, which cause the failure

### PR DESCRIPTION
**Pull request by zesluo**
**Description**
spark configuration '.' is converted to'_', which cause the failure

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by jsntcy** [comment]
@zesluo, do we have tests to cover this change?

**Comment by jsntcy** [comment]
@zesluo, do we have tests to cover this change?

**Comment by yonzhan** [comment]
Synapse

**Comment by zesluo** [comment]
> @zesluo, do we have tests to cover this change?

updated, thanks

**Review by jsntcy — APPROVED** [review]

**Review by idear1203 — APPROVED** [review]

**Pull request merged**
