### PR TITLE
{History} Expose core history in azure-cli

### PR DESCRIPTION
**Pull request by fengzhou-msft**
**Description**  

To increase the publicity of core changes, let's copy the Core history notes to Azure CLI history. It will be eventually copied to the release notes on MS DOC as well.

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S168

**Comment by yungezz** [comment]
only changes will impact customer experience need to be added into release note . I would suggest not append selective core history

**Comment by jiasli** [comment]
I think we can sift out the entries we don't want in the releasing process. We need to review the history  in the "bump version" PR before merging.

**Comment by jiasli** [comment]
Thanks Feng for the PR, but lets add them manually in the release process.

**Comment by fengzhou-msft** [comment]
> Thanks Feng for the PR, but lets add them manually in the release process.

Agree.

**Pull request closed without merging**
