### PR TITLE
{CODEOWNER} Update code owners for Batch module

### PR DESCRIPTION
**Pull request by gingi**
**Description**
Updates Batch code owners

**Testing Guide**
N/A

**History Notes**
N/A

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
CODEOWNER

**Review by yonzhan — APPROVED** [review]

**Comment by dpwatrous** [comment]
Hmm, looks like it's still not happy with the PR title here.

Link to guidelines (though I'm not sure why it's failing): https://github.com/Azure/azure-cli/blob/dev/doc/authoring_command_modules/README.md#submitting-pull-requests

**Comment by gingi** [comment]
I corrected it last night (added the “[CODEOWNER]” prefix) but when I tried to rerun it didn’t detect the correction. Just reran it again and it seems to have resolved.


________________________________

**Comment by fengzhou-msft** [comment]
Changed PR title as the change is not customer-facing.

**Comment by gingi** [comment]
Thank you @fengzhou-msft!

**Pull request merged**
