### PR TITLE
[SQL] Update az sql mi examples

### PR DESCRIPTION
**Pull request by kukislav**
**Description**

Adding examples for new commands.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
SQL

**Review by evelyn-ys — APPROVED** [review]

**Comment by kukislav** [comment]
@fengzhou-msft Can you take a look why pipelines are stuck?

**Comment by yonzhan** [comment]
You could also ping @evelyn-ys after holiday.

**Comment by kukislav** [comment]
@yonzhan I just need anyone with permission to rerun pipelines.

**Comment by yonzhan** [comment]
I've kicked CI jobs, we'll review this one when back from holiday

**Comment by kukislav** [comment]
Thanks!

**Pull request merged**
