### PR TITLE
[Synapse] BREAKING CHANGE: `az synapse sql/pool audit-policy`: Remove `--blob-auditing-policy-name`

### PR DESCRIPTION
**Pull request by zesluo**
**Description**
remove parameter blob-auditing-policy-name from az synapse sql/pool audit-policy 

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Synapse

**Review by wonner — APPROVED** [review]

**Comment by evelyn-ys** [comment]
This is a breaking change, are you sure to remove directly? Usually we mark arguments as deprecated for 1 or 2 sprint and then remove them...

**Comment by zesluo** [comment]
> This is a breaking change, are you sure to remove directly? Usually we mark arguments as deprecated for 1 or 2 sprint and then remove them...

**Comment by zesluo** [comment]
> This is a breaking change, are you sure to remove directly? Usually we mark arguments as deprecated for 1 or 2 sprint and then remove them...

Yes, we'd like to remove it directly. In fact, "blob-auditing-policy-name" didn't take effect. So we'd like to remove it in order to prevent customer from getting confused.

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
