### PR TITLE
Aladdin generated examples

### PR DESCRIPTION
**Pull request by aladdindoc**
- Add Aladdin crafted examples.

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S169

**Comment by aladdindoc** [comment]
Can someone look into Azure.azure-cli pipeline. The failure doesn't look related to this PR. Here is the error
A task is missing. The pipeline references a task called 'ms-codeanalysis.vss-microsoft-security-code-analysis.build-task-credscan.CredScan'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 2, job 'CredScan', step ''.)

**Comment by haroldrandom** [comment]
@aladdindoc we will take care of it.

**Pull request merged**
