### PR TITLE
Update to use managed disks in default windows arm template

### PR DESCRIPTION
**Pull request by jsturtevant**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

### Command Guidelines

- [x] (N/A) Each command and parameter has a meaningful description.
- [x] (N/A) Each new command has a test.

(see [Authoring Command Modules](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules))

### CODE REVIEW

**Comment by jsturtevant** [comment]
Any interest in this PR?

**Comment by tjprescott** [comment]
Due to recent changes to the CLI core, you will need to rebase your changes against the latest in the dev branch.

**Comment by jsturtevant** [comment]
completed rebase. thanks!

**Comment by tjprescott** [comment]
Thanks @jsturtevant please check out the CI failures.

**Pull request closed without merging**
