### PR TITLE
Update test scripts and mechanisms

### PR DESCRIPTION
**Pull request by troydai**
1. Ping to azure-devtools==0.4.3
2. Change the test invocation in build.sh to reduce output from
coverage.
3. Update coverage configuration
4. Fix missing storage test

screen shot 2017-07-05 at 1 43 54 pm

Break from PR #3963

### CODE REVIEW

**Comment by troydai** [comment]
@tjprescott this is essentially the first half of the PR #3963. It will suppress the code coverage output. I can merge as soon as it is approved.

**Comment by tjprescott** [comment]
Why not just merge #3693?

**Comment by troydai** [comment]
@tjprescott @derekbekoe need more time for the logger changes.

**Comment by troydai** [comment]
Ping @tjprescott

**Pull request merged**
