### PR TITLE
{Feedback} Fix feedback minification

### PR DESCRIPTION
**Pull request by gukoff**
The previous implementation had 3 bugs:
- `IndexError` when only 1 line in `error_string` [example: #11889];
- infinite loop when repeatedly can't strip down `error_string`;
- ", ln" instead of ", in" in one matching expression that rendered it useless.

Also the logic itself was "magical": it removed 4 lines at a time, starting from a middle line but if possible (never successfully) from a line before that has an exception start in it...

This change should fix all these problems.

### CODE REVIEW

**Comment by yonzhan** [comment]
feedback

**Comment by jiasli** [comment]
@gukoff, first thanks for the careful work.

Actually, we are considering removing the feedback minification logic, as it has caused us many problems (https://github.com/Azure/azure-cli/issues/16386). 

Also, given modern browsers are already accepting URL length exceeding the old limitation (https://stackoverflow.com/a/417184):

https://github.com/Azure/azure-cli/blob/e3ac647675035d40877b43636843f4f737edcd42/src/azure-cli/azure/cli/command_modules/feedback/custom.py#L34

the motivation to minify the `error_string` seems less reasonable.

**Comment by gukoff** [comment]
If you're not doing it before the next release, this fix still makes sense :)

I agree that minification needs a revamp - large parts of code seem unnecessary and not tested.

The URL length limit is still there, it's just usually higher than 2KB. E.g. the (undocumented?) GitHub's serverside limit on URL length is 8KB.

Perpahs minification could always strip the prefix of the error message. 

Also, after the minification (or instead of it) we can ask the user in the CLI if opening the issue was successful. If not, write the manual instructions to the terminal: "1. open this page", "2. copy-paste this text".

---

About GitHub serverside limit:

image
[_example URL_](https://github.com/azure/azure-iot-cli-extension/issues/new?template=Bug_report.md&body=%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%23%23%23+%2A%2AThis+is+autogenerated.%0A%0A%2)

**Comment by jiasli** [comment]
> If you're not doing it before the next release, this fix still makes sense :)

Of course. But for the time being I really don't have enough time to go through your code thoroughly. 😥

> Also, after the minification (or instead of it) we can ask the user in the CLI if opening the issue was successful. If not, write the manual instructions to the terminal: "1. open this page", "2. copy-paste this text".

Yes, we do have this logic. I will make it more user-friendly.

**Review by jiasli — APPROVED** [review]

**Review by fengzhou-msft — APPROVED** [review]

**Pull request merged**
