### PR TITLE
[IoT] Remove IoT PNP preview commands from core CLI

### PR DESCRIPTION
**Pull request by c-ryan-k**
**Description**  

These preview commands have changed significantly, (as has the structure of the service) and we will be moving their implementation into the IoT Extension.

**Testing Guide**  

All preview commands under `az iot pnp` have been removed.

**History Notes**  

[IoT] BREAKING CHANGE: az iot pnp a: Preview `az iot pnp` commands will require the IoT CLI Extension

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
IoT

**Comment by c-ryan-k** [comment]
@yonzhan  / @zhoxing-ms - just curious if there's any update on this? Would like to avoid any last minute changes to this PR

**Comment by zhoxing-ms** [comment]
@c-ryan-k Hi, may I ask why not delete the relevant tests and just delete the record files??

**Comment by c-ryan-k** [comment]
> @c-ryan-k Hi, may I ask why not delete the relevant tests but just delete the record files?
@zhoxing-ms:  Not quite sure I understand - I've deleted both the PNP test file and the PNP recorded test file, and only out of "latest" because we did not include the PNP commands in our previous profile tests.

Is there another file (or other files) I should have removed?

**Comment by zhoxing-ms** [comment]
@c-ryan-k OK, there are no other files need to be deleted. 
By the way, the deletion of the command will cause a breaking change to the customers. Has the impact been evaluated and is it acceptable?

**Comment by digimaun** [comment]
The deletion of these out-of-date preview commands align with IoT goals and future plays. A different implementation of these commands will exist in the IoT extension for Azure CLI. Users should expect `preview` (as everything removed here is under preview) labeled commands have no guarantee of stability as preview/concept technology can rapidly change.

Is there anything else pending for the merge of this PR? We would like to get this in the scheduled 7/14 Azure CLI release.

**Comment by Juliehzl** [comment]
Hi @c-ryan-k  and @digimaun , through telemetry, `az iot pnp` is used by 1 subscription in the past 30 days. I will recommend you to add deprecation information for one sprint and hide the commands. And then we can remove them.

**Comment by jsntcy** [comment]
> Hi @c-ryan-k and @digimaun , through telemetry, `az iot pnp` is used by 1 subscription in the past 30 days. I will recommend you to add deprecation information for one sprint and hide the commands. And then we can remove them.

@Juliehzl, from our CLI guideline ` Items marked preview can be changed, broken or removed at any time without following the deprecation process.`, I think it's OK to delete these preview commands directly.

**Pull request merged**
