### PR TITLE
[AKS] BREAKING CHANGE: `az aks create`: Updates to option `--enable-managed-identity`

### PR DESCRIPTION
**Pull request by FumingZhang**
**Related command**

`az aks create`

**Description**

- Resolve issue [#7012](https://github.com/Azure/azure-cli-extensions/issues/7012).
- Specifying `--enable-managed-identity` and `--service-principal`/`--client-secret` at the same time will cause a `MutuallyExclusiveArgumentError`
- Change the default value of option `--enable-managed-identity` from `True` to `False`
- When options `--service-principal` and `--client-secret` are not specified at the same time, CLI will backfill the value of `--enable-managed-identity` to `True` to maintain the same behavior as before (that is, create an cluster with managed system assigned identity by default)

**Testing Guide**

**History Notes**

[AKS] BREAKING CHANGE: `az aks create`: Specifying `--enable-managed-identity` and `--service-principal`/`--client-secret` at the same time will cause a `MutuallyExclusiveArgumentError`
[AKS] BREAKING CHANGE: `az aks create`: Change the default value of option `--enable-managed-identity` from `True` to `False`
[AKS] `az aks create`: When options `--service-principal` and `--client-secret` are not specified at the same time, CLI will backfill the value of `--enable-managed-identity` to `True` to maintain the same behavior as before (that is, create an cluster with managed system assigned identity by default)

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by matthchr** [comment]
Do we actually want to change this?
> Change the default value of option --enable-managed-identity from True to False

I think it's OK that this default is true? Rest of the change seems reasonable to me though.

**Comment by FumingZhang** [comment]
> Do we actually want to change this?
> 
> > Change the default value of option --enable-managed-identity from True to False
> 
> I think it's OK that this default is true? Rest of the change seems reasonable to me though.

If the default is kept as `True`, I guess there is no way to distinguish whether the user has specified this option, and thus cannot raise MutuallyExclusiveArgumentError

**Comment by FumingZhang** [comment]
> > [AKS] BREAKING CHANGE: az aks create: Specifying --enable-managed-identity and --service-principal/--client-secret at the same time will cause a MutuallyExclusiveArgumentError
> > [AKS] BREAKING CHANGE: az aks create: Change the default value of option --enable-managed-identity from True to False
> 
> Since this PR contains multiple breaking changes, could we release it in the next breaking change window (next Build Event sprint)?

marked as draft

**Pull request closed without merging**
