### PR TITLE
{ACR} `az acr check-name`: Fix registry commands to loaded with right profile version to support both Azure and Edge

### PR DESCRIPTION
**Pull request by rjaini**
**Related command**
az acr check-name

**Description**
The code changes are done in ACR base code flow to support the registry related commands to be supported on Azure and Edge. New code changes made it to support only a particular version of API and that version is not supported in Edge.

**Testing Guide**
`az acr check-name` should work fine with latest and 2020-09-01-hybrid profile

**History Notes**

[ACR] `az acr check-name`: Make command work with different profile

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Review by larisaborodina — APPROVED** [review]

**Review by chappleg — APPROVED** [review]

**Comment by yonzhan** [comment]
ACR

**Comment by zhoxing-ms** [comment]
@rjaini Could you please address these CI issues?

**Review by rosanch — APPROVED** [review]
LGTM

**Comment by rjaini** [comment]
@zhoxing-ms can you also look at the PR and approve appropriately.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
