### PR TITLE
[vm] vm create: add --computer-name 

### LINKED ISSUE #8402: az vm create should have a parameter to set osprofile.computerName (hostname)
**Is your feature request related to a problem? Please describe.**
Yes. I can create a VM from one of my images easily for everything including networking but for some reason there isn't a parameter to set osprofile.computerName (ie the hostname) of the new VM.
I need this almost everyday and I have to resort to a group deployment with templates and many files just to set up a simple VM 

**Describe the solution you'd like**
there should be a --computer-name switch to specify the hostname of each created VM.

**Describe alternatives you've considered**
I have to go through the hassle of a az group deployment with JSON files for this simple thing.

**Additional context**

### PR DESCRIPTION
**Pull request by adewaleo**
Expose `--computer-name` option for vm create.

Closes #8402 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by adewaleo** [comment]
> 2 comments:
> 
> 1. I suggest do not add a strong argument just for one user for a pretty edge scenario. More arguments always add to the complexity.
> 2. We can consider exposing a generic setter for any extra tweaks, e.g. `--set osProfile.computerName="vm-12345"`. Ideally, we could make it a global support on all create commands, but we can do it step by step. Doing this follows the guidelines of 80% simple and 20% possible, so I would support it.
> 
> Let us bounce some ideas with @tjprescott

Hello @yugangw-msft, that's fair. Maybe we can discuss this more after scrum?

**Comment by yugangw-msft** [comment]
closing since we have decided not to go this route

**Comment by carlosvsilva** [comment]
What was the final choice for route to go? Thanks

**Comment by adewaleo** [comment]
@carlosvsilva we plan on implementing generic set on VM create, to enable users to set parameters that aren't exposed through arguments. However, due to our implementation of our VM create command and other high priority items, this might take a while (some months) to implement. I apologize for the inconvenience.

For now it seems like the best work around for you would be to stick with az group deployment.

However, you or I might be able to build a docker image from this pull request which contains this argument, just to deal with this inconvenience, you are facing.

**Comment by yugangw-msft** [comment]
@carlosvsilva, you can use `az vm create --debug --validate` to get the template underline and then add one more property for your purpose.

**Pull request closed without merging**
