### PR TITLE
{testsdk} Remove `CommunicationResourcePreparer` from `azure-cli-testsdk`

### PR DESCRIPTION
**Pull request by moirf**
**Description**

Add default connection string required in communication extension in resource preparer file.
**Testing Guide**

NA
**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by jiasli** [comment]
Please add more context for why this is changed.

**Review by jiasli — CHANGES_REQUESTED** [review]
Please add more context for why this is changed.

**Review by beltr0n — APPROVED** [review]

**Comment by moirf** [comment]
> Please add more context for why this is changed.
The test cases for azure-cli-extension, validate the endpoints, for consistency we update the endpoint matching with sanitized.

**Comment by beltr0n** [comment]
> 

I think I'd also like to know, did the previous value work, or is this just a change for consistency? This isn't a new value being added, it's a change to an existing value. I believe for Azure SDK, there's code that checks the value conforms to a certain format.

**Comment by moirf** [comment]
@beltr0n @jiasli we are writing the cli-extension commands for communication, the PR for this is pending here -  https://github.com/Azure/azure-cli-extensions/pull/4206
For running the live mode, the test cases are passed because the account_key( which is actually connection string see line 185) will return the string into correct format, in case of playback mode we need the connection string in same connection string format. since this is not into a correct connection string format, test cases failed as it is looking for an URI into it.

**Review by wangzelin007 — APPROVED** [review]

**Comment by jiasli** [comment]
I would suggest not to put `CommunicationResourcePreparer` (from #20552) in `azure-cli-testsdk`, as `azure-cli-testsdk` is only for common preparers. Instead, it should go to you own command module/extension.

**Comment by moirf** [comment]
@jiasli Ok, will revert the changes for [#20552](https://github.com/Azure/azure-cli/pull/20552). And close this PR.

**Review by jiasli — APPROVED** [review]

**Review by yonzhan — APPROVED** [review]

**Comment by moirf** [comment]
@yonzhan @jiasli can you please merge the branch as I do not have access.

**Comment by jiasli** [comment]
Done. Thanks for notifying me.

**Pull request merged**
