### PR TITLE
[App Service] Backport Breaking Change: Redact appsettings, storage-account, configs

### PR DESCRIPTION
**Pull request by amberwang113**
**Related command**
az webapp config appsettings set/delete
az logicapp config appsettings set/delete
az functionapp config appsettings set/delete
az staticwebapp appsettings set/delete
az webapp config connection-string set/delete
az webapp config storage-account add/update/delete

**Description**
Backport fixes from #27565 and #27629 for issue #28631

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AppService

**Comment by bebound** [comment]
You need to update `test_vm_image.py` like https://github.com/Azure/azure-cli/pull/28751 to pass the test.
Related PR: https://github.com/Azure/azure-cli/pull/26543

**Comment by amberwang113** [comment]
Got it - fixed now! Thanks.

**Comment by amberwang113** [comment]
@bebound No button for another engineer to approve the PR; he will leave a comment here

**Comment by shnjefff** [comment]
@bebound This is Shengnan(Jeffery) from control plane. This pr looks good but I do not have the permission to approve. Can anyone in the reviewer approve this pr please?

**Review by bebound — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@amberwang113 @bebound Since this PR includes breaking change, could we consider moving it to the breaking change window of the next sprint for release **(05-21)**? Or is it a security related issue that must be released in this sprint?

**Review by zhoxing-ms — APPROVED** [review]

**Review by jiasli — APPROVED** [review]
Approving only for branch management.

**Pull request merged**
