### PR TITLE
{ServiceBus} az servicebus: fix typos in help docs

### PR DESCRIPTION
**Pull request by scottsauber**
**Description**
Fix typos

**Testing Guide**
N/a

**History Notes**
N/A

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
ServiceBus

**Review by Juliehzl — APPROVED** [review]

**Review by fengzhou-msft — APPROVED** [review]

**Comment by Juliehzl** [comment]
Hi @scottsauber, as you  send the PR to master at the begginning, which is not allowed in our CI system.
Currently although I change the target branch, ADO still treats System.PullRequest.TargetBranch as master.
Could you create a new PR target dev branch not master?

**Comment by scottsauber** [comment]
@Juliehzl - yep will do.

**Comment by scottsauber** [comment]
See: #17642

**Pull request closed without merging**
