### PR TITLE
{Packaging} Update Homebrew template to use python3.10 executable

### PR DESCRIPTION
**Pull request by chenrui333**
**Related command**

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

----

update brew PR template, relates to https://github.com/Homebrew/homebrew-core/pull/109727

### CODE REVIEW

**Comment by yonzhan** [comment]
homebrew

**Comment by carlocab** [comment]
For context here:

We recently changed the way we package Python formulae. The latest version will have a `python3` executable added to the user's `PATH`, while earlier versions will only have ones with both the major and minor version. For example, `brew install python@3.9` adds only `python3.9` to your `PATH`, and no `python3` will be in its `bin` directory. See https://github.com/Homebrew/homebrew-core/pull/107517.

Hence, it makes sense to fully qualify `python3` as `python3.10` to make sure the reference is not broken when Python 3.11 is packaged in Homebrew.

**Comment by bebound** [comment]
@carlocab Correct me if I'm wrong. When 3.11 is not released, this PR makes no difference. After 3.11 is out, it will prevent linking `python3` in user PATH?

**Comment by carlocab** [comment]
When 3.11 is released, `python@3.10` will not have a `python3` in its `bin` directory. It will only have `python3.10`, so we cannot rely on calling `python3.10` as `python3`.

**Comment by bebound** [comment]
@chenrui333 Could you please sync this PR with `dev` branch? Thank you.

**Review by bebound — APPROVED** [review]

**Comment by carlocab** [comment]
ping @chenrui333

**Review by jiasli — APPROVED** [review]

**Pull request merged**
