### PR TITLE
{Packaging} Remove Fedora 35 build

### PR DESCRIPTION
**Pull request by bebound**
**Description**

Fedora 35 is [end of life](https://docs.fedoraproject.org/en-US/releases/eol/) on 2022‑12‑13 and the test job fails at `dnf update`
```
2023-03-29T02:18:31.7686349Z  > [build-env 2/6] RUN dnf update -y:
2023-03-29T02:18:31.7716524Z #6 55.05 Fedora 35 openh264 (From Cisco) - aarch64       430  B/s | 2.5 kB     00:05    
2023-03-29T02:18:31.7717010Z #6 62.91 Fedora Modular 35 - aarch64                     434 kB/s | 3.2 MB     00:07    
2023-03-29T02:18:31.7717377Z #6 63.95 Fedora 35 - aarch64 - Updates                   562  B/s | 196  B     00:00    
2023-03-29T02:18:31.7717733Z #6 63.95 Errors during downloading metadata for repository 'updates':
2023-03-29T02:18:31.7718235Z #6 63.95   - Status code: 404 for https://download-cc-rdu01.fedoraproject.org/pub/fedora/linux/updates/35/Everything/aarch64/repodata/repomd.xml (IP: 8.43.85.72)
2023-03-29T02:18:31.7719131Z #6 63.95   - Status code: 404 for http://download-cc-rdu01.fedoraproject.org/pub/fedora/linux/updates/35/Everything/aarch64/repodata/repomd.xml (IP: 8.43.85.72)
2023-03-29T02:18:31.7719683Z #6 63.95   - Status code: 404 for http://dl.fedoraproject.org/pub/fedora/linux/updates/35/Everything/aarch64/repodata/repomd.xml (IP: 38.145.60.23)
2023-03-29T02:18:31.7720237Z #6 63.95   - Status code: 404 for https://dl.fedoraproject.org/pub/fedora/linux/updates/35/Everything/aarch64/repodata/repomd.xml (IP: 38.145.60.23)
2023-03-29T02:18:31.7720776Z #6 63.95   - Status code: 404 for https://d2lzkl7pfhq30w.cloudfront.net/pub/fedora/linux/updates/35/Everything/aarch64/repodata/repomd.xml (IP: 52.85.150.43)
2023-03-29T02:18:31.7721304Z #6 63.96 Error: Failed to download metadata for repo 'updates': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
2023-03-29T02:18:31.7721624Z ------
2023-03-29T02:18:31.7721795Z fedora.dockerfile:7
2023-03-29T02:18:31.7722031Z --------------------
2023-03-29T02:18:31.7722216Z    5 |     ARG python_package=python3
2023-03-29T02:18:31.7722374Z    6 |     
2023-03-29T02:18:31.7722550Z    7 | >>> RUN dnf update -y
2023-03-29T02:18:31.7722951Z    8 |     RUN dnf install -y wget rpm-build gcc libffi-devel ${python_package}-devel openssl-devel make bash coreutils diffutils patch dos2unix perl
2023-03-29T02:18:31.7723197Z    9 |     
2023-03-29T02:18:31.7723399Z --------------------
2023-03-29T02:18:31.7723732Z ERROR: failed to solve: process "/bin/sh -c dnf update -y" did not complete successfully: exit code: 1
2023-03-29T02:18:31.7784719Z ##[error]Bash exited with code '1'.
```

It is said that the content is moved to archives (From https://dl.fedoraproject.org/pub/fedora/linux/releases/35). It's weird that amd64 version still works.

> The contents of this directory have been moved to our archives available at:
http://archives.fedoraproject.org/pub/archive/fedora/

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Packaging

**Comment by jiasli** [comment]
> Fedora 35 is end of life on 2022‑12‑13

Let's add the source of it.

**Review by jiasli — APPROVED** [review]

**Review by kairu-ms — APPROVED** [review]

**Pull request merged**
