### PR TITLE
[App Service] `az webapp ssh`: Backport #25141 to 2.38.0

### PR DESCRIPTION
**Pull request by StrawnSC**
**Related command**

`az webapp ssh`

**Description**

Backport the security fix in #25141 to version 2.38.0

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
App Service

**Comment by zhoxing-ms** [comment]
> Backport the security fix in https://github.com/Azure/azure-cli/pull/25414 to version 2.38.0

https://github.com/Azure/azure-cli/pull/25414 @StrawnSC This PR doesn't seem relevant, are you sure you linked it correctly?

**Comment by bebound** [comment]
> > Backport the security fix in #25414 to version 2.38.0
> 
> #25414 @StrawnSC Silas Strawn FTE This PR doesn't seem relevant, are you sure you linked it correctly?

It should be #25141, I've fixed it.

**Review by bebound — APPROVED** [review]

**Review by jiasli — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Comment by StrawnSC** [comment]
@zhoxing-ms @jiasli, anything else needed here before we can publish the fix?

**Pull request merged**
