### PR TITLE
[Backup] `az backup restore restore-disks`: Allow `--disk-encryption-set-id` for cross region restore

### PR DESCRIPTION
**Pull request by zubairabid**
**Related command**

`az backup restore restore-disks`

**Description**

Allows the usage of the `--disk-encryption-set-id` parameter for the cross region restore scenario (Can use it alongside the `--use-secondary-region` flag).

**Testing Guide**

Run a `restore-disks` command with the `--disk-encryption-set-id` and `--use-secondary-region` parameters both. The job should be triggered. Earlier, there would have been an error message saying: "disk_encryption_set_id can't be specified".

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Backup

**Comment by zhoxing-ms** [comment]
Could you add some tests for this change?

**Comment by zhoxing-ms** [comment]
@zubairabid Any update?

**Comment by zubairabid** [comment]
> @zubairabid Any update?

The latest commit I pushed should work, I'm currently running the test and ran the commands manually to test it first.

**Comment by zhoxing-ms** [comment]
OK, we can merge this PR first, and you can submit a separate new PR to add the test later

**Review by zhoxing-ms — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
