### PR TITLE
[AppService] az appservice domain create, show-terms: Add ability to create app service domain

### PR DESCRIPTION
**Pull request by calvinsID**
**Description**  

Add commands `az appservice domain create` and `az appservice domain show-terms` to create AppService Domain, and show legal terms for purchasing & creating AppService Domain

- Show terms: 
image

- Create domain, terms not accepted:
not_accepted

- Create domain, terms accepted, dryrun:
image

**Testing Guide**  
- `az appservice domain create -g MyResourceGroup --hostname "MyCustomDomain.com" --contact-info=@'C:\path\to\contactinfo.json' --accept-terms`

- `az appservice domain show-terms -g MyResourceGroup --hostname "MyCustomDomain.com"`

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Review by qwordy — APPROVED** [review]

**Comment by yonzhan** [comment]
AppService

**Comment by yungezz** [comment]
not sure it's good idea to show term text in console output directly, maybe output to a file?

**Comment by calvinsID** [comment]
> not sure it's good idea to show term text in console output directly, maybe output to a file?

@yungezz Moved the console output to https://storedomainslegalterms.blob.core.windows.net/domain-purchase-legal-terms/legal_terms.txt, and updated the screenshot to reflect this

**Comment by qwordy** [comment]
ready to merge?

**Comment by calvinsID** [comment]
@qwordy Yes pls!

**Pull request merged**
