### PR TITLE
[Security] Define security api-collections and security-connectors commands

### PR DESCRIPTION
**Pull request by ivadim**
**Related command**
```
az security api-collection
az security security-connector
az security security-connector devops
```

**Description**
This PR adds the commands for api-collections and security-connectors APIs
Covering next REST specs:
* https://github.com/Azure/azure-rest-api-specs/blob/main/specification/security/resource-manager/Microsoft.Security/preview/2023-09-01-preview/securityConnectorsDevOps.json
* https://github.com/Azure/azure-rest-api-specs/blob/main/specification/security/resource-manager/Microsoft.Security/preview/2023-10-01-preview/securityConnectors.json
* https://github.com/Azure/azure-rest-api-specs/blob/main/specification/security/resource-manager/Microsoft.Security/stable/2023-11-15/apiCollections.json

**Testing Guide**
Covered by pre-recorded test scenarios

**History Notes**
[Security] `az security api-collection`: Manage Azure API Management API connections to Microsoft Defender for APIs
[Security] `az security security-connector`: Manage cloud security posture management (CSPM) and cloud workload protection (CWP) across multicloud resources

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Security

**Comment by eliagrady** [comment]
suggestion: rename branch to `feature-new-security-features' according to https://github.com/Azure/aaz-dev-tools?tab=readme-ov-file#51-azure-cli

**Review by aditdalvi — APPROVED** [review]

**Comment by eliagrady** [comment]
LGTM

**Review by eliagrady — APPROVED** [review]
LGTM

**Review by necusjz — APPROVED** [review]

**Pull request merged**
