### PR TITLE
[AppService] Fix #11698 #15198 #14862 #15409: az webapp/functionapp config access-restriction add

### LINKED ISSUE #11698: webapp: Apply access restriction to resources in different resource groups
I'd like to add VNET access restriction to Azure Function App. Azure Function App is located in RG1 and VNET is located in RG2.
I can't get it to work even with IDs.
Command:
`
az webapp config access-restriction add 
  --priority 100 
  --action Allow 
  --name $newParameters.FunctionAppName 
  --rule-name "APIm" 
  --subnet $newParameters.APImSubnetName 
  --vnet-name $newParameters.VnetName
`
Error message:
The Resource 'Microsoft.Network/virtualNetworks/dev-deploy-vnet' under resource group 'dev-deploy-rg-dev' was not found.

Command:
`az webapp config access-restriction add 
  --priority 100 
  --action Allow 
  --rule-name "APIm" 
  --ids $b, $c
`
Message:
/subscriptions/xxx/resourceGroups/dev-deploy-rg-dev/providers/Microsoft.Web/sites/dev-deploy-fadev,: "(ResourceNotFound) The Resource 'Microsoft.Web/sites/dev-deploy-vnet' under resource group 'dev-deploy-rg' was not found."
/subscriptions/xxx/resourceGroups/dev-deploy-rg/providers/Microsoft.Network/virtualNetworks/dev-deploy-vnet: "(ResourceNotFound) The Resource 'Microsoft.Web/sites/dev-deploy-fadev,' under resource group 'dev-deploy-rg-dev' was not found.

It's possible through Azure Portal.
Any suggestions?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c788e908-cee3-ae46-fac4-956d0606ad76
* Version Independent ID: 2ed69bfd-bb05-3d09-072e-00e505856fba
* Content: [az webapp config access-restriction](https://docs.microsoft.com/en-us/cli/azure/webapp/config/access-restriction?view=azure-cli-latest#az-webapp-config-access-restriction-set)
* Content Source: [latest/docs-ref-autogen/webapp/config/access-restriction.yml](https://github.com/MicrosoftDocs/azure-docs-cli/blob/live/latest/docs-ref-autogen/webapp/config/access-restriction.yml)
* Service: **app-service-web**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

### PR DESCRIPTION
**Pull request by madsd**
**Description**  
Fixes to reported issues #11698 #15198 #14862 #15409 for config access-restriction add command. 

#15409 Improved the error description to suggest using --Action Deny
#14862 #15198 (duplicate) Included check for scm_site in validation code
#11698 Improve help text and examples with subnet resource id as well as adding a --vnet-resource-group to explicitly be able to specify this.

**Testing Guide**  
Add Access Restriction opening (Allow) named remote_agents in vNet 'corp01' in rg 'vnets' with
    subnet 'agents'
        az webapp config access-restriction add -g ResourceGroup -n AppName --rule-name
        remote_agents --action Allow --vnet-name corp01 --subnet agents --priority 500 --vnet-
        resource-group vnets

Add Access Restriction to both scm site and main site
        az webapp config access-restriction add -g ResourceGroup -n AppName --rule-name developers
        --action Allow --ip-address 130.220.0.0/27 --priority 200

        az webapp config access-restriction add -g ResourceGroup -n AppName --rule-name scm_developers
        --action Allow --ip-address 130.220.0.0/27 --priority 200 --scm-site

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AppService

**Review by qwordy — APPROVED** [review]

**Comment by madsd** [comment]
Seem to be some issue loading test extensions, but I do not have permissions to rerun the build.

**Pull request merged**
