### PR TITLE
[batchai] logger: specify 'group' resource type

### PR DESCRIPTION
**Pull request by mmacy**
Changes logger output on `az batchai cluster create` to specify that the resource type it's creating is a resource **group**.

* was: Creating %s resource for auto-storage account
* now: Creating %s resource group for auto-storage account

Unsure if this counts as **docs only**. If it doesn't, let me know and I'll update HISTORY.rst. Thanks!

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by mmacy** [comment]
Looks like this does need a version update:

```
The following modules have invalid versions:
azure-cli-batchai
See above for the full warning/errors
The command "./scripts/ci/precheck_header.sh" exited with 1.
...
Done. Your build exited with 1.
```

@matthchr Hey Matt, maybe this should be rolled into someone else's update? Not sure we want a version bump just for this. If you're not the correct contact, who might I ping? Thanks -MM

**Comment by troydai** [comment]
@mmacy update the package version is not critical, you just need to update the `setup.py` and add an entry to the `HISTORY.rst`

**Comment by troydai** [comment]
@mmacy update?

**Comment by mmacy** [comment]
@troydai Whoops, forgot about this one. Will try to get to it today!

**Comment by mmacy** [comment]
@troydai How's this looking?

**Pull request merged**
