### PR TITLE
[RDBMS] Add support for server log files for PostgreSQL flexible server

### PR DESCRIPTION
**Pull request by ambrahma**
**Related command**
`postgres flexible-server server-logs list --resource-group testGroup --server-name testserver` to list server log files for PostgreSQL flexible server.
`az postgres flexible-server server-logs download --resource-group testGroup --server-name testserver --name serverlogs/f1.log serverlogs/f2.log` to download the server log files serverlogs/f1.log and serverlogs/f2.log

**Description**
Added support for Server Log files for PostgreSQL flexible server. It supports commands to list and download the server log files.

**Testing Guide**
Added automated tests to enable server parameter for download log files and set retention period for log files. Then validate the list and download of log files.

**History Notes**

[RDBMS] `az postgres flexible-server server-logs list`: List server log files for PostgreSQL flexible server
[RDBMS] `az postgres flexible-server server-logs download`: Download server log files for PostgreSQL flexible server

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
RDBMS

**Comment by ambrahma** [comment]
@evelyn-ys I need help understanding pending AZ CLI Style failure:

Running pylint on modules...
Pylint: PASSED
ERROR: ************* Module azure.cli.command_modules.rdbms._params
src/azure-cli/azure/cli/command_modules/rdbms/_params.py:28:0: R0915: Too many statements (502/500) (too-many-statements)

------------------------------------
Your code has been rated at 10.00/10


ERROR: Pylint: FAILED

Running flake8 on modules...
Flake8: PASSED


##[error]Bash exited with code '8'.

**Comment by evelyn-ys** [comment]
@ambrahma Probably you need to modify the max configuration [here](https://github.com/bebound/azure-cli/blob/9ba55d8f2d6ceb3c7554f5568517247a58a742c8/pylintrc#L69-L70) due to the `disable=too-many-statements` not working issue

**Comment by evelyn-ys** [comment]
@ambrahma Please fix the linter failure according to the guide here: https://github.com/pylint-dev/pylint/issues/8806#issuecomment-1858110502

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
