### PR TITLE
[StandbyPool] `az standby-vm-pool`: Add `az standby-vm-pool`: Add

### PR DESCRIPTION
**Pull request by fangru2023**
**Related command**

`az standby-vm-pool create`
`az standby-vm-pool update`
`az standby-vm-pool show`
`az standby-vm-pool list`
`az standby-vm-pool delete`

`az standby-container-group-pool create`
`az standby-container-group-pool show`
`az standby-container-group-pool list`
`az standby-container-group-pool delete`

**Description**

We are trying to make Standby pool service GA, our target release date is 2024-04-30 release

**Testing Guide**

**History Notes**

[standby-container-group-pool] `az standby-container-group-pool create` / `az standby-container-group-pool show` /`az standby-container-group-pool list`/`az standby-container-group-pool delete`: Add some customer-facing feature
[standby-vm-pool] `az standby-vm-pool create` / `az standby-vm-pool show` /`az standby-vm-pool list`/`az standby-vm-pool delete` / `az standby-vm-pool update`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Comment by fangru2023** [comment]
Hi @jsntcy, let me know if you have any questions!

**Comment by jsntcy** [comment]
It's a new module, and you should not add [breaking change] in pr title.

**Comment by fangru2023** [comment]
> It's a new module, and you should not add [breaking change] in pr title.

I see, updated. I didn't find the right tag for this cases, maybe I missed it from document.

**Comment by fangru2023** [comment]
Hi @zhoxing-ms , @yanzhudd , any feedback, any need from our side?

**Comment by zhoxing-ms** [comment]
@fangru2023 May I ask why you are not considering adding this module into CLI extension? CLI extension usually has more flexible release times, suitable for new RP onboards. 
Additionally, we are currently planning a lightweight core CLI and typically do not recommend new RPs to put into the main repo unless there are necessary business requirements.

**Comment by fangru2023** [comment]
> @fangru2023 Actually, I believe this should be a PLR related feature, and there is already a related PR https://github.com/Azure/azure-cli-extensions/pull/7430/files in the CLI extension. Why submit a similar PR to the main repo? CLI extension usually has more flexible release times, it is more suitable for new RP `microsoft.standbypool` onboards. Additionally, we are currently planning a lightweight core CLI and typically do not recommend new RPs to put into the main repo unless there are necessary business requirements. We even have plans to migrate some non-essential modules for customers from main repo to CLI extensions. cc @jsntcy @kairu-ms

Hi @zhoxing-ms , if that's suggestion, then I can close this PR. But looks like no one is actively reviewing cli extension PR TBH, would you mind review that PR? 

Also, looks like there is some documentation gap, I didn't find any suggestion or guidance that pointing out new RP should add CLI extension module instead of CLI module. Here are documentations that I followed  https://azure.github.io/aaz-dev-tools/, https://eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/control-plane-bburns/azure-cli-tools-azure-cli-powershell-and-terraform/azure-cli-tools/onboarding/azurecli/overview.

Also, we really want to have our CLI catch the April release train.  Would you guys mind take a look at this PR https://github.com/Azure/azure-cli-extensions/pull/7430? It's already pending for several weeks!

Really appreciate your help! Thanks in advance.

**Comment by kairu-ms** [comment]
Duplicated with https://github.com/Azure/azure-cli-extensions/pull/7430

**Pull request closed without merging**
