### PR TITLE
[SQL] az sql db replica create: Add --partner-database argument

### PR DESCRIPTION
**Pull request by bradrich-msft**
**Description**  
Adding optional parameter to sql db replica create command, --partner-database.  This allows creation of secondary
replicas that have a different name than the source database.

**Testing Guide**  
sql db replica create --partner-database foo

**History Notes**  
Not a breaking change

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
SQL

**Review by Juliehzl — CHANGES_REQUESTED** [review]
No need to change history.rst now. We will auto-generate history.rst according to your PR title.

**Comment by evelyn-ys** [comment]
Since we will auto-generate history.rst according to your PR title. It will be nicer to make the title:
[SQL] `az sql db replica cerate`: Add --partner-database argument
according to [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests)

**Review by Juliehzl — APPROVED** [review]
LGTM

**Review by evelyn-ys — APPROVED** [review]

**Comment by bradrich-msft** [comment]
Hello @evelyn-ys it appears this pull request has been approved.  Can it now be merged?  Thank you.

**Pull request merged**
