### PR TITLE
[APIM] az apim restore: New command to restore a backup of an API Management service

### PR DESCRIPTION
**Pull request by Jeej**
**Description**
The current Azure CLI has a preview for APIM commands. One of the commands is to back-up a APIM instance, but the restore command is not implemented. This PR is for adding the restore command to Azure CLI. This will fix issue #14114

It is implemented in the same way as the back-up command is implemented.

Remark: Setting up an dev environment on Windows is not easy with your steps. I ended up with using WSL and VSCode remoting. 

**Testing Guide**
Unfortunately I have absolutely no how tests are being done. I see that there some test files (scenario's) with responses from the API, but I have no clue how to get data in the file. 

Also trying to run the tests (`azdev test apim`) in console resulted in a whole bunch of errors.

Please guide me how to add tests and I will try to add them.

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
APIM

**Review by haroldrandom — CHANGES_REQUESTED** [review]
Please fix the style error CI reporting

**Comment by Jeej** [comment]
I have updated the indenting, but I see in the previous build that [this](https://dev.azure.com/azure-sdk/public/_build/results?buildId=620680&view=logs&j=168ccbe3-da49-5c0b-6478-08f7016e4bf5&t=10a595be-4223-5cc7-9a73-012871b6eaee) step failed. I don't understand why it failed and how I should resolve it.

```
-  FAIL - MEDIUM severity: require_wait_command_if_no_wait
    Command-Group: `apim product` - Group does not have a 'wait' command, yet 'apim product create' exposes '--no-wait'
```
How was this previous commit without failing the checks?

```
-  FAIL - HIGH severity: option_length_too_long
    Parameter: apim restore, `storage_account_container` - The lengths of all options ['--storage-account-container'] are longer than threshold 22. Argument storage_account_container must have a short abbreviation.
```

Like I already wrote before, I keep it like the back-up command, there the argument was like this. 

Does the failure mean that I have to change the product and changed the 'storage_account_container' parameter?

**Comment by haroldrandom** [comment]
@Jeej The CI error complains about the length of the arguments.

One way to dismiss this error is to add a declarative file like `https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/network/linter_exclusions.yml` to exclude the too-long argument from linter detection.

The other way is to add an shorter alias by `options_list=['--xxxx']` in the declaration place of `storage_account_container` like https://github.com/Azure/azure-cli/blob/624da89b18af6666933fc5c67522293ceb31bb27/src/azure-cli/azure/cli/command_modules/network/_params.py#L1932

**Comment by Jeej** [comment]
> Please fix the style error CI reporting

It should be solved now 😄 The build was successful and all checks have passed 😄

**Review by haroldrandom — APPROVED** [review]

**Pull request merged**
