### PR TITLE
Azdev ci

### PR DESCRIPTION
**Pull request by jayr713**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by jayr713** [comment]
tjprescott:AzdevCI

**Comment by jayr713** [comment]
[microsoft-contribution-license-agreement.pdf](https://github.com/Azure/azure-cli/files/4080126/microsoft-contribution-license-agreement.pdf)

**Comment by haroldrandom** [comment]
Sorry, we are going to deprecate Travis on CI.

**Comment by haroldrandom** [comment]
Could you please take a look whether there are other problems or something we miss or other thing we might  not doing well? 

There are 2 parts of azdev existing, one is tools/automation. the other is Azure/azure-cli-dev-tools. We are planning to migrate all the functionalities from the first one to the second one and code refine the second one.

It would be appreciated and grateful if any contribution to those. :)

Feel free to reopen if anything I miss.

**Pull request closed without merging**
