### PR TITLE
[Packaging] Add Debian Bookworm support

### LINKED ISSUE #25750: Installation fails on Debian bookworm due to outdated dependencies
**Related command**
`$ curl -sL https://aka.ms/InstallAzureCLIDeb | docker run --rm -i debian:bookworm bash -`

**Describe the bug**
The azure-cli package provided for Debian bookworm depends on the packages libffi7 and libssl1.1, which are not available:
```
The following packages have unmet dependencies:
 azure-cli : Depends: libffi7 (>= 3.3~20180313) but it is not installable
             Depends: libssl1.1 (>= 1.1.1) but it is not installable
```

**To Reproduce**
Running the documented installation command `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash` on a Debian bookworm installation causes the installation failure. Easily reproducable by using the `debian:bookworm` docker image (see related command above).

**Expected behavior**
Expected the installation to succeed without error on Debian bookworm.

**Environment summary**
Installation method: apt-get (via the installation script, see above)
OS version: Debian bookworm (testing), specifically tested on docker image `debian:bookworm-20230227` (see above)

### PR DESCRIPTION
**Pull request by bebound**
**Description**

Fix #25750.
Bookworm is released on 2023-06-10.

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Packaging

**Comment by jiasli** [comment]
Consider using the GitHub linking convention: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue:

> Fix https://github.com/Azure/azure-cli/issues/25750

**Comment by jiasli** [comment]
Ubuntu 22.10 and 23.04 are also based on Debian bookworm:

```
> docker run --rm -it ubuntu:22.10 cat /etc/debian_version
bookworm/sid
> docker run --rm -it ubuntu:23.04 cat /etc/debian_version
bookworm/sid
```

See https://askubuntu.com/questions/445487/what-debian-version-are-the-different-ubuntu-versions-based-on

Not sure if we want to support them as well, though according to https://wiki.ubuntu.com/Releases, Ubuntu 22.10 will soon be deprecated in July 2023.

**Comment by jiasli** [comment]
Once bookworm is supported, the `deb_install.sh` script should fall back to `bookworm` for non-supported distributions:

https://github.com/Azure/azure-cli/blob/e0883f12fe8c5f00e7dee7cd6d8999d78c004900/scripts/release/debian/deb_install.sh#L65

**Review by jiasli — APPROVED** [review]

**Pull request merged**
