### PR TITLE
Proposal: Add Dockerfile.spot?

### PR DESCRIPTION
**Pull request by derekbekoe**
Support creating 'Spots' directly from PRs in the repo.

### CODE REVIEW

**Comment by troydai** [comment]
Mind add a few comments in the source?

**Comment by derekbekoe** [comment]
Sure.
Add more comments to the Dockerfile?

**Comment by troydai** [comment]
Yes. So that whoever read the code in the future understand what is this for.

**Comment by troydai** [comment]
Merge once CI passes (CI actually does nothing regarding this change. Just for the formality)

**Comment by troydai** [comment]
Forgot you still have the merge privilege.

**Comment by troydai** [comment]
Old habit die hard...

**Pull request merged**
