### PR TITLE
{AKS} Remove Unnecessary ContainerInsights Solution Addition since this being added in AKS RP

### PR DESCRIPTION
**Pull request by ganga1980**
**Description**

Container Insights Solution being added (if it doesnt exist already) by the AKS RP as part of the monitoring addon enablement. This PR removes this unnecessary ContainerInsights solution addition.

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AKS

**Comment by wangzelin007** [comment]
@ganga1980，
[] means this change is customer-facing and the message will be put into HISTORY.rst.
May I ask whether you want to put this message in release HISTORY.rst ?

**Comment by ganga1980** [comment]
> @ganga1980， [] means this change is customer-facing and the message will be put into HISTORY.rst. May I ask whether you want to put this message in release HISTORY.rst ?

> @wangzelin007 ,  I dont think, this require update to release HISTORY file as this removing of adding unnecessary resource.

**Comment by ganga1980** [comment]
hi, @wangzelin007, @FumingZhang  , can you please review this PR?

**Review by wangzelin007 — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Review by FumingZhang — APPROVED** [review]
LGTM

BTW, we have the same code in aks-preview. Could you please help remove the deployment for csi in that repo?

**Pull request merged**
