### PR TITLE
{IoT} Iot Central Track 2 Changes

### PR DESCRIPTION
**Pull request by abalogun-dev**
**Description**
IoT Central code on Azure Cli Python SDK needs to be updated due to the breaking changes presented in Track 2 version of SDK. 
**Testing Guide**

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ x ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

-  [x  ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ x ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
IoT

**Review by zhoxing-ms — CHANGES_REQUESTED** [review]
@abalogun-dev Could you please run some related tests for this change?

**Comment by zhoxing-ms** [comment]
@abalogun-dev  Please solve the comment in time today, otherwise this PR will miss the release of this sprint and can only be released in the next sprint (about 08-06)

**Comment by abalogun-dev** [comment]
> IoT

sorry, i am not sure what this comment is for, is something being suggested?

**Comment by abalogun-dev** [comment]
> @abalogun-dev Could you please run some related tests in live mode for this change?

do you mean i should run the following commands? 
o	“azdev style iot”
o	“azdev linter iot”
o	“azdev test iot --no-exitfirst”,
 I don't understand what related tests in live mode means, so could you please on expand on your comment

**Comment by zhoxing-ms** [comment]
@abalogun-dev You need to run all the tests that be affected by the modified method in live mode
Such as: `azdev test your_test_case --live`

**Pull request closed without merging**
