### PR TITLE
{Compute} `az vmss create --orchestration-mode flexible`: fix converting `--edge-zone` to template json 

### PR DESCRIPTION
**Pull request by cxznmhdcxz**
**Description**
Fix: https://github.com/Azure/azure-cli/issues/21793

There are two problems with this issue:
1. `--edge-zone` parameter is not converted through `validate_edge_zone`, resulting in the following `InvalidTemplate` error reports:
```
{"error":{"code":"InvalidTemplate","message":"Deployment template parse failed: 'Error converting value "microsoftrrdclab1" to type 'Azure.Deployments.Core.Definitions.Resources.ResourceExtendedLocation'. Path ''.'."}}
```
This PR is used to fix this problem

2. After fixing the first problem, an error will still occur because creating Flex VMSS still does not support edge zone
```
{"code":"BadRequest","message":"{ "error": { "code": "InvalidParameter", "message": "Parameter 'extendedLocation' is not allowed.", "target": "extendedLocation" }}}
```
We have confirmed with the Flex VMSS team @fitzgeraldsteele to keep this behavior and error message first, and wait for the subsequent support from service in Cu semester [comment link](https://github.com/Azure/azure-cli/issues/21793#issuecomment-1092398305)

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Compute

**Review by wangzelin007 — COMMENTED** [review]
Can we add a test for parameter `--edge-zone` ?

**Comment by cxznmhdcxz** [comment]
> Can we add a test for parameter `--edge-zone` ?

Flexible VMSS doesn't support edge zone yet. There exists a test for uniform VMSS `--edge-zone`.

**Review by zhoxing-ms — APPROVED** [review]
@wangzelin007 I have updated the PR description to specifically explain the background of this PR. Please help review it again

**Review by wangzelin007 — APPROVED** [review]

**Pull request merged**
