### PR TITLE
Aladdin generated examples for Role

### PR DESCRIPTION
**Pull request by glGarg**
- Sort commands alphabetically in help files for easy diff.
 - Add Aladdin crafted examples.
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by glGarg** [comment]
Oops sorry accidentally closed it. Restored.

**Comment by tjprescott** [comment]
This now has conflicts that need to be resolved.

**Comment by glGarg** [comment]
I've resolved all the conflicts 😄

**Comment by tjprescott** [comment]
@marstr @yugangw-msft please take a look if these examples look good to you

**Comment by tjprescott** [comment]
ping @marstr @yugangw-msft

**Comment by yugangw-msft** [comment]
LGTM to me at a quick look. Seems like most changes are just about re-ordering

**Comment by tjprescott** [comment]
@yugangw-msft look just as the second commit to see the new examples.

**Comment by yugangw-msft** [comment]
I will merge right after the release branch gets cut out

**Comment by marstr** [comment]
@yugangw-msft, I have cut the `release` branch.

**Comment by yugangw-msft** [comment]
@marstr, no worries, we don't need to include this for the upcoming release

**Pull request merged**
