### PR TITLE
Use list_publishing_credentials to get the SCM URL

### PR DESCRIPTION
**Pull request by Nking92**
Description
---
This is a fix for https://github.com/Azure/azure-cli/issues/4348

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by panchagnula** [comment]
@Nking92 thanks for the change we might need to re-record some tests with this change, Also we wanted to update the web app create command when using docker to take care of the web hook url as well? this one https://github.com/Azure/azure-cli/issues/7261

**Comment by panchagnula** [comment]
@yugangw-msft , is there anyway if Nick can get the changes needed & get the build to pass we can take it for this current Sprint?

**Comment by yugangw-msft** [comment]
if the build can pass in the next hour or so, then we will take for the current release
CC @zikalino

**Comment by panchagnula** [comment]
> if the build can pass in the next hour or so, then we will take for the current release
> CC @zikalino
Thanks @yugangw-msft , for now i marked this for next sprint, so that we can add address this as well #7261 & update the tests as well accordingly.

**Comment by panchagnula** [comment]
@Nking92 is this something we can take care of today to get in this current sprint?

**Comment by Nking92** [comment]
@panchagnula The CI is failing because of 2 tests that need to be recorded. I'll see if I can get them working today. I had some difficulty last time I tried, so I might need some help.

**Comment by yugangw-msft** [comment]
please resolve the merge conflicts

**Pull request merged**
