### PR TITLE
[Compute] support --upload-size in disk creation, support incremental snapshots

### PR DESCRIPTION
**Pull request by qwordy**
Implement #10477 

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by qwordy** [comment]
I haven't modify the history file. Just review the changes I have made.

**Comment by qwordy** [comment]
Any ideas of parameter name? --upload-size should be used together with --for-upload.

**Comment by MyronFanQiu** [comment]
> Any ideas of parameter name? --upload-size should be used together with --for-upload.

However about `--blob-size` since you mentioned the `for uploading blobs` in `--for-upload` argument. I think `--upload-size` is a little bit confusing....

**Comment by ramankumarlive** [comment]
@qwordy -upload-size must be called as -upload-size-bytes otherwise customers might enter a value in Gib. Also, the system will accept this parameter only when disk is create --for-upload

**Pull request closed without merging**
