### PR TITLE
{Packaging} add perl in docker

### LINKED ISSUE #12015: "git add --patch" fails due to missing perl package
### Azure CLI Version
2.0.80

### Expected Behavior
No error

### Actual Behavior
`git: 'add--interactive' is not a git command. See 'git --help'.`

### Steps to Reproduce
```
docker run -it --rm mcr.microsoft.com/azure-cli:2.0.80
bash-5.0# git clone https://github.com/Azure/azure-cli.git
Cloning into 'azure-cli'...
...
bash-5.0# cd azure-cli/
modify any file, e.g. README.md
bash-5.0# git add -p
git: 'add--interactive' is not a git command. See 'git --help'.
```

### Important Factoids
To fix: `apk add --no-cache perl`

### PR DESCRIPTION
**Pull request by fengzhou-msft**
Fix #12015

### CODE REVIEW

**Comment by yonzhan** [comment]
add to S165.

**Comment by haroldrandom** [comment]
Why need perl? 
As I far as I understand, this issue should install perl by he/she self in his/her Dockerfile, it's not a azure-cli requirement.

**Comment by fengzhou-msft** [comment]
> Why need perl?
> As I far as I understand, this issue should install perl by he/she self in his/her Dockerfile, it's not a azure-cli requirement.

The docker doesn't need git either if we just want to run azure-cli.
I guess git was put in the docker for user's convenience, as some git functions rely on perl. We may also put in perl.

**Comment by haroldrandom** [comment]
> > Why need perl?
> > As I far as I understand, this issue should install perl by he/she self in his/her Dockerfile, it's not a azure-cli requirement.
> 
> The docker doesn't need git either if we just want to run azure-cli.
> I guess git was put in the docker for user's convenience, as some git functions rely on perl. We may also put in perl.

Understood, if that so, I would recommend to put `perl` ahead of git since it's more fundamental that git, many other softwares rely on it.

**Pull request merged**
