### PR TITLE
[App Service] `az appservice ase update`: Add `--allow-incoming-ftp-connections` and `--allow-remote-debugging` parameters

### PR DESCRIPTION
**Pull request by bmis**
**Related command**

az appservice ase update

**Description**

Adding two parameters allow-incoming-ftp-connection and allow-remote-debugging to the az appservice ase update command.

**Testing Guide**

This command will enable FTP connections
az appservice ase update -n ase-asedemo-prod-01 -g rg-asedemo-prod-01 --allow-incoming-ftp-connections

This command will enable remote debugging
az appservice ase update -n ase-asedemo-prod-01 -g rg-asedemo-prod-01 --allow-remote-debugging

This command will disable FTP connections
az appservice ase update -n ase-asedemo-prod-01 -g rg-asedemo-prod-01 --allow-incoming-ftp-connections false

This command will disable remote debugging
az appservice ase update -n ase-asedemo-prod-01 -g rg-asedemo-prod-01 --allow-remote-debugging false

**History Notes**

[App Service] `az appservice ase update`: Add `--allow-incoming-ftp-connections` to allow incoming FTP connections 
[App Service] `az appservice ase update`: Add `--allow-remote-debugging` to allow remote debugging

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
App Service

**Review by madsd — APPROVED** [review]
LGTM

**Comment by zhoxing-ms** [comment]
Could you add some scenario tests for these new parameters?

**Comment by bmis** [comment]
> Could you add some scenario tests for these new parameters?

I added to this test test_app_service_environment_update_asev3. If we need to add any additional tests, please let me know.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
