### PR TITLE
[App Service] `az staticwebapp create`: Add new parameter `--login-with-ado` to create azure dev ops token automatically

### PR DESCRIPTION
**Pull request by StrawnSC**
**Related command**

`az staticwebapp create` 

**Description**

In the `az staticwebapp create` command, we currently allow the user to create a SWA from a GitHub repo without passing in a token by using the `--login-with-github` parameter to generate one automatically (by logging in via a web browser). This PR adds an equivalent parameter, `--login-with-ado`, which uses the user's azure credentials to create an azure dev ops token automatically (no actions in a web browser required) 

**Testing Guide**

Create a static web app from an ADO repo without specifying the token
`az staticwebapp create --source <ADO repo link> -b <branch> --login-with-ado -g <> -n <>`

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
staticwebapp

**Comment by StrawnSC** [comment]
@zhoxing-ms, I'm not sure why the check "Verify src/azure-cli/requirements.py3.Darwin.txt" is failing. I didn't modify the src/azure-cli/requirements.py3.Darwin.txt file in this PR 

Do you know what's going on there?

**Comment by zhoxing-ms** [comment]
@StrawnSC I rerun the CI pipeline, could you please add some tests for the new parameter?

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
