### PR TITLE
[App Service] `az webapp list-runtimes`: Support node 16-lts runtime for linux and windows 

### PR DESCRIPTION
**Pull request by StrawnSC**
**Description**

See title 

**Testing Guide**

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by panchagnula** [comment]
Thanks @StrawnSC can you check if we need the same update on functions runtime stack as well or is it just for Webapps?

**Comment by StrawnSC** [comment]
@panchagnula no function apps change is needed -- the node 16 stack is already in the CLI for function apps and is still in preview on the portal

**Review by panchagnula — APPROVED** [review]
LGTM! Do we need to add a test case specific to this version.

**Comment by yonzhan** [comment]
App Service

**Review by wangzelin007 — APPROVED** [review]

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
