### PR TITLE
[Storage] `az storage file upload-batch`: Allow uploading files in parallel to improve performance

### PR DESCRIPTION
**Pull request by pateljay43**
**Related command**

`az storage file upload-batch`

**Description**

- Why this PR?
  - Resolved a pending TODO for improving performance.
- What is changed?
  - Uploading files in batch in parallel. 
- What is the effect?
  - Faster `az storage file upload-batch` command execution depending on `--max-connections` argument. 

**Testing Guide**

- Default: 1 thread worker for uploading one file at a time.
  - `az storage file upload-batch -s "source" -d "destination" --account-name "storage_account_name" --account-key "storage_account_access_key"`
- Parallel: `--max-connections 4` argument -> 4 thread worker -> each worker uploading one file at a time .
  - `az storage file upload-batch -s "source" -d "destination" --account-name "storage_account_name" --account-key "storage_account_access_key" --max-connections 4`

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Storage

**Comment by pateljay43** [comment]
@microsoft-github-policy-service agree company="UiPath"

**Comment by pateljay43** [comment]
> @pateljay43 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
>  > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree company="UiPath"

**Comment by calvinhzy** [comment]
Can you add some tests as well as fix the PR description based on the CI error? If you can link other issues that were making the feature update, that would be helpful as well.

**Comment by pateljay43** [comment]
> Can you add some tests as well as fix the PR description based on the CI error? If you can link other issues that were making the feature update, that would be helpful as well.

1. There was an issue with the PR title and I already updated my PR title.
2. I was not able to find any issues related to my change.
3. I didn't find any guide on writing test. can you please share it with me?

**Comment by calvinhzy** [comment]
There are tests for uploading batch, https://github.com/Azure/azure-cli/blob/00a31dce8f804b9210227b79e2043ae48e0c5e13/src/azure-cli/azure/cli/command_modules/storage/tests/latest/test_storage_batch_operations.py#L227 
Since you have changed the function call completely, need to add a new test case with --max-connections, just add a section at the end of existing test and make sure the existing tests all run successfully.

**Comment by pateljay43** [comment]
@calvinhzy I have updated tests. can you please review this PR?

**Comment by pateljay43** [comment]
> @calvinhzy I have updated tests. can you please review this PR?

cc @jsntcy @zhoxing-ms @evelyn-ys

**Review by calvinhzy — APPROVED** [review]
Test run successfully with --live locally

**Pull request merged**
