### PR TITLE
{Compute} Regenerating SSHKEY code and repairing

### PR DESCRIPTION
**Pull request by qwordy**
**Description**

Rewrite `readme.az.md` and keep `generated` code unmodified.

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Review by yungezz — APPROVED** [review]

**Comment by fengzhou-msft** [comment]
Do you have tests for `sshkey`?

**Comment by qwordy** [comment]
> 
> 
> Do you have tests for `sshkey`?

Yes, I do.

**Review by fengzhou-msft — APPROVED** [review]

**Comment by fengzhou-msft** [comment]
Do you have a PR to update the `readme.az.md` in `azure-rest-api` repo?

**Comment by qwordy** [comment]
> 
> 
> Do you have a PR to update the `readme.az.md` in `azure-rest-api` repo?

https://github.com/Azure/azure-rest-api-specs/pull/13436

**Pull request merged**
