### PR TITLE
[Event Grid] Fix #21521: System topic subscription update attribute error

### LINKED ISSUE #21521: system topic subscription update causes error: 'ServiceBusTopicEventSubscriptionDestination' object has no attribute 'destination'`
**Describe the bug**

Trying to call `az eventgrid system-topic event-subscription update` causes error `AttributeError: 'ServiceBusTopicEventSubscriptionDestination' object has no attribute 'destination'`

**To Reproduce**

1. Create a system topic on a storage account.
2. Create a subscription to that topic. In my use case, I was delivering to a service bus topic with a managed identity access.
3. Run `az eventgrid system-topic event-subscription update --name mysubscription--resource-group myrg --system-topic-name mysystemtopic --delivery-attribute-mapping label dynamic subject`

**Expected behavior**

Delivery property is added with `label` using dynamic type and has the value of `subject`

**Actual behavior**

```
The command failed with an unexpected error. Here is the traceback:
'ServiceBusTopicEventSubscriptionDestination' object has no attribute 'destination'
Traceback (most recent call last):
  File "/opt/az/lib/python3.8/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 658, in execute
    raise ex
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 692, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/eventgrid/custom.py", line 1198, in cli_system_topic_event_subscription_update
    params = _update_event_subscription_internal(
  File "/opt/az/lib/python3.8/site-packages/azure/cli/command_modules/eventgrid/custom.py", line 1378, in _update_event_subscription_internal
    current_destination_with_resource_identity.destination,
AttributeError: 'ServiceBusTopicEventSubscriptionDestination' object has no attribute 'destination'
```

**Environment summary**

```
azure-cli                         2.34.1

core                              2.34.1
telemetry                          1.0.6

Extensions:
azure-iot                         0.13.0

Dependencies:
msal                              1.16.0
azure-mgmt-resource               20.0.0

Python location '/opt/az/bin/python3'
Extensions directory '/home/ken/.azure/cliextensions'

Python (Linux) 3.8.12 (default, Mar  2 2022, 07:26:21) 
[GCC 9.3.0]
```

**Additional context**

### PR DESCRIPTION
**Pull request by ahamad-MS**
**Description**

The fix here is to address a customer reported issue https://github.com/Azure/azure-cli/issues/21521  when trying to update an event subscription with system managed idenity

The issue was due to using wrong vatiable

**Testing Guide**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [X] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [X] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by navba-MSFT** [comment]
Fixes #21521

**Comment by yonzhan** [comment]
Event Grid

**Comment by navba-MSFT** [comment]
@evelyn-ys @calvinhzy This is waiting for your approval. Could you please review this and merge once you get a chance ? 
**cc:** @ahamad-MS

**Review by calvinhzy — APPROVED** [review]

**Comment by navba-MSFT** [comment]
Thanks @calvinhzy for approving this PR. Please merge this PR once the tests are successful.

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
