### PR TITLE
{Service Fabric} Bump Python SDK version

### PR DESCRIPTION
**Pull request by mwesigwaguma**
Also removing unsupported parameters Precision and Mode
**Related command**

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Service Fabric

**Comment by zhoxing-ms** [comment]
@mwesigwaguma Could you please resolve these CI issuses?

**Comment by mwesigwaguma** [comment]
> @mwesigwaguma Could you please resolve these CI issues?

I am seeing this error where after the test runs and passes in live mode but in playback they fail. 
It seems to be a the testframework issue

except CannotOverwriteExistingCassetteException as ex:
>           raise AssertionError(ex)
E           AssertionError: Can't overwrite existing cassette ('/mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/recordings/test_update_settings_and_reliability.yaml') in your current record mode ('once').
E           No match for the request (<Request (GET) [https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.KeyVault/vaults/clitestrg000001?api-version=2023-02-01>](https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.KeyVault/vaults/clitestrg000001?api-version=2023-02-01%3E)) was found.
E           Found 3 similar requests with 1 different matcher(s) :

**Comment by mwesigwaguma** [comment]
Hi,

I am seeing this error <https://dev.azure.com/azclitools/public/_build/results?buildId=123946&view=logs&jobId=8b87d530-5472-5986-1c88-cfbbd7928469&j=8b87d530-5472-5986-1c88-cfbbd7928469&t=11cc7245-08a2-5894-29fb-f5b6001226e6> where after the test runs and passes in live mode but in playback they fail.
It seems to be a the testframework issue



except CannotOverwriteExistingCassetteException as ex:

      raise AssertionError(ex)


E AssertionError: Can't overwrite existing cassette ('/mnt/vss/_work/1/s/src/azure-cli/azure/cli/command_modules/servicefabric/tests/latest/recordings/test_update_settings_and_reliability.yaml') in your current record mode ('once').

E No match for the request (<Request (GET) https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.KeyVault/vaults/clitestrg000001?api-version=2023-02-01><https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/clitest.rg000001/providers/Microsoft.KeyVault/vaults/clitestrg000001?api-version=2023-02-01%3E>) was found.

E Found 3 similar requests with 1 different matcher(s) :

________________________________

**Comment by yonzhan** [comment]
Please fix conflicting files.

**Comment by mwesigwaguma** [comment]
> Please fix conflicting files.

updated

**Comment by yonzhan** [comment]
Please fix CI issues.

**Comment by zhoxing-ms** [comment]
@mwesigwaguma Any update?

**Comment by yanzhudd** [comment]
Please note that we'll have a code freeze at 02/27/2024 10:00 UTC. Please address all the comments by that time, otherwise it has to be postponed to next sprint (next release train: 04-02).

**Comment by jsntcy** [comment]
@evelyn-ys, do you know why errors happen to key vault requests?

**Comment by mwesigwaguma** [comment]
@Yishi ***@***.***> Can you please take a look at this issue : Azure/azure-cli: Azure Command-Line Interface (github.com)<https://github.com/Azure/azure-cli/issues/28283>
This is blocking a lot of other items including bugs that are affecting customers.

Thanks,
Guma
________________________________

**Comment by evelyn-ys** [comment]
Please sync with latest `dev` branch and run `azdev setup -c` again before re-recording tests

**Review by evelyn-ys — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
@mwesigwaguma Could you please resolve these conflicts?

**Review by a-santamaria — APPROVED** [review]

**Review by a-santamaria — APPROVED** [review]

**Comment by zhoxing-ms** [comment]
> @mwesigwaguma Could you please resolve these conflicts?

@mwesigwaguma  Any update?

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
