### PR TITLE
{appservice} Fix exception in functionapp ssl bind

### LINKED ISSUE #21237: FunctionApp:`az functionapp config ssl bind` returns error saying webapp not found
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**
Running `az functionapp config ssl bind` returns error even if functionapp exists
image

**To Reproduce**
`az functionapp config ssl bind`

**Expected behavior**
Expected not to error

**Environment summary**
Happens in az cli version 2.33.0+

### PR DESCRIPTION
**Pull request by calvinsID**
**Description**
Fixes #21237 21237

**Testing Guide**
`az functionapp config ssl bind` throws app not found error

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change.
[Component Name 2] `az command b`: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
functionapp

**Comment by panchagnula** [comment]
Can we add a test case for functionapp bind  scenario?

**Review by panchagnula — CHANGES_REQUESTED** [review]
Add test case please.

**Review by StrawnSC — APPROVED** [review]
Fixes https://github.com/Azure/azure-cli/issues/21237 for me when I try it. Thanks for taking care of this!

**Comment by wangzelin007** [comment]
@calvinsID,
image

**Comment by calvinsID** [comment]
Closing due to @panchagnula fixing in another PR

**Pull request closed without merging**
