### PR TITLE
[Monitor] `az monitor log-analytics workspace table`: Add new command `restore create` and `migrate`  to support Restored logs table/migrate operations

### PR DESCRIPTION
**Pull request by PARADISSEEKR**
**Description**

workspace table operation https://github.com/Azure/azure-cli/issues/20903

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change.
[Component Name 2] `az command b`: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Monitor

**Review by wangzelin007 — CHANGES_REQUESTED** [review]
Please add some tests for these new commands.

**Comment by PARADISSEEKR** [comment]
> Please add some tests for these new commands.

Unable to test for special reasons.
image

**Review by jsntcy — APPROVED** [review]

**Review by necusjz — APPROVED** [review]

**Review by wangzelin007 — APPROVED** [review]

**Pull request merged**
