### PR TITLE
{Misc.} Replace NBSP with normal ASCII space

### PR DESCRIPTION
**Pull request by jiasli**
**Description**

For unknown reason, https://github.com/Azure/azure-cli/pull/15998 added NBSP ([Non-breaking space U+00A0](https://en.wikipedia.org/wiki/Non-breaking_space)) to `scripts/release/debian/deb_install.sh`

PyCharm:

image

VS Code:

image

This leads to display issue in Edge browser:

https://azurecliprod.blob.core.windows.net/$root/deb_install.sh

image

This PR replaces NBSP with normal ASCII space.

We've seen this issue before:

- https://github.com/Azure/azure-cli/pull/19442
- https://github.com/Azure/azure-cli/pull/8785

### CODE REVIEW

**Comment by yonzhan** [comment]
Packaging

**Comment by bebound** [comment]
There are also some NBSP under `src` path, should we also replace them?

For example:  `src/azure-cli/azure/cli/command_modules/appservice/custom.py`
Screen Shot 2022-05-09 at 12 20 52

**Comment by jiasli** [comment]
> There are also some NBSP under `src` path, should we also replace them?
> 
> For example: `src/azure-cli/azure/cli/command_modules/appservice/custom.py` Screen Shot 2022-05-09 at 12 20 52

Nice catch!

https://github.com/Azure/azure-cli/blob/c2bffb8bef23728919fe8a315ef7553b103ec393/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L2719

https://github.com/Azure/azure-cli/blob/c2bffb8bef23728919fe8a315ef7553b103ec393/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L2730

They are added by #21309.

**Comment by bebound** [comment]
I found more special character in our source code.

`doc/azure2az_commands.rst` and `doc/authoring_command_modules/README.md` contains NBSP
`src/azure-cli/HISTORY.rst` contains NBSP & ZWSP

If this possible to create some rules to prevent these characters being merged?

**Comment by jiasli** [comment]
I searched across the project but have no idea why PyCharm didn't find them. 🤔 I purged the cache, and it works now. Fixed everywhere.

> There are so many unicode whitespace characters. If this is possible to create some rules to prevent these characters being merged?

Surely we can. I am just curious how they are inserted in the first place!

**Comment by jsntcy** [comment]
Use non-breaking spaces instead of regular spaces when you don't want Word to break a line at a certain space. Is it possible some of them are added for specific purpose, for example, avoid to break command into multiple lines?
@jiasli

**Review by wangzelin007 — APPROVED** [review]

**Review by calvinhzy — APPROVED** [review]

**Review by bebound — APPROVED** [review]

**Review by jsntcy — APPROVED** [review]

**Comment by jiasli** [comment]
> Is it possible that some of them were added for specific purpose, for example, avoid to break command into multiple lines?

These are not valid scenarios, since line breaks are acceptable. We can resume our investigation once we see more occurrences.

**Pull request merged**
