### PR TITLE
Make argument parameters match up.

### PR DESCRIPTION
**Pull request by brendandburns**
@tjprescott

### CODE REVIEW

**Comment by brendandburns** [comment]
fwiw, this appears to be an unrelated failure:

```
FAILED (errors=1)
Coverage.py warning: No data was collected.
Coverage.py warning: No data was collected.
Coverage.py warning: No data was collected.
Coverage.py warning: No data was collected.
Coverage.py warning: No data was collected.
Coverage.py warning: No data was collected.
Coverage.py warning: No data was collected.
Coverage.py warning: No data was collected.
Coverage.py warning: No data was collected.
Coverage.py warning: No data was collected.
Coverage.py warning: No data was collected.
==== Test module azure-cli-core result ====
/home/travis/build/Azure/azure-cli/test_results/tests_20170403_163113/nosetests-report.xml
==========
```

**Comment by tjprescott** [comment]
The error isn't unrelated. You are essentially trying to alias the lock name and the resource name to --name/-n. In this case it should refer to the lock, so --resource-name is fine. 

```
argparse.ArgumentError: argument --name/-n: conflicting option strings: --name, -n
```

**Comment by brendandburns** [comment]
Thanks for finding that. (The error looks are pretty spammy...)

Why is that an error in cli.core? That is what confused me.

--brendan


________________________________

**Comment by tjprescott** [comment]
That test basically runs `az -h`, which results in all of the help files being loaded. That results in all of the help-related validation being run on all of the commands.

**Pull request merged**
