### PR TITLE
{SQL VM} Update Python SDK to 1.0.0b3

### PR DESCRIPTION
**Pull request by rchlkm**
**Related command**

**Description**

Released Python package 1.0.0b3 for SQL VM 2021-11-01-preview on 6/5/2022.
This API update renamed the following enum values: AssessmentDayOfWeek, AutoBackupDaysOfWeek.
This PR has no custom facing breaking changes, as it only updates the enum value reference for AssessmentDayOfWeek.
We have yet to implement CLI commands for AutoBackupDaysOfWeek, so this enum value is untouched in this PR.

Related links:
https://github.com/Azure/sdk-release-request/issues/2871
https://pypi.org/project/azure-mgmt-sqlvirtualmachine/1.0.0b3/

**Testing Guide**

```
> azdev test sqlvm 
```
Confirmed `Everyday` is no longer an accepted value for assessment-day-of-week
```
> az sql vm update -g <TESTRG> -n <TESTVM> --assessment-day-of-week Everyday --assessment-weekly-interval 3 –-assessment-start-time-local "23:00"
az sql vm update: 'Everyday' is not a valid value for '--assessment-day-of-week'. Allowed values: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday.
```

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
SQL VM

**Comment by rchlkm** [comment]
@evelyn-ys Could you help me understand why `azdev test` keeps failing with this error? What should I do to unblock this PR?
`"code":"DeploymentFailed","message":"At least one resource deployment operation failed."`

**Comment by evelyn-ys** [comment]
It fails in `SqlVmAndGroupScenarioTest.test_sqlvm_add_and_remove`:
https://github.com/Azure/azure-cli/blob/33cbd01f75c7d4c3814de5a1cbf6f42de7890467/src/azure-cli/azure/cli/command_modules/sqlvm/tests/latest/test_sqlvm_commands.py#L627

Maybe you have to check what's wrong with your scenario test

**Comment by evelyn-ys** [comment]
Can `test_sqlvm_add_and_remove` pass in live run with the original package version?

**Comment by evelyn-ys** [comment]
duplicated with #23035

**Pull request closed without merging**
