### PR TITLE
{ACR} Update Storage SDK used for uploading source in ACR

### PR DESCRIPTION
**Pull request by cormacpayne**
**Related command**

`az acr build`
`az acr pack build`
`az acr run`
`az acr task run`

**Description**

Corresponding PR in `azure-cli-extensions` repository for `containerapp` module: https://github.com/Azure/azure-cli-extensions/pull/6313

The `az containerapp up` command contains multiple flows that call the [`upload_source_code`](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/_archive_utils.py#L22) function to push user-provided application source code to a Storage blob that an ACR Build/Task would then be executed against. However, while writing tests against these flows, I found that an exception was being thrown when the Storage blob client was trying to upload the source, and the exception _only_ ever said `utf8`. This issue only occurred within the test suite and never with live runs of the command.

I looped in the Storage SDK for Python folks and they recommended updating the Storage SDK from V1 (`ResourceType.DATA_STORAGE`) to V2 (`ResourceType.DATA_STORAGE_BLOB`), which is the change being made in this PR (and the `containerapp` PR linked above). There is still a flow within the `az containerapp up` command that relies on the `acr` module and its `upload_source_code` function directly (through the `acr_task_run` function), so the intent of this PR is to update the Storage SDK here to re-enable the tests for this `containerapp` flow in the other repository.

The related commands I listed above are the ones I found that call the `upload_source_code` function that is being updated, but if there are any other instances that I may have missed, please let me know.

_Note_: there is another case of this outdated Storage SDK being used in the [`_stream_utils.py`](https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/acr/_stream_utils.py#L55) file, but I didn't update the `stream_logs` function that it's used in as a part of this PR.

**Testing Guide**

I have live-only tests for the `az containerapp up` scenario in the other repository's PR, but if there are any tests you'd like for me to introduce in this PR, please let me know (I haven't had a chance to dive too deep into the existing `acr` test coverage).

**History Notes**

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
ACR

**Comment by jsntcy** [comment]
@cormacpayne, please fix the CI error first.

**Comment by cormacpayne** [comment]
@jsntcy -- just pushed a commit to remove the unused import that was failing style checks 👍

**Comment by zhoxing-ms** [comment]
@cormacpayne Could you please re-run some related tests in live mode to ensure this PR change is in line with expectations?

**Comment by cormacpayne** [comment]
@zhoxing-ms -- Hey Xing, I just refreshed the recordings for existing tests using commands that would be affected by this change. Please feel free to let me know if there's anything else required on my side.

**Review by zhoxing-ms — APPROVED** [review]

**Pull request merged**
