### PR TITLE
[IoT] include IoT module in install script

### PR DESCRIPTION
**Pull request by xscript**
Include IoT module in install script. Also bump to the latest build which contains the IoT module.

### CODE REVIEW

**Comment by derekbekoe** [comment]
The install script modified in the PR is for the set of packages that will be pulled down by default when the user installs the CLI.

If a module isn't included by default, it can still be installed by the user.
For example with the following command:
`az component install -n iot -p`

I would suggest that we leave the `iot` module as something that can be installed but isn't included by default at this time.

cc @JasonRShaver

**Comment by xscript** [comment]
@derekbekoe It is fine to exclude IoT from default install. I've reverted that part.
But 2016.08.02.nightly build is already out of date. Users would have to update all other modules before they can install the IoT module.
So I still keep the version bump in the install guide for Windows. Any concern?
If version bump is acceptable, someone needs to help do the same for Linux install script.
Thanks!

**Comment by derekbekoe** [comment]
@xscript, in PR #828, we remove the need to specify a nightly build version when installing so setting the environment variable `AZURE_CLI_NIGHTLY_VERSION` would be no longer needed.

**Comment by xscript** [comment]
@derekbekoe great! I am closing this PR.

**Pull request closed without merging**
