### PR TITLE
{Storage} `az storage fs directory/file move`: Fix typo in ADLS Gen2.md

### PR DESCRIPTION
**Pull request by koudaiii**
Typo `mymewfilesystem` -> `mynewfilesystem`

**Related command**

**Description**

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Thank you for your contribution! We will review the pull request and get back to you soon.

**Review by yonzhan — APPROVED** [review]

**Comment by yonzhan** [comment]
Please fix CI issues.

**Comment by koudaiii** [comment]
@yonzhan Thank you for review. I'll try it 😄

**Comment by koudaiii** [comment]
I checked in https://github.com/Azure/azure-cli/blob/7a4d03f077151be8fc312c9ce82febd1dda118cb/azure-pipelines.yml#L31-L51

## self-check

```console
$ curl https://api.github.com/repos/Azure/azure-cli/pulls/27889 | jq -r '.title'
{Storage} Fix the typo from mymewfilesystem to mynewfilesystem in ADLS Gen2.md

$ curl https://api.github.com/repos/Azure/azure-cli/pulls/27889 | jq -r '.body' 
Typo `mymewfilesystem` -> `mynewfilesystem`
....


$ title=$(curl https://api.github.com/repos/Azure/azure-cli/pulls/27889 | jq -r '.title')
$ body=$(curl https://api.github.com/repos/Azure/azure-cli/pulls/27889 | jq -r '.body')
$ python3 scripts/ci/check_pull_request.py $title $body
Start check pull request ...

```

passed

**Review by calvinhzy — APPROVED** [review]

**Pull request merged**
