### PR TITLE
[Containerapp] `az containerapp revision copy`: Fix `--from-revision` bug for inheriting a specific revision contains scale rules

### PR DESCRIPTION
**Pull request by Greedygre**
**Related command**

`az containerapp revision copy`

**Description**

Fix https://github.com/Azure/azure-cli-extensions/issues/5435

**Testing Guide**

**History Notes**

[Component Name 1] BREAKING CHANGE: `az command a`: Make some customer-facing breaking change
[Component Name 2] `az command b`: Add some customer-facing feature

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
Containerapp

**Comment by Greedygre** [comment]
Hi @zhoxing-ms @yanzhudd 

The tests failed:
FAILED src/azure-cli/azure/cli/command_modules/sql/tests/latest/test_sql_commands.py::SqlManagedInstanceExternalGovernanceTest::test_sql_mi_refresh_external_governance_status

Could you help to handle it when you have chance? Thanks.

**Comment by Greedygre** [comment]
Hi @zhoxing-ms @yanzhudd @wangzelin007 

The Azure.azure-cli (Test Extensions Loading Python311) failed with following error:
`ERROR: The checksum of the extension does not match the expected value. Use --debug for more information.
`
Can you have to handle when you have chance? Thanks.

**Comment by yanzhudd** [comment]
> Hi @zhoxing-ms @yanzhudd @wangzelin007
> 
> The Azure.azure-cli (Test Extensions Loading Python311) failed with following error: `ERROR: The checksum of the extension does not match the expected value. Use --debug for more information. ` Can you have to handle when you have chance? Thanks.

Rerunning that failed item can work, and now it passes

**Comment by Greedygre** [comment]
Hi @Juliehzl 

Can you help to review this PR? Thanks.

**Review by Juliehzl — APPROVED** [review]

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
