### PR TITLE
[ARM] az group deployment create: Fix "stat: path too long for Windows" error when using large parameters.json file (#11646)

### PR DESCRIPTION
**Pull request by zhoxing-ms**
Fix issue: #11646

When the prefix of the `--paramters` parameter passed in is `@`, the JSON data will be loaded ahead of time by `_pre_command_table_create()`.
Later in the process, `os.path.isfile()` is called to determine whether the JSON data is a file name . 
When the length of the JSON data is too long, `os.stat()` will have an error of "stat: path too long for Windows" (belonging to ValueError). 
In Python 3.8, the ValueError would be caught, whereas in versions before 3.6, it will make a direct error.
So add the logic to catch ValueError in order to compatible with the older versions of Python.

**History Notes:**  
(Fill in the following template if multiple notes are needed, otherwise PR title will be used for history note.)

[Component Name 1] (BREAKING CHANGE:) (az command:) make some customer-facing change.  
[Component Name 2] (BREAKING CHANGE:) (az command:) make some customer-facing change.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by Juliehzl** [comment]
A small question here is that "path too long" is caused by file name or file content size?

**Comment by zhoxing-ms** [comment]
> A small question here is that "path too long" is caused by file name or file content size?

@Juliehzl The prefix of the filename contains `@` and the contents of the file are too large will cause this problem.

**Comment by Juliehzl** [comment]
> > A small question here is that "path too long" is caused by file name or file content size?
> 
> @Juliehzl The prefix of the filename contains `@` and the contents of the file are too large will cause this problem.

What about no `@` in parameter value? From my previous understanding, `@` is just used to help find file path in some scenario. And eventually they will call the same load file function. So I think it should also have the same error although there is no `@` in parameter value. Is it right?

**Comment by zhoxing-ms** [comment]
> What about no @ in parameter value? From my previous understanding, @ is just used to help find file path in some scenario. And eventually they will call the same load file function. So I think it should also have the same error although there is no @ in parameter value. Is it right?

@Juliehzl There is no problem if the prefix of the parameter does not contain `@`, because when `os.path.isfile(value)` is called in `_process_parameters()`, the value is a filename.
But when the parameter prefix is `@`, the contents of the file are loaded ahead of time by `_pre_command_table_create()`. Then in the `_process_parameters()` process, `os.path.isfile(value)` is used to determine if the value is a filename, at which point the value has become the contents of the file.

**Pull request merged**
