### PR TITLE
[App Service] Fix #14701: implement functionapp create --assign-identity

### LINKED ISSUE #14701: functionapp create --assign-identity not implemented
> ### `az feedback` auto-generates most of the information requested below, as of CLI version 2.0.62

**Describe the bug**

Missed implementation of "az functionapp create **--assign-identity**"  in PR https://github.com/Azure/azure-cli/pull/14233

**To Reproduce**

**Expected behavior**

**Environment summary**

**Additional context**

### PR DESCRIPTION
**Pull request by cxznmhdcxz**
**Description**  

fix issue: https://github.com/Azure/azure-cli/issues/14701
This PR implements  `az functionapp create --assign-identity`
No tests added, since identity assigning of functionapp and webapp is calling exactly the same implementation.

**Testing Guide**  

**History Notes**  

[Component Name 1] BREAKING CHANGE: az command a: Make some customer-facing breaking change.  
[Component Name 2] az command b: Add some customer-facing feature.

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
functionapp

**Comment by jongio** [comment]
@cxznmhdcxz @tzhanl - I looked at the code, but I'm not sure how the --assign-identity parameter will surface on the command without explicitly adding it.  Can you verify that the parameter is there and help is rendered for it when I `az functionapp create -h`

**Comment by cxznmhdcxz** [comment]
>  I looked at the code, but I'm not sure how the --assign-identity parameter will surface on the command without explicitly adding it. Can you verify that the parameter is there and help is rendered for it when I `az functionapp create -h`

@jongio I checked, and it's all good. Code about parameters mapping is already updated in the last PR.

**Comment by yungezz** [comment]
ADO pipeline result https://github.com/Azure/azure-cli/pull/14702/checks?check_run_id=991745040 all passed, but not reflected in github. Merge this PR.

**Pull request merged**
