### PR TITLE
Update Batch cli to use latest python SDK.

### PR DESCRIPTION
**Pull request by xingwu1**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by promptws** [comment]
View a preview at https://prompt.ws/r/Azure/azure-cli/5924
This is an **experimental preview** for @microsoft users.

**Comment by xingwu1** [comment]
@annatisch Could you review the change?

**Comment by annatisch** [comment]
@xingwu1 - LGTM
I guess you ran generate_full_cli_help.bat to confirm that the other commands remained consistent after the regex change?

**Comment by xingwu1** [comment]
@annatisch Add 2 help.txt files. The diff result looks good.

**Comment by xingwu1** [comment]
@tjprescott @derekbekoe @troydai  can anyone review my PR?

**Comment by xingwu1** [comment]
@derekbekoe could you merge it? BTW, what is next release time?

**Comment by derekbekoe** [comment]
Next public release is 4/10 - https://github.com/Azure/azure-cli/milestone/37

**Pull request merged**
