### PR TITLE
[SQL] `az sql server audit-policy show`: Add `isManagedIdentityInUse` info in output

### PR DESCRIPTION
**Pull request by IliasKhan**
**Related command**
`az sql server audit-policy show`
``

**Description**
We have updated blob auditing api to new `2021-08-11`, we have added an extra parameter `isManagedIdentityInUse`.
**Testing Guide**
running `az sql server audit-policy show` you should see an extra parameter `isManagedIdentityInUse`

**History Notes**

[SQL] `az sql server audit-policy show`: Add `isManagedIdentityInUse` info in output

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by evelyn-ys** [comment]
After bumping version, please re-record all related tests

**Comment by IliasKhan** [comment]
> After bumping version, please re-record all related tests

For my current PR, I just updated new version of SDK and don't have much changes..
Still for test_sql_db_replica_mgmt showing `Internal server error`..all other tests are passing..

Is this error known?

```
E           azure.core.exceptions.HttpResponseError: (InternalServerError) An unexpected error occured while processing the request. Tracking ID: 'cc0b5b09-2f90-4ffc-88af-db16b0b800c2'
E           Code: InternalServerError
E           Message: An unexpected error occured while processing the request. Tracking ID: 'cc0b5b09-2f90-4ffc-88af-db16b0b800c2'


 
D:\env\lib\site-packages\azure\core\polling\base_polling.py:523: HttpResponseError
FAILED src\azure-cli\azure\cli\command_modules\sql\tests\latest\test_sql_commands.py::SqlServerDbReplicaMgmtScenarioTest::test_sql_db_replica_mgmt - azure.core.exception.
```

**Comment by evelyn-ys** [comment]
Sorry this seems to be server error should reach out to service team

**Comment by evelyn-ys** [comment]
Please make sure all CI pass

**Review by evelyn-ys — APPROVED** [review]

**Review by evelyn-ys — CHANGES_REQUESTED** [review]
Why `SqlServerDbReplicaMgmtScenarioTest` has been fully commented out?

**Comment by IliasKhan** [comment]
> Why `SqlServerDbReplicaMgmtScenarioTest` has been fully commented out?

This test record is not running as Replication Links API has some bug. Old version of this api also not working. That's why old record is not passing as well. Geo-Dr team is working on [this PR](https://msdata.visualstudio.com/Database%20Systems/_git/38da4503-59cd-469b-ad0b-a2ee2b33afed/pullrequest/878719?path=%2FSql%2Fxdb%2Fmanifest%2Fsvc%2Fmgmt%2Fworkflows%2FManagementWorkflows.cs).

**Review by evelyn-ys — APPROVED** [review]

**Pull request merged**
