### PR TITLE
[ACR] `az acr create`: Add validation for registry name to support domain name label

### PR DESCRIPTION
**Pull request by trisavo-msft**
**Related command**

az acr create 
**Description**

[PRD Link](https://microsoft.sharepoint.com/:w:/r/teams/AzureContainerRegistry/_layouts/15/doc2.aspx?sourcedoc=%7B43C3346D-2EE3-4118-BC93-9389E09D1D8E%7D&file=[ACR-Deterministic-Naming-Library-DNL.docx](https://microsoft.sharepoint.com/:w:/r/teams/AzureContainerRegistry/_layouts/15/doc2.aspx?sourcedoc=%7B43C3346D-2EE3-4118-BC93-9389E09D1D8E%7D&file=ACR-Deterministic-Naming-Library-DNL.docx&action=default&mobileredirect=true&DefaultItemOpen=1)&action=default&mobileredirect=true&DefaultItemOpen=1)

The aim is to allow users to add a domain name label hash to their registry login server to prevent domain takeovers, such as "myacr-dnlhash123.azurecr.io". For CLI, this means users must be able to reference their registry in 3 ways: 

```
az acr login -n myacr
az acr login -n myacr-dnlhash123
az acr login -n myacr-dnlhash123.azurecr.io
```

1. Allow '-' character when referring to registry name "-n" or "--name" 
2. If referring to registry name using "az acr create" function, block '-' character. The '-' is automatically added if a user wants to use domain name label hash. This feature will be implemented in a later PR. 

**Testing Guide**

Added three unit tests.
azdev test acr.test_acr_create_invalid_name --live --discover 
azdev test acr.test_registry_name_with_dnl_suffix --live --discover 
azdev test test_registry_name_with_dnl_suffix_loginserver --live --discover 
**History Notes**

[ACR] Add validation for registry name to support domain name label

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Review by nhu1997 — COMMENTED** [review]
Is this a new restriction or a missing validation? Any spec talks about the requirements?

**Review by rosanch — APPROVED** [review]
LGTM

**Comment by yanzhudd** [comment]
> @trisavo-msft please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@trisavo-msft please reply with this information

**Comment by trisavo-msft** [comment]
> Is this a new restriction or a missing validation? Any spec talks about the requirements?
[PRD Link](https://microsoft.sharepoint.com/:w:/r/teams/AzureContainerRegistry/_layouts/15/doc2.aspx?sourcedoc=%7B43C3346D-2EE3-4118-BC93-9389E09D1D8E%7D&file=[ACR-Deterministic-Naming-Library-DNL.docx](https://microsoft.sharepoint.com/:w:/r/teams/AzureContainerRegistry/_layouts/15/doc2.aspx?sourcedoc=%7B43C3346D-2EE3-4118-BC93-9389E09D1D8E%7D&file=ACR-Deterministic-Naming-Library-DNL.docx&action=default&mobileredirect=true&DefaultItemOpen=1)&action=default&mobileredirect=true&DefaultItemOpen=1)

Yes, the aim is to allow users to add a domain name label hash to their registry login server to prevent domain takeovers, such as "myacr-dnlhash123.azurecr.io". For CLI, this means users must be able to reference their registry in 3 ways: 

```
az acr login -n myacr
az acr login -n myacr-dnlhash123
az acr login -n myacr-dnlhash123.azurecr.io
```

**Comment by trisavo-msft** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Review by rosanch — APPROVED** [review]
LGTM Just please review the PR Notes

**Comment by trisavo-msft** [comment]
@yanzhudd Is there anything else needed from this PR? The Azure CLI tests are not running.

**Comment by yanzhudd** [comment]
> @yanzhudd Is there anything else needed from this PR? The Azure CLI tests are not running.

We need to trigger the CI manually for now due to security issues.

**Comment by trisavo-msft** [comment]
@zhoxing-ms

**Comment by yanzhudd** [comment]
Is this PR ready to review/merge?

**Comment by trisavo-msft** [comment]
@yanzhudd  Yes it is ready for review/merge

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
