### PR TITLE
[AppService] `az functionapp create`: Remove workarounds for Centauri

### PR DESCRIPTION
**Pull request by kamperiadis**
**Related command**
`az functionapp create`

**Description**
In Centauri Private Preview, we did the following workarounds (which we are removing with this PR):
- sending the managed environment ID attribute in the PUT request when creating a function app
- using send_raw_request to fetch the managed environment ID attribute in the GET function app request

Removing these workarounds resolves the following [issue](https://github.com/Azure/azure-functions-on-container-apps/issues/22) because after the `enabling_additional_properties_sending` call, any `site_config.app_settings.append` statements are ignored, which is why the `APPINSIGHTS_INSTRUMENTATIONKEY` app setting is not added when the `--app-insights-key` param is passed. 

Additionally, we are removing https://github.com/Azure/azure-cli/blob/22feb5a5dcb1e23f0c1f1a444ff99af5c5502b19/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L3828 in this PR because we already add that app setting later in the function here:
 https://github.com/Azure/azure-cli/blob/22feb5a5dcb1e23f0c1f1a444ff99af5c5502b19/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L3930
The only reason why we were adding it in L3828 before is because of the app settings getting ignored with the workarounds as described in the previous paragraph. 
 
**Testing Guide**
1. Create a Centauri function app: `az functionapp create`
2. See that the managed environment ID attribute is not None: `az functionapp show`

**History Notes**
For Private Preview, we were given an exception to use the workarounds listed above but we want to have those removed.
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [x] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [x] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
AppService

**Comment by yanzhudd** [comment]
Please add test for this change.

**Comment by yanzhudd** [comment]
please not that CLI only review the code style and specifications but is not responsible for business logic. It is better to involve service team to review it as well.

**Review by khkh-ms — APPROVED** [review]

**Review by arroyc — APPROVED** [review]

**Review by yanzhudd — APPROVED** [review]

**Comment by yanzhudd** [comment]
please resolve conflicts

**Review by arroyc — APPROVED** [review]

**Review by yanzhudd — APPROVED** [review]

**Pull request merged**
