### PR TITLE
remove breaking change notice in deployment commands.

### PR DESCRIPTION
**Pull request by Tiano2017**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR has modified HISTORY.rst describing any customer-facing, functional changes. Note that this does not include changes only to help content. (see [Modifying change log](https://github.com/Azure/azure-cli/tree/master/doc/authoring_command_modules#modify-change-log)).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
@Juliehzl  please help with this PR.

**Comment by Juliehzl** [comment]
Hi @Tiano2017 , can you announce your removal in release note for user awareness?

**Comment by qwordy** [comment]
> 
> 
> Hi @Tiano2017 , can you announce your removal in release note for user awareness?

He just removes a notice. Maybe it's not that necessary to update history file.

**Comment by Tiano2017** [comment]
> > Hi @Tiano2017 , can you announce your removal in release note for user awareness?
> 
> He just removes a notice. Maybe it's not that necessary to update history file.

yep. We didn't update history file when we added the notice, so I guess it's fine. Let me know if it's required.

**Pull request merged**
