### PR TITLE
interpret the '@' syntax if something higher hasn't already done that.

### LINKED ISSUE #1379: CLI inconsistency -- to specify a parameters file, one must not use equal sign
If you use an equal sign between --parameters and the actual file path, you end up with the following:

```
az resource group deployment create --resource-group=jmsdcosrg --template-file=./output/azuredeploy.json --parameters="@./output/azuredeploy.parameters.json"
No JSON object could be decoded
```

Removing the equal sign works:

```
az resource group deployment create --resource-group=jmsdcosrg --template-file=./output/azuredeploy.json --parameters "@./output/azuredeploy.parameters.json"
```

### LINKED ISSUE #1419: [Generic Update] @file does not work in --set
The syntax for the generic update set option is:
`--set property=value`

If you try to use something like:
`--set property=@file` to load a JSON file as the value, the @ sign expansion will not occur.

### PR DESCRIPTION
**Pull request by brendandburns**
Fixes #1379
Fixes #1419 

@jmspring @yugang-msft

### CODE REVIEW

**Comment by tjprescott** [comment]
@brendandburns this issue applies more generally to the CLI. See issue #1419. I think it can fixed more generally by making a change here: https://github.com/Azure/azure-cli/blob/master/src/azure-cli-core/azure/cli/core/application.py#L200

In addition to startswith('@') we can probably have something like `or '=@' in ...`.

**Comment by derekbekoe** [comment]
Can we not make use of this?
https://docs.python.org/3/library/argparse.html#fromfile-prefix-chars

cc @tjprescott @johanste

**Comment by brendandburns** [comment]
@tjprescott thanks for the tip, I moved the code to that location (and I added unit tests too as a bonus!)

please take another look.

Thanks!
--brendan

**Comment by tjprescott** [comment]
@derekbekoe 

>  then arguments that start with any of the specified characters will be treated as files, and will be replaced by the arguments they contain

This problem is that with `foo=@bar`, the @ is in the middle of the string.

**Comment by brendandburns** [comment]
@tjprescott fixed (and added tests to cover it) please take another look.

Thanks
--brendan

**Comment by tjprescott** [comment]
Awesome! Thank you @brendandburns !

**Pull request merged**
