### PR TITLE
[AKS] BREAKING CHANGE: `az aks create`: Remove deprecated parameter `--docker-bridge-cidr`

### PR DESCRIPTION
**Pull request by paulgmiller**
**Related command**
az aks create

**Description**
This field was deprecated in newest api so now getting this warning with every create

 

docker_bridge_cidr is not a known attribute of class <class 'azure.mgmt.containerservice.v2023_06_01.models._models_py3.ContainerServiceNetworkProfile'> and will be ignored

**Testing Guide**
Non for remove

**History Notes**

[aks]  `az aks create`: removed docker_bridge_cidr

---

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] The PR title and description has followed the guideline in [Submitting Pull Requests](https://github.com/Azure/azure-cli/tree/dev/doc/authoring_command_modules#submitting-pull-requests).

- [ ] I adhere to the [Command Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/command_guidelines.md).

- [ ] I adhere to the [Error Handling Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/error_handling_guidelines.md).

### CODE REVIEW

**Comment by yonzhan** [comment]
aks

**Comment by FumingZhang** [comment]
We should do this breaking change (remove the option) in the next breaking change window around November.

**Comment by qpetraroia** [comment]
@paulgmiller, @FumingZhang, @zhoxing-ms, 

Are we still good to have this in breaking change release? Just want to make sure we don't forget. Thanks!

**Review by FumingZhang — APPROVED** [review]
LGTM

As this is a breaking change, should update the history note to something like
> [AKS] BREAKING CHANGE: `az aks create`: Removed deprecated option `--docker-bridge-cidr`

**Comment by zhoxing-ms** [comment]
@paulgmiller Could you please resolve these conflicts?

**Comment by zhoxing-ms** [comment]
@paulgmiller Could you please resolve these CI issues?

**Comment by zhoxing-ms** [comment]
Please note that we are launching the release for this sprint this week. Please resolve all comments by xxx, otherwise the release of this PR will have to be postponed to the next sprint **(on 12-05)**

**Comment by FumingZhang** [comment]
Replaced by PR #27784.

**Pull request closed without merging**
